### ISSUE TITLE
Preferences activity doesn't keep the scroll position after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [mpcjanssen/simpletask-android#1002]
When I change the orientation of the device screen, Preferences activity doesn't keep the scroll position
![2019-07-24 15-08-22_before](https://user-images.githubusercontent.com/53469180/62222585-e9877f80-b3b3-11e9-8cae-ace33b18ce65.png)
![2019-07-24 15-08-22_after](https://user-images.githubusercontent.com/53469180/62222586-e9877f80-b3b3-11e9-964a-b1b4a3a3dbcf.png)

**Comment by mpcjanssen** [comment]
Reconfiguration handling is a PITA in Android. Probably not going to fix this. It's a mild inconvenience.
