### ISSUE TITLE
ScriptConfigScreen activity changes its state after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [mpcjanssen/simpletask-android#1003]
When I change the orientation of the device screen, ScriptConfigScreen activity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
The Dialog disappears
![2019-07-24 13-26-13_before](https://user-images.githubusercontent.com/53469180/62222702-176cc400-b3b4-11e9-9fa8-a94b3eaf79e7.png)
![2019-07-24 13-26-13_after](https://user-images.githubusercontent.com/53469180/62222704-176cc400-b3b4-11e9-95cc-a783630811c9.png)

-- second case --
The menu disappears
![2019-07-24 13-23-53_before](https://user-images.githubusercontent.com/53469180/62222705-18055a80-b3b4-11e9-9bd4-78888dc05ea9.png)
![2019-07-24 13-23-53_after](https://user-images.githubusercontent.com/53469180/62222707-18055a80-b3b4-11e9-89e1-d619953a3d46.png)

**Comment by mpcjanssen** [comment]
I don't think this is fixable on Android. @dlicse do you know of any apps where this works properly?

**Comment by mpcjanssen** [comment]
Seems issues created by some automated process spamming hundreds of projects with the same minor issues. Wont fix unless there is anything where dataloss is occurring.
