### ISSUE TITLE
Simpletask activity changes its state after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [mpcjanssen/simpletask-android#1004]
When I change the orientation of the device screen, Simpletask activity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- fist case --
The menu loses the first element, "Search"
![2019-07-24 12-12-30_before](https://user-images.githubusercontent.com/53469180/62222933-73cfe380-b3b4-11e9-9c8a-7a3c7eac4304.png)
![2019-07-24 12-12-30_after](https://user-images.githubusercontent.com/53469180/62222934-73cfe380-b3b4-11e9-9e3b-49b564a6d234.png)

-- second case --
The text "test123" inside the search bar disappears
![2019-07-24 11-49-31_before](https://user-images.githubusercontent.com/53469180/62222936-73cfe380-b3b4-11e9-9a91-4ad6e713aae4.png)
![2019-07-24 11-49-31_after](https://user-images.githubusercontent.com/53469180/62222938-74687a00-b3b4-11e9-9762-bed6a508ec46.png)

-- third case --
The Dialog disappears
![2019-07-24 11-44-17_before](https://user-images.githubusercontent.com/53469180/62222939-74687a00-b3b4-11e9-82e2-440ec61d6d83.png)
![2019-07-24 11-44-17_after](https://user-images.githubusercontent.com/53469180/62222941-74687a00-b3b4-11e9-8969-f5b140a4d2fa.png)

**Comment by mpcjanssen** [comment]
The dialog and the right drawer opening are purposely built this way to demonstrate the UI. Restoring dialogs and menus is probably not possible. @dlicse do you know of any apps where this works properly?

**Comment by mpcjanssen** [comment]
Seems issues created by some automated process spamming hundreds of projects with the same minor issues. Wont fix unless there is anything where dataloss is occurring.

**Comment by dlicse** [comment]
Thank you for your answer, I opened these issues for research purpose. I would like to know whether you consider them as failure and yes, I know apps in which such problems do not manifest.

**Comment by mpcjanssen** [comment]
@dlicse can you give an actual example? Even the google apps exhibit the same behavior. Only real way to fix it is to not use menus or popups.

**Comment by dlicse** [comment]
For example, here nothing happens when I rotate the screen two times, I analyzed a large number of apps and I'm trying to figure out whether the developers accept the issues I posted as failures. Thank you for your contribute.
![2019-07-21 19-30-08_before](https://user-images.githubusercontent.com/53469180/62290008-89024c00-b460-11e9-83c3-1fcc85d6c5da.png)
![2019-07-21 19-30-08_after](https://user-images.githubusercontent.com/53469180/62290011-899ae280-b460-11e9-8b4a-b7ac313a675f.png)

**Comment by mpcjanssen** [comment]
@dlicse you would probably have a higher success rate with your checks if:

1. You would discuss with the developer that you are going to do this check and if they would think it's useful.
2. Only log a single issue describing all the failures.

Your current approach is very close to spam.

**Comment by dlicse** [comment]
Maybe you are right, I opened one issue for every activity in which I found these problems. I'm currently collecting the answers of the developers.

**Comment by mpcjanssen** [comment]
Main issue I have with all this is that it requires quite some time for me to review with very little value in return. Most of the detected issues are cosmetic and not really a big deal.

**Comment by mpcjanssen** [comment]
Search box issue is related to #997.
