### ISSUE TITLE
FR: Provide a simple text editor (for notes etc.)

### ISSUE THREAD

**Issue by tomtom** [mpcjanssen/simpletask-android#1005]
Since opening links under root makes simpletodo crash (see bug #709), it would be nice if simpletodo provided a simple text editor to open notes (and maybe create new notes if the file does not yet exist) under the root directory.

My personal use case: Edit markdown files under a ``root://notes`` subdirectory.

**Comment by mpcjanssen** [comment]
This would be much better served by using a dedicated note application and sharing the notes with simpletask. You can then use the `content://` link to open the note.

I am not going to include a note taking functionality.

**Comment by tomtom** [comment]
May I kindly ask, what is a content link? I know simpletask supports root:// and file:// but content:// is new to me.

**Comment by tomtom** [comment]
Ok, I see now. But this isn't compatible with any other OS. The beauty of todo.txt (and simpletask) is that it works on many platforms.

**Comment by mpcjanssen** [comment]
True but linking to another file is pretty much impossible to make work over all platforms. Linking to an URL still works fine.

**Comment by tomtom** [comment]
I don't know Android, but couldn't you use the mechanism for content:// links for root:// links (after replacing root:// with content://..../folder/? Is it absolutely necessary to expose the whole machinery to the user? I would be fine with root:// links if they worked.

**Comment by mpcjanssen** [comment]
Unfortunately, that's not how content:// links work. The links themself generally don't make sense. I still need to look into the root:// error though.
