### ISSUE TITLE
Future / Threshold start date conflict with other todo.txt apps

### ISSUE THREAD

**Issue by lucker999** [mpcjanssen/simpletask-android#1006]
Hello Mark,

Thank you for very convenient and powerful app to manage tasks. I like almost all in your app especially MYN compatibility. Alas, there is one issue.

The problem is with theshold date. As I understand it intends to indicate a date when a task should be started (and appear in the list if a filter applied). In order to achieve this your app add additional t:YYYY-MM-DD record to a task. Also your app doesn't account the creation date as a start date (as the other todo.txt apps do). This make a conflict between your app and the other I use (e.g. jdotxt on windows and linux and thunderbird plugin). SO, in order to use a filter with start date across the apps (which I do) I must edit a task created in your app to change the creation date. It is counterproductive, IMHO.

I'm sure you could choose another own solution to mitigate the issue, but here is my simple suggestion to fix that. First, a function to use a creation date as a start/threshold date should be added to your app. Second, add an option in settings to choose between (1) current implementation of the threshold date and (2) creation as a start date (as do the other todo.txt-compatible apps). This should help to avoid problem with compatibility when new function is added. In this case the people who use your app exclusively should change nothing. The people who sync the todo.txt file across devices could use the new function. 

Anyway, thanks again for awesome app.

**Comment by mpcjanssen** [comment]
Menu -> Filter -> Other tab select create is threshold.

**Comment by mpcjanssen** [comment]
Create is threshold was one of the first things I added after adding the threshold function. To aid in compatibility this was indeed created as a (filter specific) option as you suggested. So I couldn't agree more with you request 😄

**Comment by lucker999** [comment]
Ok, then let's find out why it doesn't work for me. 

I have a task with a date in the future:
`(A) 2019-08-20 Test task from phone`
It suppose to be hidden if I check "Create is threshold" AND uncheck "Show tasks with theshold dates in future" simultaneously. Alas, this doesn't provide expected results, neither in the app nor in widget. Actually I tried this option before I open the thread. 

I have Android 5.1 (Meizu Pro5 without Gapps) and all other features in the app work as expected (those I tested, of course :)) 

What should I do to help fix this?

**Comment by lucker999** [comment]
Also, with the option "Show tasks' age" I see the actual date in future. For other tasks it shows "yesterday", "two days ago", etc.

**Comment by lucker999** [comment]
BTW, I use the latest Simpletask Nextcloud version 10.3.1.3212 from play store.

**Comment by mpcjanssen** [comment]
I suspect hide tasks in the future doesn't obey the create is threshold setting.

**Comment by mpcjanssen** [comment]
Also ages in the future are shown as dates on purpose. This is not a bug.

**Comment by lucker999** [comment]
So, how I can make the tasks in the future obey? :) It's really frustrating...

Also, I noticed strange filter behavior. If I open the app by tapping on widget header, the filter from widget apply to the list instead of filter from the app.

**Comment by aubreyz** [comment]
> Also, I noticed strange filter behavior. If I open the app by tapping on widget header, the filter from widget apply to the list instead of filter from the app.

I can confirm that -- but it makes perfect sense to me that it should work that way. If it just chose any other random filter, the stuff shown may have nothing to do with the widget which is how you got to the app on this occasion.

**Comment by mpcjanssen** [comment]
@lucker999 what do you mean with: 

> how can I make the tasks in the future obey?

 As I mentioned this is probably a bug, because I never considered the create date in the future scenario.

**Comment by mpcjanssen** [comment]
Widget header opening the app with the filter from that widget works as designed because of the reason @aubreyz mentioned and is not going to change.

**Comment by lucker999** [comment]
> As I mentioned this is probably a bug ...

Sorry, I guess I just missed the added bug (perhaps I answered from email or something). Nevermind. I am happy to wait for the bugfix. 

Thank you once more for the awesome app!

**Comment by mpcjanssen** [comment]
The task `inFuture` method should take create is threshold into account.

https://github.com/mpcjanssen/simpletask-android/blob/development/app/src/main/java/nl/mpcjanssen/simpletask/task/Task.kt#L241
