### ISSUE TITLE
Sort by Due or Threshold Date does not work

### ISSUE THREAD

**Issue by Abies-sand** [mpcjanssen/simpletask-android#1007]
## Description
Sorting by Due Date or Threshold Date does not work.

## Versions and device
- SimpleTask (Cloudless)  10.3.0
- Android  9
- MI9

## Steps to Reproduce
1. Create two same tasks with different due dates only.
2. Choose Filter on the top right corner.
3. Choose  "SORT" and Click "Due Date" (Threshold Date) to change ascending or descending order.

### Actual behaviour
The order of tasks does not change.
### Expected behaviour
The order of tasks changes to be ascending or descending according to the sort selection.

**Comment by aubreyz** [comment]
It works fine for me. What do you mean "Click" the dates? The sorting items have to be in an order (what is on the top of the list?, where does due date feature in the sorting list?) If there is an issue, you will need to be more precise so that it can be reproduced by others.

**Comment by aubreyz** [comment]
Do the below series of screenshots help you?

![tempshots](https://user-images.githubusercontent.com/25100168/63254177-2b953a00-c26b-11e9-869f-af0128abc8b5.jpg)

**Comment by mpcjanssen** [comment]
@Abies-sand you will need to drag and drop the Threshold and Due date sorts to the top of the list. By default they are very low so the sorts above override the setting.

**Comment by Abies-sand** [comment]
@aubreyz Sorry for my unclear description. And the screenshots do help me figure out how to sort when I notice the Due Date is at the top of the list, as @mpcjanssen pointed out.
The sort works fine for me now. Thanks a lot.

**Comment by arthur-star** [comment]
> Do the below series of screenshots help you?
> 
> ![tempshots](https://user-images.githubusercontent.com/25100168/63254177-2b953a00-c26b-11e9-869f-af0128abc8b5.jpg)

Yes. Before I read this issue, I don't know is the method to rearrange the list is hold and drag. I tried to click the list item, the up arrow turns down, which make me confused.

Because this list is not a multi-level list, using arrow icons are misleading. Below implementation should be better for good user experience.

![image](https://user-images.githubusercontent.com/53738161/63276462-fe31a600-c2d5-11e9-8862-f7a1ceb185ae.png)

**Comment by mpcjanssen** [comment]
The arrows do determine the sort order. I probably should re-add the drag and drop sash though.
