### ISSUE TITLE
Scroll position changes on Device Rotation

### ISSUE THREAD

**Issue by Abies-sand** [mpcjanssen/simpletask-android#1008]
## Versions and device
- SimpleTask (Cloudless)  10.3.0
- Android  9
- MI9

## Steps to Reproduce
1. Open task list
2. Scroll down
3. Orientation change

### Actual behaviour
The previous scroll position disappears and it goes back to the head of the list
### Expected behaviour
The scroll position persists

**Comment by mpcjanssen** [comment]
Duplicate of #941 .
