### ISSUE TITLE
Review mode

### ISSUE THREAD

**Issue by mimmori** [mpcjanssen/simpletask-android#1020]
it would be really useful to implement a review mode that allows you to quickly filter one element at a time (both project and context). 

The simplest way would be to introduce a button in the filter panel which, if only one element is selected, allows you to select the next one and deselecting the previous one.

**Comment by mpcjanssen** [comment]
Between the two filter drawers and the automatic headers when the list is sorted on lists or tags (contexts and projects), I only see limited added value with this addition. And it will further clutter an already complex interface.
So probably not going to be added.

**Comment by mimmori** [comment]
the algorithm used to list the activities has a bug that does not allow to see the single activity under all relative contexts. To be sure I have to filter one context at a time, but this operation is very slow (deselecting the previous context and selecting the next one)

**Comment by mpcjanssen** [comment]
Do you have a lot of contexts so that open left drawer and select next is slow? Retaining the drawer scroll position and offering a single select option would be something I would consider adding.

**Comment by mpcjanssen** [comment]
Single select mode would also close the drawe after selecting.

**Comment by mimmori** [comment]
I do not have a lot of context but every time I want to check one I have to scroll the list. I think the single select mode and retain position could solve this issue.

**Comment by smichel17** [comment]
It sounds like scrolling the list is the problem. If the list did not reset position each time, it would not be very much effort to unselect the previous before serving the next.

That is, I think fixing #820 would probably be enough.

**Comment by mimmori** [comment]
I think could be a good workaround.
Thanks
