### ISSUE TITLE
Extra space before List or Tag header

### ISSUE THREAD

**Issue by tveulemans** [mpcjanssen/simpletask-android#1031]
Hi,

It would be great to have some additional space before the list/tag header when sorting on list/tag. With the current settings the last task from the previous list (or tag) is very close to the next header.

Kind regards
Thomas

**Comment by ddisanti** [comment]
@tveulemans  I deal with it using a new line character ( ``` \n ``` ) inside the header string. 
```
function OnGroup(t, f, e)
    return "\nTHIS IS A HEADER"
end
```

**Comment by tveulemans** [comment]
@ddisanti 
Thanks, great trick!! 

I modified it slightly to fit my purpose:
```
function onGroup(t, f, e)
    return "\n" .. next(f.lists)
end
```
