### ISSUE TITLE
Changing grouping

### ISSUE THREAD

**Issue by tveulemans** [mpcjanssen/simpletask-android#1037]
Hello,

I thought that changing the sorting order would also change the grouping, but somehow I cannot change the grouping logic (it always groups by list).

Is this the expected behavior?

Regards,
Thomas

**Comment by smichel17** [comment]
Generally grouping happens by the top sort criteria. However, you can override this with the onGroup lua callback.

**Comment by tveulemans** [comment]
Thanks for the information - I had forgotten that I am indeed using a lua script...
