### ISSUE TITLE
Webdav support

### ISSUE THREAD

**Issue by uGeek** [mpcjanssen/simpletask-android#1040]
Webdav support within the application for Nextcloud would be possible?
Nextcloud is a very heavy cloud with a simple webdav server. 

In addition, there would be synchronization with many more clouds.

**Comment by mpcjanssen** [comment]
https://mpcjanssen.nl/artifacts/10.4.0-26-d8c6cc4/webdav/ contains a webdav enabled version of Simpletask which seems to work with my own Nextcloud server.

**Comment by uGeek** [comment]
374/5000
Amazing!!!
Synchronizes perfectly and without any problems.
Could it be possible to enable http connection? For local and VPN connections it is ideal.

Does this version come in the next version of Simpletask for Nextcloud?

I am going to test the application with other webdav clouds like Box.com, Yandex, stackstorage, ...

Many thanks!!!

**Comment by mpcjanssen** [comment]
If you add http:// in front of the webdav it should work. This will be a new version. Not sure if i will release it via the Play store or just as a download for now.

**Comment by uGeek** [comment]
I have tested public clouds like Box.com and Yandex, they work perfectly using webdav

To connect to WebDAV

Box.com:
Server: https://dav.box.com/dav
Login: Email address and password.

Yandex:
Server:  https://webdav.yandex.com or https://webdav.yandex.ru
Login: User and password

HiDrive:
Server: https://webdav.hidrive.strato.com
Login: User and password

More clouds no tested:
4shared	https://webdav.4shared.com/
CloudMe	https://webdav.cloudme.com/
DriveOnWeb	 https://storage.driveonweb.de/probdav
IDrive Sync dav.idrivesync.com
Koofr  https://app.koofr.net/dav
Memopal	https://dav.memopal.com/
MyDrive	webdav.mydrive.ch
PowerFolder Free	my.powerfolder.com/webdav
Safecopy Backup	dav.safecopybackup.com
Stack	 https://user.stackstorage.com/remote.php/webdav/
Storage Made Easy (US)	webdav.storagemadeeasy.com
Storage Made Easy (EU)	webdaveu.storagemadeeasy.com

**Comment by uGeek** [comment]
> If you add http:// in front of the webdav it should work. This will be a new version. Not sure if i will release it via the Play store or just as a download for now.

When you connect via http, it displays the following message:
```
Login faild: CLEARTEXT communication to 192.168.1.100 not permittedby network security policy
```

**Comment by mpcjanssen** [comment]
@uGeek https://mpcjanssen.nl/artifacts/10.4.0-28-766e9ae-dirty/webdav/ should fix the http issue.

**Comment by uGeek** [comment]
> @uGeek https://mpcjanssen.nl/artifacts/10.4.0-28-766e9ae-dirty/webdav/ should fix the http issue.

Work perfectly with http!!!!

Synchronization is instantaneous with the webdav server, extremely fast.

Thank you very much for your time and modifying the app
Thanks a lot

**Comment by mpcjanssen** [comment]
I might release this version on fdroid

**Comment by uGeek** [comment]
That would be great news. it would have much more visibility and possibilities to install it.

I will wait for it to be published on F-Droid and I will make an article and podcast talking about all the possibilities of synchronization with public and private clouds.

I mounted the webdav server by docker on a Raspberry Pi and the synchronization with Simpletask webdav is very fast and perfect

**Comment by mpcjanssen** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6534 for inclusion in FDroid

**Comment by uGeek** [comment]
Thank you. It is great news !!!
Today I record the podcast and when the app is published, I publish it.
I'm also going to start the post.
I have many followers who use webdav as a server, I am sure they will use it.

The app works perfectly, 0 sync errors.

Before, I used the todo.txt synchronizing a directory with Syncthing and Simpletask, many times there was conflict in the synchronizations, I also used the Nextcloud version, but with webdav, it is very fast, I love it.

I mounted this Docker with a lightweight Webdav server. https://ugeek.github.io/blog/post/2019-10-22-docker-servidor-webdav.html and everything works perfect

**Comment by smichel17** [comment]
@mpcjanssen with all the versions floating around, I wonder if it would make sense for you to put out a request for packagers -- maybe people like @uGeek who have requested the different versions -- who could handle doing the various releases, to lower the burden for you a little.

**Comment by mpcjanssen** [comment]
@smichel17 once the version is developed, releasing is not the burden. Actually testing all the backends is. So if people raise any issues that is very helpful.

Deploying of all versions is completely automated.

**Comment by paullemmens** [comment]
Will this be a separate app like cloudless or nextcloud? Or how should i use this functionality?

**Comment by smichel17** [comment]
Yes, it will be a separate app.

**Comment by paullemmens** [comment]
Any idea on an ETA for this release @smichel17 ? Will it indeed be via FDroid as indicated above? In that case I'll manually monitor that.

**Comment by mpcjanssen** [comment]
@paullemmens see https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6534 no idea on ETA

**Comment by smichel17** [comment]
@paullemmens watch the merge request linked above. It'll appear in f-droid when that is merged, plus some delay depending on how long it takes the F-Droid folks' deploy process to get around to building it (last time I pushed a Red Moon update, this was around a week).
