### ISSUE TITLE
Gets frozen in aeroplane mode

### ISSUE THREAD

**Issue by IvanKazak** [mpcjanssen/simpletask-android#1043]
Simpletask Nextcloud.

If in Aeroplane mode Simpletask freezes (showing just black screen). When switching phone back to standard mode simpletask starts working again. Log is attached.

Taking a chance - thank you for the great app!

[Simpletask nextcloud v10.4.0 (3222) log.txt](https://github.com/mpcjanssen/simpletask-android/files/4311533/Simpletask.nextcloud.v10.4.0.3222.log.txt)

**Comment by mpcjanssen** [comment]
it seems determining the remote version is not done on the background

**Comment by IvanKazak** [comment]
Thank you for the quick reply. So any idea on how to fix it? While in the air it makes it impossible to work on todos...

**Comment by mpcjanssen** [comment]
I will look into it.

**Comment by mpcjanssen** [comment]
@IvanKazak could you test with a new build from https://mpcjanssen.nl/artifacts/nextcloud/release/ ?

**Comment by IvanKazak** [comment]
Still black screen when in Aeroplane mode. Log is attached.

[Simpletask nextcloud v10.4.0 (3222) log.txt](https://github.com/mpcjanssen/simpletask-android/files/4325469/Simpletask.nextcloud.v10.4.0.3222.log.txt)

**Comment by IvanKazak** [comment]
I've made additional testing, seems that the issue is also because of a running VPN-client. When in Aeroplane mode the VPN-client is still running in the background (still intercepting connection requests) and trying to tunnel the connections further (obviously without any success) - in this case SimpleTack gets frozen. 

After the VPN-client has been manually closed and still in Aeroplane mode, SimpleTask began to be responsive again. 

My guess is that Simpletask gets frozen because of the network probe approach it uses - it can open connection, but because of VPN-client (or any other intermediaries) never gets the network response back and waits infinity... If that is true, can the network probe be separated from the core functionality? So still be able to work even if no network (or problems with network)?

**Comment by mpcjanssen** [comment]
@IvanKazak network activities should already be completely done in the background. Can you do a test again with https://mpcjanssen.nl/artifacts/10.4.0-17-987630e/nextcloud/ so I know what version you have tested last.

**Comment by IvanKazak** [comment]
Thank you! I've tested with the mentioned version - it still gets frozen if a VPN client is running. Log attached. 
[Simpletask nextcloud v10.4.0-17-987630e (10004000) log.txt](https://github.com/mpcjanssen/simpletask-android/files/4339478/Simpletask.nextcloud.v10.4.0-17-987630e.10004000.log.txt)

**Comment by mpcjanssen** [comment]
@IvanKazak thanks for the extensive testing

**Comment by mpcjanssen** [comment]
Next version with more logging and another possible fix at https://mpcjanssen.nl/artifacts/10.4.0-19-e0c2c70/nextcloud/release/

**Comment by IvanKazak** [comment]
Works like a charm! Awesome!
19:39 - aeroplane off, VPN-client on, OK
19:40 - aeroplane on, VPN-client on, OK!
19:41 - aeroplane on, VPN-client off, OK!
19:42 - aeroplane on, VPN-client on, OK!
19:43 - aeroplane off, VPN-client on, OK!

Log:

[Simpletask nextcloud v10.4.0-19-e0c2c70 (10004000) log.txt](https://github.com/mpcjanssen/simpletask-android/files/4344631/Simpletask.nextcloud.v10.4.0-19-e0c2c70.10004000.log.txt)

**Comment by mpcjanssen** [comment]
That is great news. Please be aware that the fix was to remove a lot of unneeded thread synchronisation. I do recall adding it as a blunt fix for a concurrent modification exception so that might reoccur. For now treat this version as alpha.

**Comment by mpcjanssen** [comment]
@IvanKazak can you confirm that 10.5.2 has not reintroduced the slow startup?

**Comment by IvanKazak** [comment]
@mpcjanssen it has some noticeable delay when it starts for the first time (didn't notice big change), but then works really fast (feels like became faster), e.g. switching using predefined filters.

The most important thing that it works when network is not available ))

**Comment by mpcjanssen** [comment]
@IvanKazak thanks for confirming that the fix for #1027 has not reintroduced the broken behavior.
