### ISSUE TITLE
Lua config error: config.lua file saved as config.lue

### ISSUE THREAD

**Issue by ddisanti** [mpcjanssen/simpletask-android#1054]
Title is self explanatory.

- Go to `Lua config`.
- Tap on `Save and export` from `Import/Export Menu`.

The `config.lua` file is saved as `config.lue`.

I noted this when doing some backups and noted the new config.lue file. This was introduced in version 10.5.2 because it never happened before.

**Comment by ddisanti** [comment]
@mpcjanssen looks like you already fixed this [here](https://github.com/mpcjanssen/simpletask-android/commit/67d3cb2afb74026c2a3003906ba60823e4e996f0#diff-7e261d05fe4be52d4e9f37b880a68f66R73).

**Comment by mpcjanssen** [comment]
was indeed a typo.
