### ISSUE TITLE
commas in projects will don't show their tasks

### ISSUE THREAD

**Issue by MAWSpitau** [mpcjanssen/simpletask-android#1060]
Hi there,

I have several projects like:

`+name,forename`

if I want to see all tasks from one project via the menu on the left, simpletask shows me nothing. There won't be a checked checkbox either. 

Other clients, like todo.sh or todotxt-maschine accepting those syntax of projects.

Bug in here or am I not allowed to use commas ins projects?

Greetings
MAW

**Comment by mpcjanssen** [comment]
If todo.sh accepts this, this is a bug.

**Comment by mpcjanssen** [comment]
commas are allowed. Can you share a screenshot demonstrating the issue?

**Comment by mpcjanssen** [comment]
![image](https://user-images.githubusercontent.com/146895/79316594-cfbba780-7f04-11ea-80a3-b3d06f2376ab.png)

**Comment by MAWSpitau** [comment]
Hy thanks to care about this problem. 
I send you a screencast, where I show you the problem. I won't post it here, because of the names I used in my todo.txt. 

- The projects are shown on up in the left sidebar
- but the tasks will not show up in the main-view. 
- Also the project will not be checked in the sidebar.

**Comment by mpcjanssen** [comment]
Ah thanks for expanding. The issue is clear. Will check

**Comment by mpcjanssen** [comment]
@MAWSpitau you can download a version with fix from https://mpcjanssen.nl/artifacts/10.5.4-7-3c06437/

**Comment by MAWSpitau** [comment]
Great! It Works! Thanks a lot!
