### ISSUE TITLE
Use application for shortly notes

### ISSUE THREAD

**Issue by ev-ta** [mpcjanssen/simpletask-android#107]
I have a task (edit view):
XXXX-XX-XX Developer SimpleTask application -- Name: Mark -- email: mark....@gmail -- Notes: other information.

It would be great if this problem could be seen as(task list view):
Developer SimpleTask application
Name: Mark
email: mark...@gmail.com
Notes: other information

After click "save" - the program parsing line and found there marks (group special characters):
- A special symbol(exmaple, "--" two two hyphens) - means the transfer of a new line (return) (works only with the presence of the second line mark)
- The second special marks indicates that the line is the shortly note, and application need to hide the checkbox in the task list view

**Comment by smichel17** [comment]
@mpcjanssen What is the action for this issue? Do you intend to do it?
