### ISSUE TITLE
option for not using upper case for list and tag group header

### ISSUE THREAD

**Issue by aisbergde** [mpcjanssen/simpletask-android#1073]
I don't want simpletask to write the headers for list and task grouping in upper case but as I defined them. Maybe an option could be implemented to set this?

**Comment by aisbergde** [comment]
I would really like this option, because I use case sensitive list and tag for different meaning.

**Comment by mpcjanssen** [comment]
@aisbergde it was not as hard as I thought. Fixed now.

**Comment by aisbergde** [comment]
thank you!

**Comment by mpcjanssen** [comment]
I will be in the next 11.0.1 release from F-Droid. You can also get it at: https://mpcjanssen.nl/artifacts.
