### ISSUE TITLE
Recurring donation

### ISSUE THREAD

**Issue by PetrVladimirov** [mpcjanssen/simpletask-android#1082]
@mpcjanssen - simpletask is a great app :1st_place_medal: that many use everyday. Thank you very much for its development and maintenance!

You have to fix bugs and maintain compatibility with platforms updates. Moreover many people ask for new features and it would be great to get at least some of them in future (no pressure :smile:)

So I thought that it might be fair for your to open recurring donation opportunity for people who want to support the project. It is quite easy nowadays via github directly or platforms like patreon. What are you thoughts?

**Comment by aubreyz** [comment]
There is already a donation app for simpletask (I have donated) - though it seems slightly odd as a mechanism.

https://play.google.com/store/apps/details?id=nl.mpcjanssen.simpletask.donate&hl=en_US

**Comment by smichel17** [comment]
There's also a paypal link in the [readme](https://github.com/mpcjanssen/simpletask-android/blob/master/app/src/main/assets/index.en.md). However, neither of those are a recurring donation method, so I think @PetrVladimirov's question still stands. :)

**Comment by mpcjanssen** [comment]
To be honest, even though I appreciate the sentiment, looking at the amount of donations I think setting up a recurring donation will be more trouble than it's worth. And it will create expectations for changes or fixes in Simpletask.
