### ISSUE TITLE
repeating "Saving of todo file failed" popup message

### ISSUE THREAD

**Issue by spiralofhope** [mpcjanssen/simpletask-android#1088]
#### Version

<details>
 <summary>Click to expand</summary>

Simpletask 10.5.4

Settings > About phone > 

* Custom built version:  alps-mp-q0.mp1.V8.4

Settings > About phone > Android version

* Android version: 10
* Android Security patch level: 5 December 2019
* Baseband version:  MOLY.LR12A.R3.MP.V84.T1,MOLY.LR12A.R3.MP.V84.T1
* Kernel version:  4.14.141
  *  `#1` Thu Mar 19 09:23:51 CST 2020
* Build number: UMIDIGI_Power_3_V1.1_20200319

</details>

#### Problem

Simpletask keeps regularly shows a popup reporting that the autosave fails.

It has storage permission, and I confirm that the file is being changed.

**Comment by mpcjanssen** [comment]
please attach the logging after this happens. from Settings->other

**Comment by spiralofhope** [comment]
https://gist.github.com/spiralofhope/25e6edda132ce114a9c22e84f6495aaa

**Comment by aubreyz** [comment]
Perhaps not entirely related by my dropbox version persistently fails to write and creates a new dropbox file (with numbers appended) citing version clash (even though my single phone and simpletask are the SOLE devices connected to my dropbox account, so there is nothing else altering things).

**Comment by mpcjanssen** [comment]
this os the cloudless version giving an error?

- does thr cloudless version have storage access
- how fo you sync to dropdox

**Comment by aubreyz** [comment]
No the cloudless version works great. 

It is the dropbox version that is causing the problem. I actually have both versions running and I use them for different purposes.

**Comment by mpcjanssen** [comment]
@aubreyz that was a question for @spiralofhope

**Comment by spiralofhope** [comment]
> this is the cloudless version giving an error?

Yes it is just simpletask from f-droid.

> does the cloudless version have storage access?

Yes it does.  I am able to open, change and save files normally.  This message keeps appearing, but it does not need to.

**Comment by scheunengeist** [comment]
I have the same problem now after switching to LineageOS 17.1 (Android 10), using Simpletask Cloudless 10.9.0 from F-Droid: popup "Saving of todo file failed".

After reinstalling Simpletask, I'm greeted with "Loading of todo file failed". Trying to open my todo file from the menu entry produces a seemingly crippled file picker, showing nothing but ".." below the alleged current directory. No files are shown, and I cannot pick anything.

The log has grown huge quickly, so I don't put it up here in full. From the log, I took the standard file location where ST is looking for the todo.txt file. My todo.txt file is in fact located elsewhere. Copying it to the standard location shows all of my entries, and modifying the file seems to work, as it does not produce "Saving of to do file failed" message.

The application has storage permission. Maybe Android 10 changed something in this permission area?

Thanks in advance for looking into this issue!

**Comment by smichel17** [comment]
Perhaps also #1100 and #1102; and see #1110

**Comment by scheunengeist** [comment]
After reading a bit more (thanks @smichel17 for the additional links), I'd like to add two things:

* I tried SimpleTask 10.9.0-20-2e2a362-saf from artifacts, and it works great in my first tests. Thank you for providing it @mpcjanssen!
* I totally sympathize with you concerning the never ending changing around of Android internal functionality. It is annoying even for a mere conscious user. For a developer, I can only imagine it must be severely frustrating. For what it's worth, ST is the best todo.txt utility I'm aware of. You've created something really cool, don't let the corporate bullies spoil that feeling for you. :)

**Comment by mpcjanssen** [comment]
@scheunengeist can you try the version https://mpcjanssen.nl/artifacts/10.9.0-2-f162a66-fullaccess/cloudless/release/app-cloudless-release.apk ?

**Comment by scheunengeist** [comment]
@mpcjanssen Sorry, didn't get around to it right away. When trying to install the above version, the packet installer gives me an error "parsing the package".

**Comment by mpcjanssen** [comment]
@scheunengeist you are on Android 11?

**Comment by scheunengeist** [comment]
That's correct, I'm using LineageOS 17.1, which corresponds to Android 10.

The version of ST you posted above behaves in the same way the one on F-Droid does (don't know if they are different): I can open a file picker dialog through "open todo file", but anything outside `/storage/emulated/0/Android/data/nl.mpcjanssen.simpletask` is invisible (except for '..', which brings me ever higher into seemingly empty directories up to /).

When using the above directory as location for the todo and done files, everything works fine. Personally, I can live with this, as long as my files stay offline. I'm syncing / backing up my data using adb-sync, so I just added the 'new standard' file directory to my list of stuff to pull. People who go the Syncthing/Nextcloud way may have a bigger plight.

**Comment by mpcjanssen** [comment]
@scheunengeist can you try with this version: https://mpcjanssen.nl/artifacts/issues/1088/app-cloudless-release.apk which falls back to the old Android 9 permission system om Android 10. It works as expected on my LineageOS 17.1 pixel 2.

**Comment by mpcjanssen** [comment]
@aubreyz could you log a separate issue for you Dropbox multiple conflict files?

**Comment by mpcjanssen** [comment]
I now have a build which should have full storage access both on Android 10 and lower devices and on Android 11. This will probably be the next f-droid release.

**Comment by aubreyz** [comment]
I am ecstatically happy that you have managed to get out of the (well merited) depression @mpcjanssen 

I have stopped using the Dropbox version completely (because of this) so would be a bad candidate to test it.... 
That said the current Webdav version very occasionally does something odd but different

Dropbox past issue:
- This would happen nearly daily
- was connected as the only device so no possibility of a conflict coming from anywhere else
- Dropbox would create a conflict (with  new name containing the word conflict)
- ST would then be connected to that new file automatically not todo.txt (so no data loss)
- Eventually would end up with a trail of many dozens of conflicted files with ST being connected to the most recent
- Current file name gets progressively longer and longer....

Webdav
- Again only connected device to that folder
- On just a couple of occasions there was a conflict
- In this case ST continued to be connected to the todo.txt with the conflict file having some recent data
- So so possibility of data loss here
- But as I said this only happened twice, both times when I was rapidly doing stuff (i.e update threshold date on many items one after the other - a reasonably big file with about 2000 lines so maybe due to rapid successive updates to a file that cannot be uploaded fast enough)

I think if I were testing I would do it with very rapid successive updates on a fairly large file

**Comment by mpcjanssen** [comment]
@aubreyz if it happens again please log a separate issue. What might be related is the 6s delay Simpletask now waits after the last change before writing the file. Maybe reducing the time in the settings makes a difference.

**Comment by mpcjanssen** [comment]
> Perhaps not entirely related but my dropbox version persistently fails to write and creates a new dropbox file (with numbers appended) citing version clash (even though my single phone and simpletask are the SOLE devices connected to my dropbox account, so there is nothing else altering things).
> 
> It works still but the file that it is using and saving to is the latest so called conflicted copy -- so I get nervous about the integrity of my data (albeit that it works fine through the transmuting file names)
> 
> ![simpletask problem](https://user-images.githubusercontent.com/25100168/91964000-84b0fe00-ed06-11ea-8d5a-76f2973e4813.png)

@aubreyz see https://github.com/mpcjanssen/simpletask-android/issues/1116 for this issue

**Comment by scheunengeist** [comment]
@mpcjanssen I installed https://mpcjanssen.nl/artifacts/issues/1088/app-cloudless-release.apk and can confirm that I can navigate through the file system, open and save todo.txt from my 'old' location, as well as edit and archive issues with no error messages, as far as tested.

**Comment by mpcjanssen** [comment]
I'll close this issue then. Any remaining non-cloudless issues can become new issues.

**Comment by scheunengeist** [comment]
Thanks for your work on this!

**Comment by spiralofhope** [comment]
> I'll close this issue then. Any remaining non-cloudless issues can become new issues.

Just to follow up, the error message does continue but only displays once; this is an acceptable annoyance.

I'm using 10.9.1 on F-Droid (from 2021-04-11)

Thanks for your effort.  👍
