### ISSUE TITLE
Accessibility of right sidebar

### ISSUE THREAD

**Issue by ComedyTomedy** [mpcjanssen/simpletask-android#1090]
It's not always possible to swipe, meaning one can't always open the Saved Filters panel.

I'd like to suggest adding an item "Show Saved Filters" in the overflow menu (top right). There may be other solutions.

Examples of the problem: 
* SimpleTask works well in Andoid split-screen mode, but at least on my Xiaomi "MIUI" phone, accessing the saved filters list in this mode isn't possible.
* As referenced in #1084, this also applies to devices that can't swipe, eg desktops.
* People with motor disabilities might also be unable to swipe.

**Comment by smichel17** [comment]
This seems like a good, low-effort compromise, until someone has the inclination to do a UI update to fix this in a better way.

**Comment by smichel17** [comment]
I had another idea for a UI change that I think has a very good ratio of effort to benefit:

Add another FAB, above the current one, to open the right drawer.
It should be the small style of FAB, not big like the +.

I think it would not cover too much task list area, but I might be wrong; in that case, we should offer the option to hide it (or move to the overflow menu), instead.

**Comment by aubreyz** [comment]
Ahhh. this problem has now rendered simpletask unusable on my new moto G8. There is no possible way I can see to access the right swipe menu or the filters. Any attempt to do that just exits the app. If this is an "easy" fix then it's an urgent one as I am completely disabled for now....

The left swipe menu is obviously still accessible from the "3-line" menu.

**Comment by mpcjanssen** [comment]
Yet another google hoop :clap: Adding a menu item should be easy.

**Comment by mpcjanssen** [comment]
Code is already there to show the right drawer on first launch

**Comment by aubreyz** [comment]
Thank you for this (not yet looked). As to Google, I couldn't agree more. The best software I use (over many decades) is nearly perfectly backwards compatible (like LaTex). Windows is even quite backwards compatible at least over one decade. 

They could easily have done these meta-gestures in a very different way that would be mostly compatible (e.g over a very narrow slice of the vertical screen, at a very different rate or a different swipe e.g full screen width).
