### ISSUE TITLE
Removed metadata

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#1093]
I just noticed 801bbb0abfb9536b58cb42649d4079c79b44e260 — @mpcjanssen FYI, this is going to affect F-Droid, to whatever extent the metadata is not in the fdroiddata repo (but, they have been encouraging devs not to use that approach, and to host metadata in their own repo (fastlane/triple-t style) instead).

You don't need the Triple-T plugin, just the metadata in that location (or the fastlane one).

**Comment by mpcjanssen** [comment]
ah that's a better option. The plugin keeps breaking the build.

**Comment by mpcjanssen** [comment]
Reverted by 63141bb6eb0eac6d4f4efdf32d6e0dd57d86ff76
