### ISSUE TITLE
Possible error when access webdav server

### ISSUE THREAD

**Issue by steinm** [mpcjanssen/simpletask-android#1097]
I have put my todo.txt into seeddms (another open source dms) and access it via webdav. When I open a todo file I see PROFIND calls with a path '//' which I suppose should be '/'. seeddms webdav server response with not a found msg. Opening a subdirectory is working fine. I'm not sure if it is '//' is a valid path for the root folder but I doubt it. Can this be fixed?

**Comment by mpcjanssen** [comment]
What did you enter for server address? And did it have a trailing slash?

**Comment by steinm** [comment]
No trailing slash. It's just a php page `https://..../webdav/index.php`.

When I access a subfolder I can see a correct access on `/foldername/`. My first thought was, that you always put a `/` in front and after the foldername. In case of the root folder this results in `//`. But that is just a guess.

**Comment by mpcjanssen** [comment]
@steinm could you try with https://mpcjanssen.nl/artifacts/10.8.0-5-5980466/webdav/release/app-webdav-release.apk

**Comment by steinm** [comment]
I tried to install it, but for some reason it doesn't do it. It starts fdroid and asked me whether I would like to install it. After clicking continue it starts to install, but then issues the error msg 'the app could not be installed'.

**Comment by mpcjanssen** [comment]
Ah you installed the fdroid version? Then you should uninstall that first. Fdroid signs the build with their own (different) key.

**Comment by steinm** [comment]
Got it installed and now its working flawlessly. The path to PROPFIND is a single dash for the root folder and all subfolders are also still working. Thanks for fixing this.

**Comment by smichel17** [comment]
Fixed by https://github.com/mpcjanssen/simpletask-android/commit/598046661dcb948e95a89cb2c45a6ce2fa5f0e38
