### ISSUE TITLE
Todo file content overwritten

### ISSUE THREAD

**Issue by mmmok** [mpcjanssen/simpletask-android#1098]
Hi, I have been using Simpletask Cloudless for many years, and I am very grateful for the app, and had never found a problem like this one.

I don't know how, the content of one of my todo files (let's call it file B) was replaced with the content of another one (let's call it file A). Both files live on the same directory.

I am almost certain that file A was the last one I opened and worked with last night (also I didn't use any other app expected to mess with these files), and what I did this morning was to:
1. Open the app
2. Select the "Open task list file" menu
3. Select file B
4. And then file B presented the same content as file A
5. I checked up modification dates, only file B has been modified today

So, my guess is that file B was somehow overwritten, at the moment it was open this morning, with the content that was on the app at the time.

I use Simpletask Cloudless version 10.8.0 installed through F-Droid on Android 10.

I hope this helps.

Thank you.

**Comment by mpcjanssen** [comment]
@mmmok I hope this didn't cause any data loss and until it's clear what's causing this I would suggest not switching todo files.

**Comment by mpcjanssen** [comment]
@mmmok could it have been the case that you had changes pending while switching todo files? i.e. do you recall if there was a red bar showing?

**Comment by mpcjanssen** [comment]
@mmmok fixes are included in the released 10.9.0 version.

**Comment by clach04** [comment]
@mmmok can this be closed now?
