### ISSUE TITLE
Webdav PROPFIND works but PUT fails

### ISSUE THREAD

**Issue by chadvoegele** [mpcjanssen/simpletask-android#1099]
Hi @mpcjanssen! Thank you for simpletask! It is a really great progam.

I am trying to switch from the Dropbox version to Webdav. My webdav server is nginx ([example](https://wiki.archlinux.org/index.php/WebDAV#Nginx)) behind a reverse proxy with Basic HTTP Auth.

The login and fetching of the `todo.txt` file works but saving fails. It looks like the username/password is not provided during the PUT to save.

nginx logs
```
174.21.87.43 - - [19/Oct/2020:03:47:23 +0000] "PROPFIND /dav/todo/todo.txt HTTP/2.0" 401 180 "-" "okhttp/4.3.1"
174.21.87.43 - chad [19/Oct/2020:03:47:23 +0000] "PROPFIND /dav/todo/todo.txt HTTP/2.0" 207 476 "-" "okhttp/4.3.1"
174.21.87.43 - - [19/Oct/2020:03:47:23 +0000] "PUT /dav/todo/todo.txt HTTP/2.0" 401 180 "-" "okhttp/4.3.1"
2020/10/19 03:36:47 [info] 6#6: *52 no user/password was provided for basic authentication, client: 174.21.87.43, server: home.chadvoegele.com, request: "PUT /dav/todo/todo.txt HTTP/2.0", host: "home.chadvoegele.com"
```

[simpletask_log.txt](https://github.com/mpcjanssen/simpletask-android/files/5401652/simpletask_log.txt)

I'm on version 10.9.0 pulled from here: https://mpcjanssen.nl/artifacts/10.9.0/apk/webdav/release/app-webdav-release.apk

I'll try to see if I can figure out a fix.

(FWIW, my Webdav server is working with Orgzly.)

**Comment by mpcjanssen** [comment]
Is there any (temporary) option to test this without the intermediate nginx proxy?

**Comment by chadvoegele** [comment]
Yup, I will try that.

Also, I noticed that Orgzly has the same behavior where the request is submitted once without the username/password and then again with it. I see the same `no user/password was provided for basic authentication` with Orgzly but it goes through on the subsequent call. I'm trying to look more into the `okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR` error in the Simpletask logs.

**Comment by chadvoegele** [comment]
Ya, it works without the proxy so seems like Simpletask is fine. Not sure why the same setup works with Orgzly; both are using Sardine + OkHttp.

I'll close this since it is not a Simpletask issue. I'll post back if I figure out a solution with the proxy.

**Comment by chadvoegele** [comment]
I'm still doing some testing but it looks like it works with the proxy if you use OkHttp 4.10.0-RC1. I think the problem is related to this issue: https://github.com/square/okhttp/issues/4964

**Comment by mpcjanssen** [comment]
I'll see if I can update sardine and or okhttp

**Comment by chadvoegele** [comment]
Thanks for looking into it!

keepass2android hopped onto the RC for this issue: https://github.com/PhilippC/keepass2android/pull/1445/files

I completely understand if you don't want to use the RC version. I can make my own build in the meantime until this stabilizes.

**Comment by mpcjanssen** [comment]
@chadvoegele I have no issues with using RC version if they fix a real world problem. I will make a build for you to try.

**Comment by mpcjanssen** [comment]
@chadvoegele updated build at https://mpcjanssen.nl/artifacts/10.9.0-1-4598ad4/webdav/

**Comment by chadvoegele** [comment]
Wow, thanks so much for the quick fix!

It is working for me!

I need to back out all of the config I added for testing but I'm pretty sure the OkHttp upgrade does it.

**Comment by chadvoegele** [comment]
I cleaned up everything and it's still working with your build. Thanks so much for your help!

**Comment by mpcjanssen** [comment]
@chadvoegele thanks for finding out the probable fix, that was most of the effort, making the build was 5 minutes work :smile:
