### ISSUE TITLE
Unable to find todo.txt

### ISSUE THREAD

**Issue by thehungryturnip** [mpcjanssen/simpletask-android#1101]
The app (cloudless version) seems unable to recognize the presence of any files. The "open task list file" button seems to only see folders. E.g.

No files show up:
![Screenshot_20201029-221246](https://user-images.githubusercontent.com/91952/97652320-75171280-1a34-11eb-8f65-bf0c34394666.png)

Other app showing for presence:
![Screenshot_20201029-221317](https://user-images.githubusercontent.com/91952/97652362-911ab400-1a34-11eb-80e2-baba0ba98589.png)

* I've browsed to other directories. Also don't see any files. Only folders.
* I've tried sitting the todo.txt file at different locations. Also can't be seen.

Love the work you're doing. Thanks in advance for your help!

**Comment by smichel17** [comment]
If you are on Android 11, this is a duplicate of #1100

**Comment by thehungryturnip** [comment]
Thanks... You are correct... Unfortunately I searched but didn't spend enough time. Sorry and thanks for the quick reply!

**Comment by smichel17** [comment]
No worries, it happens. Particularly, GitHub's UI makes it easy to forget to search *closed* issues in addition to open ones.
