### ISSUE TITLE
Two versions of Simpletask missing in play store

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#1102]
The dropbox and cloudless versions of Simpletask have been suspended in the playstore because of a "repetitive content" violation.
To me it's not clear how one should publish different flavours of the same app in the playstore then. For now. I will start adding builds to https://mpcjanssen.nl/artifacts if or when I will find a proper solution to this which doesn't risk suspending my whole gmail account.

![image](https://user-images.githubusercontent.com/146895/98340814-3d98ff00-200e-11eb-99e9-5d6711c2d459.png)

**Comment by mpcjanssen** [comment]
Appeal text:

> The set of applications nl.mpcjanssen.todotxtholo, nl.mpcjanssen.simpletask and nl.mpcjanssen.simpletask.nextcloud are three seperate versions of the same app but with different storage backends. A major selling point of the different versions is that the local storage version doesn't need network access. I do not know how to merge all these storage backends into a single app without listing unnecessary permission requirements for the local only app.
I therefore think these different version (although very similar) do provide enough differentiating functionality (the storage backend) to all be allowed. The amount of downloads for each clearly support this. 
Also going to direct suspension instead of a warning after several years being live with these apps is too harsh.

**Comment by mpcjanssen** [comment]
That didn't really help:

> Thanks for contacting the Google Play team.
Status of app (nl.mpcjanssen.todotxtholo, nl.mpcjanssen.simpletask): Suspended from Google Play due to policy violation
I’ve reviewed your appeal request and found that your apps still violate Google Play Policy.
During review, we found that your apps violate the Repetitive Content policy. We don't allow apps that merely provide the same experience as other apps already on Google Play. Apps should provide value to users through the creation of unique content or services.
For example, your apps contain highly similar content to each other. 
You can read through the Repetitive Content policy page for more details and examples of common violations.
Please note that we don’t allow 

Copying content from other apps without adding any original content or value.

Creating multiple apps with highly similar functionality, content, and user experience. If these apps are each small in content volume, developers should consider creating a single app that aggregates all the content.

Please also re-examine each of your apps to make sure that they are compliant with the Repetitive Content policy. Developers are important partners in maintaining a great user experience on Google Play and we appreciate your cooperation. 
If your developer credentials are still in good standing with Google Play and if your app allows for it, you can publish a new compliant version of the app by following these steps:

Make the necessary changes to your app to address the issue described above, if possible.

Double check that your app complies with all other Developer Program Policies. Additional enforcement could occur if there are further policy violations.

Sign in to your Play Console and upload a new app using a new package name and a new app name.

Please let me know if you have any other questions. Thanks for your continued support of Google Play.

**Comment by nicodn** [comment]
Is it possible to swap the currently active version on Google Play to the Cloudless or the main build? I'm selfishly asking so that I can install on my chromebook without having to enable developer mode in order to sideload the apk (and lose all my data) 🙏

**Comment by smichel17** [comment]
Normally, tasks are saved to the todo.txt file whenever you update the list and you can export your saved filters and lua config as well. So, migrating between different versions of Simpletask is not very much work; you just need to change the app-wide settings.

If I understand you right, though, you are currently using the Nextcloud version, but have not connected it to a Nextcloud server yet, so you don't have access to the `todo.txt`, `saved_filters.txt`, and `config.lua` files that way. In this case:

- If you are only looking to save your task list, you can easily select one item -> select all -> share
    - Now you have the full text of those tasks, and you can save it in a file somewhere. After installing the cloudless version, you can just paste the text back in on the add task screen.
- For the lua config, you can do basically the same thing. It is all in one text box, so it is easy enough to copy and paste it to a new file.
- For the saved filters, I don't know how to export these if you are using the nextcloud version, without connecting to a nextcloud instance.
    - If this is what you are looking for, I could make a temporary account for you on my nextcloud instance.

**Comment by nicodn** [comment]
I'm using the cloudless version on my phone but I can't install it on my chromebook because sideloading is blocked there. I tried installing the nextcloud version on the chromebook but it shows a login screen. I use a separate app to sync the file on my sdcard. Is there a way to open the `todo.txt` file from the local filesystem on the nextcloud version?

**Comment by mpcjanssen** [comment]
@nicodn I am currently thinking to publish a version using the storage access framework as the single google  play version. This would offer at least the same functionality as the current separate versions.

**Comment by mpcjanssen** [comment]
@smichel17 comment on wrong issue?

**Comment by mpcjanssen** [comment]
For now I have also disabled the nextcloud version in preparation of the storage access framework version.

**Comment by jason-mehmel** [comment]
(Thanks for looping me in from the erroneous issue opening.)

**Comment by mpcjanssen** [comment]
I have rolled out the Storage Access Framework version to the play store. This is missing some stuff (most notably archiving) I will re-add this functionality gradually.

**Comment by aubreyz** [comment]
I can't see it, but that might involve a delay on Google's end? 
But clarify what this replaces -- presumably this is just a replacement for the cloudless version??

If I am already running the cloudless version, can I install separately three cloudless versions (FDroid version, the old non-available one, and this new one)? It would be great if that were the case, and even better if the main program icon could be given slightly different colours to reflect which version is running.

**Comment by mpcjanssen** [comment]
@aubreyz it is still under review at google side and yes this new version can access all storage providers which integrate with the storage access framework among which Dropbox, nextcloud and Google drive if the client apps are installed.
It is also possible to install all apps in parrallel but I am not so sure if I still have the motivation to maintain all the current versions next to the new storage framework version. I think finding another way to satisfy your use case would be more likely.

**Comment by mpcjanssen** [comment]
This version is also rejected because of the donate button in the app.

**Comment by aubreyz** [comment]
Yes Google are infuriating. Can I make a small suggestion for the longer term if just maintaining one version: It would be nice if it were possible to allow the background colour (or something else glaringly obvious) to depend on which database is loaded. That way it will be clear which database one is working with. Better still to allow the filter-set to be tied to a database (maybe a filter set of the same name as database name would be a simple way to do it - if a filter set exists of same name as database then load that otherwise load a default)

**Comment by mpcjanssen** [comment]
It's live now at https://play.google.com/store/apps/details?id=nl.mpcjanssen.simpletask.saf

**Comment by jason-mehmel** [comment]
Possibly dumb question: does this version replace Simpletask with Dropbox and the Cloudless version? And this new version puts the file sync options outside of the app, at our own discretion?

**Comment by smichel17** [comment]
Yes, when you choose the option to select the todo.txt file, it will open an Android menu, not unique to simpletask. You can use it to select a local file. If you have the Nextcloud or Dropbox apps installed and logged in, you should also be able to select files from those locations, and those apps will handle the sync, similar to how you can currently sync the cloudless todo.txt file using nextcloud if you make it save in /storage/emulated/0/Android/data/com.nextcloud.client/…path/to/todo.txt

**Comment by mpcjanssen** [comment]
NB the nextcloud implementation from the nextcloud Android app has a bug where remote changes are only picked up after you release the file. Google Drive is fine.

**Comment by jason-mehmel** [comment]
On my Samsung S7, it doesn't look like the Android file menu connects to Dropbox, but I'm using Foldersync to line them up. Just doing a test now to see how well the Foldersync option works!

Also a dumb question, I've now got two version of Simpletask on my phone... the newest one and the Dropbox Sync version. I'm assuming the Dropbox version isn't being updated, but there's no current issue continuing to use it?

**Comment by mpcjanssen** [comment]
@json-mehmel you'll need to install the Dropbox client application for it to be included. The client provides the storage provider. 
Also the latest Dropbox version is still fine to use.

**Comment by jason-mehmel** [comment]
On the Dropbox app I have, there's nothing that connects Dropbox to my file browser access. Is the Dropbox Client application you'd talking about something different? Not the 'standard' Dropbox app?

It's possible that it might be in a version of the app I don't have access to...

I'm doing Android 8.0.0 on Samsung S7 with "Samsung Experience version" 9.0 (Whatever that means.)
Dropbox App version 214.2.6

(Honestly, don't worry too much regarding troubleshooting the Dropbox link within my android file system, Foldersync is helping do the job!)

**Comment by mpcjanssen** [comment]
You're right, i could have sworn that the Dropbox app provides a storage provider, but it doesn't. Sorry for the confusion.

**Comment by aurisnoctis** [comment]
Hi @mpcjanssen ,
https://play.google.com/store/apps/details?id=nl.mpcjanssen.simpletask.saf is for `Android 8.0 and up`.
Does it mean that simpletask on older Android versions cannot be updated via Google Play from now on / are stuck with latest available versions before Google took them down?

I have F-Droid - just want to understand implications for Google Play.

Thanks in advance for clarifying and thanks for this great app.

**Comment by kianboon80** [comment]
> 
> 
> NB the nextcloud implementation from the nextcloud Android app has a bug where remote changes are only picked up after you release the file. Google Drive is fine.

may i know how to release the file?

**Comment by mpcjanssen** [comment]
that should have been "reload the file" you can do that by restarting simpletask or refeshing from the menu.

**Comment by kianboon80** [comment]
Thanks. Recently, I have issue ever since I switch to a new phone(android 10). It open the file in Dropbox with no issue but after making one/two change, when I click sync. It will revert back all my changes. Then I notice that I often need to open Dropbox app before opening SimpleTask in order to get the latest. But there are also times where after my changes, it will create another todo(conflict file) in Dropbox.

**Comment by bshanks** [comment]
For other Dropbox users, currently you can download the latest Simpletask Dropbox from https://mpcjanssen.nl/artifacts/10.9.0/apk/dropbox/release/app-dropbox-release.apk and then install it by using the Files app to navigate to the Downloads folder, selecting the app-dropbox-release.apk file, and then enabling Allow Unknown Apps Installation as requested.

Very sad that Google is doing this. Simpletask is the only reason I buy Android phones instead of iPhones!

**Comment by goZealtech** [comment]
> It's live now at https://play.google.com/store/apps/details?id=nl.mpcjanssen.simpletask.saf

Is it restricted to certain country play stores?  I cant find it on the India play store.

**Comment by mpcjanssen** [comment]
@goZealtech the SAF version was very buggy with detecting remote updates. I have removed it, so now there are no versions available from the playstore.

**Comment by jeron1** [comment]
Simpletask is one of the most important apps on my phone. Super high value. Wish it was still on google play. I grabbed apk off of an old device of mine, when setting up new phone. I guess I'll look to Fdroid or something in the future.

**Comment by jacquesh** [comment]
Is there any reasonable way forward to get any version of SimpleTask back onto the Play store? Does this issue remaining open indicate that you hope to get SimpleTask back onto the Play store in future? I'm not an Android developer by any means but I would consider contributing to a fix if I knew what needed to be changed >_<

In the absence of the ability to reasonably support the various sync backends from the same app, would you consider putting the cloudless version back on the Play store? Or any version for that matter (I gather the cloudless version is just the normal one but missing the cloud-sync and thereby using fewer permissions)? I imagine having only one version would resolve Google's duplication concern at least, regardless of which version it is?

**Comment by mpcjanssen** [comment]
@jacquesh there is a bit of a Catch 22 situation here. 

1. The most logical version to upload to the playstore would be the Cloudless or the Storage Access Framework version.
2. The Storage Access Framework is a buggy PoS so that's a no go.
3. The cloudless version needs special permissions to work on newer Android versions to have access to the storage. This is not a permission that the Play Store allows by default, unless there are some google hoops you'll jump through.

So really no good way. Uploading a version with a specific storage backend is a no go IMO.

**Comment by smichel17** [comment]
One way forward would be to have someone *other than @mpcjanssen* distribute it on the Play Store. Since SimpleTask is [FLO](https://wiki.snowdrift.coop/about/free-libre-open#flo) Software licensed under the GPL version 3, anybody is free to do this — with modifications, if you desire — as you give credit and keep the same license.

The two basic problems seem to be:

- Google will not approve the Cloudless version due to permissions.
    - Maybe someone with more time, patience and/or connections at Google could convince them to approve the Cloudless version and be its steward.
- Google will not approve multiple similar versions.
    - Maybe several someones (definitely not one person with several accounts, which would be against Google's Terms) could release several *very different* forks, say, SampleTask for Dropbox, SimpleTux for Nextcloud, etc. They could take rebranding cues from the good folks who have [done this for Red Moon](https://github.com/LibreShift/red-moon/issues/214)

**Comment by mpcjanssen** [comment]
Note that I am absolutely fine with forks being published as long as it's clear that it is different from Simpletask.

**Comment by t7ko** [comment]
@mpcjanssen -- the link you provided earlier, for downloading Dropbox versions, is no longer working:

https://mpcjanssen.nl/artifacts

Shows empty page.

Has it been moved somewhere?
