### ISSUE TITLE
Feature Req: possibility to hide group headers

### ISSUE THREAD

**Issue by vinniec** [mpcjanssen/simpletask-android#1107]
Instead of the application's default sorting, I wanted the entries to be sorted by due date.
However, when I set the order each date became a header making the list a bit too cluttered (also because this information is written in Due:xxxx-xx-xx for each item).
To solve this, after some testing, I moved "Lua Script" above as the first sorting key, so the date headers disappeared.
It's a bad solution because right now I don't use any lua script and I don't know if using them one day I might need to move this sort key to another point in the list.
I'm not even saying to remove the headers because it depends on personal flavors and under the shell I think there is a fine tuning work because for example if the "completed" sorting key is put at the beginning, it does not cause the creation of a dedicated header, so I believe that the ability to hide headers is totally at the discretion of the developer :P
but of course when you keep the due date headers, repeat the field Due:xxxx-xx-xx for each entry is redundant, so you could add in the "other" panel the entry "show due date in the task" too with "hide sorting heading"

**Comment by mpcjanssen** [comment]
The fact that setting Lua as first story hides the headers is a bit of s side effect and has the disadvantage you mentioned. Instead define a Lua callback onGroup

```
function onGroup()
 return ""
end
```

**Comment by vinniec** [comment]
Work :)
Also if I don't know Lua, this is one of the things that makes your program very interesting.
Just a couple of days ago I was reading an [article](https://towardsdatascience.com/optimise-your-todo-list-with-monte-carlo-simulations-in-python-1682a8a5eb84) about how to make your own to-do list execution order more efficient, currently I think your app allows you to do what it says in the article.
Hidden in the apparent simplicity of your program you can create a A.I. secretary :P
