### ISSUE TITLE
Hide text using personal templates in the main window

### ISSUE THREAD

**Issue by ev-ta** [mpcjanssen/simpletask-android#111]
Add Buttons "+" in the Filter - Show
Example,
I have next task:
Bla bla bla started:1 +tags +tags2
I want see only Bla bla bla in the main window
I add text "started:1", add name - personalTag and click checkbox - personalTag

**Comment by smichel17** [comment]
This is closed by the new lua callbacks, I think.

**Comment by mpcjanssen** [comment]
@smichel17 correct once the onDisplay callback is implemented this can be closed.

**Comment by mpcjanssen** [comment]
rudimentary `onDisplay` is there. Closing this one. Any required refinements can be logged as new issues.
