### ISSUE TITLE
Keeps showing "Filename was changed remotely" / "Not switching files"

### ISSUE THREAD

**Issue by t7ko** [mpcjanssen/simpletask-android#1118]
I'm on Android Xiaomi Redmi Note 9 Pro.

Simpletask (with Dropbox), 10.9.0.  Installed manually from download location recommended here #1102.

When configuring, I chose option to enable entire Dropbox, not just the folder.

It's all functioning fine, able to sync back and forth, BUT -- on every "push" (i.e. when I modified sth on Android, and Simpletask is saving), it shows me two warnings:

Warning 1:

> Filename was changed remotely.  New name is: .... and here it gives the same path as I configured, over and over again.

Followed immediately by warning 2:

> Not switching files when changes are pending.

As I mentioned, it is syncing all ok, no issue there, but this warning keeps bugging me.  Plus, it sometimes appears on top of the keyboard, so I cannot continue typing my tasks, have to want these 5-10 seconds while it disappears.

**Comment by t7ko** [comment]
Note: the file was not modified outside Simpletask in these scenarios.  At least, I myself was not modifying it.

**Comment by aubreyz** [comment]
This is the same issue as https://github.com/mpcjanssen/simpletask-android/issues/1116

I think it is a Dropbox problem - which I why I eventually stopped using the dropbox version (and stopped my paid dropbox altogether)

**Comment by t7ko** [comment]
No @aubreyz  it does not seem to be the same issue.  I do not see any duplicate/conflict files in Dropbox in my case.

**Comment by mpcjanssen** [comment]
@t7ko two questions:

1. Do you use auto archive?
2. Can you try with the version: https://mpcjanssen.nl/artifacts/master/dropbox/release/app-dropbox-release.apk there was a race condition in the 10.9.0 version which could cause this.

**Comment by t7ko** [comment]
1. No I'm not using auto archive (I assume auto-archive is "move completed stories to done.txt automatically").
2. Will try the version you gave and report back - thank you.

**Comment by t7ko** [comment]
@mpcjanssen -- thank you, new version fixed it.  (It was v10.9.1.)  Closing the issue.  Thanks again!
