### ISSUE TITLE
Show feedback on conflict in WebDAV version

### ISSUE THREAD

**Issue by Flnch** [mpcjanssen/simpletask-android#1119]
Hi, thanks for the great app. I am using the `nl.mpcjanssen.simpletask.webdav` version from [F-Droid](https://f-droid.org/en/packages/nl.mpcjanssen.simpletask.webdav/) (version 10.9.1) on two different Android devices.

In case of a conflict, the app does not indicate this. In #454 you say the app shows a toast if a conflict occurs and Dropbox is used as sync target. However, on my devices with the WebDAV version, the app does not show a conflict notification. According to the logs, the conflict is detected (`FileStore: File conflict remote`) and I can confirm a `todo_conflict_....txt` is created. It would be really helpful to see such a message.

**Comment by mpcjanssen** [comment]
The code to show the notification is not storage specific. So the toast should be shown. Are you confusing a toast with a snackbar? It's easy to overlook a toast and I should probably make it a snackbar for conflicts.

**Comment by Flnch** [comment]
Thanks for your answer. Okay. No, I am not confusing those two. Although a snackbar would be nice. I will test it again tomorrow (as I am pretty sure there was no toast in my tests last time) and write down my exact steps.

**Comment by Flnch** [comment]
So, I tested this again and I could reproduce my situation. Here the exact steps.

## Starting situation
- Device `A` with WebDAV app and activated wifi connection
- Device `B` with WebDAV app (same synchronization target) and activated wifi connection
- `A` synced with most recent version of `todo.txt`
- `B` synced with most recent version of `todo.txt`

## Test
1. Turn off wifi of device `B`
2. Add the new item `item_B` to the list on device `B` (synchronization fails as device `B` is offline)
3. Add the new item `item_A` to the list on device `A` (this immediately synchronizes)
4. Turn on wifi of device `B`
5. Force synchronization of device `B` using button from the menu:
    - No message is shown (neither toast nor snackbar) on device `B`
    - However, the app intern log contains the file conflict
    - `item_B` disappeared from the list on device `B` and `item_A` appeared
6. Force synchronization of device `A` using button from the menu: No changes; `item_A` still on the list

The server finally contains a new conflict file with `item_B` in it.

**Comment by Flnch** [comment]
Today, I tested my described scenario again using two Android devices running the Simpletask WebDAV version `10.9.3`. It now works :tada:

Device `B` causes the conflict and a toast message `Filename was changed remotely. New name is: /todo_conflict_94235...2e.txt` is displayed. Device `B` also automatically switches its source to this conflict file.

**Comment by hollunder** [comment]
Out of curiosity, what do you refer to when you write 'toast' or a 'snack bar'?

How do you resolve these conflicts?
They happened to me rather frequently using two Android devices and webdav.
Recently I added a desktop client, so I expect this to happen even more frequently.

**Comment by Flnch** [comment]
> Out of curiosity, what do you refer to when you write 'toast' or a 'snack bar'?

This is Android jargon :smile: and refers to visual elements. [Toasts](https://developer.android.com/guide/topics/ui/notifiers/toasts) are this small popup messages at the bottom of the screen that disappear after a few seconds. [Snackbars](https://developer.android.com/develop/ui/views/notifications/snackbar/showing) are an visual message at the bottom of the actual app.

> How do you resolve these conflicts? They happened to me rather frequently using two Android devices and webdav. Recently I added a desktop client, so I expect this to happen even more frequently.

This is indeed a problem. I found no suitable solution to resolve conflicts. On conflict, the app creates a `/todo_conflict_94235...2e.txt` file and opens it. I basically re-opened the original `todo.txt` file and hoped nothing valuable was lost :laughing: Currently, I use the Simpletask version with Nextcloud as backend. There, I encounter far less file conflicts out of nowhere (with WebDAV, I often had conflicts even though all devices were online all the time and synchronized immediately after changes).

**Comment by hollunder** [comment]
> > Out of curiosity, what do you refer to when you write 'toast' or a 'snack bar'?
> 
> This is Android jargon smile and refers to visual elements. [Toasts](https://developer.android.com/guide/topics/ui/notifiers/toasts) are this small popup messages at the bottom of the screen that disappear after a few seconds. [Snackbars](https://developer.android.com/develop/ui/views/notifications/snackbar/showing) are an visual message at the bottom of the actual app.

Thanks for the explanation. What a strange jargon.
 
> > How do you resolve these conflicts? They happened to me rather frequently using two Android devices and webdav. Recently I added a desktop client, so I expect this to happen even more frequently.
> 
> This is indeed a problem. I found no suitable solution to resolve conflicts. On conflict, the app creates a `/todo_conflict_94235...2e.txt` file and opens it. I basically re-opened the original `todo.txt` file and hoped nothing valuable was lost laughing Currently, I use the Simpletask version with Nextcloud as backend. There, I encounter far less file conflicts out of nowhere (with WebDAV, I often had conflicts even though all devices were online all the time and synchronized immediately after changes).

Meanwhile I have a WebDAV mount on my desktop and use a diff tool in such cases, but this is still rather bothersome.
I don't understand how and why it happens. Just had it happen again today, even though I took care to only make changes on a device that was online at the time.
I guess there is something going wrong with the change detection or WebDAV.
