### ISSUE TITLE
Matrix room invite only?

### ISSUE THREAD

**Issue by SlidingHorn** [mpcjanssen/simpletask-android#1123]
I cannot join the Matrix chat. I'm given an error saying "You are not invited to this room"

Attempted using Element web & Nheko

**Comment by mpcjanssen** [comment]
It was indeed invite only. Should work now.

**Comment by SlidingHorn** [comment]
Thanks!  Appears as though posting permissions are also locked down

**Comment by smichel17** [comment]
It seems like at some point everyone was kicked, as well, since there's only the three of us in the room now and I know there were a decent number of folks hanging around at one point.

**Comment by smichel17** [comment]
At least in May, the freenode bridge did a similar thing, it was kicking out anyone who hadn't spoken in 30 days… which kind of makes sense on IRC, but not so much on Matrix.

**Comment by SlidingHorn** [comment]
> there's only the three of us in the room now

Is there another room that's not listed on the README? There's like 15-20 people in the room I'm in...I just can't post in it lol

**Comment by smichel17** [comment]
I'm looking at [#simpletask:matrix.org](https://matrix.to/#/#simpletask:matrix.org) and all I see is this:
![image](https://user-images.githubusercontent.com/6563664/126643767-47aebbd5-3a50-42d6-921b-c03500a22bf2.png)
Not sure if this is a visual bug on my side or what.

**Comment by SlidingHorn** [comment]
here's what mine shows
![Screenshot_2021-07-22_09-13-53](https://user-images.githubusercontent.com/6623121/126644869-6f21800a-5f30-4b78-bc0f-71e54e99f2c9.png)
