### ISSUE TITLE
Simpletask WebDAV v10.9.2 fails to sync

### ISSUE THREAD

**Issue by tallishpaul** [mpcjanssen/simpletask-android#1126]
Hi, thanks very much for a great app, it's really useful for me. WebDAV v10.9.1 has worked well since I installed it 2 months ago. I accept that I get the occasional conflict file on my Koofr cloud service. I use and change Simpletask multiple times most days and in > month I've only had conflicts on a couple of days, 4 files in total. I checked a bit and found no data loss.  I've used a Moto-G XT1032 with unofficial LineageOS 14.1 Falcon all along, in case that is relevant. I'm not a programmer in case you hadn't guessed.

After updating from WebDAV v10.9.1 and adding credentials to settings > WebDAV on startup, my todo list is shown. However, when I make a list change it fails to sync to the server. I get a "saving of todo file failed" message (snackbar I guess), and the red line at the top stays on all the time (until I close the app I think). Conflict files appear on my Koofr cloud service.

I re-installed WebDAV v10.9.1 and it is working fine again. I'm confused why no-one else seems to have reported this issue. If it's my old phone then hey-ho, but it might be a wider problem.

**Comment by mpcjanssen** [comment]
@tallishpaul when you get this issue with 10.9.2 can you paste the log here? (in settings -> other -> view debug log) there was a change in the 10.9.2 sync behavior to prevent conflicts.

**Comment by mpcjanssen** [comment]
I can reproduce tbe issue. Will look into it.

**Comment by tallishpaul** [comment]
would you still like the debug? I had just sat down to update to 10.9.2. to get a debug log...

**Comment by mpcjanssen** [comment]
@tallishpaul I think I have a fix.

**Comment by mpcjanssen** [comment]
I will make a test build available later today to confirm.

**Comment by mpcjanssen** [comment]
@tallishpaul could you check with https://mpcjanssen.nl/artifacts/10.9.3/webdav/release/ ?

**Comment by tallishpaul** [comment]
@mpcjanssen that's great, it's working now. Many thanks.

**Comment by mpcjanssen** [comment]
@tallishpaul thanks for confirming. This versiom should be on FDroid in the next view days.

**Comment by uGeek** [comment]
Many thanks! The new version works perfectly

**Comment by gerroon** [comment]
> Many thanks! The new version works perfectly

Are you sure? This new version seems to create many conflict files :(

**Comment by smichel17** [comment]
> This new version seems to create many conflict files :( I found hundreds of todo.txt conflict files since this version came out, not sure if it is a coincidence.

Are you sure they weren't created by the previous version?

**Comment by mpcjanssen** [comment]
I would suggest to completely uninstall simpletask webdav. Clean up the mess on the server and then reinstall. Re-opening a file from the menu should also work.

**Comment by mpcjanssen** [comment]
The previous version mistakenly stored the full url as the todo file location. Just updating will not change this location as it's stored in the settings. Re-installing will definitely clear this up, reopening from the menu might.

**Comment by gerroon** [comment]
> The previous version mistakenly stored the full url as the todo file location. Just updating will not change this location as it's stored in the settings. Re-installing will definitely clear this up, reopening from the menu might.

Thanks for the reply. 

Reopening the file does not cut it. I cleared the storage which did reset everything for the app then I added everything back. it seems to work now.
