### ISSUE TITLE
settings > donate broken on test build 10.9.3 WebDAV

### ISSUE THREAD

**Issue by tallishpaul** [mpcjanssen/simpletask-android#1127]
I don't now where I end up by clicking on it but the screen just displays "try again" and a broken satellite icon...

**Comment by mpcjanssen** [comment]
Not sure what's causing this. Maybe something blocking paypal links on newer Android version. The actual link is https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=mpc.janssen@gmail.com&lc=NL&item_name=mpcjanssen.nl&item_number=simpletask&currency_code=EUR&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted

**Comment by mpcjanssen** [comment]
This used to link to the Donate app on the play store. I removed all my apps from the play store so this doesn't work anymore.
