### ISSUE TITLE
If USB storage activated, todo.txt not updated afterwards

### ISSUE THREAD

**Issue by Dominik-K** [mpcjanssen/simpletask-android#113]
If start the USB storage, change something in Simpletask and stop the storage, the todo.txt file is not updated with the things I changed.

**Comment by mpcjanssen** [comment]
At kitkat and up the external SDCard is not writable anymore. This will probably not be fixed. I think I should check if a file is writable before allowing Simpletask to open the file.

For now, the save will fail, but it will be saved in an internal cache so at least you can share the unsaved tasks.

This should be handled more elegantly, maybe Simpletask can have a read only mode.

**Comment by mpcjanssen** [comment]
Android external SDCards are dying (unfortunately) and it will take an inordinate amount of effort to handle this well.
Simpletask now shows and error if a file is not changed (and a red line in the UI as feedback). The actual changes are cached in preferences and are shareable. This is the limit of the work I am willing to do on this.
