### ISSUE TITLE
simpletask adds new instances of recurring tasks at end of file, whether that line is blank or not

### ISSUE THREAD

**Issue by monomox3000** [mpcjanssen/simpletask-android#114]
When IFTTT appends a new task at the end of the file, sometimes it doesn't add a new line, i.e., the last edited point of the file is the end of the last task added. Then, when a recurring task is completed, ST rewrites that task right after my last IFTTT-added task, merging both. 
While this could be seen as a shortcoming of IFTTT, I think it would be cleaner for ST to make sure the line it is using is not occupied by another task.

**Comment by mpcjanssen** [comment]
Should be fixed, no feedback to confirm
