### ISSUE TITLE
Recurring compatibility with Sleek for desktop

### ISSUE THREAD

**Issue by zemua** [mpcjanssen/simpletask-android#1141]
Sleek for desktop has also the recurring functionality with the rec:3d kind of tag.
Though the UI by default doesn't add any number, and it recognizes no-numbered recurrence as "1"
https://github.com/ransome1/sleek/wiki/Recurring-todos-(rec:)

Would it be possible to have Simpletask recognize rec:d as it recognizes now rec:1d ?
That would help to avoid mistakes between mobile and desktop as sleek by default doesn't add any number.

**Comment by mpcjanssen** [comment]
Should not be too hard to add.
