### ISSUE TITLE
Cannot archive done tasks

### ISSUE THREAD

**Issue by roman-yagodin** [mpcjanssen/simpletask-android#1142]
After recent OS upgrade, the app start showing error "Task archiving failed" then I try to archive done tasks.

Possibly related symphtom: then I try to open another todo file, dialog shows empty file list with just ".." Folder path is correct, and there are .txt files in the folder.

Phone: Redmi Note 9S
OS: Android 11

**Comment by roman-yagodin** [comment]
Installing apk from https://mpcjanssen.nl/artifacts/master/cloudless/release/ resolved the issue.

**Comment by mpcjanssen** [comment]
@roman-yagodin I am almost 100% sure this has to do with the new storage permissions required for Android 11. This is indeed fixed in the latest cloudless version.
