### ISSUE TITLE
custom path of nextcloud todo.txt file 

### ISSUE THREAD

**Issue by Inesgor** [mpcjanssen/simpletask-android#1146]
Hi. Thank you for the great app(s). I use the nextcloud version of simpletask and i wanted to save my `todo.txt` file in a specific directory on nextcloud & not there in the root folder. I felt this is possible since the app displays path of todo file at the top, but i couldn't find any way to do it upon searching here in Issues. 
Would it be possible to do so?

**Comment by smichel17** [comment]
"Open task list file" in the menu selects a custom file. I think it must already exist, though.

**Comment by Inesgor** [comment]
It did work. Thanks mate.
