### ISSUE TITLE
Recursion Question

### ISSUE THREAD

**Issue by Grydpype** [mpcjanssen/simpletask-android#1148]
I have a question regarding the recursion-feature in Simpletask. I downloaded and installed the Dropbox version (10.9.3 from the site), and if I understand the notes correctly, a recursion of tasks is possible.

But apparently I am doing something wrong; tasks like "foo 2022-02-23 rec:d" are just checked off, they to not show up again as due tomorrow.

Am I missing something here, or using the syntax wrong?

Cheers, Oliver

**Comment by mpcjanssen** [comment]
It should be `rec:1d`. I still need to add the default is one day behaviour.

**Comment by Grydpype** [comment]
Perfect, that works. Thanks for the quick response. And congrats on this very nice software!
Cheers,
Oliver.
