### ISSUE TITLE
Assorted issues, versions 5.2.1 and 5.2.2

### ISSUE THREAD

**Issue by monomox3000** [mpcjanssen/simpletask-android#115]
I'm having problems with versions 5.2.1 and 2.
Last night I saw a task I thought I had marked as completed in my list (let's call it "task A"). I marked it as completed (again) and it reappeared a few minutes afterwards. I checked what was happening and realized that marking a task as completed didn't trigger the syncing process. Archiving tasks seemed to trigger the process (the "syncing circled appeared"). Last night Dropbox registered those changes, but this morning archiving does not sync at all (although the circle appears). 
I opened the txt file, and found task A three times (in consecutive lines), all of them marked as completed. Plus, one instance of task A not marked as completed (in its original place, a few lines above the three completed tasks A). 
I also found a few completed tasks at the bottom of the file, so archiving didn't do its job (I tried archiving several times using both 5.2.1 and 5.2.2). However, my file looks suspicious, because all the completed tasks are grouped at the end of the file (I don't think that's normal, is it?).
Then, finally, I tried to add a dummy task twice. Nothing happened. Not even locally. The task never appeared in my list. At that point I reverted to 4.2.5, which is working as advertised. 
I just installed CatLog, but I'm not sure how to operate it, or what to look for. 
I wonder if these are bugs or if I'm the only one experiencing this. 
Thanks!

**Comment by mpcjanssen** [comment]
Any updates? If this still occurs can you retry with the upcoming 5.2.13 and send the log (from settings)  if it does?

**Comment by mpcjanssen** [comment]
5.2.13
------

- Add option to send logs directly from the app. Fixes [#174](https://github.com/mpcjanssen/simpletask-android/issues/174).
- Respect calendar setting when changing dates in AddTask activity. Fixes [#145](https://github.com/mpcjanssen/simpletask-android/issues/145).
- Allow sharing of application log from the settings for better FDroid and debugging support.

**Comment by mpcjanssen** [comment]
Archiving should work properly in newer versions. If there are remaining issues please open a separate issue.
