### ISSUE TITLE
If the renaming character contains "?" , the renaming will be invalid

### ISSUE THREAD

**Issue by sjl872964789** [mpcjanssen/simpletask-android#1161]
**Describe the bug**
If the renaming character contains "?" , the renaming will be invalid

**To Reproduce**
1. Long click a file
2. Click Rename button
3. Enter a new name which containing "?"
4. Click Ok
5. The rename fails

**Expected behavior**
It should be possible to have a "?" in the file name, or the user can't type "?"

**Screenshots**
https://user-images.githubusercontent.com/15941953/164259048-ba8291d3-e012-4a9b-b98e-2c53c41117e7.mp4

**Smartphone (please complete the following information):**
- OS: Hydrogen OS
- Rooted: No
- Version: 10.9.3
- Device: OnePlus 8T

**Comment by mpcjanssen** [comment]
Eh, wrong project?
