### ISSUE TITLE
Places to send tips?

### ISSUE THREAD

**Issue by jason-mehmel** [mpcjanssen/simpletask-android#1164]
Not really an issue, but I'd love to know if there's a way to show you my gratitude, through a patreon, ko-fi, paypal, something similar! I can't offer much, but considering how quickly you solve problems and support users, you deserve it!

**Comment by mpcjanssen** [comment]
Much appreciated.

From the app go to Menu -> Help, Menu -> Donate

or directly at: [Paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=mpc%2ejanssen%40gmail%2ecom&lc=NL&item_name=mpcjanssen%2enl&item_number=Simpletask&currency_code=EUR&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted)
