### ISSUE TITLE
Click to edit task does not bring up keyboard

### ISSUE THREAD

**Issue by fmartelg** [mpcjanssen/simpletask-android#1165]
**Given** I have the latest release of Simpletask for Dropbox open on a Pixel 4a running Android 12,
**When** I click to create / edit a task
**Then** the keyboard does not come up, hence there is no way for me to create / edit tasks.

**Comment by fmartelg** [comment]
I rebooted the phone and that seems to have solved it. Will keep an eye on it and report back if it happens again.

**Comment by sphenotux** [comment]
@fmartelg it has been a while... Did the behaviour you described appear, again - ideally 😉 even reproducable?
Or can this issue be closed?

**Comment by fmartelg** [comment]
I've not experienced this again. The issue can be closed. Thank you for following up.

**Comment by mpcjanssen** [comment]
I think this is/was a bug in Android. Controlling the keyboard visibility from code is impossible as far as I was able to determine when I encountered this issue a long time ago. Glad to see it seems fixed.
