### ISSUE TITLE
Simpletask dropbox v11.0.0 not loging in

### ISSUE THREAD

**Issue by smellymoo** [mpcjanssen/simpletask-android#1181]
Was displaying a toast something like "can't save todo file" then I tried reinstalling, then tried installing the latest Dropbox version... Still Dropbox doesn't work, it keeps returning to the initial Dropbox login screen in app.

tried sharing the debug info, but it doesn't look like that works right. it just set the title to "Simpletask dropbox v11.0.0 (11000000) Git: 10.9.3-77-8094bed-dirty log" but didn't include the log.

Love your app BTW.

**Comment by smellymoo** [comment]
ran the debug version, it comes up with "simple tasks keeps stopping" before reshowing the initial login screen. it doesn't offer an option to send a bug report?

**Comment by mpcjanssen** [comment]
Are you sure you are using version 11? Which link did you use to download Simpletask?

**Comment by mpcjanssen** [comment]
@smellymoo never mind. The git version is confusing. Do you use full dropbox access or folder access?
Also did you completely uninstall the old simpletask and reinstalled the new one?

**Comment by smellymoo** [comment]
I tried both (app folder and full)

When you say "completely" what do you mean? I uninstalled it then installed git version.

How would I be able to share the debug info? It doesn't seem to be easy to do.

**Comment by mpcjanssen** [comment]
Ah it seems to be a problem with the dropbox API tokens. They were update for the new API version but now are pending review for production.

**Comment by mpcjanssen** [comment]
@smellymoo for me I see the login screen again after the `can't save todo file` toast. IS this the same for you? If so can you select Debugging Info after that and share the log?

**Comment by mpcjanssen** [comment]
For me I get a connection issue with an IPv6 address.

**Comment by smellymoo** [comment]
I'll check everything you have suggested and reply as soon as possible.

Your app is critical to my productivity, if it turns out to be hard to fix I'm happy to post a bug bounty.

**Comment by smellymoo** [comment]
@mpcjanssen tried those steps, it must be silently crashing after selecting login, as it goes back to simpletask login screen (that has debug info button).

the debug info tool needs fixing really, as it only has a share button, and you haven't got that working right, if I share it on github it just changes the title and doesn't add the file, and it's awkward to find a work around, as there isn't an option on the share menu for export file or copy to clipboard. But I figured a way round...

[simpletask.txt](https://github.com/mpcjanssen/simpletask-android/files/9034376/simpletask.txt)

**Comment by smichel17** [comment]
> there isn't an option on the share menu for [...] copy to clipboard

This excellent app adds one! https://f-droid.org/en/packages/com.tengu.sharetoclipboard/

**Comment by smellymoo** [comment]
> 07-03 09:40:28.357 17080 18943 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.dropbox.core.DbxRequestConfig.getUserLocale()' on a null object reference
07-03 09:40:28.357 17080 18943 E AndroidRuntime: 	at com.dropbox.core.DbxPKCEManager.makeTokenRequest(DbxPKCEManager.java:107)
07-03 09:40:28.357 17080 18943 E AndroidRuntime: 	at com.dropbox.core.android.AuthActivity$TokenRequestAsyncTask.doInBackground(AuthActivity.java:793)
07-03 09:40:28.357 17080 18943 E AndroidRuntime: 	at com.dropbox.core.android.AuthActivity$TokenRequestAsyncTask.doInBackground(AuthActivity.java:782)
07-03 09:40:28.357 17080 18943 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)

looks to be the issue.

**Comment by mpcjanssen** [comment]
Seems to be caused by: https://github.com/dropbox/dropbox-sdk-java/issues/347
Not much I can do about that. Do you by any chance use process cleaners or things like that? Probably not, but if you do disable all of them.

**Comment by smellymoo** [comment]
I don't even know what that means? I'll go with no.

**Comment by smellymoo** [comment]
one of the last messages in that thread seems vital: https://github.com/dropbox/dropbox-sdk-java/issues/347#issuecomment-1011462566

> The problem is the AuthActivity instance at step 3 may not be the same instance created at step 1. Android is free to kill and re-create activities as it wishes. It's quite easy to reproduce such a situation. Between step 2 and step 3 when we are in the browser or Dropbox app, rotate the device to change its screen orientation. Then tap on "Allow" button.

suggesting to me that it you are right that it is a dropbox-sdk issue, but that also it could easily be avoided by changing the activity flow, so just guessing, it changes between the login activity, and another, during that it gets confused and calls a null pointer, that kinda thing.

**Comment by smellymoo** [comment]
on a plus side, I have started using [sleek](https://github.com/ransome1/sleek) on my laptop in the interim until your (fabulous) app is fixed. So I can continue my work at least :). Whole reason I took up the todo.txt philosophy is for this exact problem (2 fold; multi-platform and no propriety lock in), so feeling very smug overall :+1:.

**Comment by mpcjanssen** [comment]
@smellymoo the creating of the dropbox login activity is done by the dropbox SDK. I don't think I can control that in any way. But I will look into it.

**Comment by aubreyz** [comment]
> on a plus side, I have started using [sleek](https://github.com/ransome1/sleek) on my laptop in the interim until your (fabulous) app is fixed, so I can continue my work at least :).
> 
> Whole reason I took up the todo.txt philosophy is for this exact problem (2 fold; multi-platform and no propriety lock in), so feeling very smug overall 👍. But the missing link for me is dropbox synch, it allows me to be cross-platform with 1 todo list.

Sleek is a great contender. Unfortunately a) at the moment the engine it uses scrambles the order of then data line (putting tags at other positions) and b) there is as yet no good system for saved filter/sort profiles as in simpletask. However Sleek is by far the best desktop contender for a simpletask companion.

**Comment by smellymoo** [comment]
So is there anything that can be done to use Dropbox atm? I can't find a way to synch files outside of the app in android?

Do you think a bug bounty will help this? Guess it won't to Dropbox, but might help you find the enthusiasm to solve it?

**Comment by smellymoo** [comment]
is this https://github.com/todotxt/todo.txt-android/pull/509 helpful?

**Comment by smellymoo** [comment]
Ooo... Just found that "Jopin" from f-droid works well with Dropbox (using private "app" folder too) and I assume it's open source. Good to fix dropbox support 😏

**Comment by smellymoo** [comment]
@mpcjanssen this source code will definitely help fix the dropbox issues, specially as it does it in it's own app folder :D

**Comment by smellymoo** [comment]
have you fixed something? I got version 11.0.1 working!
