### ISSUE TITLE
simpletask on sourceforge -- consider deleting entirely?

### ISSUE THREAD

**Issue by xkcd386at** [mpcjanssen/simpletask-android#1189]
Apologies; this is not really an "issue" with the tool per se.  I love the tool, and use it every single day -- thank you for your efforts and getting us such a clean product with so many features!

Somewhere, somehow, a search for simpletask got me to https://sourceforge.net/projects/simpletaskandr/ and I was momentarily stymied by the "Status: Abandoned" note at the top.  Then I saw the "last update 2013" and realised I had to fix my search.

But there is potential for confusion.

Not sure if sourceforge allows you to change that text and make it link to github.  Or maybe since the last update is 2013 you could just delete the sourceforge repo/page completely.

Once again, apologies if this is a stupid issue to raise, and thanks for a great tool!

**Comment by mpcjanssen** [comment]
I was not aware of this project anymore. Thanks for putting it to my attention. Deleted now.
