### ISSUE TITLE
System / Device-based light / dark theme.

### ISSUE THREAD

**Issue by dessalines** [mpcjanssen/simpletask-android#1194]
Most apps can now theme either light or dark, based on the system theme. 

This would be useful to have, as I have the dark theme default, but when I go outside when its light out, I have to manually change the theme to light, to be able to read my tasks.

**Comment by adastx** [comment]
I'm gonna try and implement this, at some point in the near future.
Seems like a good first issue.

**Comment by ulville** [comment]
Is there any work done regarding this issue? I would like an option to follow the system theme (light/dark) both for main app and for the widgets. My phone has an option to switch between dark and light themes based on time of the day. It's really annoying when everything turns dark but my simpletask app/widget keeps beaming brightness on my face or vice-versa.

**Comment by dessalines** [comment]
I've switched to tasks.org , both because the app is much more maintained, and also because the the todo.txt protocol [stopped development > 4 years ago](https://github.com/todotxt/todo.txt/issues/80#issuecomment-1355844363), and there are only few apps hanging on. It has the automatic theme light/dark theme.

I've written a todo.txt format -> tasks.org script, linked in that comment.

**Comment by ulville** [comment]
> I've switched to tasks.org , both because the app is much more maintained, and also because the the todo.txt protocol [stopped development > 4 years ago](https://github.com/todotxt/todo.txt/issues/80#issuecomment-1355844363), and there are only few apps hanging on. It has the automatic theme light/dark theme.
> 
> I've written a todo.txt format -> tasks.org script, linked in that comment.

@dessalines I don't agree with todo.txt protocol being unmaintained/dead. It's a simple protocol at its core but extensible via key:value tags. And mature enough for most usecases. It's a good thing its core is stable which means it's future proof.

I tried Tasks.org before and it's good for some peoples usecases but I prefer something todo.txt based rather than something more obscure. I like being able to quickly search or edit my tasks from a terminal or a code editor for example.

@adastx @mpcjanssen If you're still interested implementing it I'm opening a new issue regarding this request. I beleive it's something that a lot of people would appreciate

**Comment by aubreyz** [comment]
> I've switched to tasks.org , both because the app is much more maintained, and also because the the todo.txt protocol [stopped development > 4 years ago](https://github.com/todotxt/todo.txt/issues/80#issuecomment-1355844363), and there are only few apps hanging on. It has the automatic theme light/dark theme.
> 
> I've written a todo.txt format -> tasks.org script, linked in that comment.

This is comparing chalk and cheese. An intentionally simple and flexible text based system that is reliant on little else and is future proof (and can be addressed with a LOT of tools that will be used by some people who know what they are doing), with a closed system that will certainly suit some people. Nothing wrong with either. The whole point of the todo.txt protocol is that it does not "develop" (within limits) albeit the tools that are applied might.

**Comment by dessalines** [comment]
tasks.org is not a closed system, the software and format is fully open source, and exportable / importable.

Meanwhile, the mainainers of todo.txt are mostly MIA, and have issues and PRs on their repo that have gone unanswered for going on 5 years now. "future-proof" means being able to adapt to change and add features as necessary, not to stagnate. 

As proof, this app here is the last *somewhat actively developed* todo.txt client, there are no other apps, except for one other closed source one. If the todo.txt format were healthier, it would have an entire ecosystem of actively developed applications on different platforms.

**Comment by aubreyz** [comment]
> 

Open source and closed system have nothing to do with each other. There is a whole ecosystem -- it is called the code text editor -- which has been around for 50 years and will be around for the next century - with thousands of apps, grep tools, diff tools and so on. (tasks.org is a closed system, not based on any standards, cannot be read with a text editor, and is also a commercial paid-for app with features locked away -- it is a good app, but you are coming here to make completely erroneous comparisons and slurs based on a concept of pure text-based functionality you don't really understand. 

If you want to go the tasks.org route, there are MANY other competitors so you would be best attacking those not this.
