### ISSUE TITLE
archived tasks in done.txt not a separated by linebreak

### ISSUE THREAD

**Issue by trevor87** [mpcjanssen/simpletask-android#1200]
I am not sure if this is intended: When tasks are marked as done and added to done.txt the line breaks in the file are missing.

Example:

![Screenshot_20220911-140334~2](https://user-images.githubusercontent.com/6329259/189526651-d65612f1-2b59-43a0-b9f1-99551d6aa093.png)

I did not find a setting to change this. I also tried setting it to "use windows linkebreaks" but it did not change anything.

I am using the cloudless version 11.0.0 from fdroid.

Edit: I am using the auto-archive setting.

**Comment by smichel17** [comment]
Hi, this is a duplicate of https://github.com/mpcjanssen/simpletask-android/issues/1187

@mpcjanssen Maybe we should push a new release to F-Droid?

**Comment by trevor87** [comment]
Thanks for the quick answer! While I searched for this issue it seems I forgot the closed issues..

**Comment by sphenotux** [comment]
Hi, sry to intervene, just trying to clean up a little...
@smichel17 says (above) this is a duplicate. So, I guess, @trevor87 this issue can be closed..?

**Comment by smichel17** [comment]
Let's leave it open until a new release is out, lest we get more dupes (GitHub doesn't do a very good job of reminding you to search closed issues).

**Comment by trevor87** [comment]
I agree with smichel17. I think it would be easier to find if it is open.

**Comment by sphenotux** [comment]
OK. - Question: How do you track to close **this** very issue once the release is out?

IMHO the less issues open, the better 😉?!

**Comment by trevor87** [comment]
Just got the new release on fdroid and the problem is solved. Thank you very much!
