### ISSUE TITLE
implement easy ways call http links (and other links), stored in tasks

### ISSUE THREAD

**Issue by aisbergde** [mpcjanssen/simpletask-android#1202]
I can share http links to Simpletask and they look like "https://aaa.bbb.ccc/ddd.html"

But is hard to open them. I need to edit, then I can mark the link, then I get a context menu where I can select to browse the link.

It would be fine to implement a more easy way to call the link, without the need to open the task for editing. But directly from the task. Maybe using one more action button, which could open the first link in the task (in case there are more then one link)

When I use Markor to open my todo.txt, then it is easier to select the link, because Markor is always in the edit modus.

I am using MIUI, and I know that often context menus on links are not available in MIUI, but in other android phones. Maybe this is also the case here. But I can't do anything regarding the MIUI limitations. And I know, that some apps are able to provide context menus on links, others are not. I don't know, why this happens.

**Comment by smichel17** [comment]
It is not very discoverable, but if you long-press on a task, it will open up a pop-up list of links in the task (including `tel:` links, for calling phone numbers)

**Comment by aisbergde** [comment]
Oh, this works fine! I didn't try a long press. Maybe this could be explained in the help docs?

**Comment by smichel17** [comment]
Or even better: https://github.com/mpcjanssen/simpletask-android/issues/911

**Comment by sphenotux** [comment]
IMHO #911 is a good approach, would have made it easier for me as well 😊.
So @aisbergde Thank you for your suggestion - can this #1202 be closed?
