### ISSUE TITLE
Missing newline at end of file

### ISSUE THREAD

**Issue by CoD-ZT** [mpcjanssen/simpletask-android#1205]
Simpletask v. 11.0.0 (no sync support) doesn't add a newline at eof when adding a task.
How to reproduce:
- in settings enable "append to file"
- add a new task
- import to pc
- add a task from pc

the last task will be on the same line of the previous one because no newline was added at the end of file

**Comment by mpcjanssen** [comment]
Try with 11.0.1. This should be fixed by https://github.com/mpcjanssen/simpletask-android/commit/d4a79f3fd2a67b57d9b8553ed2963aba0f2f89ba

**Comment by CoD-ZT** [comment]
Confirmed. That was quick! Thank you
