### ISSUE TITLE
v10.9.0 for NextCloud crashes when trying to open todo.txt files

### ISSUE THREAD

**Issue by nnako** [mpcjanssen/simpletask-android#1210]
Hi,

I use the NextCloud version of SimpleTask v10.9.0 as this is the version which I can install on a Samsung Note 8 device (Android v9) from GooglePlay.

Using different todo.txt files for different people / projects, I sometimes have to open different files using the menu within the app. Unfortunately, I recently discovered that the SimpleTask app immediately crashes after choosing "open todo.txt file" from the app's top menu (three dots).

Can somebody help me solving this issue? Is there an new SimpleTask version to come?

In the meantime...

If I knew, in which file within the Android file system the current todo.txt path was specified, I could change it there. Until the "open todo.txt file" works properly, again.

Thanks.

**Comment by sphenotux** [comment]
Hm... I am using ST Nextcloud edition v11.0.1 from F-Droid store. Opening a todo.txt file, or switching to (and back from) a different file, works.
I can not estimate if this is a major issue, or a minor issue, and if it is a simpletask issue at all.
Would this be an option in the meantime: use a text editor for the todo files on your phone?
*Yes, I know, less comfortable 😉, but maybe better than nothing.*

**Comment by sphenotux** [comment]
... What do you mean @nnako where does simpletask store the user's settings, config on the phone? (currently searching, but typing here to gain time ;—))

**Comment by nnako** [comment]
Hi @sphenotux . Thank you for your quick answer. Yes, I will, as a temporary workaround, edit the text file by hand (that is one of the benefits of using text-based data stores). In your 2nd comment  you asked:

> What do you mean where does simpletask store the user's
> settings, config on the phone?

I thought that SimpleTask stores its configurations somewhere on my phone. Configurations e.g. about where the recently loaded todo.txt file is located within the connected NextCloud server. By editing this file location (path) within the configuration file, I would be able to manually change the path which SimpleTask uses at startup to load the todo.txt file. Then I probably could continue using SimpleTask to edit that file.

A workaround if the load via menu does not work properly.

One further question:

>  I am using ST Nextcloud edition v11.0.1 from F-Droid store...

Is SimpleTask not updated on PlayStore, anymore? Why? Does it have to do with hosting costs?

**Comment by sphenotux** [comment]
OK, I interpreted your 'backdoor approach' right. By the way found no config folder or settings file. Check source code? Hm.
As an option: Remove ST Google PlayStore version, and give F-Droid edition a chance?
Well knowing this is not a, or THE, solution - however, worth trying?

**Comment by mpcjanssen** [comment]
@nnako Simpletask stores the configuration in stand Android settings. This an XML file under the covers but not something you can easily modify.
If you want to edit a local copy of a `todo.txt` file you should use simpletask cloudless. 
Regarding the other question, Simpletask is only on FDroid or directly on https://mpcjanssen.nl/artifacts/ see #1102 for the rationale.

**Comment by nnako** [comment]
Hi, thanks for the information so far.

I just (accidentally) solved this issue by disconnecting and reconnecting from / to the NextCloud server. This got me the message that the "certificate changed" within the app. Which I had to confirm to become valid again. After this, the change of todotxt files using the respective menu in the SimpleTask app works again.

In order for other users to not run into the same issue, it would be good to provide an appropriate error message within the app instead of just letting the app crash without notice.

Thanks for this great app.
