### ISSUE TITLE
Allow preprocessing of new/updated tasks in Javascript

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#122]
Because we now have the embedded Javascript engine, we can add functionality to rewrite tasks in Javascript before adding or updating them.

This will allow scenarios such as:
- Squash duplicate whitespace
- Move tags or lists to the end
- Shorthands (e.g, \St -> Simpletask)

**Comment by smichel17** [comment]
Would it be possible / make sense to replace LUA script functionality with js?

**Comment by mpcjanssen** [comment]
Rhino Javascript was replaced with Lua. The main reason being that its easier to embed and it performs better. The functionality is the same.
If there are better javascript engines I might consider going back because Lua is not widely know. I would love if this could be kotlin as well.

**Comment by smichel17** [comment]
Ah. I agree, kotlin would be the best, if that's possible. I went through all the issues related to filtering and referenced this one, so it is a good place to discuss how filtering should be implemented, going forward.

**Comment by smichel17** [comment]
Does the new lua engine close this?

**Comment by mpcjanssen** [comment]
@smichel17 not yet, I will need to add the onUpdate callback first

**Comment by mpcjanssen** [comment]
Partially supported using `onAdd` Lua callback.

**Comment by mpcjanssen** [comment]
Remaining part `onUpdate` is covered by #933.
