### ISSUE TITLE
lua library compilation time

### ISSUE THREAD

**Issue by k4nd1l** [mpcjanssen/simpletask-android#1231]
Hello ,
I am using the same library to compile lua script in kotlin . This script has functions defined in lua and others defined in kotlin class which i load to the globals. The purpose of this is to carry our some functions on database related entries. I append a certain formula call to the script and call it to return the value. This is done by feeding the luaService the a list of formulas one after the other. I find that this endpoint takes a lot of time and I think the library used is the issue . Do you have insight on a different library that i could use to compile lua in kotlin?

**Comment by mpcjanssen** [comment]
Not really, the lua library used in simpletask seems fast enough.
