### ISSUE TITLE
Provide merge of conflicted copies

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#130]
If there is a conflict when writing to Dropbox, the Sync API will create a conflicted copy of the todo.txt. If that happens, offer the use an option of merging the conflicting files. This requires:

* A merge algorithm, without graphical merging combining and removing duplicates is the best we can do.
* Detect conflict, this is surprisingly hard to do in code with the Sync API. Maybe offer the user a general merge option so other files could also be merged.

**Comment by mpcjanssen** [comment]
Never going to happen. Merge conflicts should be very rare now and the history database and dropbox conflicted copy behavior make it less scary if they do -> closed

**Comment by ndemou** [comment]
Out of curiosity, after 1 year did your prediction for very rare conflicts turned to be accurate? I've been using todo.txt app for 2 months and had one conflict and it was silent (I only found out by accidentally looking at the dropbox folder). Got really worried, started googling and found your app and this issue.

**Comment by mpcjanssen** [comment]
Conflicts can indeed happen (easily) the never going to happen was meant as I will never include merging in simpletask. I can add a notice if a conflict has occurred (and a conflicted copy is created )

**Comment by mpcjanssen** [comment]
See #454
