### ISSUE TITLE
Only archive tasks in current view

### ISSUE THREAD

**Issue by alehandrof** [mpcjanssen/simpletask-android#131]
When no tasks are selected, and the view is filtered, I would like the Archive option to only archive the completed tasks in the current view.

The current behavior is to archive all tasks. What I'm requesting for is a setting to alter the behavior, but IMO, what I suggest is a lot more logical than the current behavior.

But I would think that, wouldn't I? :)

**Comment by y2kbugger** [comment]
I like this Idea also.

**Comment by mpcjanssen** [comment]
Closed with 7ef7b9d601d6e6754dc8960836c9858679972efe
