### ISSUE TITLE
Make list and tag prefix configurable

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#133]
Currently the list and tag prefixes are @ and +. It would be nice if this is configurable so we could have ! for list and # for tag for example.

This doesn't have the issues that changing the terms has, but it will result in writing files which are not in the todo.txt format anymore.

**Comment by smichel17** [comment]
I would advise not to break the todo.txt format. However, I would support custom prefixes as an _extension_ of the format.

**Comment by smichel17** [comment]
#122 has a bit of overlap with this issue.

**Comment by smichel17** [comment]
I think this is closed by the updated lua functionality.

**Comment by mpcjanssen** [comment]
This will break `todo.txt` format for little benefit. It will also make parsing the tasks more complex. Not going to happen.
