### ISSUE TITLE
Due date notifications

### ISSUE THREAD

**Issue by ubuntudroid** [mpcjanssen/simpletask-android#138]
It would be great if the app would notify the user of tasks due at the same day using the Android notification system. The user should be able to set a specific time when the daily reminder occurs. Default could be 8 am.
In the first implementation iteration clicking on the notification could simply open the app. Further iterations could add quick actions like "Mark as done" or "Delay until tomorrow" for single task notifications. Clicking on multi task notifications could route the user to a specific "due today" page (which would be a feature on its own).

**Comment by the-solipsist** [comment]
I really enjoy Simpletask, but I too was missing this feature.  Are there plans still of adding this?

**Comment by ubuntudroid** [comment]
Sorry, real life turned out much more demanding than hoped - and I've switched to another TODO manager in the meantime, so unfortunately don't see any realistic chance for this to be completed by me, sorry! :(

**Comment by the-solipsist** [comment]
If I may ask, which one do you use now?

**Comment by ubuntudroid** [comment]
@the-solipsist [Todoist](https://todoist.com).

**Comment by vojtechkral** [comment]
I implemented this via calendar reminders about a year ago... (I hope I'm talking about the same thing here).

**Comment by mpcjanssen** [comment]
@vojtechkral it's part of the functionality. But between being able to sync with the calendar and putting custom Lua filters on a widget, more of this functionality is very low on the list.

**Comment by smichel17** [comment]
@the-solipsist I'm a little confused. What would this feature add that calendar reminders on due/threshold dates does not already cover?

**Comment by mpcjanssen** [comment]
Use calendar integration for this. More is not going to happen.
