### ISSUE TITLE
Add Simpletask to the todotxt.com website

### ISSUE THREAD

**Issue by alehandrof** [mpcjanssen/simpletask-android#147]
Instructions: http://blog.todotxt.com/post/97913180512/faq-how-do-i-let-the-community-know-about-my-new

**Comment by mpcjanssen** [comment]
This doesn't seem to go anywhere. Closing, if you really want this to happen follow the link above to the todotxt.com issue.

**Comment by mpcjanssen** [comment]
Note: the todo.txt gh-pages was merged 8 days ago.

**Comment by alehandrof** [comment]
Indeed. I was offline for a couple of weeks, so I didn't catch up until yesterday.
