### ISSUE TITLE
Use 'tri-state' checkboxes when changing tags or lists on multiple tasks

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#149]
This should solve the following issue:

Here goes. Whenever you click multiple items from different categories, say @Buy and @Call and @Waiting, to add them (with the list icon) to a new list let's say @Computer this assigns *all* categories to the selected set. So, even when a todo item did not have a @Buy and I just wanted to add @Computer, it gets @Buy,@Waiting,@Computer  and @Call. That of course is undesired as I just wanted to add a single category, not all.

**Comment by y2kbugger** [comment]
Thanks! This is one of the things I came here to submit.

**Comment by mpcjanssen** [comment]
Fixed in 7.0.16. For any UI updates log a new issue.
