### ISSUE TITLE
Enhance filter option

### ISSUE THREAD

**Issue by directional-star** [mpcjanssen/simpletask-android#160]
It would be great to apply an 'AND' filter to contexts - currently when multiple contexts are selected for filtering tasks, tasks with any one of the selected contexts are displayed. 

I have multiple tasks that I must do @Home that also requires a @Laptop. Currently when @Home and @Laptop context are filtered - tasks with @Home OR @Laptop are displayed. 

I can an option to have the default filter behaviour (AND  or OR) will be great. 

I can get around the current issue using an unnatural context @HomeLaptop when there is not such thing as a Home-Laptop in my case.

**Comment by mpcjanssen** [comment]
With the embedded Lua filtering and filters are fairly easy to write as a script. For example

```
function onFilter(t,f,e)
  return f.lists.listA and f.lists.listB
end
```

will return all task with `listA` and `listB`

**Comment by smichel17** [comment]
**I think this use case is common enough that we should support it natively.**

*However!*

I don't think this requires an AND filter; I don't think anybody wants to create different filters for:

- `@home` AND `@laptop`
- `@work` AND `@laptop`
- `@laptop` AND `@phone`
- `@home` AND `@phone`
- etc.

Nor would it be any fun to try each of those combinations manually from the left drawer.

---

@directional-star would it solve your problem if you could select all of the contexts where they are right now -- `@home`, `@laptop`, `@phone` -- and have simpletask only show tasks that have a subset of these contexts (ie, all the tasks you can do right then -- those that require being `@home` and/or `@laptop`, but no other contexts)?

You can actually get that functionality right now, without lua, albeit in an awkward way: invert the filter, then select all contexts *except* `@home` and `@laptop`. 

---

In any case, this is a bit hard to implement with the current UI, so I suggest waiting until we make major UI changes to tackle it.

**Comment by arvinboggs** [comment]
Any news on this feature? I would love to use a "match all tags" feature. As it stands now, I have no usecase for the "match any tag". Thanx.

**Comment by smichel17** [comment]
@arvinboggs I'm working on a UI update, next iteration will be up soon in #484. We should wait for that, to work on this.

**Comment by mpcjanssen** [comment]
@arvinboggs for now any filters not directly supported by the UI can easily be achieved by Lua scripting (this was part of the reason for adding it) so either you add a script (it's not that hard once you grasp Lua) or you wait and hope the UI will ever support it.

**Comment by smichel17** [comment]
@mpcjanssen this is about quick filtering though, not saved filters.

**Comment by arvinboggs** [comment]
@smichel17, @mpcjanssen Thanx for prompt reply. Sorry if my first post sound as if I'm impatient but reading the previous posts (circa 2014) of this issues, I thought that the feature was already added but was eventually removed.

**Comment by mpcjanssen** [comment]
@arvinboggs. No problem. Just wanted to make sure you were aware that its possible in scripting. For quick filtering that doesnt help though.
