### ISSUE TITLE
Simpletask - item in Settings untranslated

### ISSUE THREAD

**Issue by onekk** [mpcjanssen/simpletask-android#161]
Some items, "Font size" and the relative description is untraslated in italian translation.

string name="ARCHIVE_settings_header" seem to be unapplied and string name="archive_now_pref_title">Archivia ora</string is applied instead

"Donate" and the relative description is untranslated and so is the "Experimental" title and item

In the "left drawer" the titles "list" and "tag" in italian must be plurals what string name this items have? 
If  you please update the files i will refine the existing translation and  complete the translation also with the new strings. 

Carlo D.

**Comment by smichel17** [comment]
You've been playing with settings recently -- is now a good time to close this?

**Comment by mpcjanssen** [comment]
Closing for other/new missing translations open a new issue.
