### ISSUE TITLE
Optional attachment

### ISSUE THREAD

**Issue by somenxavier** [mpcjanssen/simpletask-android#168]
Hi,

Can you improve your simpletask cloudness with attach files?
Some tag like `^attach:".
I think technically, it's better to include a link to a file rather than copy in the task.

Thanks,

**Comment by y2kbugger** [comment]
I think attaching photos is a bit beyond the scope of a todo.txt based app

**Comment by somenxavier** [comment]
Well, change attachment for link and this is what I want. A link is just a text. Attachment is a whole file.

**Comment by mpcjanssen** [comment]
http:// links are supported. Anything else is not going to happen, sorry.
