### ISSUE TITLE
Widget stops updating when changes are made in app.

### ISSUE THREAD

**Issue by tigamai** [mpcjanssen/simpletask-android#169]
The widget stops updating sometimes when new tasks are added.

The following types of updates also have no effect on the widget:
- new tasks don't appear (as above)
- marking off a task as complete in the app
- opening a different todo list from the app doesn't update the list being shown in the widget

The bug has occurred twice but I have been unable to reproduce it.

The bug can be worked around by removing the widget and re-adding it again.

Version info:
Simpletask Cloudless: 5.2.12 from F-Droid
ROM version: cm-11-20141008-SNAPSHOT-M11-hammerhead (android 4.4.4)

**Comment by mpcjanssen** [comment]
hmm it seems a bit more involved than that. Next release will include the option to send app logs directly from the application. If this issue occurs again with that version, then please send me the logs.

**Comment by tigamai** [comment]
Another occurence of the bug.

Renamed a pre-existing task "@Work sometaskA, sometaskB" to "@Work sometaskA" and created a new task "@Work sometaskB". Widget still shows "@Work sometaskA, sometaskB" (i.e no changes made). Loading the app shows the edited task and the newly created task.

Here's the application log at the time:
--------- beginning of /dev/log/main
[ 01-13 04:39:50.775  8223: 8223 V/Simpletask ]
onCreate

[ 01-13 04:39:50.835  8223: 8223 V/Simpletask ]
handleIntent: launched with filter+!completed,+!by_context,+!by_prio,+!alphabetical,+!file_order,+!by_project,+!by_creation_date,+!in_future,+!by_due_date,+!by_threshold_date

[ 01-13 04:39:50.835  8223: 8223 V/Simpletask ]
handleIntent: saving filter in prefs

[ 01-13 04:39:50.835  8223: 8223 V/TodoApplication ]
Preference TITLE changed

[ 01-13 04:39:50.835  8223: 8223 V/TodoApplication ]
Preference JAVASCRIPT changed

[ 01-13 04:39:50.835  8223: 8223 V/TodoApplication ]
Preference JAVASCRIPT_TEST_TASK changed

[ 01-13 04:39:50.835  8223: 8223 V/TodoApplication ]
Preference query changed

[ 01-13 04:39:50.845  8223: 8223 V/Simpletask ]
setFilteredTasks called: nl.mpcjanssen.simpletask.task.TaskCache@41c352e8

[ 01-13 04:39:51.125  8223: 8223 I/Timeline ]
Timeline: Activity_idle id: android.os.BinderProxy@41c53798 time:39244037

[ 01-13 04:39:54.905  8223: 8223 V/Simpletask ]
onMenuItemSelected: 2131230800

[ 01-13 04:39:54.905  8223: 8223 I/Timeline ]
Timeline: Activity_launch_request id:nl.mpcjanssen.simpletask time:39247815

[ 01-13 04:39:55.225  8223: 8223 I/Timeline ]
Timeline: Activity_idle id: android.os.BinderProxy@41b16e10 time:39248135

**Comment by mpcjanssen** [comment]
Is this still an issue?

**Comment by tigamai** [comment]
Seems like the issue is fixed (tested in 6.0.8).

It was an intermittent issue but I've been using simpletask a fair bit over the last few months and haven't seen the problem again.

**Comment by mpcjanssen** [comment]
@tigamai thanks for the feedback. If this happens to reoccur don't hesitate to reopen, but I think the redesign of the data backend actually did fix this.
