### ISSUE TITLE
Allow recurring with business days.

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#172]
Received via email:
it would be nice to have the option to specify recurrence based on working days. For example rec:5wd will be a week later.

**Comment by smichel17** [comment]
implemented as of 957c50fabe46b3db714de86044edea34ef7de080?

**Comment by mpcjanssen** [comment]
@smichel17 not quite. A week day is not the same as a working day. It ignores bank holidays for now. However adding bank holidays is never going to happen anyway so indeed implemented as much as feasable.
