### ISSUE TITLE
Saved views

### ISSUE THREAD

**Issue by RomainEndelin** [mpcjanssen/simpletask-android#177]
First of all, thanks for the great app :).
I am using simpletask for GTD. I have a particular setup which I really love. It relies mostly on `priorities`: *No priority* is for **inbox**, *A* and *B* are for **next actions** (*A* for what I plan today, *B* for later), *C* is **someday/maybe**, and *D* is **waitingFor**.
In addition, I have a lean way to manage my projects: I simply let them emerge from my `+aProject` in taks.

As you can guess, I need to use filter very often to either see my inbox, my next actions, etc... Thanks to the widgets, I can easily run simpleTask with filters. But it would be great to maintain a list of `saved views`/`saved filters` and easily switch views in the side-panel.

Thanks

**Comment by mpcjanssen** [comment]
This is already implemented:
1) Set the proper filter
2) Slide from the right
3) Press the plus
4) Name the filter (saved filters are alpha sorted so you can use numbers for ordering)
5) Press OK

Now pressing the saved filter will apply it. Long pressing gives some options to change the filter.

**Comment by RomainEndelin** [comment]
Oh yes! Sorry that I didn't see that before posting the issue... Thanks :).

**Comment by mpcjanssen** [comment]
No problem. If anything, this proves that the discoverability of the right navigation drawer is not as it could be.
