### ISSUE TITLE
Dropbox sync can be slow

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#178]
In certain situations (for instance after being offline) Simpletask takes a long time to detect remote changes. This seems to be cause by slow syncing of the Dropbox Sync API.

Several approaches to fix this:

- Investigate an option to force sync
- Switch back to the core API and make polling and syncing from scratch. The Sync API didn't bring what I hoped anyway (seamless sync)

**Comment by kalafut** [comment]
Yes.

It's also probably a contributor to a lot of "Conflicted" copies I've been seeing. At this point, I've taken to stopping and restarting the app if I've been working on my laptop, for fear that changes might not have been picked up and edits will cause more conflicts.

**Comment by mpcjanssen** [comment]
New versions use the Core API again and handle connection detection and syncing from code. This should be fixed. If not please open a new issue.
