### ISSUE TITLE
When editing lists and tags, checked lists or tags should rise to the top 

### ISSUE THREAD

**Issue by y2kbugger** [mpcjanssen/simpletask-android#180]
For example if you want to move a task from one list to another, it would be helpful to have the list that it is already on right at the top for easy access.

**Comment by smichel17** [comment]
I think this is one of those things that sounds great on paper, but then when you try it out it's actually just really confusing to have your tasks jumping all around when you select them. If @y2kbugger agrees, my vote is to close this.

**Comment by y2kbugger** [comment]
Hmm, i wasn't clear here. I didn't mean for them to move interactively. I meant when editing an old task sort the checked ones to the top, in addition to the being in their normal order. separated by a thin gray live (or something) from the bulk list.
This is helpful for two reasons: you can see which lists were already associated at a glance, and it makes it quicker to remove a list or two. when checking a new list it should just check in place like normal.

**Comment by y2kbugger** [comment]
The idea is similar to using a customer's IP address and floating their country to the top of the combo box on e-commerce sites.

**Comment by smichel17** [comment]
Ah! I think you mean on the popup where you pick lists/tags? So if I have this list:
```
a @a
b @b
c @c
d @d
```
And it's sorted by context so it appears like:
```
a:
  a
b:
  b
c:
  c
d:
  d
```
If I select d and b, then open the list dialogue, it will look like this:
```
b ☒
d ☒
a ☐
c ☐
```

**Comment by y2kbugger** [comment]
not sure I understand how that the middle part about how it sorted is relevant, but yes.

Just to give a more relatable picture:
```
get a new lawnmower @projects @store
tissues @store
cereal @store
learn chinese @projects
yellowstone @vacationPlaces
sonic reducer - the deadboys @music
mars attacks @movies
```

Showing how it would work with tri-value checkboxes if you selected the first two on the above list:
```
store☒ <--fully checked
projects ☒ <--partial(grey) checked
------------------------------
movies ☐
music ☐
vacationPlaces ☐
```
and I would like to promote the idea of making the "floated" lists *in addition* to the regular list for reasons described below. 
```
store☒ <--fully checked
projects ☒ <--partial(grey) checked
------------------------------
movies ☐
music ☐
projects ☒ <--partial(grey) checked
store☒ <--fully checked
vacationPlaces ☐
```
The *in addition* method would be especially helpful when using prefixes to denote list type eg. all checklists start with ^ so if you are moving something from the `@^weekly` to `@^monthly` they will still be adjacent in the popup rather than one at the top and one buried in the list. Also, when you have 200 lists duplicating the two or three that go at the top won't be a clutter or performance hit.

**Comment by smichel17** [comment]
You can use this for partial checked: ☑

**Comment by smichel17** [comment]
Now that I understand this idea, I like it very much.

**Comment by y2kbugger** [comment]
Also for sure don't try to make them disappear from the top when unchecked. Though adding `@lists` to the top when checking might provide a nice summary of your changes before committing them

**Comment by smichel17** [comment]
>Though adding `@lists` to the top when checking might provide a nice summary of your changes before committing them

I think that this would be confusing, because each time you checked a list it would shift the location of some of the others. It would also be more confusing if un-checking a list did not remove it from the top (since you would be taking away the "lists at top were initially checked" paradigm but not introducing "lists at the top are currently checked.")

>not sure I understand how that the middle part about how it sorted is relevant,

Not sure I understand, either, haha. (Actually, it was because of something I was thinking originally that I decided was not a good idea -- sorting the list-of-lists z->a if the tasks were sorted by list z->a).

**Comment by smichel17** [comment]
Related: #132
