### ISSUE TITLE
when sort case sensitive is enable, it is ignored on the main page

### ISSUE THREAD

**Issue by y2kbugger** [mpcjanssen/simpletask-android#181]
There are also issues with carats on the main view

EX:
The edit lists is sorted properly via ascii:
Ab
Ac
^Ab
^Ac
^ab
^ac
ab
ac
~Ab
~Ac
~ab
~ac

but in the main list the lists are displayed in all caps, and are sorted thusly (number is the proper sorting order)
^ab 5
^Ab 3
^ac 6
^Ac 4
ab 7
Ab 1
ac 8
Ac 2
~Ab 9
~Ac 10

**Comment by mpcjanssen** [comment]
All sorting is now using exactly the same algorithm so this should be fixed.
@y2kbugger can you confirm this is fixed in newer versions?

**Comment by y2kbugger** [comment]
Yes that they both look the same now although they're not sorted via ASCII.
From what I could tell all symbols are sorted before letters what Locale
are you sorting by?

**Comment by mpcjanssen** [comment]
@y2kbugger. I sort by the default device locale.

**Comment by y2kbugger** [comment]
Can't argue with that, it would be nice to be able to choose the sorting locale but I think I've gotten used to my work around:

Originally I wanted to use capital letters to bump some things above some special characters, and use other special characters to put them to the bottom. Right now I just prefix every list with an extra @ aka @@ and then when's I want to bump to the very top of the list I use triple at sign @@@.

For others that are thinking about how to sort things this is my method:

Metalists:
@@@projects
@@@waitingfor
@@@oneday

Projects:
@@
