### ISSUE TITLE
when adding a new list/tag the keyboard stays open when submit is hit

### ISSUE THREAD

**Issue by y2kbugger** [mpcjanssen/simpletask-android#183]
this is 4.4 and using the newest google material design keyboard.

hitting submit does nothing and the user must hit the [back] key and then press the [OK] button. Not a mission critical bug but it feels very awkward every time I have to do it.

**Comment by mpcjanssen** [comment]
Keyboard behaviour is not as i want it right now sometimes it pops up, sometimes it doesn't. Will investigate this.

**Comment by mpcjanssen** [comment]
I think if you add a tag/list the following should happen, the item should be added to the list below and it should be checked.

**Comment by y2kbugger** [comment]
yea that is not what happens at all.

**Comment by mpcjanssen** [comment]
I know. I still need to make it like this.

**Comment by smichel17** [comment]
I've started on this. I'm trying to figure out how the UX should go, and interested in feedback.

I open the dialog, tap on the text box, and type `a<space>b<enter>`. Two questions:

1. Should checked items `a` and `b` appear in the list below only when I press enter, or should `a` appear when I press space?
2. When I press enter, should the keyboard stay open, or close?

**Comment by mpcjanssen** [comment]
Agreed on both. So only on enter and close keyboard. You might also check the items (you are adding them for a reason)
