### ISSUE TITLE
Save task by *touching* the back button.

### ISSUE THREAD

**Issue by whudwl** [mpcjanssen/simpletask-android#185]
When adding a task, I think it's better if *touching* the back button(not the physical back button or navbar) on the top of the screen saves the task. 
I guess most users nowadays expect this kind of behavior. 
Besides, there's already a cancel button at the bottom of the screen.

**Comment by whudwl** [comment]
Thank you for the response. 
I've turned on the option "Back button". but for me only pressing the physical back button saves the task, pressing the on screen button doesn't. maybe the behavior varies by device?

**Comment by mpcjanssen** [comment]
The commit fixes this. It will be in the next release. Then the setting controls the Up button behavioralso

**Comment by whudwl** [comment]
Thank you!

**Comment by mpcjanssen** [comment]
BTW if you want you can already test with one of the APKs from: https://mpcjanssen.nl/files/simpletask/master/2015-01-13-a442aa4/

**Comment by whudwl** [comment]
I tried the Jan 13 build. it worked perfectly. Thank you!

On Tue, Jan 13, 2015 at 5:32 PM, Mark Janssen <notifications@github.com>
wrote:

> BTW if you want you can already test with one of the APKs from:
> https://mpcjanssen.nl/files/simpletask/master/2015-01-13-a442aa4/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mpcjanssen/simpletask-android/issues/185#issuecomment-69717604>
> .
>



-- 
Regards
Wenlong Dai
