### ISSUE TITLE
save scroll position after editing an item from the main list

### ISSUE THREAD

**Issue by y2kbugger** [mpcjanssen/simpletask-android#188]
I know that there is the possibility of list length and order changing after an edit, but I think that a simple "stay at the same scroll percentage" would suffice for most cases, and be at least as good "always jump back to the top"

**Comment by mpcjanssen** [comment]
I thought I implemented this so it should work already. Problem is that asking for the current position doesn't always give the right value. I will look into this

**Comment by y2kbugger** [comment]
I'll watch this one more closely to make sure it is always performing the same way.

**Comment by mpcjanssen** [comment]
Should be fixed in 5.5.0
