### ISSUE TITLE
move show hidden option

### ISSUE THREAD

**Issue by y2kbugger** [mpcjanssen/simpletask-android#190]
wouldn't it this be better placed under filters along with show items before threshdate, show completed items, etc?

**Comment by mpcjanssen** [comment]
I don't think so. The idea is that you show hidden only occasionally when you want to edit hidden items. When you activate a filter the current hidden option should be observed.
What is your use case with hidden tasks? 

Note that for temporarily hiding tasks I use the threshold functionality.

**Comment by y2kbugger** [comment]
I use them to placehold "permanent" lists such as @home.

so when i go to move things around for example split @home---->@house and
@yard and you have to go both places to make thresholded, completed, and
hidden tasks all visible.  Honestly I don't imagine doing this often, but
it might make it clearer for new users (like me) who are still shuffling
lists around like crazy.

**Comment by mpcjanssen** [comment]
After some more thought, it makes sense to group all visibility and sorting items in the filter. I will move this option when i have time.

**Comment by flusi100** [comment]
Thank you for this - I also think this setting should be moved into the filter settings (although this option usually will not be altered)
Fortunately I found this issue before opening a new one ;-)
