### ISSUE TITLE
Simpletask for iOS - possible?

### ISSUE THREAD

**Issue by stratmaster** [mpcjanssen/simpletask-android#194]
simpletask for android is the best app for managing a todo.txt!
But on iOS there seems to be only the todo.txt touch app (https://github.com/ginatrapani/todo.txt-ios), which is acceptable but lack of further features (e.g. filter). So is it possible to fork and modify the original ios app (at reasonable expense)?

**Comment by mpcjanssen** [comment]
The problem is at a reasonable expense. I would need a developer licence at a yearly cost and some i-devices to develop and test on.
I am too invested in the android eco system for that to happen. 

So as much as i would like it this is not going to happen.
