### ISSUE TITLE
Trim entries

### ISSUE THREAD

**Issue by patcon** [mpcjanssen/simpletask-android#195]
I've specifically noticed this when using tags or contexts at the end of entries, but it would be nice if this was cut out. (I believe most soft keyboards add a space when autocompleting, so perhaps that's the origin fwiw.)

**Comment by mpcjanssen** [comment]
I have the main view that the task should go in unmodified. Done people might be using whitespace for sorting out alignment.

I understand the request though and there is an issue somewhere to use the embedded JavaScript interpreter to post process added/edited tasks.

If that is done this is a trivial thing to implement.

**Comment by mpcjanssen** [comment]
Closed as duplicate/part of #122
