### ISSUE TITLE
Add two or three customizable dates

### ISSUE THREAD

**Issue by beyercj** [mpcjanssen/simpletask-android#196]
First congratulations to Simpletask. This is a great app for android. Could you add two or three customizable dates and enter them in the text file in a format like this:

x (A) created:YYYY-MM-DD due:YYYY-MM-DD custom1:YYYY-MM-DD custom2: YYYY-MM-DD task1 @list1 +tag1
x (B) created:YYYY-MM-DD due:YYYY-MM-DD custom1:YYYY-MM-DD custom2: YYYY-MM-DD task2 @list2 +tag2
if the dates are always at the same column position for each row in the text file this would enable any text editor to sort the file by dates.

**Comment by mpcjanssen** [comment]
You can always add a threshold or due date and change the prefix if you want quick date entry. One idea might be to split the date entry from the due and threshold date.
Support for custom fields without any root in an existing todo.txt extension is not going to happen.

**Comment by smichel17** [comment]
> One idea might be to split the date entry from the due and threshold date.

Tracked in #366
