### ISSUE TITLE
No option to work with tasks that have future threshold dates?

### ISSUE THREAD

**Issue by harshad1** [mpcjanssen/simpletask-android#198]
Hi all,

I see no way to make visible / edit tasks with future threshold dates. This functionality appears to have been addressed at one stage : 
https://gitorious.org/simpletask/android/commit/3bcf75cdffe9a6a620c6576a580b67191c1ad7c8
but I can't find it in the simpletask app available through f-droid.

Please help.

Thank you

**Comment by mpcjanssen** [comment]
The option to show or hide tasks with a threshold date in the future can be found in the detailed filter view.

You can open this by clicking the tags/labels icon and selecting the 'show' tab.

I will check the docs if they still are correct.

**Comment by harshad1** [comment]
Never mind. I'm an idiot apparently :)

Please delete the bug report.

Thanks

**Comment by mpcjanssen** [comment]
I should probably restore the explanation of threshold dates in the help. Not sure why I removed it.
