### ISSUE TITLE
Development is stalling

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#200]
Because I have been very busy with work lately, development of Simpletask is stalling.
It would be great if there are additional contributors.

**Comment by mimmori** [comment]
Do you think to freeze the project for some time or to abandon it?

**Comment by mpcjanssen** [comment]
I am definitely not abandoning it. I do have some ideas for improvement under the hood. Currently changes take more time than necessary so I want to do some redesign. But I just don't have the time for it now.

**Comment by chipbite** [comment]
Hi! It's the best todo.txt app on android! :)

**Comment by mpcjanssen** [comment]
@chipbite thanks, apparently just logging this issue made me work on simpletask again :)

**Comment by mpcjanssen** [comment]
Fixed :)
