### ISSUE TITLE
Clear all lists and tags

### ISSUE THREAD

**Issue by harshad1** [mpcjanssen/simpletask-android#202]
Hi,

I have a new feature request - Would it be possible to add a button to clear all selected list and tag filters in the sidebar? 

Thanks

**Comment by mpcjanssen** [comment]
When you have a selection of lists and filters, the top line of the screen will show a summary of the filter (with the total number of tasks and the visible ones)

Clicking the X in the left top will clear all filter. Does this help?

Note you can also save a cleared filter in the right navigation drawer if you prefer drawers for some reason.

**Comment by harshad1** [comment]
Thanks.
