### ISSUE TITLE
Refresh todo.txt manually?

### ISSUE THREAD

**Issue by fxshpac** [mpcjanssen/simpletask-android#203]
I have my todo.txt synced between phone and pc and notice that when the changes are made on pc and synced to phone, there is no way for me to refresh the content of the file to see the latest status. I understand that the app will refresh the file every 5 minutes but it will be nice to be able to manually trigger the refresh. Let me know if this is something you will consider. Thx in advance.

**Comment by mpcjanssen** [comment]
Is this with Dropbox?  The status should be updated immediately. If not this is a bug. 
Can you give some more details?  

Are you using cloudless or the Dropbox version? 
Is the main view not updated or the widget?

**Comment by fxshpac** [comment]
Sorry but I didn't make it clear. I was using cloudless version and I sync the file over my LAN without going through dropbox. The main view is only one I tried. Hope that answers your questions.

**Comment by mpcjanssen** [comment]
As soon as the todo file has synced the main view should update.  Can you send me a log from the settings when this happens?

**Comment by mpcjanssen** [comment]
Should be fixed in latest versions. Manual refresh for cloudless is not necessary any discrepancy in the file and the view in Simpletask is a bug. Please open a new issue if this occurs again.
