### ISSUE TITLE
Calendar reminders: due today

### ISSUE THREAD

**Issue by tomtom** [mpcjanssen/simpletask-android#210]
I have activated calendar reminders for due dates. When I create a new task with a due date = today, the reminder is created as a whole day event. No reminder is displayed because this event starts in the past (0:00 of today) and the reminder is displayed 12 hours before.

I would prefer the following behaviour: A reminder some time (1 hr?) later the same day.

It would also be nice if I were able to set the exact time of the reminder in the task. e.g. `due:2015-04-08 duetime:11:30` or so.

I use Simple Tasks cloudless 5.3.0.

Regards

**Comment by vojtechkral** [comment]
I don't think I can make it set the reminder an hour later, because the calendar syncing occurs each time tasks are modified and the code doesn't really know which task is new and which has already existed.

I could make a special case "0 days prior", for example setting the reminder at noon the same day, but that's probably not what you're looking for.

Have you tried creating a reminder for a task? Go to the main screen, select a task, go to context menu, pick "_Add reminder_" and it opens a calendar dialog for you.

**Comment by mpcjanssen** [comment]
The google calendar app allows setting notifications for all day events at a specific time so there might be an option. However in the docs I can't find any obvious way of doing this.

In the mean time would it be possible instead of a whole day event to add the event a a configurable time? For example:

Whole day [ ]

If no: 
Time: Clock picker
Create 15 minute free event with reminder at time

**Comment by tomtom** [comment]
> In the mean time would it be possible instead of a whole day event to 
> add the event a a configurable time?

In order to clarify my report: IMHO it would be preferable to optionally 
add a time for the event, if that were possible, instead of introducing 
a special case for same day event.

**Comment by vojtechkral** [comment]
Okay, I'll see what I can do...

@mpcjanssen BTW you also had a request about accounts, could you please file an issue on that and cc me in it? I might forget about it otherwise...

**Comment by mpcjanssen** [comment]
@vojtechkral even better, I have added you as collaborator and assigned the  ticket. Even though you can commit to this repo now I would prefer  pull requests to prevent merge issues and to keep a better view of what goes in.

**Comment by vojtechkral** [comment]
@mpcjanssen Ok :) I'll see if I have time, as of now it's quite ok...

As to the issue, I'm not sure I see a way how to do this. A reminder can be set at any point in time using the `MINUTES` column, but I'm not sure how to determine the number in some user-friendly way.

Maybe the `due:` extension could be further extended to include time as well, rather than creating a new extension (`duetime:`). It could contain, for example and (ISO-formated datetime)[https://en.wikipedia.org/wiki/ISO_8601], as in `2015-04-09T00:08:46Z`.

**Comment by vojtechkral** [comment]
@mpcjanssen @tomtom Here's an idea:

What if we ditched creating reminders for due & threshold dates and instead defined a new extension for reminders and had those synces into the calendar? The syntax could be something like 

`rem:<iso-datetime>`

ie. for example `rem:2015-04-11T00:15:30Z`. There could be a dialog for editing it just like the ones for `due:`, `t:`, etc...

How would that fit your use cases?

**Comment by tomtom** [comment]
> |rem:<iso-datetime>| 
Sounds good for me.

Thank you very much for your work on this feature request.

**Comment by mpcjanssen** [comment]
@vojtechkral @tomtom 
I would prefer not to add a new extension for this. Main reason is that it would require you to fill a lot of fields for a task due at a specific day and for which you want a reminder. I would suggest the following approach:

In settings:

* Keep current settings and add a default reminder time.
* Add a new extension `rem:001530Z` to override the default reminder time.

**Comment by vojtechkral** [comment]
Ok, the extension could be in format `rem:hhmmZ` I suppose...

**Comment by vojtechkral** [comment]
@mpcjanssen Mind if I use the [betterpickers lib](https://github.com/derekbrameyer/android-betterpickers/)? It has the nice radial time picker thingy.

**Comment by mpcjanssen** [comment]
No problem but please include it as a maven dependency, don't include the actual jar.

**Comment by vojtechkral** [comment]
Status: I'm still trying to figure out how to go about this. It occured to me recently that it would be possible to fill in a `rem:` field without having filled in any `due:` or `t:` date. I wonder how to handle that in the calendar sync code. IMHO the easiest would be to simply ignore such a `rem:` field, is it ok if I do that?

**Comment by mpcjanssen** [comment]
You are designing it so it's your call :)
But I would think that ignore rem in this case would be OK.

**Comment by vojtechkral** [comment]
Ok :)

**Comment by vojtechkral** [comment]
Okay, so after giving it some thought and experimenting with code, I've come to the decision not to implement this, at least not now. There's just too many corner cases / difficulties / bugs (such as in date4j). Sorry.

You can now customize reminder time, though. Also, as a workaround, the _Add reminder_ functionality is still available...

**Comment by tomtom** [comment]
Ok. Thanks for giving users an opportunity to customize the reminder time.

**Comment by vojtechkral** [comment]
Hi. I'm reopening this issue. I might've finally figured out how to do this in a sane manner, hopefully.
I'd like to introduce the `rem:` extension after all, but this time I'm making it _relative_ to the due or threshold date.

That is, for example, you might have a default automatic reminder time set to 2 days prior a due date. But for a specific task you might want to change this time and that's what you'd do with the `rem:` syntax. I'd also like the syntax to support hours, too, for example:

`rem:4d` would set a reminder 4 days before a task is due
`rem:1h` would set a reminder 1 hour before a task is due. This would need to extend the due syntax with _time_ as well.

So far, there's a test implementation in my `reminders` branch. There's no GUI yet, you have to type the extension manually (but it's pretty simple) and also setting hours isn't much useful yet, but setting days seems to work nice.

Obviously I'd also update/refactor the reminders settings screen to reflect the changes. I'd like to make it easier to understand.

Thoughts?
@mpcjanssen  @tomtom

**Comment by tomtom** [comment]
Hi!

Thanks for re-opening the issue.

> |rem:4d| would set a reminder 4 days before a task is due
>
> |rem:1h| would set a reminder 1 hour before a task is due. This would 
> need to extend the due syntax with /time/ as well.
>

I personal don't quite understand when rem:1h will alert me. I 
personally would very much prefer being able to state a time, e.g.

     due:2015-09-03.9 -> alert me on 3. Sep at 9 o'clock
     due:2015-09-03.12:30 -> alert me on half past 12

or

     due:2015-09-03 at:9

and maybe a period

     due:2015-09-03.12:30 for:1h
     due:2015-09-03 at:12:30 for:1h

I personally find the concept of reminders x hours/days before the 
actual due time confusing.

Regards,
Tom

**Comment by mpcjanssen** [comment]
I would prefer not to change the due syntax because of compatibility with the main todo.txt format. I do like the at: for: syntax. It would be great if missing at for would mean full day event as well.

**Comment by vojtechkral** [comment]
> I personally find the concept of reminders x hours/days before the
actual due time confusing.

I understand, it is a bit confusing. Maybe I'm doing a very good job explaining it, too...

My usecase, basically, is this: I have a doctors appointment, let's say on 10th October at 8AM, so I create task for that with the due date set to 10th Oct. I'd like to reminded a couple days before that, though, because reminding me at the due date and time is too late. I hope that clarifies where I'm comming from? Maybe I'm not using the system right...

However, reminding at the start of the event with no advance should be an option too, you're right about that.

The at/for syntax looks good to me.

**Comment by vojtechkral** [comment]
Btw. you can tell me about your usecases too if you want, that might help me figure out how to do this.

**Comment by mpcjanssen** [comment]
I don't use due dates at all. Anything with a date is on my calendar as gtd intended ;)

**Comment by tomtom** [comment]
> Btw. you can tell me about your usecases too if you want, that might 
> help me figure out how to do this.
>

I use due dates for tasks I want my phone (or some other todo.txt 
compatible tool) to remind me -- and I don't want to think about that 
task before that date (& optionally time). I want to be able to easily 
reschedule such reminders, which is why I prefer using something like 
simpletask to the calendar app for these tasks. Something in the line of 
e.g. do this tomorrow after work when it is likely that I have time for 
it, or do that on friday morning.

For fixed appointments like e.g. visiting a doctor, meetings, which I 
cannot easily reschedule, I use the calendar app.

I could of course also use the calendar app for every task that has a 
date/time, but I don't like the calendar app very much.

Before using simpletask, I used DGT GTD, which IMHO does reminders 
pretty well. But I eventually decided that I prefer the plain-text 
approach of todo.txt.

**Comment by vojtechkral** [comment]
Ok, I understand your use case.

> I could of course also use the calendar app for every task that has a
date/time, but I don't like the calendar app very much.

Couldn't agree more. The calendar app is IMHO too cumbersome and the other calendar apps (Google or 3rd party) aren't much better.

> Before using simpletask, I used DGT GTD, which IMHO does reminders
pretty well.

I checked out DGT GTD, looks nice, their reminders seem to be similar to what I was trying to do, except it's more self-explanatory I suppose...

**Comment by mpcjanssen** [comment]
> and I don't want to think about that 
task before that date

For this usecase I use threshold dates and I hide future tasks. That's a part of MYN that I use extensively.

+1 on the crappy calendars.

**Comment by vojtechkral** [comment]
Just to clarify, the `at` and `for` would apply to due only, right? Or threshold too?

**Comment by mpcjanssen** [comment]
threshold wouldn't make any sense. So due only.

**Comment by mpcjanssen** [comment]
Keep in mind that this will make the text part really complicated. So I am not sure I would merge an at: for: extension

**Comment by mpcjanssen** [comment]
. If you want tasks at specific times use the existing add reminder option, or add it to the calendar directly. Simpletask is not intended to be a calendar replacement.

**Comment by smichel17** [comment]
>>and I don't want to think about that task before that date
>
>For this usecase I use threshold dates and I hide future tasks. That's a part of MYN that I use extensively.

FWIW, @mpcjanssen, maybe you got this from MYN, but it also seems to be a part of GTD; it's an implementation of the tickler file.
