### ISSUE TITLE
Allow calendar sync with online calendar

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#212]
It would be nice if the account to create the synced calendar on would be selectable. In this way you could for instance add it to your google account

**Comment by vojtechkral** [comment]
So if the calendar were created on the Google account, the Google sync feature would automatically sync it?

**Comment by mpcjanssen** [comment]
I think so. I have never tested this though.

**Comment by vojtechkral** [comment]
Allright, I have gapps on my older phone so I can give it a try...

**Comment by vojtechkral** [comment]
Closing due to lack of time and scope. Feel free to reopen if needed...
