### ISSUE TITLE
Duplicate calendars (and events doesn't show in my calendar)

### ISSUE THREAD

**Issue by sanzoghenzo** [mpcjanssen/simpletask-android#213]
I've enabled the reminders calendar option, but I have 2 problems. I'm using Business Calendar 2

1. I see that there are multiple "Simpletask reminders" calendars (8 at the time of writing)
2. Events doesn't show in the calendar. Akll the calendars are enabled in BC2. Event reminders are showing up, thogh.

**Comment by vojtechkral** [comment]
1. This should be fixed in #211 
2. I have no idea why this might happen. Can you see the events in the built-in app?

**Comment by sanzoghenzo** [comment]
thanks @vojtechkral 
1. I have to remember to remove "is: issue is:open" when searching :)
2. I don't have built in cal apps, but I have 2 version of business calendar (I paid the old one but I have to pay again if I want only the new one :( ) and the old one is showing the events fine. So no problem with your app, need to sort it out by myself!

**Comment by vojtechkral** [comment]
Okay :)

**Comment by vojtechkral** [comment]
BTW enabling and disabling the calendar sync should remove excessive calendars (even before the patch)...

**Comment by mpcjanssen** [comment]
Yes I found that too.
