### ISSUE TITLE
When a filter is active, back button exists app

### ISSUE THREAD

**Issue by vojtechkral** [mpcjanssen/simpletask-android#216]
I often go back and forth between a couple of filters and the no-filter main app screen.
I know there's little cross button in the upper left-hand corner, but being able to deactivate the filter with the back button would be nice and also consistent with task selection..

**Comment by mpcjanssen** [comment]
Back navigation in Android is a bit tricky especially if the intents contain the filters (as in simpletask). I could never make back work properly. So switching back to a previous filter.
However clearing the filter if it is set when pushing back should be fairly easy to implement.

**Comment by vojtechkral** [comment]
Awesome, thanks!
