### ISSUE TITLE
Filter name of task

### ISSUE THREAD

**Issue by simonwjackson** [mpcjanssen/simpletask-android#217]
I would like to use LUA to filter the name of the task
some of my todo items have additional metadata:

`thing to do note:Gy6.txt (#pomo: 0/2)`

this is vital info on my PC but in simpletasks i want to write a LUA script to filter this to:

`thing to do`

In its current state, it seems like its only able to `return true` (or false) just to show or hide the task completely

Would this be possible to implement?

**Comment by mpcjanssen** [comment]
I have been considering this. In the current setup the filters only allow inclusion exclusion. I don't think changing the display should be part of that functionality.

I did consider adding lua hooks for rewriting tasks on: display, edit, create, delete. This would cover your scenario. The infrastructure groundwork is there. I just need to find the time to do this.

**Comment by simonwjackson** [comment]
Good to hear that its possible,
I'd help if i could write java :/

**Comment by mpcjanssen** [comment]
See also #349

**Comment by mpcjanssen** [comment]
This can be implemented using the `onDisplay` Lua callback: https://github.com/mpcjanssen/simpletask-android/blob/master/app/src/main/assets/script.en.md#ondisplay-task-fields-extensions---string
