### ISSUE TITLE
synchronization with webdav file

### ISSUE THREAD

**Issue by dalf** [mpcjanssen/simpletask-android#218]
Is it possible to add webdav support ?

It would be useful with owncloud or seafile.

**Comment by mpcjanssen** [comment]
I wont add other sync options, it requires a lot of effort to get right
For other cloud options than dropbox use the cloudless version of simpletask in combination with something like foldersync (which does support webdav IIRC)

**Comment by vojtechkral** [comment]
Doesn't the OwnCloud app provide option to sync files?

**Comment by mpcjanssen** [comment]
Not easily. I am sure synced files are stored locally, but I have no idea where. FolderSync also supports OwnCloud with webdav (it's what I use)
