### ISSUE TITLE
Reminders repeated when tasks are updated

### ISSUE THREAD

**Issue by vojtechkral** [mpcjanssen/simpletask-android#222]
When reminders are added to calendar, they immediately go off if they are in past. This makes reminders go off again when tasks are updated. Gonna fix this ASAP.

**Comment by mpcjanssen** [comment]
Please base PR on maintenance branch. Master is wip and I want to release the fix quickly.

**Comment by vojtechkral** [comment]
Ok. PR still against master?

**Comment by mpcjanssen** [comment]
no against maintenance so I can directly publish it

**Comment by vojtechkral** [comment]
Ok. Almost done...
