### ISSUE TITLE
Force-close when trying to update filter

### ISSUE THREAD

**Issue by aurisnoctis** [mpcjanssen/simpletask-android#225]
Hello all,

Simpletastk force-closes when I enter the filter page by pressing the tags symbol in the main view, and then select any tab other than the preselected <code>LIST</code> tag.

- This happens independent of having or not having already filtered before by search or saved filters.
- Making a new saved filter in the swipe-from-right menu works fine, for instance after a search in the main window.
- Swipe-from-left menu works flawlessly as well.

<pre>
simpletask version: 5.3.2 (d2b9f76)
installed via GooglePlay after the same crash happened with v5.3.1
Exception class name: java.lang.NullPointerException
Source file: FilterActivity.java
Source class: nl.mpcjanssen.simpletaskFilterActivity$MyTabsListener
Source method: onTabSelected
Line number: 484
</pre>

Sorry in advance in case this issue was reported already. I searched for "filter force-close", but in the past, GitHub sometimes didn't show issues according to search. The Google report EULA looked scary so I pasted the crash information above.

**Comment by mpcjanssen** [comment]
Can you try the build from https://mpcjanssen.nl/files/simpletask/latest/

**Comment by aurisnoctis** [comment]
Hi @mpcjanssen , wonderful, v5.3.2 (7f0a209) seems to be working fine. (I only tested basic functionality and filtering for a minute or so.)

**Comment by mpcjanssen** [comment]
I will release this as 5.3.3 shortly.
