### ISSUE TITLE
Different views in main window

### ISSUE THREAD

**Issue by ix5** [mpcjanssen/simpletask-android#226]
Similar to Google Keep, Simpletask should allow viewing task lists side by side.
![Google Keep Screenshot](http://upload.wikimedia.org/wikipedia/en/1/15/Google_Keep_Android.png)

Since priorities are already color-coded, it would be easier to navigate lists or task collections of different priorities with screen estate used more wisely.
The vertical list should stay the default; the "flashy" Keep-style would be an option.

**Comment by mpcjanssen** [comment]
The UI of simpletask could use some refinement, but I am not a very good UI designer and I don't really have the time to implement it. I do want to look into the card interface to see how that would work, but this is not going to happen anytime soon.

**Comment by ix5** [comment]
Simpletask could be considered feature-complete, and most issues here are really just minor changes to better suit an individual's workflow.
There is an [example](https://developer.android.com/samples/CardView/project.html) on the Android developer website, maybe this could be a good starting point.
I might take a look at this and sift through the Android docs, but uni is stressing me out a great deal right now and I hate Java with a passion.

**Comment by ix5** [comment]
Simpletask could be considered feature-complete, and most issues here are really just minor changes to better suit an individual's workflow.
There is an [example](https://developer.android.com/samples/CardView/project.html) on the Android developer website, maybe this could be a good starting point.
I might take a look at this and sift through the Android docs, but uni is stressing me out a great deal right now and I hate Java with a passion.

**Comment by mpcjanssen** [comment]
One main issue with using a recyclerview with cards is that it requires manually writing the complete selection code.

**Comment by smichel17** [comment]
I think this is a someday/maybe, as it seems relatively high effort, low reward (much of this can be replicated through excessive use of widgets).

Related: #412

**Comment by ix5** [comment]
Closing, unlikely to ever be implemented.
