### ISSUE TITLE
Add ability to link between todo files with todo://

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#235]
Current master allows linking between files with todo:// 

It changes the way links in tasks are handled.

* If no links/mail addresses or phone numbers are available, single click selects
* Otherwise single click gives a popup to launch the links.
* Long click always selects regardless of links.

Furthermore there is a trail of opened files. The back button will switch back to the previous file (after clearing the filter on first click if that is enabled in settings) 

Things to do:

* Allow opening a specific file from an intent. This should only allow absolute paths
* (Possibly) specify the file for widgets.  Currently when you switch files, the widgets also switch.

**Comment by mpcjanssen** [comment]
Note to self, limit breadcrumb depth to last 5 or maybe add recent files to right drawer.

**Comment by mpcjanssen** [comment]
Right drawer number of recent files should probably be configurable

**Comment by jonhind** [comment]
Opening specific files would be lovely

**Comment by fxshpac** [comment]
was looking for a way to open any file type (jpg, doc, etc) from the path in the task. this is the closest that i can find. any chance to implement it. a relative path support is even better to make it portable.

**Comment by mpcjanssen** [comment]
Link to any file type is implemented by #393
