### ISSUE TITLE
Export/Print formatted list

### ISSUE THREAD

**Issue by barbuduccle** [mpcjanssen/simpletask-android#238]
One of the great things about simpletask is the flexibility of the filters and the clarity of the displayed lists. I'd like to be able to view the lists on my PC or export to other devices or to print. I haven't found any PC software that displays the todo.txt like simpletask does.

I know I can 'share' the list which generates a text file. I'd really like to be able to print a formatted, colour list with headings and to be able to view that formatted list on other devices, PC etc. Maybe to export as an html file? Ideally I'd like this formatted list to be saved in the same folder as the todo.txt file so any device on my network could display this nicely formatted list.

**Comment by mpcjanssen** [comment]
It's not easy to export a listview to html. It requires the html file to be built from scratch. So even though I like the idea, this is not going to happen any time soon.

**Comment by smichel17** [comment]
@mpcjanssen tag with someday/maybe?

**Comment by smichel17** [comment]
Related: #236

**Comment by mpcjanssen** [comment]
Never going to be added to simpletask.

Workaround, use the `onDisplay` callback to show more structured text view of the task and use a different application to change this to html.
