### ISSUE TITLE
lists bad ordered on main view

### ISSUE THREAD

**Issue by AnderRasoVazquez** [mpcjanssen/simpletask-android#239]
If I have those lists: @@agenda @projects @_Areas

In left drawer they appear on this order:
@agenda
Projects
_Areas

But in the main view they're on a bad order:
@agenda
_Areas
Projects

**Comment by mpcjanssen** [comment]
The drawer and main view use a different sort for string sorting. I also think there is an issue with prefixes like _, I will fix both. Note that in that case the second order is actually the correct one (because of the _ before Areas)

**Comment by mpcjanssen** [comment]
I can't reproduce the sorting you have in the left drawer. What is your setting "Sort case-sensitive) ? And can you put an example task list with these three lists which shows the behavior?

**Comment by AnderRasoVazquez** [comment]
If short "case-sensitive" is marked, it orders on the left drawer as I wrote before. If it isn't, it orders this way:
@agenda
_Areas
Projects

Here's my current task list, hope this helps ^^
![simpletask-bug](https://cloud.githubusercontent.com/assets/3936719/7656794/31abd08e-fb2d-11e4-80e9-c063799ac2fe.jpg)

**Comment by mpcjanssen** [comment]
The handling of sorting is not consistent (some sorts obey the case sensitive setting and some don't) I will fix this.

**Comment by smichel17** [comment]
Related: #181

**Comment by aurisnoctis** [comment]
This bug affects tags, too (#699) @smichel17
