### ISSUE TITLE
Default time unit for recurrence

### ISSUE THREAD

**Issue by robertvanbregt** [mpcjanssen/simpletask-android#241]
Recurrence will only work when the `rec:` pattern contains a time unit (e.g. day, week, month or year). If the unit is omitted, no new task is created.

Suggested enhancement is, to default to days when no unit is provided.

So: `rec:3` would be handled like `rec:3d`

**Comment by mpcjanssen** [comment]
This sounds like a good idea except that I can imagine that for some people weeks or `w` would be a better default so that would need to be configurable.
I suspect the real issue here is that you want to quickly add recurrence. I therefore think a better way would be to make adding recurrences easier. 

Or is your use case editing the file in a separate app?

**Comment by robertvanbregt** [comment]
My use case was indeed quick entry. But on the other hand, I think this
syntax (rec:15) could possibly be better used to specify "every n-th day
of the month".

Assuming this item:

Pay bill due:2015-05-12 rec:15

then at completion the newly created item would become:

Pay bill due:2015-05-15

(This looks the same as rec:1m if the current due date is already at the
day of the month)

But if the next due date is calculated `rec:1m` from the completion date
or on the next `rec:15` after the completion date then it would be
different.

Am I making sense?


Op Ma jun 1 2015, om 14:06 schreef Mark Janssen:
> This sounds like a good idea except that I can imagine that for some
> people weeks or w would be a better default so that would need to be
> configurable.
>
I suspect the real issue here is that you want to quickly add
recurrence. I therefore think a better way would be to make adding
recurrences easier.

> Or is your use case editing the file in a separate app?


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/mpcjanssen/simpletask-android/issues/241#issuecomment-107417720

**Comment by mpcjanssen** [comment]
The small overhead of adding the actual recurring unit doesn't offset the additional complexity of setting the default setting properly and all the extra code. Biggest disadvantage is that a recurring part can mean different things based on the config.
This leads to very difficult to debug issues. So I am not going to change this.
