### ISSUE TITLE
Widget does not update

### ISSUE THREAD

**Issue by frankhommers** [mpcjanssen/simpletask-android#245]
This might be a duplicate of https://github.com/mpcjanssen/simpletask-android/issues/203 

My widget does not update if I refresh the todo.txt through FolderSync

Also, would it be possible to create a public event to force reload of everything. I use Tasker to Sync files and when the Tasker task is completed I would like to trigger a force refresh to the app and widget.

**Comment by mpcjanssen** [comment]
Does this still occur with 5.4.1?

**Comment by frankhommers** [comment]
It seems to work now! Thanks.

**Comment by frankhommers** [comment]
I have the problem again, but not only with the widget also with the app. If I update the todo.txt externally the app and widget are not refreshed. (I don't know since when because I didn't use the app for a long time). Can I send SimpleTask an intent to force updates?

**Comment by mpcjanssen** [comment]
@frankhommers can you send me a log of when this occurs? You can share a log from Settings->Other->View debug information

**Comment by mpcjanssen** [comment]
Also I will consider adding an intent to force refresh.

**Comment by frankhommers** [comment]
I fixed it by (ab)using the existing intents. I set up tasker to listen for SYNC_DONE, to trigger the file synchronization.
I also set up tasker to sync on an interval, and after that it sends the intent UPDATE_UI.

This works flawless now, but I guess these intents aren't meant to be sent/listened for?

**Comment by mpcjanssen** [comment]
@frankhommers I am surprised it even works. The are local broadcast events for the app. However the wat you are doing it now is what Simpletask itself also does (should do)
The SYNC_DONE event in the app should already trigger an UPDATE_UI so I wonder why it doesn't work without tasker tricks.
