### ISSUE TITLE
Deleting task makes two more instances of every other

### ISSUE THREAD

**Issue by chris-barry** [mpcjanssen/simpletask-android#246]
When I delete a task, every other task is added two more times.

I am running Simpletask cloudless v5.4.1 (1553) from F-Droid.

**Comment by mpcjanssen** [comment]
Does it actually double the tasks in the todo file too or is the actual file still ok?

**Comment by chris-barry** [comment]
Of course after it happening for two days, I not can't reproduce to check. :sad: 

If it reappears I will re-open.

**Comment by mpcjanssen** [comment]
Silly Heisenbugs.
