### ISSUE TITLE
When sorting by reverse file order, adding a new task reverses order in the actual todo.txt

### ISSUE THREAD

**Issue by shayneholmes** [mpcjanssen/simpletask-android#247]
1. Create a new todo.txt file with three lines: "A/B/C"
2. Open in Simpletask
3. Set sort to reverse file order
 * Simpletask correctly displays "C/B/A"
4. In Simpletask, add new task "D"

**Expected**: Simpletask displays "D/C/B/A", file says "A/B/C/D"

**Actual**: Simpletask displays "D/C/B/A", but file is also reversed: "D/C/B/A"

Note: If you reload the file, Simpletask displays the list as "A/B/C/D" (the file stays "D/C/B/A")

This has been playing havoc with my file sorting.

**Comment by shayneholmes** [comment]
Also, this is fairly recent, I'd say within the last week.

**Comment by mpcjanssen** [comment]
tasks are actually saved sorted now (since 5.4.0) this is a bug. Can you try with a test build? If so send me a mail and if you use cloudless or dropbox

**Comment by mpcjanssen** [comment]
5.4.3 which i just uploaded fixes this.
