### ISSUE TITLE
Adding task through Google Now voice has twice wiped my todo.txt on dropbox

### ISSUE THREAD

**Issue by jflinchbaugh** [mpcjanssen/simpletask-android#251]
Version: Simpletask free v5.4.5 (1557)

Twice this week, I've added some tasks by voice on my morning drive ("OK Google, take a note file a bug for simpletask") and simpletask managed to wipe my entire todo.txt file and start fresh with the newly added task(s).  The first day, it kept the 2 new tasks I added, and on the second day it did it, it kept the one and only task I added.

Other operations of checking off tasks, editing, etc have been fine.  Later in the day, adding a task from a widget is fine, as is adding a task by voice.

I sort of wonder if it coincides with adding the first task after an update.  (Were there 2 updates pushed through Google play in this time frame (12 June - 19 June 2015)?

If I figure out anything else on reproducing the issue, I'll add it here.

**Comment by jflinchbaugh** [comment]
I've continued a bit with editing the file outside the app and inside the app, and the changes are reflected nicely and all the data is kept as has always been the case.

**Comment by mpcjanssen** [comment]
I think it fails if Simpletask is not running yet. So if you close Simpletask and add something without opening Simpletask first, it will probably fail.

**Comment by mpcjanssen** [comment]
I think I know the issue. SImpletask loads the file in the background. But when starting and doing note to self the background load is not finished before the task  is appended resulting in an empty file.

**Comment by mpcjanssen** [comment]
Next release will fix this. For now just adding any widget should prevent the issue.

**Comment by jflinchbaugh** [comment]
I just got the update, cleared all the running apps from recent, and added a note by voice successfully.

**Comment by jflinchbaugh** [comment]
I've seen this happen again!  I added an item through Google now and it wiped the entire file.

**Comment by mpcjanssen** [comment]
I assume this is with 5.5.7? Could you attach the application log file? Not sure if it will help, but it will at least give some context.

**Comment by jflinchbaugh** [comment]
5.5.6. It was yesterday evening that it happened.   My logcat doesn't have anything from yesterday in it, so I'll try to reproduce it today and attach that logcat.

**Comment by mpcjanssen** [comment]
I really should improve on the application logging. As it is now, it's as good as useless.

**Comment by mpcjanssen** [comment]
Versions in http://mpcjanssen.nl/files/simpletask/latest have much better logging. Logging is kept for a day, so if this re-occurs, the logging should be of more help. @jflinchbaugh could you try with that version? It also has some changes which should prevent this from ever occurring, but if does happen the logging should tell more.

**Comment by mpcjanssen** [comment]
@jflinchbaugh any update on this. Did this happen again with the latest version 6.0.8?

**Comment by jflinchbaugh** [comment]
I've not seen it happen again, so it's probably safe to close this.
