### ISSUE TITLE
How I can delete a List created with h:1?

### ISSUE THREAD

**Issue by logos88** [mpcjanssen/simpletask-android#257]
First, thanks for this great app. I love it!!

I have created a List with h:1 and now I don't know how to delete it. I have tried to archive everything and only the others list disappears. How could I do it?

Maybe an option to delete or rename a list or tag when you push them more than 1 second in the filters screen would be nice :)

**Comment by mpcjanssen** [comment]
I am considering the longclick on list option, it's also good for delete etc. There is already an issue for this. #231.

For now enable `Show hidden tasks` in the settings and then you can remove the hidden task.

**Comment by logos88** [comment]
OKs, it worked, thanks!
