### ISSUE TITLE
Completing tasks in dropbox sync doesn't change the file 

### ISSUE THREAD

**Issue by shayneholmes** [mpcjanssen/simpletask-android#259]
Dropbox Sync 5.5.2: if I mark a task as complete, it doesn't change the file in drop box, and if there is no other change, the next time it syncs, my tasks will be incomplete again. (If I mark a task, then add a task, the completion mark syncs with the new task.)

**Comment by mpcjanssen** [comment]
Do you complete using the checkbox or using the menu?

**Comment by shayneholmes** [comment]
The menu – I have checkboxes turned off.

**Comment by mpcjanssen** [comment]
Ok that explains, will be fixed in 5.5.3
