### ISSUE TITLE
Date new task (bug)

### ISSUE THREAD

**Issue by Cidxx** [mpcjanssen/simpletask-android#261]
First, let me thank you for your great creation!

I'd like to bring your attention to a *possible* bug after last days updates: in spite of "Date new tasks" enabled in the behavior section of the settings, the new tasks are without any creation date.

Thanks,

Cid

**Comment by mpcjanssen** [comment]
Confirmed, will fix.

**Comment by mpcjanssen** [comment]
Will be in 5.5.4
