### ISSUE TITLE
file not newline terminated

### ISSUE THREAD

**Issue by y2kbugger** [mpcjanssen/simpletask-android#262]
causes git to squeal about this issure, but more importantly it breaks the canonical todo.txt-cli implementation
![simplebug](https://cloud.githubusercontent.com/assets/6101677/8447229/8212f38e-1f83-11e5-83df-9fe8ff1f212a.png)

 t sadd http://www.mcmaster.com/#30505a5/=xuv5nt
sidenote: sadd is my own "sync+add" command for a local git repo.....cause sometimes files get trashed unexpectedly......

As you can see in the picture, the new task gets shoved joined to the last line rather than its own.

**Comment by mpcjanssen** [comment]
Is this with cloudless or dropbox version?
