### ISSUE TITLE
Widget doesn't get material design

### ISSUE THREAD

**Issue by David-Guillot** [mpcjanssen/simpletask-android#263]
Hi,

I'm trying to apply Material theme to my widget but only Holo is working...

Thanks

**Comment by mpcjanssen** [comment]
Material theme for widgets is not implemented yet. I will either remove the options or implement it.

**Comment by mpcjanssen** [comment]
Removed unsupported theme options for now. Will look into implementing Material theme for the widgets.

**Comment by David-Guillot** [comment]
Thank you, looking forward into this material widget :)
