### ISSUE TITLE
differently dated tasks receiving same due date when using calendar picker (ST cloudless)

### ISSUE THREAD

**Issue by scheunengeist** [mpcjanssen/simpletask-android#264]
This seems to have been introduced with the 5.5.x series.

Here's what I do:
* I select task A and push it to tomorrow.
* I select task B and assign a specific new due date using the picker, say 2015-07-05.
* I select task C and assign a new due date, 2015-07-03.

And this happens:
In the list view, task B and C remain unchanged for quite some time or until I scroll the list up and down a few times. Then the new due date appears. They also retain their list positions, which I think I've read somewhere in the changelog is the new default behaviour (task A is being moved immediately though, on a sidenote).

Now here's the weird thing: On assigning the new due date to task C, after the list gets updated, both C and B have the same due date (that of C).

I'm presently using Simpletask Cloudless 5.5.4 (from f-droid) on a Samsung S4 mini running Cyanogen 11.
Thanks in advance!

**Comment by mpcjanssen** [comment]
I think this issue is fixed in 5.5.6. I have tagged that about an hour ago. So it should be in the playstore shortly. I dont know exactly how long fdroid takes.

Can you recheck with 5.5.6?

**Comment by mpcjanssen** [comment]
Btw the position keeping is not of the tasks, they follow the sort, but of the list scrolling position so you can easily chexk a sequence of tasks in the middle of the list.

**Comment by scheunengeist** [comment]
5.5.6 showed up in f-droid today and I tried it. The issue seems to be corrected from what I've tested.
Thank you for the quick fix!
