### ISSUE TITLE
todo list disappears after checking item as done

### ISSUE THREAD

**Issue by aurisnoctis** [mpcjanssen/simpletask-android#265]
SimpleTask version: cloudless v5.5.6 (1569)

Since the update, which I made today to the version number shown above:

When I check an item from a list, the list sometimes doesn't reappear afterwards. Instead, the screen shows `(0/0)` in the upper left area, and `No tasks to display.` in the middle of the screen.

To bring the list back, I have to go via the menu button in the lower right corner, then `Open todo file`, and then choose `todo.txt`. The list reappears without the check-marked item as expected.

No data is lost, but losing the list view and having to open the `todo.txt` file via menu is inconvenient.

Unfortunately, this behavior is not always reproducible. All the hints I had so far when it happens and when not didn't turn out to be decisive. It did happen several times, also after closing and reopening the SimpleTask app freshly (stopping the app in-between).

**Comment by mpcjanssen** [comment]
Are you using some sort of synchronisation software in the background?

**Comment by aurisnoctis** [comment]
Hi Mark, thanks for answering so fast!   No, I only have my local todo file.

Update:
* When I try to produce a log cat via the SimpleTask settings, it appears to be empty.
* I don't have to open the `todo.txt` file again via menu - it's enough to press the phone's `back` button. That's more convenient than reopening, but not as it is supposed to work.

To reproduce, try
* checking an item with priority A or B (that's where it happened to me, but I am not sure if priority is decisive)
* then unchecking it again
* then checking again
* -> Either right away or after some such cycles, the screen is empty as described above.
* press back button to bring list back

**Comment by aurisnoctis** [comment]
Update:
* This time, I saw the new (very nice) new waiting screen with the moving circle in the middle and dimmed screen for a short while
* pressing the back button now stopped SimpleTask (did not bring list back)
* had to open SimpleTask, and then open `todo.txt` from the menu

So the back button is only sometimes a kind of workaround.

All these issues started with the last update.

**Comment by kai11** [comment]
Same problem for me. No sync, default todo.txt file location.
Happens randomly. Back button workaround sometimes closes app instead of reloading.

**Comment by mpcjanssen** [comment]
I can reproduce the issue.. Will investigate

**Comment by mpcjanssen** [comment]
The issue has to do with the background file observer. If you click the tasks a bit slower, everything works as expected. Will investigate further.

**Comment by mpcjanssen** [comment]
Issue is caused by the fact that the background loading loads the incorrect path. It loads todo.txt instead of /full/path/to/todo.txt

This explains why back reopens the previous correct file and why the list is empty.

**Comment by mpcjanssen** [comment]
@aurisnoctis @kai11 could you try with the latest version at http://mpcjanssen.nl/files/simpletask/latest to check if this has fixed it?

**Comment by mpcjanssen** [comment]
Waiting for confirmation

**Comment by msquared-id-au** [comment]
I also had this problem.  Installing the version at http://mpcjanssen.nl/files/simpletask/latest seems to have fixed the problem.  The new behaviour where the screen dims with the "please wait" circle: that has also stopped since I installed the version at http://mpcjanssen.nl/files/simpletask/latest

**Comment by mpcjanssen** [comment]
The version at that url equals 5.5.7 from the playstore.

**Comment by kai11** [comment]
I can confirm fix in release cloudless version at http://mpcjanssen.nl/files/simpletask/latest
