### ISSUE TITLE
Dropbox: Adding items via intent will sometimes overwrite todo.txt with empty file

### ISSUE THREAD

**Issue by shayneholmes** [mpcjanssen/simpletask-android#266]
I have a Tasker task that adds items to my todo.txt programmatically via the background task intent. Since recently (the new Dropbox core sync API?), this action will occasionally overwrite my todo.txt with an empty (technically 2-byte, I'm guessing just the the utf-8 bom) file. I can get it back through the Dropbox deleted versions, but this would otherwise be a data loss issue.

1. Create a file with "A"
2. Call the background add task intent with text "B"

Expected:
Todo.txt has "A/B"

Actual:
Todo.txt is empty. The last version on Dropbox is "A"; Dropbox never sees the "B" item.

I've installed the latest debug version (5.5.7); I've got a logcat that I took just after this occurred again, which I have pasted here: https://gist.github.com/shayneholmes/e2ef30340f92b6feb5af

**Comment by mpcjanssen** [comment]
When does this happen. Does it always happen? Or does it only happen of Simpletask was not running already?

**Comment by mpcjanssen** [comment]
Logcat indicates that Simpletask is not running in the background at this point yet.

**Comment by mpcjanssen** [comment]
This issue us caused by the fact that an item is being added while the todolist is still loading in the background.
It's easy to reproduce by killing simpletask and doing a note to self.

**Comment by mpcjanssen** [comment]
Only way to prevent race conditions like this is to queue changes on the todolist. I am working on a queueing mechanism for this, but that takes some time. For now add a widget somewhere to ensure simpletask is running in the background.

**Comment by mpcjanssen** [comment]
@shayneholmes could you please retest with the version at http://mpcjanssen.nl/files/simpletask/latest ?

**Comment by shayneholmes** [comment]
Tested and verified it worked right once, will check over the next day for
assurance. Thanks!

**Comment by shayneholmes** [comment]
With about 24 hours on this change, I haven't been able to reproduce the bug. I also checked it out with the "kill-first" step you outlined, both online and off-, and no problems. I'll go ahead and close this.

**Comment by shayneholmes** [comment]
Okay, so I've seen this crop up once again; I will watch it over the next few days' usage and post back here if I see anything untoward.

**Comment by kai11** [comment]
I had problem with urls from "share" menu today as well and my todo.txt is empty (in cloudless version it's problematic, dropbox keeps old versions).
@mpcjanssen , can you add versioning?
E.g. move todo.txt to todo-{timestamp}.txt before any change will save A LOT of time if this issue occurs in the future.

**Comment by mpcjanssen** [comment]
Old versions are stored in an internal sqlite database. For now you can share the whole db and extract with a salute editor. Next release will have a built in history viewer. In the meantime I will keep investigating this issue.

**Comment by mpcjanssen** [comment]
@kai11 and @shayneholmes  can you share your log files with me when this happens (preferably after updating to the latest version from https://mpcjanssen.nl/files/simpletask/latest)
I have no clue why this is happening.

**Comment by mpcjanssen** [comment]
I was able to reproduce this issue on my device. So I can look into a fix.

**Comment by mpcjanssen** [comment]
Of course as soon as I have said I can reproduce it and have added logging, it doesn't occur anymore.

**Comment by shayneholmes** [comment]
I've got the latest debug (22 July) installed, will keep an eye out for this again.

**Comment by mpcjanssen** [comment]
@shayneholmes the current playstore version is actually newer.

**Comment by shayneholmes** [comment]
Thanks for the pointer, I've got that one now. I'll keep using it on Dropbox and will be background adding about daily; I'll update here and mail logs if I see the overwrite.

**Comment by mpcjanssen** [comment]
I am currently running a tasker action in the background as well. Haven't
seen any issues.

**Comment by mpcjanssen** [comment]
With the queuing I am pretty convinced this is fixed. Please re-open if this re-occurs.

**Comment by mimmori** [comment]
@shayneholmes Could you share your tasker Task/Profile?

I am going to work to add more automation in todo management (add task by mail / whatsapp, show task for current location / ... ) and your work could be a good starting point.

Thanks.
Domenico
