### ISSUE TITLE
h:1 entry shows even if unchecked in settings

### ISSUE THREAD

**Issue by fmartelg** [mpcjanssen/simpletask-android#267]
Using free version. 

h:1 item shows all the time even if unchecked in settings. HTC ONE M9 Android 5.0.2.  Here is the entry: 

`2015-07-10 h1: Reference lists & tags @-waiting.for @-inbox @-someday @-reference @-ideas @-read.review +calls +computer +errands +home +agenda`

**Comment by mpcjanssen** [comment]
Am I missing something? :h1 is not h:1

**Comment by fmartelg** [comment]
Ha!  I am afraid I was the one missing something ;-)  Changed the spelling and it works.

That said, it is more natural to think of `h1:` than `h:1`. That is I think of `h1` as a header then `:` then the rest.

**Comment by mpcjanssen** [comment]
Only problem with h1: is that it doesn't follow the todo.txt defined extension format. So h:1 it stays.
