### ISSUE TITLE
Save previous versions of todo.txt file

### ISSUE THREAD

**Issue by kai11** [mpcjanssen/simpletask-android#269]
I had problem with urls from "share" menu today as well and my todo.txt is now empty.
It can be a major problem in cloudless version, dropbox keeps old versions.
Is it easy to save versions?
Move todo.txt to todo-{timestamp}.txt before any change will save A LOT of time if this issue occurs in the future.

**Comment by kai11** [comment]
Can be a "development" switich for unstable versions.

**Comment by mpcjanssen** [comment]
New versions have an internal database which keeps 2 days of old files. Current development version also has a history viewer built in. History can be shared to other applications (including simpletask itself)

**Comment by kai11** [comment]
Since it's simple sqlite3 db, I was able to extract my data on my own.
