### ISSUE TITLE
Group tasks by priority

### ISSUE THREAD

**Issue by kai11** [mpcjanssen/simpletask-android#270]
When I select tasks for daily work, I ususally set A or B priority to them.
To see them, I need to filter priorities - and both A's and B's will be mixed in the list because it's grouped by list by default.

Can you add "group by priority" option as well?
I think logical place to put this will be before Settings; "Group By" and submenu List, Tag, Priority should be self-explanatory and easy to use.

PS. "No priority" should be lowest group; does not make much sense to put biggest list of postponed tasks to the top; Other cases (Tist and Tag) it's ok on the top.

**Comment by mpcjanssen** [comment]
There is always only one grouping level. If the top group is by priority, the grouping will be there. What you could do is create a `Todo today` filter which sorts by priority first and save that in the right sidebar so it's easy to switch to the grouped by prio view.

**Comment by kai11** [comment]
Ok, I figured out how to group tasks by priority by rearranging them on sort screen.
Suggestion: add this to help page (I checked it first).
Saving filter is not available - maybe it's in new version only - but it's not big deal yet.

**Comment by kai11** [comment]
Probably make sense to keep task open as reminder to update help page

**Comment by mpcjanssen** [comment]
Saving a filter can be done from the right navigation drawer. Then press plus and set a name. I use that a lot.
And I agree I need to give the help files some love.

**Comment by mpcjanssen** [comment]
Documentation will be tracked with #338 .
