### ISSUE TITLE
Editing an existing task will move it to end of list

### ISSUE THREAD

**Issue by xanharris** [mpcjanssen/simpletask-android#274]
When using v6.0.3, I found that when editing an existing task, say 3rd task out of 5, it will be moved to the end of the list in todo.txt file. IMHO, the correct behavior is to maintain task position in the list. This affects my task order as I'm using "File Order (Unsorted)".

Thank you.

**Comment by mpcjanssen** [comment]
Yes this is different behavior. An update to a task is now implemented as deleting the old one and appending the updated one. This simplifies the code a lot, but I can revert this as I see the issue with it.
