### ISSUE TITLE
Switching lists disturbs filters

### ISSUE THREAD

**Issue by sam-wj** [mpcjanssen/simpletask-android#276]
Normally, I have the 'other' items set to show only the tasks' ages with nothing else selected. I also have my lists sorted by vPrio, vDue, ^Create.  When I switch lists, the 'other' items toggle and the sort reverts to the default.

It doesn't always happen. Lately, however, it's happened more often than not.

**Comment by mpcjanssen** [comment]
This only happens for filter tabs which were not visible before pressing filter. Wiil fix this in 6.0.5

**Comment by mpcjanssen** [comment]
And if it was not shown, it's reverting the values on the Other tab
