### ISSUE TITLE
Lots of newline(s) in todo txt file

### ISSUE THREAD

**Issue by jorgb** [mpcjanssen/simpletask-android#277]
For some odd reason, a lot of newlines are present in the todo txt file. I did not notice this before, but when I am resolving conflicts with a diff compare tool, I noticed that the textfile contains superfluous empty lines.

For example;
```
x 2015-07-28 2015-07-26 Task A
    
    
    
    
    
    
x 2015-07-28 2015-07-24 task B
x 2015-07-28 2015-07-26 task C
x 2015-07-28 Task D
2015-07-28 Task E
2015-07-11 Task F
    
    
```
All the empty lines contain 4 spaces. In hex this looks like;

```
0001bd0: 0d0a 2020 2020 0d0a 2020 2020 0d0a 2020  ..    ..    ..  
0001be0: 2020 0d0a 2020 2020 0d0a 2020 2020 0d0a    ..    ..    ..
0001bf0: 2020 2020 0d0a 2020 2020 0d0a 2020 2020      ..    ..    
0001c00: 0d0a 2020 2020 0d0a 2020 2020 0d0a 2020  ..    ..    ..  
0001c10: 2020 0d0a 2020 2020 0d0a 2020 2020 0d0a    ..    ..    ..
0001c20: 2020 2020 0d0a 2020 2020 0d0a 2020 2020      ..    ..    
0001c30: 0d0a 2020 2020 0d0a 2020 2020 0d0a 2020  ..    ..    ..  
0001c40: 2020 0d0a 2020 2020 0d0a 2020 2020 0d0a    ..    ..    ..
0001c50: 2020 2020 0d0a 2020 2020 0d0a 2020 2020      ..    ..    
0001c60: 0d0a 2020 2020 0d0a 2020 2020 0d0a 2020  ..    ..    ..  
0001c70: 2020 0d0a 2020 2020 0d0a 2020 2020 0d0a    ..    ..    ..
0001c80: 2020 2020 0d0a 2020 2020 0d0a 2020 2020      ..    ..    
0001c90: 0d0a 2020 2020 0d0a                   
```

**Comment by mpcjanssen** [comment]
Two questions:

1) is this for dropbox?
2) Can you clean the whitespace and when it reoccurs send me the log?

**Comment by jorgb** [comment]
Yes, it syncs with Dropbox
The newlines are removable (not sure if they will be rewritten, I will check: no they stay gone)
When this occurs again, I will send you the log.
What puzzles me, are the four spaces. Like there should have been something there but isn't
Also, it seems to happen around a conflict, where the todo.txt gets renamed to todo XYZ conflicted copy (1).txt

**Comment by mpcjanssen** [comment]
Do you use intents, note to self or share to add tasks to Simpletask on regular basis?

**Comment by jorgb** [comment]
Nope, I rarely share something to SimpleTask. I usually make new tasks through the widget. I sync between my Nexus7 and SonyXperia Z3.

**Comment by shayneholmes** [comment]
I'm seeing this as well (I'm using store version of Dropbox sync). I was seeing naming conflicts, too, but am still seeing the extra spaces now that things are more cleanly synced up, too.

**Comment by mpcjanssen** [comment]
Could you try with the version at http://mpcjanssen.nl/files/simpletask/latest which includes the two fixes  above?

**Comment by mpcjanssen** [comment]
@jorgb is this still ocuuring with the latest version from the playstore (6.0.8) ?

**Comment by jorgb** [comment]
No, I have not seen newlines anymore. Good fix, thanks!
