### ISSUE TITLE
"List/List Inverted" headers don't refresh on change

### ISSUE THREAD

**Issue by shayneholmes** [mpcjanssen/simpletask-android#279]
1. Pull in the left slider
2. Click on "LIST" header

Expected:
Changes to "LIST INVERTED"

Actual:
While the todo list filter is reversed, there is no change to the header title (still says "LIST").

3. Scroll the list so the "LIST" header is off the screen, then back again so it's visible
   * Now it says "LIST INVERTED"

Same goes for "TAG" header below that.

**Comment by mpcjanssen** [comment]
Seems to be fixed in the latest versions. @shayneholmes can you confirm?

**Comment by shayneholmes** [comment]
Verified in latest. Thanks!
