### ISSUE TITLE
Tasks in widget change depending on which file is open in SimpleTask

### ISSUE THREAD

**Issue by flight16** [mpcjanssen/simpletask-android#282]
1. Create a widget and filter that applies to your current todo.txt
2. Look at the widget on the home screen
3. Open a different file in SimpleTask
4. Look at the widget on the home screen.

I expect the widget in 2 and 4 to display the same tasks.  What actually happens is that 4's tasks reflect the file I opened in 3.  I think you could argue why this happens, but I don't think it's the behavior most users want.

I think when you create widget filter it needs to be associated with a specific todo file, too.

Background:

I was trying to create a widget for my shopping list, and also link to other todo:// files to break down larger projects.  I left a separate project open in SimpleTask, looked at my shopping list widget on my home screen, and it was empty.

**Comment by mpcjanssen** [comment]
This works as designed, so  I will reclassify this as a feature request.
The big challenge with linking widgets to specific files is how to keep the widgets updated if Simpletask is showing another task list and the widget files is changed remotely.
Currently Simpletask is not designed to do this at all.
I personally use different lists to split the files so I have a context @@errands for my shopping list. I then use saved filters to quickly switch to different views. This gives a lot of the same functionality without all the technical issue.

**Comment by y2kbugger** [comment]
Crazy, I use @@errands also. I just thought I was using the program wrong to make some lists look like lists and others like contexts. Cool!

**Comment by mpcjanssen** [comment]
Because of the difficulty of tracking background file changes and the already available options to partition the todo file, this is never going to happen. Closed.
