### ISSUE TITLE
todo.txt is empty after phone battery fell out

### ISSUE THREAD

**Issue by aurisnoctis** [mpcjanssen/simpletask-android#286]
I was inside the SimpleTask app when I dropped my phone, and the phone battery fell out.

I restarted the phone, and my todo.txt was empty. I checked with a file browser, and the size is now 0 (empty).

SimpleTask version 6.0.6

**Comment by mpcjanssen** [comment]
You should be able to restore the last saved version from Settings->History. You can then share the version you want to restore with Simpletask and you should have your tasks back.
Preventing data loss like this with a plain text format is almost impossible.

**Comment by aurisnoctis** [comment]
Thank you!

I forgot to mention I use cloudless, but I found the history as you described. The most recent one is empty, but the one before has my entries.

Now I have the options `next`, `previous`, `share`, and inside the menu `empty database` and `share database`. Which option do I use to restore?

**Comment by mpcjanssen** [comment]
Use the share option and share with simpletask

**Comment by aurisnoctis** [comment]
Ok, thank you. Rather obvious, ruling out the other options :'D Thanks for all your work!

**Comment by mpcjanssen** [comment]
Just curious, what is the size of your history DB (it shows in the title)

**Comment by aurisnoctis** [comment]
The most recent one is empty and shows `5028KB` in the title (empty in file browser). 1 previous to that shows `5028KB` in the title and contains entries from 10:10 today. Going to more `previous` versions actually all show `5028KB` in the title ...

Now I choose the most recent version that is not empty (1st `previous`). I press `SHARE` at the bottom. I select `SimpleTask Cloudless`. The screen returns back to the history version I selected for sharing. Now I press the `back` arrow in the upper left. I get back to `Settings`. Now I use my phone back button and I get back to the main SimpleTask screen, but it is still empty (no filter or search active). Now I tried closing SimpleTask completely and start new: the list is still empty. According to the file browser, `todo.txt` is still empty, so opening it from the menu doesn't help.

What does happen when I open done.txt from the menu is that the size of the history versions changes. Now all history versions show `4448KB`. In the file browser, the size of my `done.txt` is given as 50kB.

**Comment by mpcjanssen** [comment]
The size in the title shows the total size of the database. It only keeps the different versions of the last two days. Sharing the tasks should have re-added it to simpletask, will look why this didn't happen. For now, just share the todo.txt via email and put it in the file like that,

**Comment by mpcjanssen** [comment]
Sharing does work for me, so it would be interesting to see your log. I think your todo might actuially be too big to share as plain text. If sharing to mail also fails, please share the database with me and I can recover the last version for you.

**Comment by aurisnoctis** [comment]
Next attempt: sharing with myself by email (I just saw that that's your suggestion as well): an attachment is created `simpletask.txt`, but the email arrives without attachment. When I forward this sent email to myself, the tasks now appear in the body of the email. (Could be a K9 email app glitch, no idea).

Now I can use the tasks in the email body -- the list seems complete. Only handwork required: all 'ä', 'ö', 'ü' that appeared without problem in SimpleTask became ��. Again, that could be an encoding problem of my email app since the tasks were in the end in the body of the email instead of in an attachment.

**Comment by mpcjanssen** [comment]
Simpletask uses UTF-8 everywhere.

**Comment by mpcjanssen** [comment]
I can reproduce the issue with tasks not being shared correctly with Simpletask directly, I will look into this.

**Comment by aurisnoctis** [comment]
Yes, I thought it was an email glitch. I just sent you my log by email. Let me know if I can test anything or provide more information.

**Comment by mpcjanssen** [comment]
Sharing of large todo.txt file is fixed.

**Comment by aurisnoctis** [comment]
Ooo. Thanks!
