### ISSUE TITLE
Changes file format / file's line terminator (LF to CRLF)

### ISSUE THREAD

**Issue by krayon** [mpcjanssen/simpletask-android#289]
It appears that when the TODO list is changed, the file gets modified, converting all LF (Line Feed) characters into CRLF (Carriage Return, Line Feed) pairs. This makes the file difficult to manipulate outside of the app and to keep sync'd.

**Comment by mpcjanssen** [comment]
Simpletask has a setting to chose between windows and Unix linefeeds. Are you on Mac? A Mac option needs to be added

**Comment by krayon** [comment]
No Linux. Sorry this was my fault, despite looking in the settings 3+ times, I missed it :S
