### ISSUE TITLE
Expand recur syntax to differentiate between days from due date and days from now

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#29]
The todo.txt 'repeat' add-on can differentiate between tasks which are scheduled from now and tasks which are scheduled from the due date. It would be useful if recur could do this too.

See https://github.com/ginatrapani/todo.txt-cli/wiki/Todo.sh-Add-on-Directory#wiki-repeat for details. Examples given

$ todo.sh repeat 3 7 # Marks item 3 as done and recreates it 7 days from now
$ todo.sh repeat 3 +7 # Marks item 3 as done and recreates it 7 days from the due date

So recur could use a similar syntax

rec:[0-9]+[dwmy] for tasks which are recreated from the due date
rec:[0-9][dwmy] for tasks which are recreated from now

Reason for request: Some of my tasks need doing every so often but it doesn't matter if I don't complete them on the due date. But other tasks are less flexible, e.g. take the rubbish out for collection every week. Currently I need to flip the 'recur tasks using original dates' preferences state before completing these tasks.
__Reporter:__ Anonymous
__Assigned to:__ Mark Janssen
__Begin:__ 2014-01-08
__Completed:__ 0

**Comment by Nelvin** [comment]
I'd love this to be implemented.
IMO I almost can't imagine someone using recurring tasks regularly but without the need for both variations.

Could be implemented in a pretty basic way, I guess - just add a character to the value part of rec:
Like rec:1wr (relative) rec:1da (absolute)? Of course any other way to differentiate would work too.
Would even be backwards compatible - without an additional character just keep it the way it is right now.

**Comment by mpcjanssen** [comment]
I am just finishing a big material theme update. This will be one of the first things I will tackle after that.

**Comment by Nelvin** [comment]
Great news - looking forward to the upcoming updates. Great work and fantastic support as usual!

**Comment by mpcjanssen** [comment]
You can preview latest at http://mpcjanssen.nl/files/simpletask/latest
