### ISSUE TITLE
lua filter for tags

### ISSUE THREAD

**Issue by aczirok** [mpcjanssen/simpletask-android#294]
Hi, could you hint me how to lua-filter on tags?
for i,t in pairs(tags) do
gives me an error: "table expected, got nil" -- but the test task does have tags associated with it..
or, is there any other way to save filters?

**Comment by mpcjanssen** [comment]
tags is an array. To iterate to array tables in Lua you'll need ipairs. This should work then. What is you test task?

**Comment by aczirok** [comment]
Hi Mark,

thanks for your response (and the great app !!)

I am new to lua, so I must be doing something wrong...
The test todo file is very simple:

(C) task1 +tag1 @list1
(D) task2 +tag2 @list2
                    
and my filter script is:

for i,t in ipairs(tags) do
  if t == "tag1" then return false;
  end
end

output (as if the task array were empty):
scipt:1: bad argument: error table expected got nil

same thing if I use ipairs(lists)

but 

if priority == "C" then return true;
end

works as it should..

**Comment by mpcjanssen** [comment]
First of all you need to fill the test task to actually test the filter. If you don't fill this you get the error.

Besides that you should use:
````lua

for i,t in ipairs(tags) do
 if t == "tag1" then return false;
 end
end
return true

**Comment by aczirok** [comment]
Mark, sure.

The output is what I got for testing a particular task.
And if I use the "simpler" priority filter:

  if priority == "C" then return true;
  end
  return false

it works as it should. so the basics are OK. :)

if I try either tags or lists, it does not work. I load my list, copy the
filter from your response, select test task as 1, and got the same error
for line 1.

this is version 6.0.8

**Comment by mpcjanssen** [comment]
All I can say is it works for me. Did you copy and paste the code?

**Comment by aczirok** [comment]
Yes.
I think somehow the tags/lists variables are not populated.
if I just test it as

 if tags==nil then return false;
 end
 return true;

then it always evaluates to false..

**Comment by mpcjanssen** [comment]
so if you apply this filter your task list is empty?

**Comment by aczirok** [comment]
very interesting. the filters actually do work (including the ipairs !) when you apply the filter and look at the list -- which is the important thing. :) I get the error only if I test them for a particular task in the filter editor panel.

**Comment by mpcjanssen** [comment]
strange indeed. Can you copy the full test task and append it to the ticket?

**Comment by aczirok** [comment]
so, I think a minimalistic set to generate the problem is the following:

task list:
```
(C) task1 +tag1 @list1
(D) task2 +tag2 @list2
```

filter:
```lua
if tags==nil then return false; 
end 
return true;
```

and if in the filter/script pane you set 1 as test task, the filter evaluates as "false".
Yet, if you apply the filter, both tasks remain visible (which is the correct behavior). 

There  is no such discrepancy for the priority variable.

**Comment by mpcjanssen** [comment]
Very interesting. I will check this.

**Comment by mpcjanssen** [comment]
Task 1 with this filter works for me. I will check if anything in the code can explain this.

**Comment by mpcjanssen** [comment]
Can't find anything that migh cause this.

**Comment by smichel17** [comment]
Another filtering issue. #160

**Comment by mpcjanssen** [comment]
Can't reproduce this. Closed. Please re-open if additional info.

**Comment by mpcjanssen** [comment]
@aczirok I am redoing the filtering in Lua. With the new functionality the tags will be the keys in a table so testing if a tag is on the task is a simple `fields["tags"][tag] ~= nil`
