### ISSUE TITLE
List appearing empty is shown when h:1 task is hidden

### ISSUE THREAD

**Issue by vwbugg** [mpcjanssen/simpletask-android#295]
I created an h:1 hidden task to house some list names and tags. When this is hidden, there will still apear a header on the main screen for the context used for the h:1 task.
![screenshot_2015-09-01-12-55-10-1](https://cloud.githubusercontent.com/assets/14080506/9614788/cf12f890-50a8-11e5-8504-d7942507041c.jpg)

**Comment by mpcjanssen** [comment]
There is a setting show empty headers. Disabling this should fix this.

**Comment by vwbugg** [comment]
Well ill be. Its right there under the option to hide the h:1 task. This was driving me nuts. Thank you.
