### ISSUE TITLE
Font size in pixels

### ISSUE THREAD

**Issue by gastus1** [mpcjanssen/simpletask-android#301]
Hello!
My name is Agassi, i'm from Spain.

I would like to thank you very much for the app - i use it all the time!

As my vision is not perfect, i'd like to have a font in the app a little bigger than the Medium option. And the Large one is too large, i mean - the jump from Medium to Large is too big.

If possible, the size picker would be better, imho.

Thanks again, you're great!

**Comment by mpcjanssen** [comment]
I will probably make the fontsize configurable in sp. See http://developer.android.com/guide/topics/resources/more-resources.html#Dimension

**Comment by gastus1** [comment]
Yes, in sp is way better! I'll be waiting!
Thak You!

**Comment by smichel17** [comment]
So this happened, but then there's #441.

@gastus1 Would an added option of "Medium-large" fix your issue, instead of making font size fully configurable?

**Comment by gastus1** [comment]
@smichel17 
Yes, i guess it will, although a selection of sizes would be better!

**Comment by mpcjanssen** [comment]
In the same way as #349, i am considering to make these kinds of settings configurable from Lua as well so you can either have limited options in the settings or unlimited options using scripting.

**Comment by gastus1** [comment]
@mpcjanssen 
Cool, but i hope some examples will be available - i'm not an expert in Lua at all (.

**Comment by mpcjanssen** [comment]
Settings like this would be something like 

```
function getTextSizeSP ()
  return 11.5
end
```

So relatively easy. If this function is defined this value will be used. Otherwise the value from the settings.

**Comment by smichel17** [comment]
>Otherwise the value from the settings

+1. Eliminating settings that supported workflows outside of the core intended functionality is great. Providing  really powerful configuration via scripting is great. **Someone who wants to use the app with the intended/opinionated workflow should not need to touch lua.**

**Comment by mpcjanssen** [comment]
Task list text size has been removed. It's not feasible to provide a setting which suits everyone. Instead the size can now be set in the main app Lua config.

Change the font size of the main task list to `16sp`:

    function tasklistTextSize()
       return 16.0
    end

**Comment by smichel17** [comment]
I don't think I agree with this decision. I think Lua should be there as a way to add advanced functionality; nobody should be required to use Lua scripting just to use the app.

I'm in favor of having the setting, with options of small/medium/large/custom. Interface being much like the interface for adding a date: a list, and if you pick the 'custom' option you get a text box to enter the font size and a numpad.

**Comment by mpcjanssen** [comment]
@smichel17 I might have been a bit to enthusiastic here. Felt nice to clean up that mess though :smile: will probably re-add it as I agree with your sentiment.

**Comment by mpcjanssen** [comment]
However you don't have to use Lua to use the app, you just have to use Lua to change the task list text size.
I will extend this with other configurable stuff like drawer text size etc. Doing this all in settings as well is a lot of work.

**Comment by smichel17** [comment]
I think the current setting works well enough that you should remove the callback.

**Comment by mpcjanssen** [comment]
The callback doesn't hurt and it fits with my goal to have every option available in Lua so you can just use a predefined lua script as a _theme_

**Comment by smichel17** [comment]
Okay, that makes sense. I like that a lot, actually.
