### ISSUE TITLE
"Today", "Tomorrow", "Next" views

### ISSUE THREAD

**Issue by gastus1** [mpcjanssen/simpletask-android#302]
It would be perfect to have Views like "Today", "Tomorrow", "Next" and "Someday".

The lua filters will not serve, i guess, because the filter is limited to its conditions, so if one Filter is created for tasks that due Today and with tag A, you cant change to tasks of another tag or contest while still looking only on Todays tasks.

And of course creating filters for every case is impossible. ))

In "Someday" view could go the tasks without due dates i guess.

**Comment by mpcjanssen** [comment]
You could create a lua filter for today and then do all the other filtering with the normal filters. It's perfectly fine to combine lua filters and prio filters for example.

**Comment by gastus1** [comment]
Oh, you're right -its perfect! I did not notice that changing normal filters does not reset the script filter.
Thank you very much!

**Comment by gastus1** [comment]
Actually, a little help with lua would be great.

I just tried to make a script to show the tasks for today only, but did not succeed.

`````
if due~=nil then
     return os.time() = due;
end
`````
gives an error.


This one works: 

`````
if due~=nil then
     return os.time()>= due;
end
`````
but it shows the tasks for today and past tasks.


Can you help with how to make a script for Today only, and for Tomorrow?

**Comment by gastus1** [comment]
I found a working script for today in this issue: https://github.com/mpcjanssen/simpletask-android/issues/93#issuecomment-105001605
Here it is for noobs like me )):
The LUA script to display the tasks for TODAY
```````
if due~=nil then
    return os.time() > due and os.time() - 86400 < due
end
return false;
```````

And by analogy, the LUA script to display the tasks for TOMORROW
```````
if due~=nil then
    return os.time() < due and os.time() + 86400 > due
end
return false;
```````

**Comment by mpcjanssen** [comment]
So fixed I guess.
