### ISSUE TITLE
Option to configure recurring task missing

### ISSUE THREAD

**Issue by whudwl** [mpcjanssen/simpletask-android#304]
the option that controls whether to use completion date or date in the task, is missing. I'm using 6.0.8

**Comment by mpcjanssen** [comment]
With the setting you only had one possibility. Either all tasks recurred from completion date or all recurred from the due date.
Instead the syntax has been extended to allow both.

rec:1d recurs from the completion date rec:+1d recurs from the original due date.

**Comment by whudwl** [comment]
Thank you so very much!
This is the number one best app on android.



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.3.5&pv=5.1.1&source=email_footer_2] On Sun, Sep 27, 2015 at 3:43 PM, Mark Janssen < notifications@github.com [notifications@github.com] > wrote:
Closed #304 [https://github.com/mpcjanssen/simpletask-android/issues/304] .

—
Reply to this email directly or view it on GitHub
[https://github.com/mpcjanssen/simpletask-android/issues/304#event-420096017] .[https://github.com/notifications/beacon/ACtgpWcQogcml4RwYdaDG-p4bNZhovE1ks5o15W2gaJpZM4GEcdl.gif]
