### ISSUE TITLE
[feature request] Allow the user to choose where to save the todo.txt

### ISSUE THREAD

**Issue by ghubby123** [mpcjanssen/simpletask-android#306]
This app is a fantastic app with a great interface that I really like, but the cloudless app should allow the user to select where they want to save the todo.txt file so that it could be made to sync with owncloud rather than dropbox.   Keep up the good work!

**Comment by mpcjanssen** [comment]
You can open a todo file from any location. After doing that, the same file will be used for updates, so I don't understand this issue.
Can you explain what you want to do which isn't covered by `Open todo file` from the menu?

**Comment by ghubby123** [comment]
Silly me, you're right; this functionality is already in the app and it works well, thank you.  

I had installed the app and added multiple entries before I tried to find a way to save the entries and have them sync via owncloud.  To correct this, I shared the full list with myself via email, then copied the output to a new file on my PC in the owncloud folder which I was then able to open via simpletask once it had sync'd to my phone.

Do you accept paypal donations?  I've got $5 for such a great app.

**Comment by mpcjanssen** [comment]
Glad you got it resolved. The PayPal link is in the support section of the main help file.
