### ISSUE TITLE
Cannot click on "..." menu icon on top right of screen.  Cannot open right pane.

### ISSUE THREAD

**Issue by fmartelg** [mpcjanssen/simpletask-android#309]
SimpleTask paid version
HTC One M9
Android 5.1
HTC Sense 7.0

### Symptoms
1. I open Simple Task.  I try to clik on `...` menu icon on top right.  Instead the Filter menu opens up.  Not an issue with fat fingers.

2. I can open left pane but right pane is unresponsive.  It does not open.

3. I long press a task in list to highlight it.  Bottom menu pops up.  Clicking on vertical `...` icon opens up priority menu (e.g. as if clicking on star icon).

To check if this is a more general issue, I open Firefox.  Have no problem clicking on `...` menu icon on top right.  But similar problem appears on Gmail.  If I open an email and click on vertical `...` icon, it acts as if I clicked on the icon next to it, the reply button.

I have restarted phone etc. to no avail.

**Comment by fmartelg** [comment]
OK.  It seems this may be a hardware issue.  A quarter inch margin on the right side of the touch panel is insensitive to touch.  Getting a replacement from HTC.  

Please close this issue

**Comment by mpcjanssen** [comment]
Thanks for the update.  Good luck with the replacement.
