### ISSUE TITLE
2 rec tags rather than option

### ISSUE THREAD

**Issue by y2kbugger** [mpcjanssen/simpletask-android#313]
rec should be based on original date.
arec(anachronistic rec) should base the recurrences on the complete date. Calling it anachronistic as a reference to anacron vs cron.

For backward compatibility look at what the option was set to in previous version. If set to the latter mode, convert all rec to arec.

Alternatively make the option tristate. Cron way, anacron way, and two tag way. This will allow for complete backwards compatibility, and also will not screw up git history for people who do that sort of thing. I still find the to option more elegant and it would only be a single commit that ends up ugly.

**Comment by mpcjanssen** [comment]
This is fixed in the latest version:

Recurrence is from today by default (if you specify for example `rec:2d`) however if you use `rec:+2d` recurrence occurs from the original date.

**Comment by y2kbugger** [comment]
That's an awesome solution!
