### ISSUE TITLE
Add Taskpaper / Plain Text format support

### ISSUE THREAD

**Issue by alienx2** [mpcjanssen/simpletask-android#315]
I would like to suggest to support taskpaper or understandable to read plain text format.

there was problem between simpletask and taskpaper like indent tab,priority (A), losing '-', add @done instead of 'x'

I will give you idea to trick: to add check/uncheck "Taskpaper term" beside todo.txt term

Function> Simpletask will support Taskpaper term or understandable to read plain text format.
- Indent tab > Don't remove indent tab that will work with subtasks in taskpaper (Bec after save sync and edited line, will lose indent tab :(  It need will work with subtasks )
- Priority > add (A) in the end of line e.g. "- do finish project (A)" or second option: "- (B) do finish project"
- Dash '-' in the first line> Dont write any in the start line. e.g. "- do finish project" <<**important**
- Complete Task >  use @done or @done(date) instead of 'x' without losing '-' dash e.g. "- do finish project @done(2015-10-20)" or can be like this "- x do finish project"
- Created date > use @date or @created(date) e.g. "- do start project @2015-10-20" or second option: "- do start project @created(2015-10-20)"
- Due date > same as created date (above) but e.g. "- do start project @due(2015-10-20)"

Before:
![before - taskpaper](https://cloud.githubusercontent.com/assets/1681482/10604962/9a9a4a36-775a-11e5-8507-c7e699edcd9d.png)
![before - simpletask](https://cloud.githubusercontent.com/assets/1681482/10604779/612632de-7759-11e5-8551-89422cace00a.png)
![before - plain text](https://cloud.githubusercontent.com/assets/1681482/10604998/d19b9e36-775a-11e5-907b-20246ea7f04c.png)

After:
![after - taskpaper](https://cloud.githubusercontent.com/assets/1681482/10604959/968e982a-775a-11e5-95a7-a1822501b024.png)
![after - simpletask](https://cloud.githubusercontent.com/assets/1681482/10604778/60f4e396-7759-11e5-8b69-8c052592343c.png)
![after - plain text](https://cloud.githubusercontent.com/assets/1681482/10604995/cccf4b5a-775a-11e5-9670-15cbbc93df89.png)

**Comment by mpcjanssen** [comment]
The text shouldn't change even if it's not proper todo.txt format. This is a bug in the parser probably. I will look into this. 
Better support for taskpaper in general is very low on the list and will probably never happen.

**Comment by alienx2** [comment]
ok then please fix not to remove intend tab after edited line (except 'x' or priority) & sync from simpletask.

**Comment by mpcjanssen** [comment]
BTW, the main limitation to properly support taskpaper and todo.txt is that todo.txt doesn't support projects with subtasks whereas taskpaper does.

**Comment by alienx2** [comment]
No.. i mean i want indent tab (yes like subtask) is untouched (no remove) in text bec it was edited by PC/MAC.

**Comment by mpcjanssen** [comment]
Not going to happen, adding another format is much better served by making a completely different app.

**Comment by smichel17** [comment]
> a completely different app

Which, for anyone interested, could be a fork Simpletask :)

**Comment by mpcjanssen** [comment]
Indeed a Simpletask UI with taskpaper backend app could work very well.
