### ISSUE TITLE
UX improvement for search

### ISSUE THREAD

**Issue by fmartelg** [mpcjanssen/simpletask-android#318]
1. Open app.
2. Click on magnifying glass to search.
3. Click again on `Search todo.txt` 
4. Cursor is on search text box, keyboard visible.
5. Type search query.

Step 3 could be skipped.  Go from 2 to 4 directly.  After Step 2 is obvious I want to type something.

Thanks!

**Comment by mpcjanssen** [comment]
Unfortunately these types of 'simple' things, are very hard to achieve on Android (or I don't know how). I will into this.

**Comment by mpcjanssen** [comment]
Commit didn't fix the issue.
