### ISSUE TITLE
UX improvement navigation

### ISSUE THREAD

**Issue by fmartelg** [mpcjanssen/simpletask-android#319]
1. I hold phone with right hand.  
2. My thumb sits close to edge of phone.  
3. Every time I scroll up and down I jump several pages because my thumb touches scroll bar.

Could not find setting to disable jumping when touching scroll bar.  That would be very useful.

**Comment by mpcjanssen** [comment]
I recently noticed this myself too. This is caused by the fast scrolling scrollbar. I will make this a configurable option.
