### ISSUE TITLE
Grouping by due data

### ISSUE THREAD

**Issue by paullemmens** [mpcjanssen/simpletask-android#322]
When I sort my list view on threshold date, I get a list/view in which tasks are nicely grouped by their threshold date. For this I set 'by threshold' date at the top of the sorting list. However, this does not work for sorting by due date. 

Is this intentional?

**Comment by mpcjanssen** [comment]
Yes this is intentional. The grouping is limited but I will change it to allow grouping by any sort field.

**Comment by paullemmens** [comment]
Great to hear, thnx! Out of curiosity, why did you initially limit it?

**Comment by mpcjanssen** [comment]
I didn't think it would make much sense to group by due date considering most groups would contain a single task. (At least for me)
