### ISSUE TITLE
documentation on https://mpcjanssen.nl/pages/simpletask.html has broken links

### ISSUE THREAD

**Issue by okurz** [mpcjanssen/simpletask-android#328]
maybe the documentation should refer to github issues instead?

**Comment by mpcjanssen** [comment]
Ah I should update my homepage indeed. Thanka for letting me know.

**Comment by mpcjanssen** [comment]
Page now refers to github.

**Comment by Opennat** [comment]
"the tracker" link on http://mpcjanssen.nl/doc/simpletask/ still go to http://mpcjanssen.nl/tracker/projects/simpletask-android (404)
