### ISSUE TITLE
date, due:date font size is too tiny

### ISSUE THREAD

**Issue by gaydenko** [mpcjanssen/simpletask-android#331]
Hi! Android 4.4.2 is in use. `Date` and `due:some-date` fields' font size is too small (and it is show stopper for my eyes, unfortunately). Moreover, font size setting doesn't result in these fields rendering change. 

Can these "additional" (but having sometimes even more sense rather than todo text itself) fields be rendered (I mean font size) the same way as todo text?

**Comment by mpcjanssen** [comment]
This is yet another request to make the UI elements of Simpletask more configurable. I will create a single issue to bundle all of these. However because of the amount of work required and the limited time I have at the moment I don't think I will get to it anytime soon.

**Comment by mpcjanssen** [comment]
@gaydenko would displaying them like the widget without "extended widget" in the settings work?

**Comment by gaydenko** [comment]
@mpcjanssen , sorry, I can not supply useful feedback as far as don't use the app - can not marry life rhythm with tasks idea.
