### ISSUE TITLE
NOW FIXED: When editing, clicking on + causes crash

### ISSUE THREAD

**Issue by erictlee** [mpcjanssen/simpletask-android#332]
I see you've fixed this - wow, very fast!  Thank you! (You need to go to Google Play to download the laterst version of the app, but it did work.)

When editing an existing task, when I click on the plus (+) sign below to tag it, I get the error message "Unfortunately, Simpletask has stopped."  This happens every time, on each task, including new ones.  This has only started happening with the newest version of Simpletask, which was updated automatically this week on my Android phone (LG G3, running Android 5.0).

**Comment by mpcjanssen** [comment]
Can you confirm this is fixed with 6.3.1 ?

**Comment by mpcjanssen** [comment]
Ah just saw the title, never mind.

**Comment by mpcjanssen** [comment]
Sorry about the initial bug.
