### ISSUE TITLE
Toast shown when calendar access denied and calendar sync disabled

### ISSUE THREAD

**Issue by vojtechkral** [mpcjanssen/simpletask-android#334]
Don't show a toast warning if due/threshold calendar events not enabled.

**Comment by mpcjanssen** [comment]
Should be fixed in latest version

**Comment by vojtechkral** [comment]
Thanks and sorry for not fixing this earlier, kind of low on free time now :-/

**Comment by mpcjanssen** [comment]
@vojtechkral no problem, I know the feeling :-)
