### ISSUE TITLE
Feature: Bulk change prio

### ISSUE THREAD

**Issue by bttrx** [mpcjanssen/simpletask-android#342]
As of today you can select multiple tasks and open an edit window, but there's no search and replace, so you have to edit each tasks priority manually. To me it would be a big step forward to have a menu item to set all selected tasks to the same prio, e.g., to change all from "(C)" to "(B)".

Background: [Rule #2: Use only the top few priorities, A-D, and make them mean something specific and time-based.](http://plaintext-productivity.net/1-03-how-i-organize-my-todo-txt-file.html#rule-2-use-only-the-top-few-priorities-a-d-and-make-them-mean-something-specific-and-time-based-)

**Comment by mpcjanssen** [comment]
You can change the prio from the main screen. There is no need to go to the edit screen. Select the tasks and press the star button.
Why do you want to do this from the edit screen?

**Comment by bttrx** [comment]
Oops, I didn't notice the star button. It exactly does, what I want. :+1:
