### ISSUE TITLE
Sorting by due date

### ISSUE THREAD

**Issue by sunnyolives** [mpcjanssen/simpletask-android#343]
Simpletask sorts alfabetically. Is there a way to make it sort by due date? In the case of no specified due date, it could sort alfabetically or by creation date.

**Comment by mpcjanssen** [comment]
Sorting is part of the filter, so if you click the double tag button, there is a tab "sort" (you might have to swipe the tabbar on a very small device.
You can then drag the "By Due Date" to the top for this to be the first sort.

**Comment by sunnyolives** [comment]
Thanks! I just hadn't explored the app thoroughly enough. Is there a website with this kind of documentation anywhere?

**Comment by mpcjanssen** [comment]
There is help in the app itself, but this is mostly more advanced usage. I should write a simple tutorial which handles all the basic functions. There is already an issue for that.
