### ISSUE TITLE
Changes not synced to Dropbox in 7.0.0

### ISSUE THREAD

**Issue by nthorne** [mpcjanssen/simpletask-android#346]
New tasks get synced to Dropbox properly, but if I for example change priority of a task, or complete a task and then hit refresh, the change is lost.

**Comment by mpcjanssen** [comment]
I think this is caused by a very small change. I will investigate.

**Comment by nthorne** [comment]
Works fine in the new release. Well done!

**Comment by mpcjanssen** [comment]
Shame on me for breaking such essential functionality in the first place though.
