### ISSUE TITLE
Recent update broke archiving

### ISSUE THREAD

**Issue by firecat53** [mpcjanssen/simpletask-android#347]
Hey, great little app! The most recent update seems to have broken the archive feature. I can click the checkbox to complete a task and the strikethrough line appears through the item, but it doesn't get archived, even when selecting  'Archive now' from the menu. Also, exiting the app and re-opening it removes the completed strikethrough but the task is still there. 

Let me know if I can provide any other info or the log file.

Scott

**Comment by mpcjanssen** [comment]
Can you confirm this is fixed in 7.0.1?

**Comment by firecat53** [comment]
Well, it's half-fixed :) It will archive the item now if I manually select the 'Archive' option from the menu, but I have 'Auto-Archive' set in the settings and that doesn't seem to be working.

Thanks!

**Comment by mpcjanssen** [comment]
With auto archive it first archives and then completes the task which is the wrong order. I will fix this.
