### ISSUE TITLE
Extended Lua features like modifying, creating tasks etc.

### ISSUE THREAD

**Issue by Nelvin** [mpcjanssen/simpletask-android#349]
Is there a chance you'll extend the support of Lua of SimpleTask beyond filtering of tasks?

F.i. create/modify tasks by script which get's called on some specific events like finished a task.

This would enable features like
- add a counter to recurring tasks
- limit the number of times a task reoccurs
- on completion unmark the done flag (x) and instead increase a pomodoro counter (this of course would in addition require a kind of simple yes/no dialog box available from Lua but that'd be useful for many kinds of confirmation dialogs anyway).
- create summary tasks that could be updated automatically (i.e. number of tasks done for a task, context, project etc.)

Thinking even further (of course that would require a even more extended Lua support) one could dream of adding support for services like Beeminder etc.

Best regards,
Michael

Design notes at: https://github.com/mpcjanssen/simpletask-android/wiki/Lua-Callbacks

**Comment by mpcjanssen** [comment]
I would love it if all this was possible. It is quite a bit easier said than done though.

**Comment by smichel17** [comment]
Food for thought: extended Lua functionality could become closer to the core of the application.

For example, in the filter view, *all* filters could be implemented in LUA, and editable, and the "script" tab could be removed in favor of an "add new filter" option. It would also be possible to download existing filters to implement additional functionality -- a possible implementation for #362 would be "just download this filter."

**Comment by mpcjanssen** [comment]
@smichel17 even though I like the idea there are several issues with doing all filtering in Lua.

* It's slower than using Java code, this matters for very large lists
* You don't have access to the full task list in the Lua code, this is needed for things like subtasks. Adding this seems to harm performance. I will look into this again though see #387.

Also modifying filters from the UI (like unchecking a tag) will be almost impossible to do in Lua only. Same goes for displaying the filter and tag part in the UI of a random Lua script.

**Comment by smichel17** [comment]
related: #122

**Comment by mpcjanssen** [comment]
Related #466

**Comment by mpcjanssen** [comment]
I will rewrite the Lua part to:

- Use specific callbacks so it's easier to extend (e.g. onFilter, onUpdate, onCalendarSync)
- Add functionality to test a specific callback in the filter screen
- Implement the onFilter and onCalendarSync part.

**Comment by mpcjanssen** [comment]
The calls will take the plain task text, the supported task fields in a LuaTable and any custom key:val extensions in another table to allow people to define their own extensions and use them easily.

**Comment by Nelvin** [comment]
Sounds fantastic ... looking forward to see what you come up with and the cool things we'll be able to do with it.

**Comment by mpcjanssen** [comment]
Example script to show all tasks with due dates:

```
function onFilter (task, f, ext)
   return f["due"]
end
```

**Comment by mpcjanssen** [comment]
I will also add `onCalendarSync` and `onDisplay` onDisplay should have an additional argument to see if it is called from a widget.

**Comment by mpcjanssen** [comment]
See https://github.com/mpcjanssen/simpletask-android/wiki/Lua-Callbacks for proposed callbacks and documentation.

**Comment by smichel17** [comment]
@mpcjanssen What about an onCreation callback? To implement 'background tag' functionality.

**Comment by mpcjanssen** [comment]
@smichel17 added to the list.

**Comment by mpcjanssen** [comment]
Also consider defining settings as function returns for example font size or theme (which could then be based on the time of day)

**Comment by mpcjanssen** [comment]
For continued use of saved filters, the `onFilter` callback definition should be saved in the filter and all other callbacks and settings should be saved as part of the configuration.

**Comment by mpcjanssen** [comment]
Base work is done. Please log any configurable requests as separate issues.
