### ISSUE TITLE
Allow testing of Lua filter without actually applying the filter

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#351]
Right now if you create a filter with an infinite loop, you will have a problem.

**Comment by smichel17** [comment]
#122

**Comment by mpcjanssen** [comment]
#122 is only meant to process task before they are saved to the `todo.txt` (for example to sort tags to the end). This is about display. The common theme is Lua though.

**Comment by smichel17** [comment]
>The common theme is Lua though.

There are some other tasks I've linked to #122 that are also about Lua/display; just trying to get them all in one place.

**Comment by smichel17** [comment]
You can now test callbacks individually from within the filter, so you can notice an infinite loop before you save.
