### ISSUE TITLE
Archiving is not creating a done.txt

### ISSUE THREAD

**Issue by bartnaaijkens** [mpcjanssen/simpletask-android#353]
Hi,

Love your app! However I came across 1 critical bug. When I archive 'done.txt' is not created. I connected SimpleTask to a Dropbox 'app folder'.

Let me know if there is anything I can do to help.

Best,
Bart

**Comment by bartnaaijkens** [comment]
Awesome! Thanks for quick response. Straight away bought the donation package to support your development.

**Comment by mpcjanssen** [comment]
@bartnaaijkens thanks for the support :)
