### ISSUE TITLE
Reminder should (if possible) use Reminder API 

### ISSUE THREAD

**Issue by jorgb** [mpcjanssen/simpletask-android#354]
Google calendar supports reminder entries which are perfect to link to from a simpletask todo item. So instead of making a calendar entry, make every reminder entry. This makes more sense as the reminders need to be dismissed to be completed, and stay in view even when the alotted time slot has expired (if you miss a calendar appointment, the reminding part will vanish together with dismissing the event) 
https://support.google.com/calendar/answer/6285327?hl=en

**Comment by vojtechkral** [comment]
Hm, how does this work, is this specific to the Google calendar app?

**Comment by jorgb** [comment]
Yes, the Google calendar has an option to either make a calendar entry or a
reminder. See attached picture. When pressing the Plus icon it shows two
options. The benefit of a reminder is that it will stick in the calendar,
if you didn't complete it on the 17th it will still be there on the 18th..
It makes more sense than a calendar entry that is volatile and will vanish
out of sight when it passes..

**Comment by vojtechkral** [comment]
@jorgb I can't find any API reference to these events. Either they are just a different interface for the existing reminder functionality or there's no API.

**Comment by jorgb** [comment]
Does this help? (quick google)
https://developers.google.com/google-apps/calendar/concepts/reminders

**Comment by vojtechkral** [comment]
@jorgb Not really. One problem is that that's a remote REST API, we need localy accesbile API. Second problem is that they only mention reminders, but there's no reference as far as I can see. Anyway, we use the Calendar Provider API (https://developer.android.com/guide/topics/providers/calendar-provider.html) that ties reminders to events.

The only way to do this from Simpletask would be to create multiple reminders, one for each day. That could be done.

Also, note that while the reminder vanishes when you dismis it, the calendar event entry itself stays - it's still visible in the calendar until the task is marked as done.

**Comment by jorgb** [comment]
Ok too bad. Thanks for looking into it!

With regards,
- Jorgen
