### ISSUE TITLE
Feature request: hide task till they are due

### ISSUE THREAD

**Issue by djibux** [mpcjanssen/simpletask-android#355]
Hello,

When I set due dates I like hiding the task till it's due.  I currently set both a due and a threshold date.  Here are a few implementations I can think of:
- Having a filter to hide due dates in the future (just like there is one for threshold)
- Having an option to use due date as threshold date
- Having an option to automatically set a threshold date equal to the due date when setting a due date

Thanks.

**Comment by mpcjanssen** [comment]
@djibux I am not quite sure I understand why you would even want to use due date in this case. Why can't you use threshold date only in this case?

**Comment by mpcjanssen** [comment]
Also it's relatively easy to filter tasks with due dates in the future using a script filter (https://github.com/mpcjanssen/simpletask-android/blob/master/src/main/assets/script.en.md).

For example:

```
if due~=nil then
     return os.time() > due;
end
--- tasks with no due date are not overdue.
return false;
```

**Comment by mpcjanssen** [comment]
So this is a typical request that can already be handled by the Lua script filter and which doesn't seem common enough to warrant inclusion as a separate filter option. So closed. @djibux , if you have questions about how to implement the exact filter in Lua, don't hesitate to ask as a comment to this issue.

**Comment by djibux** [comment]
Thanks for the script!
I want to use due dates and not threshold to be able to view it in my agenda :)

**Comment by mpcjanssen** [comment]
The main reason I embedded Lua is to allow these kind of highly customized filters without needing to change the application.

**Comment by djibux** [comment]
Yeah, that's awesome!

**Comment by mpcjanssen** [comment]
BTW you can also create agenda items based on threshold date.

**Comment by djibux** [comment]
D'oh!  I completely forgot about that, sorry.
