### ISSUE TITLE
Wrong context shown when adding multiple tasks

### ISSUE THREAD

**Issue by nthorne** [mpcjanssen/simpletask-android#358]
Version: 7.0.7

Scenario:

Add two tasks, eg.
```
Test 1 @home 
Test 2
```

If I select the second task, and open the context tag dialog, that dialog will indicate that the second task has the @home context set, which is false (unticking the context will, as you might guess, erroneously remove the context from the first task). The same problem exists for the project tag.

**Comment by mpcjanssen** [comment]
@nthorne I cannot reproduce this issue. Could you send me a screenshot demonstrating the issue?

**Comment by nthorne** [comment]
Here you go - as you can see, the cursor is after the Test 2 task, which does not have a context assigned, but still a context is indicated. This has worked in previous versions, but I am not sure as of when it stopped working.

![screenshot_2016-02-04-21-26-12](https://cloud.githubusercontent.com/assets/1839979/12828664/57e3c30e-cb86-11e5-964a-8e61f2c2411c.png)

**Comment by mpcjanssen** [comment]
@nthorne could you please retry with the latest version at http://mpcjanssen.nl/files/simpletask/latest and let me know if this is fixed? I can't reproduce the error.

**Comment by nthorne** [comment]
Seems to be working fine in 7.0.9
