### ISSUE TITLE
"recurrence" not working as expected in Lua scripts

### ISSUE THREAD

**Issue by djibux** [mpcjanssen/simpletask-android#371]
Hello,

I am trying to filter all recurring events.  I am using the global variable "recurrence", but it seems to have the value "nil" no matter what I try.

As I understand it, the following code should hide all non recurring tasks.
`return recurrence;`
It seems to hide every single task though.  For instance testing `test rec:+1w` with the code above returns "nil" but I would have expected it to return "+1w".

**Comment by mpcjanssen** [comment]
The documentation is lying. The recurrence field is never actually filled. I will update the documentation. :smile:

**Comment by djibux** [comment]
Awesome, thanks!
