### ISSUE TITLE
Choose calendar 

### ISSUE THREAD

**Issue by GrouchyGaijin** [mpcjanssen/simpletask-android#372]
This is a feature request.  
It would be great if the user could choose which calendar todo tasks should be written in. Currently the program seems to create a new calendar which is shown in the calendar program (S-Planner).  If I could choose a different calendar the todo tasks would show up on my laptop and desktop machines.

**Comment by mpcjanssen** [comment]
Using an existing calendar is never going to happen to prevent corruption or incorrect writes which would destroy an existing user calendar. Also modifying an existing calendar which already has Simpletask items is hard.

Creating a calendar that syncs with google will probably require extra permissions for the app which for me is not an option. But this is already being investigated in #212, so closing this issue.
