### ISSUE TITLE
Provide widget/shortcut for opening filtered lists

### ISSUE THREAD

**Issue by jflinchbaugh** [mpcjanssen/simpletask-android#373]
I use a couple list widgets filtered to a certain context (@grocery for example).  I can click the header  of the widget and dive right into the full view of the filtered list. The add button from the widget is really convenient too.  Those work great.  

I'd like to have widgets or shortcuts that work just like the header and the '+' of the widget without having to see the list contents in the widget.  Shrinking the existing widget can almost do what I want, but it's too cluttery in its layout.  

The existing "add task" shortcut falls short as well, since it doesn't prepopulate a context, like the widget can.

If I had such widgets/shortcuts, I'd have a handful of them on my home screen as convenient ways to quickly add and view tasks in certain lists.

Thanks!

**Comment by mpcjanssen** [comment]
You can already add a shortcut to a saved filter.

- Save the filter in the right drawer. ( press plus )
- Long press the saved filter item
- Select to homescreen to make a shortcut

You can then easily open multiple lists. To add ab item you still need to add plus. But thats already halfway there.

**Comment by jflinchbaugh** [comment]
Yay! Thanks.  That's all I wanted. ;)
