### ISSUE TITLE
Support for file urls

### ISSUE THREAD

**Issue by tomtom** [mpcjanssen/simpletask-android#376]
In issue #107, you mention that SimpleTask supports URLs and will add them to the popup menu. Obviously this doesn't work for file:// urls. It would be excellent, if SimpleTask were able to open referenced files (e.g. notes in markdown format) with a appropriate app.

**Comment by mpcjanssen** [comment]
Already added in https://github.com/mpcjanssen/simpletask-android/commit/affb0cc602c114136cee30514326772187cf0157 will be part of the next release.
