### ISSUE TITLE
Add secondary text to "Use calendar for date entry" setting

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#383]
I can't figure out for the life of me what it does.

**Comment by mpcjanssen** [comment]
Funny, at the moment it doesn't do anything :smile: it's supposed to show a calendar when picking dates. If unset it should use the spinner calendar view. 
This is a bug actually. But some secondary text will help.

**Comment by smichel17** [comment]
You mean, to implement #176?

Until this bug gets fixed, could you just add secondary text noting that "this setting currently has no effect"?

**Comment by mpcjanssen** [comment]
No this is supposed to allow you to choose between a date picker and a calendar as shown in http://i.stack.imgur.com/H4gJ0.jpg

**Comment by smichel17** [comment]
I'm a bit confused. At one point I remember seeing a date picker like the one on the left in your image. Now these are the options I have. Granted I am running on an S4, and I know Samsung makes some modifications, perhaps to the system date picker (?).

![date picker](https://cloud.githubusercontent.com/assets/6563664/13707252/c5fc2956-e776-11e5-9fae-4ab00b0a4f31.png)

**Comment by mpcjanssen** [comment]
The standard date picker has three forms. The left one (spinner) the right ibe (calendar) or both. The setting is supposed to let you swithc from spinner to calendar.

**Comment by smichel17** [comment]
Got'cha. Thanks for the clarification.

**Comment by smichel17** [comment]
I think this will be clear to people who are still using non material devices, so I'm going to call this fixed by #528
