### ISSUE TITLE
Floating Action Button for Save Task

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#385]
When you're adding or editing tasks, the primary action is saving them. It's therefore appropriate to use a floating action button. The current check mark up top is also awkward to reach. I made a mockup where save functionality is moved to a FAB (forgive a few editing errors). Shifted 'word wrap' left to make room.

![simpletask_fab](https://cloud.githubusercontent.com/assets/6563664/13694352/7d0d8e82-e722-11e5-9a9c-92ff3910d8ff.png)

**Comment by mpcjanssen** [comment]
Looks nice.
