### ISSUE TITLE
"Back Button" setting

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#389]
The problem: neither having this setting checked or unchecked is exactly what I want.

- If the setting is checked, then the only ways to discard a new task-in-creation are:
  - Exit the app, then re-open
  - Erase the entire contents of the task, then hit back
- If the setting is unchecked, I might accidentally hit the system back button (I use a galaxy S4)

The solution: replace the upper left corner back button with an 'X' button that always discards tasks. Make the setting only apply to the system back button.

This raises the question of whether a setting that will only apply to the system back button is worth supporting. IMO, it is not. Check out [Minimal](https://f-droid.org/repository/browse/?fdfilter=minimal&fdid=com.rubenroy.minimaltodo), a simplistic todo-list app with the paradigm, "upper left X discards new task, system back button saves new task." In my experience this is so intuitive that I don't miss the Simpletask setting.

---
If you decide not to implement this issue, instead consider this a request for visual improvement: when the setting is such that 'back' will discard note contents, replace the <- with an X.

**Comment by mpcjanssen** [comment]
The first scenario should work properly in the new version with FAB where you can press the X. The scenario back saves would make the FAB unnecessary so I might implement that. I will play with it a bit first.

**Comment by smichel17** [comment]
At the time I made this issue, there was no 'x' in the upper right corner. So, the original issue is solved in some sense. However, I stand by my original suggestion. At the time I didn't know this, but there is actually a [part](https://www.google.com/design/spec/components/dialogs.html#dialogs-full-screen-dialogs) of the Material guidelines that supports it.

>The “X” used in a full-screen dialog differs from an up arrow, which indicates the view’s state is constantly being saved. For example, an up arrow used in Settings indicates all changes are committed immediately without explicit confirmation or cancel actions.

This means:
- If the button in the upper left saves the task, it should be the back arrow. In this case, its functionality is exactly the same as the FAB.
- If the button in the upper left discards the task, it should be an "X". In this case, its functionality is exactly the same as the "X" in the upper right.

I see two solutions here:
- Remove the FAB and make the back arrow always save.
  - I think it is weird that the only way to move forward and save the task, is to hit the back button that's all the way in the upper left corner. The entire point of the FAB is that it's convenient. Why would we throw that away?
- Remove the upper-right "X" and make the upper-left button into an "X" that discards. (ie, my original suggestion).

As yourself here, "What is this setting trying to solve?" I think the answer is: remember back when this was implemented -- there was an X and a check in the upper right for saving/discarding tasks. The top is not an especially convenient place to tap, so users wanted a faster way to hit whichever button they used most. Since both X and check were at the top, it was also unclear what the functionality of the back button should be (ie, if it's always a check, why does the check exist otherwise?).

This isn't an issue any more. The FAB gives a quick and convenient way to save a task, so you don't need a shortcut for that. If you take my suggestion, there's no ambiguity as to what the button in the upper-left does: it's an X that always discards.

However, there *is* still a use case for having the setting: By default, the system/hardware back button is expected to save your task. However, if you frequently discard tasks without saving, it would be convenient if you could do so without reaching all the way to the upper left corner of your screen. Therefore, this setting exists to override the default, so that the system back button has the same functionality as the X in the upper left, instead of the same functionality as the more-easily-accessible FAB.

**Comment by mpcjanssen** [comment]
I am playing with it an the setting will go. 

- Left top X
- Right Send icon
- Back saves.

**Comment by smichel17** [comment]
Actually, that is my own personal preferred solution, and it's what I would have proposed if you were designing the app from scratch; but when I'm doing design work I also try to consider other people's preferences: in this case, avoiding causing regressions in some people's workflow.

**Comment by smichel17** [comment]
That said, if you remove the preference and people complain, you can always add it back in :)

**Comment by mpcjanssen** [comment]
@smichel17 if the material guidelines specify the behavior I don't mind breaking that part of the workflow. Consistency is a good thing and I don't want to fight the platform (it hurts).

**Comment by smichel17** [comment]
FWIW, for saving tasks, I still prefer the easy access of a FAB instead of an action in the header.

**Comment by mpcjanssen** [comment]
But back will also save the task now, so you wont need the FAB anymore, right?

**Comment by smichel17** [comment]
I prefer to use the button on screen to hitting back several times. Also, if a first time user looks at their screen, there's no indication that the back button saves; that's a discovered behavior. There _is_ an indication that the top button is the way to save. That's a much less convenient button, for the main action a user will take on this page, than a FAB.

Is there a reason why you want to get rid of the FAB? Perhaps there's a different way of solving that issue other than removing the FAB.

**Comment by mpcjanssen** [comment]
I just find it a bit cleaner without the fab. But i will put it back.
