### ISSUE TITLE
Rearrange Tasks by Dragging

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#39]
it would be very helpful to be able to quickly rearrange tasks by dragging.
i mostly use simpletask for really simple tasks which often change in relative priority which i am used to relate to top-down order.
thank you :)
__Reporter:__ Anonymous
__Assigned to:__ Mark Janssen
__Begin:__ 2014-01-10
__Completed:__ 0

**Comment by simonvanderveldt** [comment]
What steps could be taken to implement this?
I currently have a nice minimalist workflow pretty much as described by @chipbite where I simply prioritize like an agile backlog, i.e. the first task is the most important one, the last task is the least important one.
Adding a treshold date doesn't seem to address this. Or am I missing something?

For sorting I use one Complete and then File Order (unsorted).

**Comment by mpcjanssen** [comment]
Rearranging tasks by dragging is never going to happen, the amount of effort to build something like this with the limited out of the box support from Android makes me shudder.

**Comment by smichel17** [comment]
That's when you put on a 'Patches Welcome' tag :wink:
