### ISSUE TITLE
Allow setting defaults for all created tasks

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#391]
Allow defaults for all created tasks

**Comment by colinsullivan** [comment]
+1!

I use "+Inbox" for all incoming items.

**Comment by mpcjanssen** [comment]
@colinsullivan you do know that you can set a text to be added to any task coming in through sharing or in the background, right?

**Comment by colinsullivan** [comment]
Does that include the plus button on the widget?

----------
Colin

**Comment by smichel17** [comment]
A quick test says it does not.

**Comment by smichel17** [comment]
@colinsullivan However, if you use the plus on the widget, it will pre-fill with whatever that widget's filtering is.

So you can get the behavior you want by creating a widget that shows only things tagged with "+Inbox", and the plus button on that widget will open an entry box pre-filled with "+Inbox".

**Comment by colinsullivan** [comment]
That's not the behavior I want :P

I'd rather keep my widget with its current filtering (this happens to be
all items, sorted by due date).

Thank you for your suggestion though, I genuinely appreciate it :)

----------
Colin

**Comment by smichel17** [comment]
You can create a second widget with the 'inbox' filter, resize it to 1x1, and the + button will take up ~1/4 of the space. It's ugly as heck, but it'll approximate a "add new task to inbox" behavior that you want, I think.

**Comment by mpcjanssen** [comment]
@colinsullivan question, why do you want to tag inbox tasks? I have a filter for tasks without tags and lists which is my inbox. This works fine.

**Comment by colinsullivan** [comment]
I've thought about that, could work and would save me a few touch strokes
in my current workflow. Would just need to write a filter for todo.sh.

I'm using BitTorrent sync to synchronize with desktop! :-)

--------
Colin

**Comment by smichel17** [comment]
I have a suggestion that I think would (A) solve @colinsullivan's issue, and (B) be useful independent of this thread's original suggestion:

- Unique "Add Task" widgets:
  - Icon stays the same
  - [ ] On creation, opens a modified widget creation dialogue
    - Only includes `LIST`, `TAG`, and `PRIO` tabs.
  - [ ] When tapped, opens AddTask activity with lists, tags, and prio pre-filled.
    - Like the + in the upper right of list widgets

**Comment by mpcjanssen** [comment]
I like this. Please put in a different issue and refer to this one.

**Comment by smichel17** [comment]
@colinsullivan can we close this issue, especially since #417 exists?

**Comment by colinsullivan** [comment]
:thumbsup:

----------
Colin

**Comment by mpcjanssen** [comment]
There is still a part remaining here to have certain defaults for new tasks which come in through sharing or background actions. I for instance want a default threshold date on all tasks.

Main challenge is to distinguish updated tasks in the addtask screen from newly created ones. So I wont close this just yet.

**Comment by mpcjanssen** [comment]
This will not be added in the UI. Adding defaults can already be achieved with the `onAdd` Lua callback.
