### ISSUE TITLE
Calendar reminders

### ISSUE THREAD

**Issue by ddisanti** [mpcjanssen/simpletask-android#392]
It would be possible a more flexible global settings of calendar reminders? I know. Calendar reminders is still a experimental feature. But it would be cool to aggregate multiple notifications and more days of anticipation and not just 7.

**Comment by vojtechkral** [comment]
Could you elaborate what you mean by the aggregation? I'm not sure I follow...

**Comment by smichel17** [comment]
Right now, if you enable the experimental calendar reminders feature (as opposed to creating calendar reminders manually), it creates one reminder per task due that day, all at the same time. I am guessing that @ddisanti was wondering about creating a single calendar reminder regardless of how many tasks are due that day.

While we're talking about this feature, I'll just put it out there that I'd prefer either an all-day event for daily to-do's or the ability to set reminder times task-by-task, than having all tasks give a reminder at a specific time of day.

**Comment by ddisanti** [comment]
@vojtechkral I meant "set" (instead of aggregate). I would like to set multiple reminders. But it will be a global calendar setting and not task-by-task.

This is an example of what I meant:

3 weeks before due date at 8:00am
1 weeks before due date at 8:00am
1day before due date at 8:00am
at due date at 8:00am.

Now, it will be for all task with calendar reminder set.

**Comment by mpcjanssen** [comment]
@ddisanti considering that you can already make widgets with task due less than x weeks/x days etc using Lua filters, I will probably not add functionality like this even if someone creates a pull request. It requires quite some changes in the user interface to be able to make all this configurable.
