### ISSUE TITLE
Share an image (it's file path) to Simpletask

### ISSUE THREAD

**Issue by gastus1** [mpcjanssen/simpletask-android#393]
As lot of "Stuff" comes in as a paper (letters, invoices), it would be great to photograph it with the phone, and share it to ST as a task. 
Then, from the task we would be able to click that file path link and open the image.

**Comment by gastus1** [comment]
Or even better: 
From task creation screen initiate the camera, make the picture, and the link would automatically be created in the task text. 
(Dreams dreams 😑😁😁)

**Comment by mpcjanssen** [comment]
Direct camera access requires permissions I am not willing to request. Sharing a link to an existing image should be fairly easy.

**Comment by mpcjanssen** [comment]
Next release will allow inclusion of any type of file (as far as I have tested) which is shareable. So you can also refer to recorded voice snippets for example.
