### ISSUE TITLE
New tri-state buttons confused me

### ISSUE THREAD

**Issue by getthemike** [mpcjanssen/simpletask-android#395]
They are useful and awesome but when I opened a single task it didn't make sense. Maybe when a single task is selected the original ui could show?

Or maybe it should be better explained somewhere. 

I actually had to go look up 149 to find out what it was.

Not really sure how to make it more obvious what it's doing but it should be more obvious.

**Comment by mpcjanssen** [comment]
@getthemike  I agree, I don't like the UI at all, but I don't know a better option. I also think that having a different UI for one or more tasks is a bad idea. Maybe just adding an explanation is enough.

**Comment by mpcjanssen** [comment]
Next version will have proper tri-state checkboxes.

**Comment by getthemike** [comment]
I like this a lot better. I think it will make more sense to people.
Good work!
