### ISSUE TITLE
New task via Intent not work (via tasker)

### ISSUE THREAD

**Issue by mimmori** [mpcjanssen/simpletask-android#399]
I have some issue with intent using tasker app. In details I can not add a new task via intent. I use the guide https://github.com/mpcjanssen/simpletask-android/blob/master/src/main/assets/intents.en.md

Action: nl.mpcjanssen.simpletask.BACKGROUND_TASK
Cat: Default
Mime Type: text/*
Extra: task: <Task text with possible variables here> +tasker
Target: Activity

The result is that nothing is happen.
Who can help me? Where I am wrong?

**Comment by mpcjanssen** [comment]
@mimmori works for me. Do you see a toast (task added to simpletask) if you test the tasker Action?

**Comment by mimmori** [comment]
no, i don't see any tost

**Comment by mpcjanssen** [comment]
Strange. Do you see anything in the log? Settings->View Log?

**Comment by mimmori** [comment]
Nothing... 

At this point i think is related to tasker action. is there a way to intercept intent for analyze it?

**Comment by mpcjanssen** [comment]
Not easily. You can share the action data from the Tasks screen. 3-Dot menu->Data->Share

**Comment by mpcjanssen** [comment]
For me thos gives:

```
<TaskerData sr="" dvi="1" tv="4.8u1m">
<Project sr="proj0" ve="2">
<cdate>1458892464172</cdate>
<mdate>1458893305480</mdate>
<name>Base</name>
<tids>2</tids>
<Img sr="icon" ve="2">
<nme>hl_aaa_ext_home</nme>
</Img>
</Project>
<Task sr="task2">
<cdate>1458892506328</cdate>
<edate>1458894061535</edate>
<id>2</id>
<nme>Task</nme>
<pri>100</pri>
<Action sr="act0" ve="7">
<code>877</code>
<Str sr="arg0" ve="3">nl.mpcjanssen.simpletask.BACKGROUND_TASK</Str>
<Int sr="arg1" val="1"/>
<Str sr="arg2" ve="3">text/*</Str>
<Str sr="arg3" ve="3"/>
<Str sr="arg4" ve="3">task: +tasker</Str>
<Str sr="arg5" ve="3"/>
<Str sr="arg6" ve="3"/>
<Str sr="arg7" ve="3"/>
<Str sr="arg8" ve="3"/>
<Int sr="arg9" val="1"/>
</Action>
</Task>
</TaskerData>
```

**Comment by mimmori** [comment]
here the data

<TaskerData sr="" dvi="1" tv="4.8m">
<Task sr="task22">
<cdate>1458862451820</cdate>
<edate>1458894359646</edate>
<id>22</id>
<nme>simpletask</nme>
<pri>100</pri>
<Action sr="act0" ve="7">
<code>877</code>
<Str sr="arg0" ve="3">nl.mpcjanssen.simpletask.BACKGROUND_TASK</Str>
<Int sr="arg1" val="1"/>
<Str sr="arg2" ve="3">text/*</Str>
<Str sr="arg3" ve="3">task</Str>
<Str sr="arg4" ve="3">task from tasker</Str>
<Str sr="arg5" ve="3"/>
<Str sr="arg6" ve="3"/>
<Str sr="arg7" ve="3"/>
<Str sr="arg8" ve="3"/>
<Int sr="arg9" val="1"/>
</Action>
</Task>
</TaskerData>
Il 25/mar/2016 09:23, "Mark Janssen" <notifications@github.com> ha scritto:

For me thos gives:

<TaskerData sr="" dvi="1" tv="4.8u1m">
<Project sr="proj0" ve="2">
<cdate>1458892464172</cdate>
<mdate>1458893305480</mdate>
<name>Base</name>
<tids>2</tids>
<Img sr="icon" ve="2">
<nme>hl_aaa_ext_home</nme>
</Img>
</Project>
<Task sr="task2">
<cdate>1458892506328</cdate>
<edate>1458894061535</edate>
<id>2</id>
<nme>Task</nme>
<pri>100</pri>
<Action sr="act0" ve="7">
<code>877</code>
<Str sr="arg0" ve="3">nl.mpcjanssen.simpletask.BACKGROUND_TASK</Str>
<Int sr="arg1" val="1"/>
<Str sr="arg2" ve="3">text/*</Str>
<Str sr="arg3" ve="3"/>
<Str sr="arg4" ve="3">task: +tasker</Str>
<Str sr="arg5" ve="3"/>
<Str sr="arg6" ve="3"/>
<Str sr="arg7" ve="3"/>
<Str sr="arg8" ve="3"/>
<Int sr="arg9" val="1"/>
</Action>
</Task>
</TaskerData>

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/mpcjanssen/simpletask-android/issues/399#issuecomment-201196525>

**Comment by mpcjanssen** [comment]
This is wrong:

```
<Str sr="arg3" ve="3">task</Str>
<Str sr="arg4" ve="3">task from tasker</Str>
```

The data field should be empty and the extra requires `task:` at the beginning. So instead of 

`task from tasker` you'll need `task: task from tasker`

**Comment by mimmori** [comment]
yes, it works now! thanks

the data field remained following a try, but the descriptor "task:" i had
noticed in your guide. sorry

thanks again
Il 25/mar/2016 09:32, "Mark Janssen" <notifications@github.com> ha scritto:

**Comment by mpcjanssen** [comment]
No problem, glad it's resolved.

**Comment by smichel17** [comment]
@mimmori for future reference, [this](https://f-droid.org/repository/browse/?fdfilter=intercept&fdid=uk.co.ashtonbrsc.android.intentintercept) is a great tool.

**Comment by mimmori** [comment]
ok, thanks!
Are there only two intents availlable to other app? 

it would be helpful if i can read task data also...

**Comment by mpcjanssen** [comment]
@smichel17 indeed a very useful tool. @mimmori note that this tool doesn't work with the tasker setup which sends the intent directly to the activity

**Comment by mpcjanssen** [comment]
@mimmori the proper way to allow reading of tasks is to implement a content provider. How would you like to use the contents of a task.

**Comment by mimmori** [comment]
I want to create a report based on context of the task. The final purpose
is to ask report via mail...
Il 25/mar/2016 15:19, "Mark Janssen" <notifications@github.com> ha scritto:
