### ISSUE TITLE
Settings Hierarchy

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#401]
Here's a new hierarchy to make settings more find-able, and a couple wording changes to reflect putting the widget settings together in a sub-menu.

**N.B.** The order of settings within a category is intentional, and essentially follows the material guidelines "settings should be in order of importance" mandate. Let me know if you disagree with any of the ordering.

---

Appearance:
- ~~Application Theme~~ Theme
- ~~Change font size~~ Font size
- Color due dates
- Show hints
- Use todo.txt terms

Interface:
_Control what information is displayed._
- Task text ellipsizing
- Show todo path
- Show txt files only
- ~~Datebar in main view~~ Show datebar

Functionality:
_Enable or disable functionality_
- Show completion checkbox
- Show confirmation dialogs
- Edit shared task
- Use calendar for date entry
- Fast scrolling
- Open landscape drawers

Configuration:
_Configure app behavior._
- Task creation: _<--- this is a header_
- Date new tasks  
- Capitalize new tasks
- Append new tasks
- Misc:  _<--- this is a header_
- Auto archive
- Back button
- Prio in completed tasks
- Background tag
- File link root
- Windows line breaks

Widget:
- ~~Widget theme~~ Theme
- ~~Widget header transparency~~ Header transparency
- ~~Widget background transparency~~ Background transparency
- ~~Datebar in widget~~ Show datebar

Experimental:
- Calendar reminders
- Back clears filter
- View log

Other:
- Sort case-sensitive
- Create is threshold
- Todo history
- Archive now
- Simpletask cloudless v7.0.14 (3024)

Donate

**Comment by mpcjanssen** [comment]
Thanks for this. I will restructure if I have time.

**Comment by smichel17** [comment]
@mpcjanssen I haven't done any android development but I am a programmer; if you make a branch and do the work to separate out the appearance settings, I can use that and figure out how to change the rest.

**Comment by mpcjanssen** [comment]
@smichel17 I am not quite sure yet how to do this. But the main thing is using a `PreferenceScreen`

**Comment by mpcjanssen** [comment]
@smichel17 : see latest commit for an example you can expand upon.

**Comment by mpcjanssen** [comment]
this approach is wrong. I will change it so it's right.

**Comment by mpcjanssen** [comment]
@smichel17 proper way is elaborate, but I am getting there.

**Comment by mpcjanssen** [comment]
@smichel17 basic framework works. Files needed are:

- `preference_headers.xml`
- `preferenceFragment` in `Preferences.kt`

**Comment by mpcjanssen** [comment]
@smichel17 see f3a920c for the needed changes to add a section

**Comment by mpcjanssen** [comment]
@smichel17 don't bother spending time. I will finish this.

**Comment by mpcjanssen** [comment]
I will close this issue now as most/all? of the work is done. If there are details to be fixed, please log a new issue.
