### ISSUE TITLE
Remove name/version number "setting"

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#403]
[Material guidelines:](https://www.google.com/design/spec/patterns/settings.html#settings-usage)

>**Settings should not:**
>- Contain information about the app, such as a version number or licensing information. (These should move to a Help screen.)

Note: if you are opposed to putting this information in the help screen, you can put it in the secondary text of a different menu item (donate or view log)

**Comment by mpcjanssen** [comment]
Only issue with this is that it's a bit harder to move to the Help, but no reason to not do it.

**Comment by smichel17** [comment]
I'd rename "View log" to "View debug log", then put the simpletask version number as the secondary text of that item. Less work, and personally I like that location better anyway.

**Comment by mpcjanssen** [comment]
That makes sense. I would even think that it should be "View debug information" in that case.
