### ISSUE TITLE
Theme & font size secondary text should show current setting

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#404]
[Material Guidelines:](https://www.google.com/design/spec/patterns/settings.html#settings-labels-secondary-text)

>For non-switch settings, secondary text should show the current status of a setting only. 

This affects:

- Application theme
- Change font size
- Widget theme

**Comment by smichel17** [comment]
as with #401, if you make a commit with one of these -- so I can see all the files that need to be changed -- I can use that to do the other two.

**Comment by mpcjanssen** [comment]
Fixed
