### ISSUE TITLE
Tri-state checkboxes: allow return to original state

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#405]
Example. Here's my list:
```
a @b
c
```
Steps:
- Select a and c
- Open 'lists' menu
  - `b` checkbox is in 3rd (partial) state
- Tap `b` once
  - Checkbox becomes fully checked
- Tap `b` a second time
  - Checkbox becomes un-checked
- Tab `b` a 3rd time
  - **Current behavior:** checkbox becomes fully checked
  - **Desired behavior:** checkbox returns to 3rd, partially-checked state

**Comment by mpcjanssen** [comment]
The current tri-state box I am using doesn't support this use case so I will need to modify it. The older radioboxes did support this so the requested behavior is clear.
