### ISSUE TITLE
Clean up new/edit task interface

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#409]
@mpcjanssen If you're looking to clean up the interface (ie, address concerns in #389), take a look at [this section](https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions) of the material guidelines and see if any of those transitions is appealing to you.

Also, I'd encourage you to consider moving the "prefill next" and "word wrap" options into the overflow menu. That gives you ~~a whole extra line of space.~~ more than an extra line of space, because you can get rid of the divider, too.

**Comment by smichel17** [comment]
The overflow menu is really underused on this screen -- it has only a single option, "help." At that rate, you might as well just have a help button (note: I do not advocate replacing the overflow menu with a help button).

**Comment by mpcjanssen** [comment]
I will probably settle for readding the fab and moving the checkboxes to the overflow menu.

**Comment by smichel17** [comment]
Is it possible to do checkboxes in the overflow menu? If so, you should do that.

If not, menu items need to clearly indicate whether they are describing status or action, eg "Turn [on/off] prefill next" or "Prefill next is [activated/deactivated]."

**Comment by mpcjanssen** [comment]
Checkmarks in menus are only supported in popup menus not in action menus. (I tried). I will rephrase the menu items to reflect it's an action with disable/enable.

**Comment by smichel17** [comment]
Can you cheat, but just making it two different strings, one of which includes a unicode check?

ie, "Prefill next" vs "✓ Prefill next"

**Comment by mpcjanssen** [comment]
hmm that might be an option. No idea how nice it will look. I'll try

**Comment by mpcjanssen** [comment]
Faking it doesn't look very nice.

**Comment by mpcjanssen** [comment]
Strangely enough I got it to work now with checkboxes.

**Comment by smichel17** [comment]
You can also remove the blue and grey lines that used to separate the check box items & text box.

**Comment by mpcjanssen** [comment]
the blue line is the bottom line of the edittext. Will see if I can remove that

**Comment by mpcjanssen** [comment]
keeping the menu open doesn't seem to be possible

**Comment by smichel17** [comment]
That's fine.

>[Easy] A checkmark that is only visible when the setting is selected.

A check box is just a differently-styled check mark, right? :P
