### ISSUE TITLE
Improve support for multiple todo files

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#41]
Changing between todo files is currently rather cumbersome. Improve support for moving between predefined todo files.

One way to implement this would be to define "Workspaces" with appropriate files in settings and then switch between them via a radio button at the top of the left drawer, like with multiple accounts in the gmail client: http://myandroidchief.com/wp-content/uploads/2013/06/fc75gmail-android.jpg (top left)
**Reporter:** Alex A
**Assigned to:** Mark Janssen
**Begin:** 2014-01-10
**Completed:** 0

**Comment by t214c** [comment]
I second this.

In place of the ["Simpletask" Title](https://f-droid.org/repo/nl.mpcjanssen.simpletask/en-US/phoneScreenshots/main.png) (or the File path if option is enabled), there could be a drop down list of recently used txt files (or a custom chosen list). Like [here](https://jira.appcelerator.org/secure/attachment/39162/DropDownAlmost.png).
