### ISSUE TITLE
Open selection menu with system menu button

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#410]
On devices that have hardware menu buttons, pressing that button from the main screen will show the overflow menu.

When you select a task, that button has no effect. It would be nice if it opened the menu here as well.

Low priority.

**Comment by smichel17** [comment]
I'm going to pre-emptively close this so you don't waste time on it.

**Comment by mpcjanssen** [comment]
If you select a task the overflow menu should be gone and the selection menu is opened as toolbar so indeed closed
