### ISSUE TITLE
Update Drawer Interface (UX overhaul part 1)

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#411]
#### 2016-07-14 edit: Do not implement this right now. I am rethinking it.

---
Material design guidelines prohibit drawers on the right. That's because drawers are hidden functionality that the user is unlikely to discover for themselves (I used simpletask for a few weeks before I realized the drawer existed).

Filters are first class citizens in Simpletask. They are the core that makes this app so convenient to use. They should not be relegated to a nonstandard location. Also, while guidelines should be broken IFF there's a good reason, trying to fight the system results in a harder-to-maintain and buggier application.

I've been thinking through a redesign. It will:

- Follow material design
- preserve all existing functionality
- add a UI for managing multiple todo.txt files
- straighten out awkwardness re: updating filters
- require 4 fewer settings

I can present it as one big v8.0, or I can break it up into 2-6 smaller steps that each make sense to do on their own. Which way would you prefer?

**Comment by mpcjanssen** [comment]
Please keep this in one issue for now. The amount of issues is becoming a bit overwhelming :)

**Comment by smichel17** [comment]
## Update drawers

### a. Swap drawers

Move the filter drawer to the left and the list/tag drawer to the right.

### b. Update filter drawer

Normal view:

![filter-main](https://cloud.githubusercontent.com/assets/6563664/14405049/93f40afc-fe53-11e5-8044-c454ca5034ac.png)

Long press a filter to select it. Note that I drew these before adding "All Tasks".

![filter-select-one](https://cloud.githubusercontent.com/assets/6563664/14405299/b8aefa04-fe59-11e5-950c-a072f2c17d3b.jpg)

Select multiple filters:

![filter-select-many](https://cloud.githubusercontent.com/assets/6563664/14405304/c46dccb2-fe59-11e5-9ef9-ed2e94b96d64.jpg)

**Comment by mpcjanssen** [comment]
Very nice, note though that displaying tasks per filter is quite difficult :)

**Comment by smichel17** [comment]
## Update Filters

### a. Remove the filter drawer

### b. Move filter settings

Tasks tab:

![home-tasks](https://cloud.githubusercontent.com/assets/6563664/14406206/3d8dd0b4-fe6f-11e5-8211-f6dc92e20089.png)

Any other tab:

![home-prio](https://cloud.githubusercontent.com/assets/6563664/14406337/d6ac03f8-fe72-11e5-9114-0400d0815b7b.png)

### c. Clean up

We save updates to filters through the main view now, so we don't need it in the filter view. That means the filter selection overflow menu has only one item left in it (rename), and we can just use an icon for that.

![filter-select-one-final](https://cloud.githubusercontent.com/assets/6563664/14406398/495203ac-fe74-11e5-838a-33d7437eb201.png)

**Comment by smichel17** [comment]
>Very nice, note though that displaying tasks per filter is quite difficult :)

I don't quite understand what you mean. I don't think I've made any changes to how tasks in the list are actually displayed? The task tab should feel identical to the current main view.

**Comment by smichel17** [comment]
@mpcjanssen two notes:

1. These steps, in order, are all complete changes on their own. That is, as long as you complete all the things in a letter section and all the previous sections, the app should be usable in that form.
2. I made a few edits.
  - Nothing major, but github doesn't give notifications when updates are made so I think it's a good practice to tell people :)

**Comment by getthemike** [comment]
@smichel17 have you seen the android UI for Any.do . I checked it out the other day and I think in this redesign you should definitely process it some. 

http://www.any.do/

**Comment by smichel17** [comment]
@getthemike I saw the other issue. Will respond there.

**Comment by smichel17** [comment]
@mpcjanssen I don't think you have started this, but I want to think about it some more. I'm going to close and re-open in a bit.

**Comment by smichel17** [comment]
Not that I think this version does anything worse than the current. But if a big UI overhaul is going to happen, it's best to make all big UI changes at the same time..

**Comment by mpcjanssen** [comment]
Reopened for the mockups

**Comment by smichel17** [comment]
Having a bunch of different UI update issues made sense when they were more separate. Now it makes sense to close excess issues, so I'm closing this.
