### ISSUE TITLE
Managing github issues

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#413]
>The amount of issues is becoming a bit overwhelming :)

@mpcjanssen Hang in there, I'm trying to help clean up! Here's what I'm doing, and some suggestions:

- Anything that is actionable, I will put a checkbox and immediately after list the desired state only. This should allow you to either read an issue for full context, or skim an issue for the relevant to-do's. It will also allow you to actually check off those items as you get to them, tracking progress on the issue.

- I went back, reviewed all the issues, and referenced related issues together. Hopefully this will make it easier to tackle related issues together and prevent issues that are actually closed from slipping through the cracks and clogging up the issues view.

- I'd suggest making more use of `someday/maybe` tags, and filtering issues with `-label:someday/maybe`.

- Also, it might be helpful to use the `planned` tag more. (And I'd like to know where your priorities are so I can focus on the same things).

- [ ] If you're willing, if you add me as a collaborator on this repo, I can help with some of the above, like editing the first post in each issue to include checkboxed actionables.
  - I won't touch the code / will use merge requests like everyone else.

**Comment by mpcjanssen** [comment]
I really dont want to over organize all this. I will tag issues I really plan with planned, i will tag issues I probably wont ever do but dont want to close with someday maybe. Everythong else i will pick something I feel like doing.
Please keep the comments coming but unless I plan to actual code against it or discuss for clarification I might not react.

**Comment by smichel17** [comment]
Okay, sounds good.
