### ISSUE TITLE
Settings part 2 of 3: Phrasing

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#421]
**The vast majority of these are just changing strings; I can make a PR for that.**

---

- Appearance > Color due dates
  - [x] Secondary text reads, "Color due and threshold dates"
- Appearance > Show hints
  - [x] Secondary text reads, "Show hints when adding tasks. Disable this if you find these distracting."

---
- User Interface > Show todo path
  - [x] Label reads, "Show file path"
  - [x] Secondary text reads, "Show the path to the todo file. Directories are shortened to the first letter."
- User Interface > Datebar in main view
  - [x] Label reads, "Show datebar"
  - [x] Secondary text reads, "Display dates on a separate line."

---
- Features > Show completion checkbox
  - [x] Label reads "Show completion checkboxes"
  - [x] Secondary text removed
- Features > Show confirmation dialogues
  - [x] Secondary text reads "Prompt before actions that are irreversible or can lead to data loss."
- Features > Edit shared task
  - [x] Label reads, "Edit shared tasks."
  - [x] Secondary text reads, "Edit tasks shared to Simpletask before saving them."

---

- Configuration > Date new tasks
  - [x] Secondary text reads, "Automatically add creation date."
- Configuration > Background tag
  - [x] Label reads: Background tag
  - [x] Secondary text reads, "[Current value]"
  - This change doesn't make sense on its own. There will be an added setting for clarity.
    - [x] Create "Configuration > Text to append"
      - Secondary text reads "[current value]"
- Configuration > Append new tasks
  - [x] Label reads, "Append to list"
  - [x] Secondary text reads, "Insert new tasks at the start of the file. Otherwise, new tasks are inserted at the end."
- Configuration > Auto Archive
  - [x] Secondary text reads, "Archive tasks immediately on completion."
    - "Archive" is a larger function in the app, so the user should already understand it. If they don't, a setting is not the correct place to explain it.
- Configuration > File link root
  - [x] Label reads, "root:// directory"
  - [x] Secondary text displays current path only.
- Configuration > Windows line breaks
  - [x] Label reads, "Windows compatibility"
  - [x] Secondary text reads, "Use Windows-friendly line breaks."

---
- Widget > Datebar in widget
  - [x] Label reads, "Show datebar"
  - [x] Secondary text reads, "Display dates on a separate line."
- Widget > Widget header transparency
  - [x] Label reads, "Header transparency"
- Widget > Widget background transparency
  - [x] Label reads, "Background transparency"

---
- Calendar reminders > Reminders time
  - [ ] Secondary text reads, "[current setting]"

---
- Other > Sort case-sensitive
  - [x] Secondary text removed.

**Comment by mpcjanssen** [comment]
Please make a PR

**Comment by smichel17** [comment]
@mpcjanssen to remove secondary text, would you prefer I make the english version an empty string (or space), or that I delete the android:summary for the relevant pref and also the related strings for all other languages?

**Comment by smichel17** [comment]
I decided just to remove the `android:summary` field and leave the string, unused.

**Comment by smichel17** [comment]
I did everything except:

>- Calendar reminders > Reminders time
>  - Secondary text reads, "[current setting]"

I believe it requires overriding the onCreate function of CalendarPrefFragment, on line 132 or Preferences.kt and calling valueInSummary, but just copying over from ConfigurationPrefFragment creates crashes and I'm not sure exactly what's needed to make it work.

@vojtechkral might be able to help with this, too.

**Comment by mpcjanssen** [comment]
Yes you'll need to get access to the proper preference view. I will look at this
