### ISSUE TITLE
Push sync using longpoll can kill battery

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#424]
In situations where the network coverage is spotty. The longpoll dropbox sync can have quite some impact on battery usage.

**Comment by mpcjanssen** [comment]
Latest master will only longpoll when app is in the foreground. It will also check for any changes when coming to the foreground.

**Comment by smichel17** [comment]
I use cloudless so this doesn't affect me personally, but does that mean if I make changes from another device but don't open Simpletask, my widgets won't update?

**Comment by mpcjanssen** [comment]
Only polling when the app is active works well.
