### ISSUE TITLE
Wrong list/ tag getting applied

### ISSUE THREAD

**Issue by y2kbugger** [mpcjanssen/simpletask-android#426]
When editing a task from the main list, I noticed that the tag being applied was not the one I tapped. I repeated the multiple times, first checking the one that was mistaken added and closing the correct one. Closing the list of tags the wrong tag was applied again. I can't remember is it was always the same wrong one but it was the same at least a few of the times. also when checking a tag and scrolling away then scrolling back, it became unchecked. I think I replicated this bug with lists at least once also. For sure the "unchecked when scrolled away" visually glitch happens on both.

**Comment by mpcjanssen** [comment]
@y2kbugger how many tags do you have? Is it a large list?

**Comment by y2kbugger** [comment]
around 36 lists and 24 tags

**Comment by mpcjanssen** [comment]
I will check

**Comment by mpcjanssen** [comment]
@y2kbugger  Was this an issue in older versions? Before the indeterminate checkbox?

**Comment by y2kbugger** [comment]
only noticed it now, but to be honest I wasn't doing much other than adding
and marking complete for the last few months.

**Comment by y2kbugger** [comment]
I'm running 6.01

**Comment by y2kbugger** [comment]
Also I just got the update that the notes included tristate so I checked and I was running 7.1.1. I'm updating to 7.2.1 now

**Comment by mpcjanssen** [comment]
This should have been fixed in 7.2.2 please reopen if it doesn't work with the latest version.
