### ISSUE TITLE
Changes to a edited task are not saved on last app update.

### ISSUE THREAD

**Issue by ddisanti** [mpcjanssen/simpletask-android#427]
I've just installed the last update. And now, when I edit a task, it isn't get updated with the new data. Maybe I'm missing something. By the way, on the edit box, I find the Add Floating button a little bit confusing. You're editing a task, maybe adding new ones, so the old Send or Done Floating buttons would be a best choice.

**Comment by mpcjanssen** [comment]
FAB will have done icon in next release. Updating was only an issue on Cloudless and is fixed.
