### ISSUE TITLE
Keep tasks selected after changing them

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#43]
Currently tasks get deselected after for instance changing their lists. This makes it difficult to perform multiple actions on a group of tasks.
Fixing this requires the selection to be based on task line (id) rather than task text as it is now.
__Reporter:__ Mark Janssen
__Assigned to:__ Mark Janssen
__Begin:__ 2014-01-14
__Completed:__ 0

**Comment by smichel17** [comment]
Why is this closed?

**Comment by mpcjanssen** [comment]
Was an old issue. Was impossible to realise without backing DB now it might be possible but it can have unexpected effects with filtering .

**Comment by smichel17** [comment]
I am beginning to think through a new selection/editing interface and will take this into consideration. For now...

Rule: selected items should always appear in the active filter, regardless of whether they normally would.

If I select multiple items and change some attribute that would cause some or all of them not to be displayed, they should remain selected and displayed until I unselect them, at which point they disappear.

**Comment by mpcjanssen** [comment]
I like that idea and it's easy to implement.
