### ISSUE TITLE
Tri-state filtering

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#434]
It would be silly for me to have an `@next-action` list; 70% of my tasks would be on the list. So instead, in my filter that shows next-actions, I invert the context and exclude `@shopping` and `@wishlist` etc. When I'm looking at my next-actions, I prefer to sort them by tag than by list. I also want to be able to filter by ~~context~~ list, so I can see all the next actions I can do `@laptop`, for example.

Here's the problem: Since I'm already filtering out things that *aren't* next-actions, the filter is inverted: if I want to filter by list, I need to 'check' every list that is not the one I want to see. Turning off 'invert' doesn't help, because then the main filter view would have all of my next-action lists checked, and I'd have to un-check all but one.

I think the solution here is to do away with the concept of "inverted filter" and replace it with the concept that when you're filtering, lists/tags can be included/excluded/unchecked.

- Included: Always shown, check mark in check box
- Excluded: Never shown, x in check box
- Unchecked: Same as unchecked on live

**Comment by smichel17** [comment]
An alternative way to think about / display these states is:

- Unchecked: Like live
- Checked: Like live
- Double-checked: acts to Checked the way Checked does to Unchecked: as long as anything is double-checked, only double-checked things will be shown.

**Comment by smichel17** [comment]
Finally, I will also note that these are both somewhat temporary solutions, and thinking about a long-term solution is why I closed #411.

**Comment by vojtechkral** [comment]
To me, this sounds waaay to complex and hard to understand for users...

**Comment by smichel17** [comment]
I think that with the proper visuals it would not be difficult to understand. That said I do not think either of my proposed solutions are the proper visuals.

That's why I noted that these would both be temporary solutions, not something that's acceptable long-term. Maybe that means we should just call them bad solutions and not do anything about this until we figure out what would be an acceptable solution.

**Comment by mpcjanssen** [comment]
If you use Lua filtering this is fairly straightforward to achieve. So unless the visuals will be really intuitive, I think using Lua will be the saner option.

**Comment by smichel17** [comment]
Yeah, that's what I'm doing right now, it just seems like a really awkward script:
```
if lists==nil then
  return true;  
end
for i = 1,#lists do  
  x=lists[i]  
  if x=="hats" or x=="[redacted]" or x=="projects" or x=="media" or x=="shopping" or x=="wishlist" or x=="waiting" or x=="meals" then  
    return false;  
  end  
end
return true;
```

**Comment by mpcjanssen** [comment]
Yes in this sense Lua is crappy. I would love to have a more expressive language instead of Lua. It would be nice to say `if x in {"[redacted]", .....`

**Comment by mpcjanssen** [comment]
See  #437

**Comment by mpcjanssen** [comment]
In Tcl 

```
if x=="hats" or x=="[redacted]" or x=="projects" or x=="media" or x=="shopping" or x=="wishlist" or x=="waiting" or x=="meals"
```

translates to

```
if {[lsearch {hat projects ...} $x] > -1}
```

So that's much less verbose. I have a working interpreter now. Just need to think about migration.

**Comment by smichel17** [comment]
How's Tcl performance-wise compared to Lua?

You had talked about a kotlin interpreter; is that still on the table and if so, does it make more sense just to wait for that?

**Comment by vojtechkral** [comment]
In Python,

`if x=="hats" or x=="[redacted]" or x=="projects" or x=="media" or x=="shopping" or x=="wishlist" or x=="waiting" or x=="meals"`

becomes:

`if x in ["hats", "[redacted]", "projects", "media", "shopping", "wishlist", "waiting", "meals"]`

which is imho very nice...

> You had talked about a kotlin interpreter; is that still on the table and if so, does it make more sense just to wait for that?

I just found out there's this: https://github.com/andrewoma/kotlin-script

In Kotlin, it could be:

```
when (x) {
	"hats", "[redacted]", "projects", "media", "shopping", "wishlist", "waiting", "meals" -> /* do stuff */
	else ->
}
```

Which is nice, too, but I'm not sure this is right, I'm very new to Kotlin...

**Comment by vojtechkral** [comment]
Actually, scratch that kotlin-script link, it seems they just use scripts to compile .kt files. Never mind :-(

**Comment by mpcjanssen** [comment]
Yes kotlin doesn't have a very good embedding mode at the moment. JTcl is working out quite nicely though see #437 for some examples.

**Comment by smichel17** [comment]
Seems like the new lua engine + new UI will suit my needs.
