### ISSUE TITLE
Investigate better scripting language

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#437]
Doing more complex filters in Lua can become quite verbose quickly. Investigate better options.

**Comment by vojtechkral** [comment]
I'd vote for python, with its fairly clean syntax and its `in` operator. And also because it's quite easy to host/embed (although I've embedded it in a Java app).

I also heard Kotlin can be compiled to JS, so you could _in theory_ have the same language for implementation and scripting, however neither compiling to JS nor embeding JS are very convenient.

**Comment by mpcjanssen** [comment]
@vojtechkral I will have a look at Jython but I am a Tcl person myself.

Anyway the head of the tcl branch now allows manipulation of the task display and filtering. There are two callback `onFilter task` and `onDisplay task tokens`. Neither of them modify the actual task.

This makes this example possible

```
proc filter {list start} {
    lsearch -inline -all -not $list "${start}*"
}

proc joinTokens {tokens} {
    set result {}
    foreach tok $tokens {
        lappend result [lindex $tok end]
    }
    string trim [join $result " "]
}

proc onDisplay {task tokens} {
    set tokens [filter $tokens prio]
    set tokens [filter $tokens completed]
    set tokens [filter $tokens creation_date]
    return [joinTokens $tokens]
}
```

**Comment by mpcjanssen** [comment]
Also it is surprisingly fast. Probably not as fast as Jython though.

**Comment by mpcjanssen** [comment]
It doesn't seem Jython is a viable option as it requires quite a lot of Java SE specific stuff (such as javax)

**Comment by mpcjanssen** [comment]
JRuby uses invokeDynamic which DVM doesn't support.

**Comment by mpcjanssen** [comment]
Retried Jython, but it's a mess of dependencies (the jar is 25MB!) so Jython is out.

**Comment by mpcjanssen** [comment]
After embedding the Lua interpreter even further, Lua it will be.
