### ISSUE TITLE
The PayPal webpage link is down

### ISSUE THREAD

**Issue by ddisanti** [mpcjanssen/simpletask-android#439]

**Comment by mpcjanssen** [comment]
The link does work for me.

**Comment by mpcjanssen** [comment]
Link doesn't work from cloiudless because cloudless doesn't have internet permissions. I will try to use an intent instead.

**Comment by ddisanti** [comment]
Ok, @mpcjanssen

**Comment by bushrang3r** [comment]
The link doesn't work for me with cloudless. 

I just searched on PayPal for your email address and donated. Thank you for the best To do app there is.
