### ISSUE TITLE
How do I delete/remove the Simpletask calendar 

### ISSUE THREAD

**Issue by InfernallyT** [mpcjanssen/simpletask-android#440]
Hey, 
First of all very no nice app. How does one delete the Simpletask calendar once created. Do I have to uninstall the app? Thank you.

**Comment by vojtechkral** [comment]
The calendar should be removed when you disable syncing of both due and threshold dates in the settings (Settings → Calendar reminders → uncheck first two checkboxes).

Let me know whether that works.

**Comment by smichel17** [comment]
@vojtechkral Q: are they removed immediately or on next task list update? If it's the former, they would be more intuitive as sliders rather than checkboxes. Quoting myself from elsewhere, emphasis ~~mine~~ added now:

>Switches are pretty overrated; they're often more confusing than a checkbox would be. That said, they have their place on lone settings or** when changing the setting has an immediate effect** (like toggling wifi or switching theme).

**Comment by InfernallyT** [comment]
It worked thank you👍

**Comment by vojtechkral** [comment]
@InfernallyT Great!

@smichel17 Calendar is added / removed when settings change, but with a delay in the background. I also plan on increasing this delay so as not to update the calendar provider db too frequently. The effect should never be immediate.
