### ISSUE TITLE
Custom font size input setting

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#441]
Maybe it's different on an actual device, but on AVD Nexus 5X, the implementation is really odd, because it reloads the view as soon as the setting changes, even if I haven't let up on the slider.

You could fix this by waiting until the user lets go of the slider to update, but I would encourage you to use a [simple menu](https://www.google.com/design/spec/components/menus.html#menus-simple-menus) (or simple dialogue if a simple menu doesn't work well) instead.

**Comment by mpcjanssen** [comment]
this has to do with the way the slider updates the setting. i think a simple preference list would be better.
