### ISSUE TITLE
Feature request: open storage backend

### ISSUE THREAD

**Issue by thomas-mc-work** [mpcjanssen/simpletask-android#447]
Hello,

I would appreciate to use Simpletask with [the remoteStorage project](https://remotestorage.io/) as an option to store the data instead of dropbox. This is an open approach to host the data on your own server. I could help to implement the adapter, but I'm unable to do any interface work in the app.

What do you think?

**Comment by mpcjanssen** [comment]
@thomas-mc-work I will not implement additional storage adapters directly in the application. The maintenance burden for added APIs is too high.

For storage providers other than Dropbox the recommended way is to use Simpletask Cloudless and to use another app to do the synchronisation. 

I am not sure if there is an Android application to do this sync though (couldn't find one with a quick look)

**Comment by thomas-mc-work** [comment]
What if you would exclude the storage adapters form the main project into separate projects? And then they could be included as a plugin. This way you can free yourself and the actual development from the storage issue. Maybe then you also get more community contributions to the dropbox api as this project is more flexible and usable for other projects.

**Comment by mpcjanssen** [comment]
@thomas-mc-work that's a great idea but i don't have a clear idea of how to build this.

**Comment by smichel17** [comment]
Could you send the list contents via intent, and then a storage adaptor picks that up? And vice versa -- when the adapter picks up a changed file, it'll send an intent to simpletask.

**Comment by mpcjanssen** [comment]
Intents are limited in size (IIRC) this would probably require a content provider. Regardless this is quite a bit of work. Although the architecture

Simpletask -> IPC -> Storage Provider looks nice and expandable.

**Comment by smichel17** [comment]
see #513

**Comment by mpcjanssen** [comment]
@thomas-mc-work , the storage interface in the application is now separated logically in such a way that this shoudn't be too hard to do. I do not have time for it now though. The separate APK per storage is not going to happen. For reasons see the comment at #513

**Comment by mpcjanssen** [comment]
Not going to do this myself.  `simpletask-android\app\src\main\java\nl\mpcjanssen\simpletask\remote\IFileStore.kt` is the interface to implement.
