### ISSUE TITLE
Amoled black theme

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#448]
It would be nice if there is a completely black theme.

**Comment by ddisanti** [comment]
@mpcjanssen that would be very nice!

**Comment by ddisanti** [comment]
Nice! 👍

**Comment by ddisanti** [comment]
@mpcjanssen IMHO, for a complete black theme, the background color of the task list, filter tab and settings should be black.

**Comment by smichel17** [comment]
They are all black, for me.

**Comment by ddisanti** [comment]
@smichel17 in my case, they are dark grey and menus and drawers are black.

**Comment by smichel17** [comment]
@ddisanti what version of simpletask are you running?

**Comment by ddisanti** [comment]
Cloudless 8.1.0 from Play Store. I'm saying that the backgrounds of the different views should be black as the backgrounds of menus and drawers. I've attached a screen capture that site what I meant.
![screenshots_2016-07-18-15-04-21](https://cloud.githubusercontent.com/assets/17773786/16925155/2a824d6c-4d23-11e6-9c2d-3d48ea021173.png)

**Comment by ddisanti** [comment]
For those with an Amoled screen, like me, black themed apps means battery saving. On Amoled screens, black color is represented by just turning off those pixels. Besides that, it is just cool.

**Comment by mpcjanssen** [comment]
@ddisanti is this the dark them or the black theme? It looks like the dark theme.

**Comment by ddisanti** [comment]
@mpcjanssen is the black theme.
![screenshots_2016-07-19-06-44-12](https://cloud.githubusercontent.com/assets/17773786/16945812/f4327d98-4da6-11e6-845a-55c14570088f.png)
