### ISSUE TITLE
Does simpletask recreate the todo.txt file on write?

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#450]
I sync my todo.txt file with owncloud. It'll only auto-upload/download when you 'favorite' a file, otherwise it'll wait to sync manually.

This used to work great, but some time recently, every time simpletask writes the todo.txt file, the 'favorite' property is lost.

I just wanted to make sure that simpletask isn't doing something like deleting and re-creating the file instead of just writing to it, before I file a bug with owncloud.

**Comment by mpcjanssen** [comment]
Simpletask doesnt delete the file. It does truncate the file and rewrite it.

**Comment by smichel17** [comment]
Still definitely sounds like a bug on owncloud's end.
