### ISSUE TITLE
Sort before filtering with script

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#452]
The ability to limit the number of tasks shown in a filter is cool, but mostly useless because it's applied in file order.

Instead, all other parts of a filter should be applied before the script.

**Comment by mpcjanssen** [comment]
The reason the filter comes before the sort is that the sort is generally slower so filtering first improves performance. The limit number is a side effect of using a single context to filter all tasks anyway.
I agree the filtering really should come after the sort but with headers and all that's not easy to change.

**Comment by smichel17** [comment]
I think the script has two functions:

1. To allow particularly complex filtering that it would be impossible to offer with the native interface.
2. To make the app usable when there's places that the native interface falls short.

Any uses that fall under (2) are places where we should look to improve the native interface. I have some ideas, nothing all the way worked out yet. I'll update & re-open #411 when I'm happy with them.

For now, I think the order should be

1. Filter (not including script)
2. Sort
3. Filter sorted list with script

**Comment by mpcjanssen** [comment]
@smichel17 that proposal makes sense. General rule should be

> Do everything before executing script callbacks

**Comment by mpcjanssen** [comment]
will not be in 8.0. Probably next version.

**Comment by mpcjanssen** [comment]
Closd by #797
