### ISSUE TITLE
Developer-signed apk

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#453]
Advantage: [better security model](https://github.com/WhisperSystems/Signal-Android/issues/127).

Disadvantage: the [current process](https://f-droid.org/wiki/page/Deterministic,_Reproducible_Builds) seems a little cumbersome.

I'm not sure if this is something worth the hassle of doing right now, but it is something I'd encourage you to set up in the long term, so I figured I'd create an issue of it.

**Comment by mpcjanssen** [comment]
Loads of walls of text in those issues, but boiling down there are three options for Simpletask now:

1. Download it from the playstore with the guarantee that I built the app.
2. Download it from F-Droid with the implicit assumption that the F-Droid team doesn't tinker with it.
3. Build and sign it yourself from sources.

Considering the current distribution of new versions already is quite a bit of work, for me the above 3 options are enough. Anyone can feel free to add a different distribution mechanism based on the source though.

**Comment by smichel17** [comment]
Yeah I wouldn't worry about this until simpletask is feature complete and has a finalized UI.
