### ISSUE TITLE
Add extra functionality to "Search" function

### ISSUE THREAD

**Issue by ddisanti** [mpcjanssen/simpletask-android#459]
I would like to be able to search using basic regexp and/or multiple (sub)strings.

**Comment by mpcjanssen** [comment]
I will look into some simple fuzzy searches (for example fzf) I don't think I will add regexp.

**Comment by mpcjanssen** [comment]
Something like a combination of:

- Substring matching, task matches if it contains all the space separated strings regardless of order
- Fuzzy matching, task matches if the letters of each substring occur in the same order in the task

**Comment by ddisanti** [comment]
I would go with fuzzy matching. I use KISS Launcher [https://play.google.com/store/apps/details?id=fr.neamar.kiss](url) . It has a nice and very flexible Search. I attach an screen capture of it.
![screenshots_2016-06-07-08-08-53](https://cloud.githubusercontent.com/assets/17773786/15855799/e4e3e32e-2cb1-11e6-8711-99c2c4c43747.png)

**Comment by mpcjanssen** [comment]
Yes that is what I was thinking of too.
