### ISSUE TITLE
Investigate remoteStorage backend

### ISSUE THREAD

**Issue by thomas-mc-work** [mpcjanssen/simpletask-android#460]
[remoteStorage](https://remotestorage.io/) is an open protocol for per-user storage on the Web.

> remoteStorage is a creative combination of existing protocols and standards. It aims to re-use existing technologies as much as possible, adding just a small layer of standardization on top to facilitate its usage for per-user storage with simple permissions and offline-capable data sync.

- It's completely open
- There are several server implementations (e.g. cozy cloud)
- ~~It would resolve the main issue with todo.txt which is conflict resolution and reliable sync.~~

**Comment by mpcjanssen** [comment]
I don't see how this helps with conflict resolution, can you give a pointer?

**Comment by thomas-mc-work** [comment]
You're right, it won't overcome this issue.

**Comment by mpcjanssen** [comment]
Since this wont solve any merge issues any better than all the other file based synchronizations, this will not become a part of Simpletask itself.

**Comment by smichel17** [comment]
For anyone who ends up here in the future, see #447
