### ISSUE TITLE
Menu colors don't match theme

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#463]
The background color of the menu doesn't match the theme.

**Comment by ddisanti** [comment]
@mpcjanssen I was just thinking about that yesterday when checking for new issues to view and saw #448. But I was thinking the other way around: to get an almost complete black theme you have to change the main views background to black

**Comment by smichel17** [comment]
I would recommend both, in this case. Have:

- a light theme -> no changes
- a dark theme -> ~~menus~~ drawers have the same background color as the theme
- a 'night' theme -> the main view background is black and the accent (and headerbar) color is gray.

F-droid does it similarly to this (their night theme is not quite the same) and it's *really* nice.
