### ISSUE TITLE
Design Philosophy: Simplicity vs Flexibility

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#465]
There's a crossroads at each design decision: choose one way, or offer a setting. It's a fundamental tradeoff between power/flexibility and simplicity/ease of use; while some tradeoffs are better than others, the tradeoff always exists.

On one extreme, you could choose to always offer every choice. And then you'd end up with an app that's little more than an interpreter. Sure, that's maximally flexible, but at that point the user might as well just write their own app.

On the other extreme, you could choose never to include a setting. You'd end up with an app that's incredibly simple, useful, and easy to use for a small handful of people, and useless for everyone else.

Obviously a balance exists; the correct balance to strike varies from app to app depending on the app's target audience and goals. Since there's been a lot of design discussion recently and I'm working on a major redesign (#411 and #484), I'd like to have a conversation about what Simpletask's design philosophy should be. I hope we can come to a consensus; if not, I'll defer to @mpcjanssen's opinion and my own.

---

In my opinion, Simpletask has historically erred too far on the side of flexibility, at the cost of usability. The amount of initial configuration someone needs to do to have a working setup is very high. Every setting and configuration option you offer is a decision that users need to make before they can start using your app (be honest with yourself: How often do you start using an app without looking at its settings first?)

There are ways to lower barrier to entry while maintaining flexibility, by hiding decision points until they're relevant. For example, a website that offers a service might also have a forum section with an honor code. You could make every user accept the honor code to create an account, or you only require that when the user tries to make their first comment or post in the forums. Same complexity, smaller barrier to entry.

I think Simpletask should be more opinionated about the way it is intended to be used, though we should maintain flexibility where possible without sacrificing the intended experience. For example, in #461 my response to @jumper047 was "there's no right way to use it but this is how I do it." That's true for simpletask today, but I do think the way I use it (and the way jumper has started to use it now) is a better way, and Simpletask shouldn't pretend like either way is intended.

When there is an intended way of using the app, it is also easier to make other design decisions to offer a great experience when people use the app that way.

It's true that things like this might break the workflow of some existing Simpletask users. Some of those people can change their workflow. Others won't be able to. In situations where there's a large group of users who can't, I think we should look into other solutions for them -- but I believe it would be better to have two apps, one for each workflow, that each do an amazing job supporting that workflow, than a single app that does a mediocre job at supporting both.

---

@vojtechkral @ddisanti @mpcjanssen, anybody else watching this repo: thoughts?

**Comment by mpcjanssen** [comment]
@smichel17 I agree on most parts. I am favoring opinionated software more and more, it prevents the tirrany of choice. However, see below...

One main reason so many settings got introduced was because I wanted to change the behavior of the app, but didn't want to break existing workflows (hence a setting was needed). So for Simpletask I currently aim for:

- Opinionated defaults. The defaults should be easy to use and sensible.
- Options to tweak the defaults for power users which is the main target audience for Simpletask

Taking away the configuration flexibility will probably scare away a lot of current users.

**Comment by ddisanti** [comment]
@smichel First of all, I want to say that having almost zero dev skills I can't contribute with nothing but modest opinions to this project.

I think we all agree that the todo.txt method, for some reason, is mostly embraced by power users or people with some IT skills level. And also SimpleTask.

Having clear its targeted users, I don't see a bad thing to have (too) many settings to tweak if that allows me to work the way I'm comfortable with. Of course, it would be nice if all those settings are conveniently ordered and grouped for easy access.

**Comment by smichel17** [comment]
@mpcjanssen I'd like to know more about how most users use the app. Would you be opposed to adding a one-time popup or something encouraging people to email you (or me, or comment on an issue here) explaining their workflow, so we can strive to break as little as possible?

@ddisanti I pinged you because I've seen you around in the issues of this repo enough that you seem like one of the more involved community members.

**Comment by mpcjanssen** [comment]
@smichel17 I would love to get more feedback on workflows, I am however not willing to break any workflow. I think for a lot of users the went to Simpletask because it's the only app flexible enough to support their workflow.
If I would take away this flexibility (and thus their workflow) they will be (rightfully) annoyed. I think we should look into areas where functionality can be improved or generalized while still supporting all current flexibility. This is hard, but so be it.
So the philosophy is **flexible simplicity**. Meaning **complicated flexibility** or **simple inflexibility** are not options. I agree we are on the complicated flexibility part of the scale at the moment so lets improve that.

**Comment by smichel17** [comment]
@y2kbugger

**Comment by mpcjanssen** [comment]
I want to add that with progress on #349 the best way to add flexibility is to have more flexible Lua callbacks. Expect several options and settings to be move to specific Lua callbacks and scripts.

**Comment by smichel17** [comment]
I agree. I am a big fan of scripting in this case. It basically says, "There is a certain way Simpletask is meant to be used, and we will only support that way... but we recognize that you might want to use Simpletask in a way it's not intended. We won't support that, but we will support you in building that functionality yourself."

Unlike settings, scripting is something that is *obviously* advanced functionality that isn't intended to be used by most people, so people won't feel compelled to learn how to script if they want to use the app. So it enables us to support alternate workflows without complicating the primary/intended workflow.

I think it might also make sense to maintain a repository of lua scripts that people can easily download and use. For example, I think we should remove calendar reminder functionality from the core of the app altogether, but that would break some people's workflows. So instead we should remove the functionality altogether, and also provide a ready-made script that re-implements the removed functionality, so people who depend on that workflow aren't left out.

**Comment by smichel17** [comment]
Also, if there's a way to track how often each script is downloaded, it lets us get some usage statistics without putting tracking into the app itself, which I find morally objectionable unless it's opt-in -- and if it's opt-in it's much less useful.

**Comment by mpcjanssen** [comment]
@smichel17 I am not sure about tracking downloads but the simpletask github wiki would be a good way to capture scripts.

**Comment by smichel17** [comment]
@ddisanti @y2kbugger @mpcjanssen @vojtechkral @memeplex @Chriswaterguy @LocusutX How many filters do you use? If there are two or more filters showing the same tasks, sorted differently, count them as a single filter. Thank you!
