### ISSUE TITLE
Scripting help shortcut

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#467]
When I'm writing a lua filter, the overflow menu has only one option right now: `script from file.`

It should also have a `help` option which takes the user to the help page for scripting, so I can look at that and return to my script easily.

**Comment by mpcjanssen** [comment]
With the new elevated status of the scripting engine, I will eventually split of the scripting configuration to a separate activity (only the use script checkbox will remain in the filter settings). This separate activity should have direct access to the script help.

**Comment by smichel17** [comment]
Reminder.

**Comment by smichel17** [comment]
Closing because #488 does this, but better.
