### ISSUE TITLE
Total task count wrong when filtering

### ISSUE THREAD

**Issue by Alphalpha007** [mpcjanssen/simpletask-android#469]
If I use a filter, the total task count is wrong in the top where it shows "(6/82) filtered on: List".. I only have 69 tasks in total. Refreshing, changing todo file or unhiding tasks didn't correct it.

**Comment by mpcjanssen** [comment]
Do you use sort by list or see any other headers?

**Comment by Alphalpha007** [comment]
Any filtering produces the same problem. Whether by list, tag or script.

**Comment by mpcjanssen** [comment]
But does the filtered view have headers?

**Comment by Alphalpha007** [comment]
I'm not sure what you mean by headers.
If you mean the groupings, I use the MYN technique you recommend. So I see the threshold dates as headers.

**Comment by Alphalpha007** [comment]
http://i.imgur.com/JJgW7bZ.jpg
Here's the screenshot.

**Comment by mpcjanssen** [comment]
Thanks I will check it out.

**Comment by Alphalpha007** [comment]
I just had a look at the actual text file. There were blank lines in the file. That's what's causing the total count to show a higher number. Can you make simpletask ignore blank lines?

**Comment by smichel17** [comment]
Would it be better to ignore or remove blank lines? (Haven't thought that through yet, just raising the question).

**Comment by mpcjanssen** [comment]
@smichel17 ignoring blank lines is good, but deleting them will break todo files for people who use whitespace for organisation. Because of this the underlying data needs to keep the empty lines, they should just not be counted.

**Comment by mpcjanssen** [comment]
@Alphalpha007 that will be easy to fix.
