### ISSUE TITLE
Migrate to Dropbox v2 before June 28, 2017

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#470]
As of today, Dropbox API v1 is deprecated. This includes both the user endpoints (a.k.a. the Core API), and the team endpoints (a.k.a. the Business API). In order to provide our developers with the most up-to-date features and support a single, consistent platform, we’ll be turning off API v1 a year from now, on 6/28/2017.

**Comment by mpcjanssen** [comment]
To summarize my experience with Dropbox:

- Simpletask used V1 Core API (inherited from todotxt)
- Moved to Sync API for easier sync.
- Sync API was deprecated, had to move back to V1 Core
- V2 API announced with the remark that V1 will stop to work
- Will have to do everything all over again (together with every application that sync with dropbox on the planet).

My current impression of Dropbox is that they don't give a shit about the developers, so I am very tempted to don't give a shit in return.

**Comment by mpcjanssen** [comment]
Some 'nice' background info of the Dropbox attitude towards developers. https://disqus.com/home/discussion/dropboxdeveloperblog/deprecating_the_sync_and_datastore_apis_dropbox_developer_blog/

**Comment by felixkm** [comment]
Same here for Android :) https://github.com/CloudRail/cloudrail-si-android-sdk

**Comment by mpcjanssen** [comment]
@felixkm I looked at that, but there are several disqualifiers:

1. All communication goes via the cloudrail servers before reaching Dropbox
2. It doesn't support version meta information and handling of conflicts.

**Comment by mpcjanssen** [comment]
See also https://www.dropboxforum.com/hc/en-us/community/posts/206129823-Why-are-you-deprecating-v1- for my view on this.

**Comment by felixkm** [comment]
@mpcjanssen 
1. Where did you get that from? Actually we do all communication P2P, so no data ever passes a CloudRail server. It is basically just a replacement of the Dropbox SDK.
2. If you could elaborate that more, especially what the use case for that is, we can see if it is possible to add it.

**Comment by mpcjanssen** [comment]
@felixkm ad 1. I don't know where I got that idea, thank you for correcting me, I updated my comment

For 2. Currently simpletask stores the last revision it has seen on dropbox. Then when you put a new version to dropbox, you can include the last seen version in the request. If the remote version has changed (i.e. there is a conflict), dropbox will create a new file and return the updated filename.

**Comment by felixkm** [comment]
@mpcjanssen thanks :)

For 2: That sounds like a very good addition to our interface. I'll bring that up in our next meeting and keep you in the loop.

**Comment by mpcjanssen** [comment]
@felixkm thanks for considering it.

**Comment by mpcjanssen** [comment]
Fixed by 259f273ef0a4f6c527ea69f7e708681467173a05

**Comment by mpcjanssen** [comment]
v9.1.0 from the playstore works with the new Dropbox API
