### ISSUE TITLE
Occasionally hangs on "loading" circle in low reception

### ISSUE THREAD

**Issue by LocutusX** [mpcjanssen/simpletask-android#472]
Hello. I reported this issue via a Google Play Review, but I realize that forum is not really intended for bug reports so I tracked you down to your github :)

Basically, on certain occasions when in low reception environments (my use case is an underground Subway system) attempting to run Simpletask will cause it to hang on the "loading" circle. The phone's back button does not work in this case. After waiting about 20s (I'm impatient) I just use the Android task switcher button to kill it.

It's true that in certain low-reception (or no-reception) situations, SimpleTask loads fine - i.e. in Airplane mode. However it's puzzling why I've seen the app behave this way in several situations.

Device info: LG G4
Android 6.0
Running stock LG OS/firmware.

**Comment by mpcjanssen** [comment]
@LocutusX I will look into this. The problem is that the tasks are loading in the background and apperently in some situations the trigger to hide the loading overlay doesn't get sent. A log when this happens would be really useful.

**Comment by mpcjanssen** [comment]
@LocutusX  I have checked, this part of the code is one huge callback spaghetti. This is gonna take time to clean up.

**Comment by LocutusX** [comment]
Thanks for looking into this!

**Comment by mpcjanssen** [comment]
I have untangled the spaghetti quite a bit and I am fairly confident this can't happen anymore. Please reopen if it still occurs for any version after 10.0.0
