### ISSUE TITLE
Edit shared task doesn't work

### ISSUE THREAD

**Issue by ddisanti** [mpcjanssen/simpletask-android#473]
Although option "Edit shared task" is activated, the shared task is saved and an empty edit box is presented. Related #298

**Comment by ddisanti** [comment]
@mpcjanssen @smichel17  I'm not sure if this issue should be re opened or log a new one.
I'm facing this issue randomly again. It happens randomly when sharing one task. And it happens always when sharing a bunch of task. The first one is presented for edition (must of the times), but the next ones are saved and an entry box is presented.
If it is of any help, I recently flashed an official Samsung 5.0 stock ROM. My guess is that somehow because of all the bloatware, Simpletask don't get enough resources when it has to load the task for edition, or there is a kind of race condition when the task is saved and Simpletask tries to load it for edition.
I'm using Cloudless 8.3.1 from Play Store.
This is a link to my [debug log file](https://www.dropbox.com/s/z3xcdnr21opwsha/simpletask.txt?dl=0).

**Comment by smichel17** [comment]
This is an area of Simpletask I haven't touched yet, so I'm going to leave this one to @mpcjanssen.

**Comment by mpcjanssen** [comment]
@ddisanti if you feel adventurous you could try a `nodb` build which I think fixes this.

**Comment by ddisanti** [comment]
@mpcjanssen I was browsing the repo and saw that nodb branch. I would really like to give it a try. If it is not too much trouble, could you post somewhere a build for download?

**Comment by mpcjanssen** [comment]
@ddisanti see https://www.dropbox.com/sh/2jvpey3s5t9xev2/AAA0RvEhifHleQuGMnAOD0mJa?dl=0

**Comment by ddisanti** [comment]
@mpcjanssen can this compilation be installed together with the Play Store version or will it be overwritten?

**Comment by mpcjanssen** [comment]
@ddisanti  Play store version will be overwritten. I can add a debug version which can be used in parallel

**Comment by ddisanti** [comment]
@mpcjanssen It's okay. I felt adventurous and I installed the nodb version that you provided. :smile:
I've played a little with it. I saved several shared test tasks and apparently the bug is fixed. I will continue to testing and report any issues I find.
