### ISSUE TITLE
Task completion visual bug

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#474]
## My list

Sorted by complete -> alpha

- [ ] a
- [ ] b
- [ ] c

### Result, showing completed tasks

After a slight delay, this happens:

- [ ] a
- [x] c
- [ ] b

Then this:

- [ ] a
- [ ] c
- [x] b

### Result, hiding completed tasks

Slight delay, then

- [ ] a
- [x] c

Then

- [ ] a
- [ ] c

---

It's a bit jarring to mark b as complete, then have it briefly show C as complete; it makes me second-guess whether I marked the right one as complete.

**Comment by mpcjanssen** [comment]
Not sure how to fix this but I also notice this. Probably requires redoing the whole displaying and filtering part.
