### ISSUE TITLE
Unstable Updates (beta) on f-droid?

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#480]
With a number of new bugs popping up around the revamped lua engine, it occurs to me that with major changes, it might be helpful to get some wider testing before you push to everyone on f-droid. I'd like to do this, but it's hard because f-droid packages are signed by f-droid. In order for me  so I can't install a more recent version unless you release it through f-droid.

F-droid has a way around this: releasing unstable updates. You release a new tagged release as normal, but in AndroidManifest.xml, you keep the Current Version / Current Version Code at the last stable release. Then, only users with Unstable Updates enabled in f-droid will receive the update, so I and other users can test and we can keep common bugs from the majority of Simpletask users.

**Comment by mpcjanssen** [comment]
This does make it hard to determine which version someone is reporting bugs for as the only version that is currently the combination  Current Version / Current Version Code or am I missing something?

**Comment by smichel17** [comment]
It was my mistake; my latest understanding is that F-droid decides which versions to build based on a metadata file in the fdroiddata repo. That file has 3 relevant key:value pairs:

`Current Version:$version`: There's one of these; For F-droid, this is `v0.100.1`
`Current Version Code:$version_code`: There's one of these; it must correspond to the version; Android uses this to determine the version order and F-droid uses it to determine which version to recommend (ie, which is the latest stable version).
`Build:$version,$version_code` It also requires a flag `commit=` and then specify either the commit ID or the version number. There can be any number of these, and f-droid will build each.

Version [code] matches AndroidManifest.xml. The way you provide beta updates is by adding a `Build` line whose version/code are higher than the current version [code].

---

I am a little unclear as to how you, a developer, should update these files. Normally they will be updated automatically when you create a tag. You could do it manually by sending a merge request, but that seems cumbersome.

Information is from the [F-droid Server Manual](https://f-droid.org/manual/fdroid.html), sections 7, 7.22, 7.27, 7.33, and 7.34.

**Comment by doranism** [comment]
I would like to participate in testing beta-versions. How can I downloud them from f-droid? Or do you release beta versions only on google playstore?

**Comment by mpcjanssen** [comment]
@doranism google play has specific beta support so I release them there. For fdroid i will have to investigate

**Comment by mpcjanssen** [comment]
Due to time restraints, I can't do the manual fdroid data updates. But maybe tagging betas works.

**Comment by doranism** [comment]
OK. I try to live without a google account, but I will find a way.

**Comment by smichel17** [comment]
We've just been building and sharing debug version apks and that has worked fine. If anyone in the future sees this and wants to help testing, just ask @mpcjanssen or myself to share a debug build (which can be installed alongside the regular build, so it's better than gplay beta anyway). Or look into building yourself. If you use android studio it is not that hard.
