### ISSUE TITLE
Select all

### ISSUE THREAD

**Issue by Chriswaterguy** [mpcjanssen/simpletask-android#481]
There are times when I have many tasks showing and I want to select all of them, eg to add a project tag. It would be handy to have a select all option – say, in the menu.

**Comment by smichel17** [comment]
There is a select all option. Select one task first, then it's in the three dot menu in the lower right.

@mpcjanssen can this be motivation to implement #128? :wink:  Or at least this part of it:

> ## List view
> 
> - Icons moved to app bar:
>   - Select all: this is the normal/expected location
>   - Calendar reminder and Share: these are distinct from all the other options because they interact with other apps.
> - Icons at bottom:
>   - 'Set due date' and 'Set threshold date' moved here from the menu
>   - Rearranged to the same order at #419 (prio-due-threshold-list-tag) and span the whole bar
>     - If you won't implement #419, order should be prio-list-tag-due-threhold
> - Added FAB to edit.
> - Items left in the menu are Archive, Delete, Complete, and Uncomplete -- also all related.
> 
> ![listview-draft](https://cloud.githubusercontent.com/assets/6563664/16823857/168bcd8e-4935-11e6-8f81-dbb1a4c15307.png)
>
>![listview-optionsopen-draft](https://cloud.githubusercontent.com/assets/6563664/16823856/15334cdc-4935-11e6-9a8a-943ccbccb79c.png)

### Note

Some of the icons in the mockups are placeholders. The actual icons I'd use are:

- Due Date; "Alarm on" from [1]
- Threshold Date; "Watch Later" from [1]
  - This is the only one I'm still on the fence about. The other option is "Next Week" from [1]
- Lists; "List" from [1]
- Tags; "tag-multiple" from [2]
- Add Reminder; "Insert Invitation" from [1]


[1]: https://design.google.com/icons/
[2]: https://materialdesignicons.com/

![better-icons](https://cloud.githubusercontent.com/assets/6563664/16825269/415d31a4-4941-11e6-80f6-37813d7669d9.png)

**Comment by mpcjanssen** [comment]
@smichel17  The new UI looks great, I just don't know how to implement it. Toolbars and actionbar menus are fickle things.

**Comment by smichel17** [comment]
Noted! If the code is relatively contained, maybe this would be a good place for me to jump a little deeper into the code than the settings work I've done so far...
