### ISSUE TITLE
Allow custom font for task list.

### ISSUE THREAD

**Issue by memeplex** [mpcjanssen/simpletask-android#482]
I customized the font from the settings window but nothing happened. I tried with many fonts to no avail. Besides there seems to be a problem with 0/1-based indexing, because after returning to the font picker the one selected is the one before the originally selected.

**Comment by smichel17** [comment]
Tested this; the setting also has no effect for me.

**Comment by mpcjanssen** [comment]
Correct on both counts. This functionality is actually not implemented yet (only the setting is there)

**Comment by mpcjanssen** [comment]
Retagged enhancement as a reminder to implement it again.

**Comment by mpcjanssen** [comment]
Then duplicate of #449
