### ISSUE TITLE
Continuous translation via weblate

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#483]
Have you considered setting up a translation website like weblate? It's gratis for FLO software (or you can self-host) and makes translation much more accessible to people who aren't comfortable creating a merge request.

**Comment by ddisanti** [comment]
I'm working on a Spanish version of strings.xml. When I get it completed  I'll ask @mpcjanssen what other files needs to be translated.

**Comment by smichel17** [comment]
My own experience was that after the author or Red Moon (the other app I've contributed to) set up weblate, translation happened in more languages, much more quickly than before. See the [commit log](https://github.com/raatmarien/red-moon/commits/master).

**Comment by smichel17** [comment]
More info: https://weblate.org/en/hosting/

Just read that page (you probably want automatic push), click the `ask for hosting` or `contact us` links (they both go to the [same](https://hosted.weblate.org/hosting/) place), fill out a couple details, and submit the form.

I really can't understate how much of a difference this makes in terms of the number of people who are able to contribute.

**Comment by mpcjanssen** [comment]
Request to weblate is sent.

**Comment by smichel17** [comment]
https://hosted.weblate.org/projects/simpletask/strings/
