### ISSUE TITLE
8.0 rec task overwrote todo.txt file

### ISSUE THREAD

**Issue by andis** [mpcjanssen/simpletask-android#489]
Hi, simpletask 8.0.3 just emptied my todo.txt file :( It now only contains one line.
What happend: I used a saved filter to filter by list. Then I quickly ticked off a few done tasks. After the last screen refresh, the task list was suddenly empty. I looked into my todo.txt file, it contains only `2016-07-15 @@list task text rec:1d t:2016-07-16`. So the ticking off of the last recurring task must have overwritten my todo.txt file.

**Comment by mpcjanssen** [comment]
@andis, first things first. If you go to Settings->Other->Todo History you should  be able to see the last versions of you todo list and share it by mail or directly to Simpletask to restore all your tasks. NB this will only be there if you dodn't reinstall Simpletask.
Next can you share me the log from Settings -> Other -> View Debug Information?
Sorry for the inconvenience.

**Comment by andis** [comment]
The Todo History is very nice, sorry for the panic. I'm sending the log by email.

**Comment by mpcjanssen** [comment]
Seems to be a race condition between save and reload. Are you using any background synchronisation app?

**Comment by andis** [comment]
Normally yes, Syncthing, but I am quite sure it wasn't running at the moment of the issue.

**Comment by mpcjanssen** [comment]
Is probably fixed by 843776cdc461a01aa210d062c3b3895d98667d05 please re-open if re-occurs.
