### ISSUE TITLE
Edit shared tasks option has no effect

### ISSUE THREAD

**Issue by aurisnoctis** [mpcjanssen/simpletask-android#501]
In contrast to Issue #292 , The 'Edit shared tasks' option is available in Simpletask >Menu > Configuration. However, it does not seems to have any effect. For instance, when I share a link from the Firefox browser and would like to add a comment, this is not possible as the task is saved silently in the background. The tag +background is added correctly, but the editing of the task before saving is not possible.

**Comment by mpcjanssen** [comment]
Works for me. Try unselecting and reselecting the checkbox. Which version are you running?

**Comment by aurisnoctis** [comment]
I unselected and selected back as suggested.

Afterwards: First trial with Firefox: generated a temporary pop-up saying "Task added to Simpletask", then nothing except seeing the browser as before (no editing window appears). Second trial on same website, just repeating the sharing with Simpletask as before: pop-up and editing window appear --> seems fine.

Maybe an initialization issue? If it works from now on, I'm happy.

Thanks!
Hella

**Comment by mpcjanssen** [comment]
@aurisnoctis 8.2.0 will be released soon (is already in beta on the play store). Can you check if this works now?

**Comment by aurisnoctis** [comment]
It seems to work - thank you!
