### ISSUE TITLE
onFilter arguments

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#503]
### Assorted architecture questions/suggestions:

The `fields` table has an entry for `task`; why is the task also an argument?
- No preference about which you should get rid of, but it seems odd to have both.

---

`due`, `threshold`, and `recurrence` are extensions we use, not a core part of the todo.txt format; I think they belong in the `extensions` table, not the `fields` table.
- If you do this, you'll want to use `t` and `rec` as keys instead.

---

`f.tags` and `f.lists` will never be nil, presumably because there's a `f.tags = {}` somewhere.
That means testing for tags must be done like: `if next(f.tags)==nil then ... end`
- I think this is unintuitive, considering all other fields are nil if empty. Is there any reason why you couldn't wait to create the table until the first list or tag is found?
- If you must retain the current behavior, the above explanation for how to check if a task has lists or tags should be included in the lua help.

**Comment by mpcjanssen** [comment]
Regarding the separate task parameter, I didn't realize tasks is already in fields so it's not needed.

Regarding the non nil table, When ensuring the table is non nil, checking if a tags is available is a simple `f.tags.tagname` without a necessary `nil`check for `f.tags`. 

The `next(...)` test is shown in the Lua scripting examples.

In the end it's a judgement call about which scenario is more likely and I decided you want to check for tags more often than checking for the absense of tags.

Regarding the extensions, I could merge `fields` and `extensions` to one table then the question is if date fields like `f.due` should contain the due string or the due timestamp.

**Comment by mpcjanssen** [comment]
I prefer merging exts with field and keeping the current keys and leaving the easy access to `task` to prevent breaking existing scripts.

**Comment by smichel17** [comment]
Re task in fields: ok. Not a big deal, it's just odd to be in two places.

Re non nil table: that makes sense.

Re fields vs extensions: this means people cannot use any of the keywords (task, threshold, completiondate, etc) as extensions. Is that an acceptable cost?

Re extensions implementation: what if there are multiple of the same extension, like #466? If someone wants to add multiple reminders, extensions will need to store tables, not just a simple value.

**Comment by mpcjanssen** [comment]
@smichel17 good point about the overlapping extensions. My idea is now:

- task: is redundant but I don't want to change the interface again and it doesn't hurt
- fields: Interpreted parts of the task such as due date as a timestamp, lists as a table etc.
- ext: string, string table with all extensions (so here due will contain the original date string)

I will update the docs to this effect.

**Comment by smichel17** [comment]
@mpcjanssen I think the best solution would be to pass an iterator in a couple places (eg,`task`). http://www.lua.org/pil/7.1.html

**Comment by smichel17** [comment]
I think all the actionable stuff here is done, or done enough that we can open new issues if anything else pops up.
