### ISSUE TITLE
Elevated lua status appreciation

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#504]
By putting this in my global config:

```
exLists = {["errands"] = true, ["hats"] = true, ["wishlist"] = true, ["media"] = true, ["shopping"] = true, ["projects"] = true}

function isExcluded (table)
  for x in pairs(exLists) do
    if table[x] then return true; end
  end
  return false;
end

function isEmpty (table)
  return next (table) == nil
end
```

I can use this script for my inbox:

```
function onFilter(t,f,e)
  return isEmpty(f.lists)
         or f.lists["waiting"]
         or isEmpty(f.tags)
              and not isExcluded(f.lists)
end
```

and this for my next actions

```
function onFilter ( t, f, e )
  return not isExcluded(f.lists)
      and not f.lists["waiting"]
end
```

SO much nicer.

**Comment by Alphalpha007** [comment]
Can you please explain what this does? Looks interesting.

**Comment by smichel17** [comment]
@alphalpha007 I use simpletask for GTD. I capture stuff throughout the day, then process it daily to add projects and contexts. I also use simpletask for things like shopping -- 'excluded' is lists that are not contexts.

From there, it reads almost like english. For my inbox, a task is included if:

- It has no lists
or
- it has the 'waiting' list
  - to remind me to follow up with whomever I'm waiting for
or
- it has no tags and it's not on a shopping list or something like that

Basically, items only make it out of my inbox if I give them both a project and a context, unless it's a shopping list item, in which case it's excluded even if it has no projects.

My next-action filter shows all tasks that are not a shopping list and that I'm not waiting on someone else for.

---

The nice thing about this setup is that if I want to add a new non-gtd list (eg, separate food shopping from other shopping), I just have to add it to the 'excluded' list in my global config and all my filters that use it will automatically update, instead of having to update each filter individually.

**Comment by Alphalpha007** [comment]
Can you add excluded lists in referred format? For example, exclude all lists that begin with "e-"? Eg: "e-shopping"

**Comment by Alphalpha007** [comment]
I meant regex format

**Comment by smichel17** [comment]
I mean, you can do whatever lua allows you to do. If you want to learn lua, [the lua book](http://www.lua.org/pil/contents.html) seems to be a good resource for that. I'm in the middle of reading it; it's a relatively easy read and the language is pretty elegant.

I don't know offhand whether lua supports regex but a quick duckduckgo search pointed me to [this page](http://www.lua.org/pil/20.1.html) of the book, from which I surmise that full regex is not supported, but you could get the behavior you want with:

```
function isExcluded (table)
  local n --improves performance; no other effect
  for x in pairs(table) do
    n=string.find(x, "e-")
    if n==1 then return true; end
  end
  return false;
end
```

**Comment by Alphalpha007** [comment]
Very nice. I've tweaked that a bit too get what I want. Do you have any other interesting functions that you use? I'm trying to figure out the possibilities.

**Comment by smichel17** [comment]
Nope, that's about it. As I get further into the book I might find something else, but my filters pretty much do what I need them to, so I don't see much of a reason to change them.

**Comment by Alphalpha007** [comment]
Instead of excluding lists for next actions, may I recommend including only @@contexts? Much easier.

function isExcluded (table,e)
  local n
  for x in pairs(table) do
    n=string.find(x, e)
    if n~=nil then return false; end
  end
  return true;
end

function onFilter(t,f,e)
  return not isExcluded(f.lists,'@') and isExcluded(f.lists,'waiting')
end

**Comment by smichel17** [comment]
I ended up using `@@context`. Here's my current lua global config:

```
function isAction(f)
  return hasContext(f.lists)
     and hasProject(f.tags)
     and not f.lists["waiting"]
end

function hasContext(lists)
  local n
  for x in pairs(lists) do
    n=string.find(x, "@")
    if n==1 then return true; end
  end
  return false
end

function hasProject(tags)
  return not isEmpty(tags)
end

function isEmpty(table)
  return next(table) == nil
end
```

Then my filters for next actions just have
```
function onFilter(t, f, e)
  return isAction(f)
end
```

**Comment by smichel17** [comment]
And my inbox filter looks like
```
function onFilter(t, f, e)
  return isEmpty(f.lists)
      or f.lists["waiting"]
      or hasProject(f.tags)
         and hasContext(f.lists)
end
```
