### ISSUE TITLE
Trying to close right drawer via up actionbar button opens left drawer

### ISSUE THREAD

**Issue by stefan-girlich** [mpcjanssen/simpletask-android#505]
1. Open main screen
2. Swipe in from right screen edge to open right drawer ("Saved filters"). -> Menu icon in ActionBar animates to "back" arrow.
3. Click "back".
-> Left drawer opens _underneath_ right drawer.

Version: Simpletask cloudless v8.1.0 (3038)

**Comment by smichel17** [comment]
I can also replicate this. As I've said before, I think the best way to fix it is to stop using a right drawer.

**Comment by mpcjanssen** [comment]
Cute bug. Should be easy to fix.

**Comment by ddisanti** [comment]
@mpcjanssen in the last test release, this is fixed for the upper left Back button, but the rest of the elements in the upper toolbar remains active when the right drawer is opened. So, if you tap on Search, keyboard appears and you do as usual but right drawer remains on top (it is also for Filter and Settings buttons) I think upper toolbar and right drawer should be active one at a time for proper behaviour. Maybe right drawer could cover also the upper toolbar when opened.

**Comment by mpcjanssen** [comment]
@ddisant toolbar also stays open on left draws swipe so this is a different issue. Please log a separate issue for this.
