### ISSUE TITLE
Upper toolbar stay active when opening right/left drawers

### ISSUE THREAD

**Issue by ddisanti** [mpcjanssen/simpletask-android#515]
Search, Filters and Settings buttons on upper toolbar remains active when right or left drawers are opened, thus tapping on Search, keyboard appears, you can enter your search pattern but the drawer previously opened remains on top of the screen.
For proper behaviour, drawers should hide when tapping on upper toolbar or upper toolbar should stay inactive when drawers are opened.

**Comment by smichel17** [comment]
My opinion: wait to fix until a new interface is decided on. It's a waste to do this if, for example, we'll end up having different actions in the app bar when the drawer is open.

**Comment by smichel17** [comment]
This is fixed in the UI update branch.

**Comment by mpcjanssen** [comment]
Merged and published to beta.
