### ISSUE TITLE
Separate sort and group

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#516]
I'd like to be able to show one task per project (ie, the next action; currently possible with lua) and have headers by project, but sort by threshold date (MYN style).

The threshold date order is important to me,  but the precise date is less important, so showing project more prominently is preferable to me.

There are some issues / design decisions to tackle if you simply separate sorting and grouping (eg, what if I want the groups all together so each header appears only once?), so this is more for future reference than immediate action.

**Comment by djibux** [comment]
I would like that as well.
Creating custom groups would also be nice (for instance I would love to sort by threshold and have only three groups: past, current and future).

**Comment by mpcjanssen** [comment]
@djibux for custom groups I am thinking about a `onTaskGroup (task)` callback where you can return your own group allowing your scenario

**Comment by djibux** [comment]
Awesome!

**Comment by smichel17** [comment]
@mpcjanssen what if you just updated the onFilter callback so if you return True/False it is shown or not, or you can return the name of the group you wish the task to be shown under?

**Comment by mpcjanssen** [comment]
@smichel17 I find filtering and grouping two different concepts. I can easily imagine scenarios where you want to filter and not group or where you want to group but not filter.

So by splitting the callbacks, they are easier to reuse and maintain. Also putting everything in the onFilter will make the semantics of that function harder.

**Comment by smichel17** [comment]
@mpcjanssen I agree, this just makes the grouping interface more complicated...

On the upside, new UI is pretty modular so it shouldn't be too hard to change this to accommodate a new callback.

**Comment by mpcjanssen** [comment]
I had a scripting tab which used a spinner to select the callback to test which looked quite useful, might reintroduce it.

**Comment by smichel17** [comment]
@mpcjanssen I should have current version of the UI update posted soon (could be anywhere from a few hours to a few days). Might make sense to hold off on frontend changes until then.

**Comment by mpcjanssen** [comment]
Roger

**Comment by djibux** [comment]
Just for reference, if that can help someone, the onGroup callback allowed me to do exactly the grouping I wanted.
I sort by completed then threshold then alphabetical and then use the following filter script to view current and future tasks.

```
function onGroup(t,f,e)
  if f.completed then
    return "Completed";
  elseif f.threshold==nil or f.threshold <= os.time() then
    return "Today";
  elseif f.threshold <= os.time() + 86400 then
    return "Tomorrow";
  else
    return "Future";
  end
end
```

**Comment by smichel17** [comment]
This seems done.
