### ISSUE TITLE
Placeholder UI

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#518]
As the app is loading, if you display a screen with the same colors as the main structural elements (instead of a white background) it makes the app feel more responsive. 

>>>>>>>>>>>>>>>![Placeholder UI Example](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B7tHpXMphfIHdWdsRFRUZzJJcHM/patters-launch-screens-03.png)
Example

(don't mind the quotes, they're a hack to make the image smaller)

It should probably wait until after any other UI changes. It's definitely a small benefit, but it's the little things that make an app feel great to use.

[More](https://material.google.com/patterns/launch-screens.html#launch-screens-types-of-launch-screens) from the material design guidelines.

**Comment by smichel17** [comment]
How to: https://medium.com/@lucasurbas/placeholder-ui-launch-screen-d85c35552119#.toj4s9smp

Doesn't tell how to do it with a dark theme though.

**Comment by mpcjanssen** [comment]
This doesn't work well for dark themes. The initial view is always styled according to the theme in the manifest. Changing the theme in onCreate is too late. So you can pick one theme in manifest which will look off if the user selecta the other theme.

**Comment by smichel17** [comment]
The ActionBar color stays the same across all themes. It'd look better to start with a white background and blue actionbar, then have the background change to black, than to have all white, no header.

**Comment by smichel17** [comment]
Or -- better idea? -- we could do an entirely blue background.

**Comment by mpcjanssen** [comment]
Would be an option, but I am not sure if it would look any better.

**Comment by smichel17** [comment]
I can think of a way to make it look better with a good animation:

- Splash screen is a blue background with the simpletask logo checkmark in the center
- Upon load, the main app content scrolls up from the bottom of the page, ending as the ActionBar

The animation is visual polish and thus should be the last thing we add, imo. The blue splash with icon is a reasonable thing to add, though. Do you have a higher res version than `xxxhdpi/ic_launcher`?

**Comment by smichel17** [comment]
(clicked the wrong button, lol)
