### ISSUE TITLE
Preserve tasklist position after some actions

### ISSUE THREAD

**Issue by kai11** [mpcjanssen/simpletask-android#520]
1) Open big list of tasks
2) Scroll to middle of the list
3) Open URL in task

Expected result
1) URL opened in background (e.g. in Firefox), scroll position is the same

Actual result
1) Task list scrolled to the top, position is lost and I need to find task again

Other actions with same behavior:
1) SMS / phone call
2) Task(s) edit in text editor

Task competition and change priority/tag/project are all OK

**Comment by mpcjanssen** [comment]
When you switch away from simpletask the view is recreated when you switch back. Restoring the position in the tasklist is very hard (i tried) but i will look at it again.

**Comment by kai11** [comment]
Thanks.
What about editing task - is it switching away from simpletask as well?

**Comment by mpcjanssen** [comment]
@kai11 yes it is.
