### ISSUE TITLE
Lua config app bar should not scroll off screen

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#522]
It makes it impossible to cut/copy/paste.

**Comment by mpcjanssen** [comment]
This seems to be standard behavior if the keyboard is visible. No idea how to  fix this, but I will add a share button instead. So you can share the script.

**Comment by smichel17** [comment]
I'd prefer fixing this to adding a share button, as this also prevents me from rearranging/refactoring code or cut-and-pasting from filters (which do not have this behavior) to the global config. Not that I do those things that often now that I'm set up, but I have wanted to a couple times in the past and had to cut-paste from the top in chunks.

Don't work on it any further; I think I've figured it out and will have a PR in a bit.

**Comment by mpcjanssen** [comment]
I can't fix this, it's built in Android behavior.

**Comment by smichel17** [comment]
It is fixable and I have working example code. It involves a RelativeLayout instead of a LinearLayout. The actual fix will only take a couple minutes but I'm also learning a bunch about android dev at the same time.

**Comment by smichel17** [comment]
Working example code: https://github.com/jonan/ForkHub/blob/master/app/src/main/res/layout/comment_create.xml

**Comment by smichel17** [comment]
Also figuring out which of those attributes are important to fixing this issue and which are not.

As I said, though, don't worry about it; I'd like to do this myself since it's a good easy change to get my feet wet.

**Comment by smichel17** [comment]
Not to mention that the script box in the filter view has the correct behavior.

**Comment by smichel17** [comment]
hmm. looks like a [ScrollView](https://developer.android.com/reference/android/widget/ScrollView.html) might be the "right" solution here.
