### ISSUE TITLE
global functions aren't working in filter scripts

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#523]
I have 3 filters that show the same tasks (next actions, sorted differently) so I made a global isAction function and my onFilter functions just return isAction(f).

Right now those filters display as empty.

I'd share the exact functions but I can't because of #522.

**Comment by mpcjanssen** [comment]
@smichel17 Can you see a Lua error in the logging?

**Comment by mpcjanssen** [comment]
it seems to work for me. Double check did you use:

```
function onFilter(t,f,e)
   isAction(f)
end
```

or
```
function onFilter(t,f,e)
   return isAction(f)
end
```

You'll need the second form. The first one always returns `nil`

**Comment by smichel17** [comment]
I'm certain the issue is not with my script because it was working before the update. 

`i ActiveFilter Resetting onFilter callback in module mainui

Seems to happen immediately after loading any filter.

**Comment by mpcjanssen** [comment]
That's normal. Some other checks,

- Is the Use filter checkbox on?
- What does testing the script do?

**Comment by smichel17** [comment]
I decided to become a scribe

### Lua global config:

```
function isAction(f)
  return not isEmpty(f.lists)
     and not isEmpty(f.tags)
     and not isExcluded(f.lists)
     and not f.lists["waiting"]
end

function isExcluded(table)
  local n
  for x in pairs(table) do
    n=string.find(x, "@")
    if n~=1 then return true; end
  end
  return false
end

function isEmpty(table)
  return next(table) == nil
end
```
### Script tab of filter

- [x] Use script

```
function onFilter ( t, f, e )
  return isAction(f);
end
```

---

Any test task that I have tried so far returns `false: task will not be shown`

**Comment by smichel17** [comment]
Added `toast(isAction(f))` to the end of my filter script (after onFilter; I also tried before onFilter with the same result) . I get a Lua error which spits back my global config, followed by `:3 attempt to index ? (a nil value)` I wonder if the problem is with my isEmpty function?

**Comment by mpcjanssen** [comment]
For me the task

`test @@home +test` matches which seems to make sense

**Comment by mpcjanssen** [comment]
So it seems to me you want something like

```
function isAction(f)
  return (not isEmpty(f.tags)) or (not isEmpty(f.lists) and not isExcluded(f.lists))
end
```

**Comment by smichel17** [comment]
I used to have a specific list of "lists that are not contexts, basically" that isExcluded checked for and some other stuff, and my contexts were just normal lists instead of using the `@@context` format.

When I was testing, I forgot that I'd changed formats, so I didn't use `@@context`, hence my tests were always false.

The actual bug was the database bug, which reverted my task list to the old format.

**Comment by smichel17** [comment]
If you're curious,

`and not f.lists["excluded"]` was kind of a remnant of before the change to `@@context`. It actually does belong, but just didn't make sense the way I currently had things. I got around to updating my script, here's what I actually want/intend:

```
function isAction(f)
  return hasContext(f.lists)
     and hasProject(f.tags)
     and not f.lists["waiting"]
end

function hasContext(lists)
  local n
  for x in pairs(lists) do
    n=string.find(x, "@")
    if n==1 then return true; end
  end
  return false
end

function hasProject(tags)
  return not isEmpty(tags)
end

function isEmpty(table)
  return next(table) == nil
end
```
