### ISSUE TITLE
hide checkboxes

### ISSUE THREAD

**Issue by mgraham** [mpcjanssen/simpletask-android#526]
First of all, thank you very much for Simpletask - it is a wonderful app and by far the most-used app on my phone.

I apologize if there has been a discussion about this already - I searched but didn't find one.  

There used to be an option to hide the completion checkboxes.  I think the option is gone now.  Is there any hope of getting it back?  My main issue is that I often find that I check a task randomly by accident and then I can't find the task.

(I also got used to the extra screen space for task descriptions, but that's a minor issue)

**Comment by mpcjanssen** [comment]
@mgraham they were removed in b2b01afd546a42e18d85af9128978962f0813ffe it makes the toolbar code easier and more consistent. I will see if I can restore the setting.

**Comment by smichel17** [comment]
@mgraham Would #102 fix your main issue?

**Comment by mgraham** [comment]
@mpcjanssen - thanks for looking into it!

@smichel17 - yup, I think that a single level of undo would probably fix my main issue

**Comment by shayneholmes** [comment]
Wanted to chime in on this: for me, the main issue with the checkboxes being gone is the screen real estate. Between the individual items taking up more space and the fast scroll bar being gone, I spend a lot more time scrubbing through my list than I used to.

**Comment by smichel17** [comment]
I would like to eventually redo the UI to remove the completion checkbox entirely.

**Comment by mpcjanssen** [comment]
@shayneholmes that's Google for you, they deprecate a thing and then give you a new thing with less functionality. I haven't found any good fast scroll for a RecyclerView yet.

**Comment by smichel17** [comment]
@shayneholmes @mgraham would you be willing to chime in on #458?

**Comment by jucor** [comment]
+1 here, as it the solution recommended  by @mpcjanssen to #102.
