### ISSUE TITLE
Hide "use calendar for date entry" on material devices

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#528]
The setting has no effect on devices with material design, so it shouldn't be shown on android 5.0+.

**Comment by mpcjanssen** [comment]
Actually Material still has the spinner calendar style it's just controlled using a different way (using XML) and it can't be controlled from code (thanks Google)

See: https://developer.android.com/reference/android/widget/DatePicker.html#attr_android:datePickerMode

**Comment by mpcjanssen** [comment]
So proper way is probably to use two different XMLs and create a dialog from scratch with the proper XML (and hope that this also works on older devices)
