### ISSUE TITLE
Bottom selection bar actions spread evenly

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#534]
I know this is somewhat harder to do since splitActionBar is deprecated, but it's much nicer when actions are evenly spread.

- Looks nicer, especially when the bottom is near-full
- Easier to hit buttons that are further spread apart

**Comment by smichel17** [comment]
Actually, hold off on this while I'm rethinking this part of the interface...

**Comment by mpcjanssen** [comment]
Also can't be done as far as I am aware. The toolbar for split action bar is not equivalent.

**Comment by smichel17** [comment]
I was looking it up and there are ways, albeit hack-y, of doing it. They include adding xml variable width <Space> elements in between each action and creating our own class that will calculate the width of the screen and place visible elements accordingly.

**Comment by mpcjanssen** [comment]
@smichel17 I am not a fan of fighting the platform like that, it will be very hard to maintain. Just make it the best it can be with standard methods and for the rest blame google 😄

**Comment by smichel17** [comment]
Look at https://material.google.com/components/buttons-floating-action-button.html#transitions

There is a transition that shows a FAB transforming into a toolbar with equally spread actions. I may not know how, but that animation males me think there is an official way to do it.

**Comment by mpcjanssen** [comment]
@smichel17 that's the nice thing about material design. Google shows you all kinds of cool stuff and then you will just have to figure out how to implement it.

**Comment by smichel17** [comment]
We can do this like in the add task screen, with a LinearLayout and buttons instead of a menubar.

**Comment by mpcjanssen** [comment]
LinearLayout wont support overflow of menu items on smaller devices.

**Comment by smichel17** [comment]
How many items will fit on a screen for the smallest devices we'll support? I'm thinking of something along the lines of:

- Edit -> moved to on long press (like any.do)
- Prio
- Due
- Threshold
- List
-Tag -> possibly combined with list
- Overflow -> completion checkbox
  - Complete
  - Uncomplete
- Completion Checkbox

This would leave us with just 5 items, which I think is okay not to have an overflow menu for.

**Comment by smichel17** [comment]
This won't be relevant any more with #128.
