### ISSUE TITLE
On Selection, Hamburger Menu -> Back Arrow

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#535]
Also, next to this arrow we should display the number of selected tasks. This is the paradigm in almost every android application, material or holo.

I *think* the way to do this is, instead of clearing and re-inflating the ActionBar menu upon selection, create a new toolbar that sits on top of the ActionBar, but I want to double-check that.

**Comment by mpcjanssen** [comment]
Is easily solved with updating the title. No need for an overlay.

**Comment by smichel17** [comment]
Is it easier to update all the values than use an overlay? To me it just seems easier (albeit with a *slightly* larger memory footprint) to create and dismiss an overlay than update everything and revert it all to the previous state (particularly with #536). They could share constructors, so there's less code to maintain (although I suppose an updateActionBar function would have the same effect). Maybe that's just my inexperience with the platform talking, though.

**Comment by smichel17** [comment]
I'm also thinking beyond the present, when we start adding in animations. Dismissing the selection ActionBar doesn't require an animation, but there should be an animation for its creation, see Signal / Amaze / gmail app for references.

**Comment by smichel17** [comment]
>next to this arrow we should display the number of selected tasks

Does not currently update when using `select all`.

**Comment by mpcjanssen** [comment]
The selection code is a bit all over the place now. I should probably refactor it.
