### ISSUE TITLE
Update theme

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#536]
Left to do:

- [x] Style popup menus correctly
- [x] Add action menus when filter and nav drawers are open
- [x] Figure out how to move the filter drawer down below the actionbar and don't dim the actionbar when opening it.
  - [x] Implement this

**Comment by mpcjanssen** [comment]
![image](https://cloud.githubusercontent.com/assets/146895/18233805/7d270bf4-72f1-11e6-9975-a4999e3f54b4.png)
![image](https://cloud.githubusercontent.com/assets/146895/18233806/a7b07590-72f1-11e6-936c-bc5a37794e0f.png)
![image](https://cloud.githubusercontent.com/assets/146895/18233808/c9897aea-72f1-11e6-8eee-a7069e20a814.png)

**Comment by smichel17** [comment]
[For Reference](https://material.google.com/style/color.html)

**Comment by smichel17** [comment]
Alright, let's walk through this. there are 5 colors that matter in this app, some of which may/should be the same.

- Background color
- Actionbar color
- FAB color
- Selection color
- Selection toolbar

Each of these must be set for each of the three themes. Some colors are already decided on. I'll edit the top comment so we can track what decisions we want to make as we go.
