### ISSUE TITLE
share without selection

### ISSUE THREAD

**Issue by leoauri** [mpcjanssen/simpletask-android#538]
Currently, without a selection, the share button does nothing
Request: when there is no selection, the share button shares all currently displayed events

**Comment by smichel17** [comment]
How would you feel if the share button were just removed from that place (it would still be available when tasks have been selected). If you want to share your whole list, select one task -> select all -> share.

**Comment by mpcjanssen** [comment]
@leoauri fixed in f6ed27d050c8fbd1be6206e176c31af25693f2f0

@smichel17 the share without selection is very useful to share views of your tasklist (for example `@errands``) I use this quite often.

**Comment by leoauri** [comment]
Top
