### ISSUE TITLE
newbie-friendly issues

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#542]
I'd like to help out more on the code side of things. I've started doing this, but have reached the limit of what I can do in just xml.

At the moment, I'm comfortable making kotlin/java changes that don't require me to have a great understanding of the architecture (ie, those that are mostly contained within a single file). It'd be great if there were a label on issues like that, which are easy to tackle.

**Comment by mpcjanssen** [comment]
Most really easy issues are fixed, but I will add a label for this.

**Comment by mpcjanssen** [comment]
I will tag issues with 'easy' or 'hard' based on my estimate of difficulty.

**Comment by smichel17** [comment]
No need to tag the hard ones, that can be assumed by lack of label. I imagine the remaining easy ones are low priority, which is fine.

**Comment by mpcjanssen** [comment]
hard is a good label too. Some issues are really hard. So there is easy, hard and rest.
