### ISSUE TITLE
Clear selection upon changing the filter

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#543]
Otherwise things get very buggy very quickly. This is the simplest, most intuitive solution. Seems like it should be easy so I'm going to take a pass at this myself first, I'll either make a PR or let you know when I've given up.

**Comment by mpcjanssen** [comment]
Not as easy as it sounds. Couple scenarios. What if you change the filter but the selected tasks still are visible? What if the filter changes without explicit action? For example using time dependent Lua filtering? 

The current behavior of always showing selected tasks is the most predictable and conistent. And it's all wired up to make it a setting.

**Comment by smichel17** [comment]
>What if you change the filter but the selected tasks still are visible?

When you change the filter, the tasks won't be selected any more, so it's just like it would be if you hadn't selected anything before you changed the filter.

>What if the filter changes without explicit action? For example using time dependent Lua filtering?

Which tasks are shown in the filter have changed, but the active filter has not changed, so no change in selection should occur.

>The current behavior of always showing selected tasks is the most predictable and conistent.

I agree. I am not saying we should change that behavior. I am saying that when the user selects a different filter, any selection should be cleared.

>And it's all wired up to make it a setting.

This is what I'm trying to avoid. We already have too many settings.

>Also in this case it's not buggy. Selected means show.

Disagree. If I am viewing my shopping list, and I select a couple items, then switch to my next action filter, and the items from my shopping list still show up, that feels buggy to me.

**Comment by mpcjanssen** [comment]
> >What if you change the filter but the selected tasks still are visible?
> 
> When you change the filter, the tasks won't be selected any more, so it's just like it would be if you hadn't selected anything before you changed the filter.

My point was, I find this a bit unintuitive.

> >What if the filter changes without explicit action? For example using time dependent Lua filtering?
> 
> Which tasks are shown in the filter have changed, but the active filter has not changed, so no change in selection should occur.
> 

Ok I think I agree here.

> >The current behavior of always showing selected tasks is the most predictable and conistent.
> 
> I agree. I am not saying we should change that behavior. I am saying that when the user selects a different filter, any selection should be cleared.

> 
> >And it's all wired up to make it a setting.
> 
> This is what I'm trying to avoid. We already have too many settings.

Totally agree, but it does change the current behavior. I So lets go without settings now and see if people complain 😄 

> >Also in this case it's not buggy. Selected means show.
> 
> Disagree. If I am viewing my shopping list, and I select a couple items, then switch to my next action filter, and the items from my shopping list still show up, that feels buggy to me.

Agreed on second thought

**Comment by mpcjanssen** [comment]
One tricky thing, it's not so clear now when the filter has changed because a user action.

**Comment by smichel17** [comment]
This probably requires a wrapper function, so when you change the filter from the drawer it first clears the selection, then does whatever it's doing right now.

Which means you're probably right about refactoring the selection code.

---
This whole thing is one step towards separating quick filters and saved filters. In that way of thinking, saved filters (views) are more of an object or navigation item, whereas now they just save a certain filter.

I have a couple other small changes that will start to move us towards the new design without actually changing the layout yet.

**Comment by smichel17** [comment]
Worth noting that the current (published) behavior is even weirder, as you can have tasks that are selected but not visible after changing the filter.

**Comment by smichel17** [comment]
From #581:

>@mpcjanssen: Easy way to achieve this is to clear selection when clicking drawer items

>@smichel17: Also the right way, I think.

>@mpcjanssen: Yes agreed
