### ISSUE TITLE
Play Store beta channel

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#551]
How many people currently are using the beta channel? How much work is it to make a new release (on the beta channel)?

**Comment by smichel17** [comment]
When you do new releases, can you make the beta release be based on the `ui-update` branch?

**Comment by mpcjanssen** [comment]
@smichel17 sure, it might accidently go into production though.

**Comment by smichel17** [comment]
I guess you'll just have to be careful, then ;)

If it went into production it would not be the end of the world, but I'd prefer not to move things around on people without offering usability improvements; right now it's just a new coat of paint.
