### ISSUE TITLE
Selection complete/uncomplete to a tri state checkbox

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#554]
Instead of the overflow menu with complete and uncomplete actions, we should have a checkbox in the bottom toolbar. When multiple items are selected it should be a tri-state checkbox for complete all/uncomplete all/start state.

**Comment by mpcjanssen** [comment]
Not sure how this will interact with auto archive when you complete tasks

**Comment by smichel17** [comment]
With auto-archive, you'll never be able to get the intermediary state (or completed state, for that matter). Checking off multiple items will act just like selecting multiple items and using the 'complete' menu item right now. They'll be completed, auto-archived, and de-facto unselected.

**Comment by smichel17** [comment]
@ddisanti @y2kbugger @mpcjanssen @vojtechkral @memeplex @Chriswaterguy @LocutusX @krayon @Alphalpha007 @getthemike @twckr @djibux @shayneholmes @doranism @knitterb @ComedyTomedy @paullemmens 

I've written out how I'm thinking this feature will work below. If you have a short moment, I'd appreciate your feedback. For each of the cases below (especially the tricky case), is this the way you'd expect it to work?

Note: whenever I'm talking about the new Checkbox, I will capitalize it. A lower case checkbox means I'm talking about one of the checkboxes in the list, that already exist. 

### The basic case, included just to be clear on what the feature is

1\. Selecting a subset of your list with mixed checked and unchecked items starts the Checkbox in an indeterminate state:
```
task a
x task b
task c
```
2\.  Tapping the Checkbox once moves it to a checked state and completes the tasks:
```
x task a
x task b
x task c
```
3\. Tapping the Checkbox again moves it to an unchecked state and uncompletes the tasks:
```
task a
task b
task c
```
4\. Tapping the Checkbox a third time returns it to an indeterminate state and the tasks to their state from (1):
```
task a
x task b
task c
```
### The mid-level case. I'm pretty confident in this.

1\. Selecting a subset of your list with mixed checked and unchecked items starts the Checkbox in an indeterminate state:
```
task a
x task b
task c
```
2\. Tapping the checkbox in front of `task c` completes `task c`, doesn't change any other tasks, and keeps the Checkbox in an indeterminate state:
```
task a
x task b
x task c
```
3\.  Tapping the Checkbox once moves it to a checked state and completes the tasks:
```
x task a
x task b
x task c
```
4\. Tapping the Checkbox again moves it to an unchecked state and uncompletes the tasks:
```
task a
task b
task c
```
5\. Tapping the Checkbox a third time returns it to an indeterminate state and the tasks to their state from (2):
```
task a
x task b
task c
```

### The tricky case. This is what I'm particularly interested in.
1\. Selecting a subset of your list with mixed checked and unchecked items starts the Checkbox in an indeterminate state:
```
task a
x task b
task c
```
2\.  Tapping the Checkbox once moves it to a checked state and completes the tasks:
```
x task a
x task b
x task c
```
3\. Tapping the Checkbox again moves it to an unchecked state and uncompletes the tasks:
```
task a
task b
task c
```
4\. Tapping the checkbox in front of `task c` completes `task c`, doesn't change any other tasks, and puts the Checkbox in an indeterminate state:
```
task a
task b
x task c
```
5\.  Tapping the Checkbox once moves it to a checked state and completes the tasks:
```
x task a
x task b
x task c
```
6\. Tapping the Checkbox again moves it to an unchecked state and uncompletes the tasks:
```
task a
task b
task c
```
7\. Tapping the Checkbox a third time returns it to an indeterminate state and the tasks to their state from (4):
```
task a
task b
x task c
```

### A different form of the tricky case.

Same exact problem, but maybe this one is easier to imagine and figure out what you expect.

1\. Selecting a subset of your list with mixed checked and unchecked items starts the Checkbox in an indeterminate state:
```
task a
x task b
task c
```
2\.  Tapping the Checkbox once moves it to a checked state and completes the tasks:
```
x task a
x task b
x task c
```
3\. Tapping the checkbox in front of `task c` uncompletes `task c`, doesn't change any other tasks, and puts the Checkbox in an indeterminate state:
```
x task a
x task b
task c
```
4\.  Tapping the Checkbox once moves it to a checked state and completes the tasks:
```
x task a
x task b
x task c
```
5\. Tapping the Checkbox again moves it to an unchecked state and uncompletes the tasks:
```
task a
task b
task c
```
6\. Tapping the Checkbox a third time returns it to an indeterminate state and the tasks to their state from (3):
```
x task a
x task b
task c
```

**Comment by smichel17** [comment]
The alternative behavior is that any time you select or unselect an item, consider yourself in state 1. After that, no matter how you complete or uncomplete any items, the Checkbox will switch between all tasks complete, none complete, and the original state (unless the original state was all or none, in which case it just switches back and forth). 

Due to technical limitations until #617 is done (which might be a while), I will probably have to go with this alternative behavior for now. The question is whether I should consider this feature to be done at that point or not.

**Comment by y2kbugger** [comment]
For the alternative behavior, can you clarify what you mean by "consider
yourself in state 1" if that means that the new state becomes considered
the new "original state", then I don't see how it is different from the
non-alternative behavior.

**Comment by smichel17** [comment]
@y2kbugger Updated my comment to be much more descriptive.

**Comment by djibux** [comment]
It seems natural enough to me. It returns to the latest state that was manually forced/input.

Mid case you talk about returning to state 2 (which makes sense to me) but your example seems to be state 1…

Le 14 octobre 2016 00:09:14 GMT+02:00, smichel17 <notifications@github.com> a écrit :
>@ddisanti @y2kbugger @mpcjanssen @vojtechkral @memeplex @Chriswaterguy
>@LocutusX @krayon @Alphalpha007 @getthemike @twckr @djibux
>@shayneholmes @doranism @knitterb @ComedyTomedy @paullemmens 
>
>I've written out how I'm thinking this feature will work below. If you
>have a short moment, I'd appreciate your feedback. For each of the
>cases below (especially the tricky case), is this the way you'd expect
>it to work?
>
>Note: whenever I'm talking about the new Checkbox, I will capitalize
>it. A lower case checkbox means I'm talking about one of the checkboxes
>in the list, that already exist. 
>
>### The basic case, included just to be clear on what the feature is
>
>1\. Selecting a subset of your list with mixed checked and unchecked
>items starts the Checkbox in an indeterminate state:
>```
>task a
>x task b
>task c
>```
>2\.  Tapping the Checkbox once moves it to a checked state and
>completes the tasks:
>```
>x task a
>x task b
>x task c
>```
>3\. Tapping the Checkbox again moves it to an unchecked state and
>uncompletes the tasks:
>```
>task a
>task b
>task c
>```
>4\. Tapping the Checkbox a third time returns it to an indeterminate
>state and the tasks to their state from (1):
>```
>task a
>x task b
>task c
>```
>### The mid-level case. I'm pretty confident in this.
>
>1\. Selecting a subset of your list with mixed checked and unchecked
>items starts the Checkbox in an indeterminate state:
>```
>task a
>x task b
>task c
>```
>2\. Tapping the checkbox in front of `task c` completes `task c`,
>doesn't change any other tasks, and keeps the Checkbox in an
>indeterminate state:
>```
>task a
>x task b
>x task c
>```
>3\.  Tapping the Checkbox once moves it to a checked state and
>completes the tasks:
>```
>x task a
>x task b
>x task c
>```
>4\. Tapping the Checkbox again moves it to an unchecked state and
>uncompletes the tasks:
>```
>task a
>task b
>task c
>```
>5\. Tapping the Checkbox a third time returns it to an indeterminate
>state and the tasks to their state from (2):
>```
>task a
>x task b
>task c
>```
>
>### The tricky case. This is what I'm particularly interested in.
>1\. Selecting a subset of your list with mixed checked and unchecked
>items starts the Checkbox in an indeterminate state:
>```
>task a
>x task b
>task c
>```
>2\.  Tapping the Checkbox once moves it to a checked state and
>completes the tasks:
>```
>x task a
>x task b
>x task c
>```
>3\. Tapping the Checkbox again moves it to an unchecked state and
>uncompletes the tasks:
>```
>task a
>task b
>task c
>```
>4\. Tapping the checkbox in front of `task c` completes `task c`,
>doesn't change any other tasks, and puts the Checkbox in an
>indeterminate state:
>```
>task a
>task b
>x task c
>```
>5\.  Tapping the Checkbox once moves it to a checked state and
>completes the tasks:
>```
>x task a
>x task b
>x task c
>```
>6\. Tapping the Checkbox again moves it to an unchecked state and
>uncompletes the tasks:
>```
>task a
>task b
>task c
>```
>7\. Tapping the Checkbox a third time returns it to an indeterminate
>state and the tasks to their state from (4):
>```
>task a
>task b
>x task c
>```
>
>### A different form of the tricky case.
>
>Same exact problem, but maybe this one is easier to imagine and figure
>out what you expect.
>
>1\. Selecting a subset of your list with mixed checked and unchecked
>items starts the Checkbox in an indeterminate state:
>```
>task a
>x task b
>task c
>```
>2\.  Tapping the Checkbox once moves it to a checked state and
>completes the tasks:
>```
>x task a
>x task b
>x task c
>```
>3\. Tapping the checkbox in front of `task c` uncompletes `task c`,
>doesn't change any other tasks, and puts the Checkbox in an
>indeterminate state:
>```
>x task a
>x task b
>task c
>```
>4\.  Tapping the Checkbox once moves it to a checked state and
>completes the tasks:
>```
>x task a
>x task b
>x task c
>```
>5\. Tapping the Checkbox again moves it to an unchecked state and
>uncompletes the tasks:
>```
>task a
>task b
>task c
>```
>6\. Tapping the Checkbox a third time returns it to an indeterminate
>state and the tasks to their state from (3):
>```
>x task a
>x task b
>task c
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mpcjanssen/simpletask-android/issues/554#issuecomment-253653370

-- 
djib

**Comment by smichel17** [comment]
Note that I am not handling any special cases around changing selection, yet. If you add or remove a task from selection, that's the equivalent of starting completely over from step 1.

**Comment by smichel17** [comment]
>Mid case you talk about returning to state 2 (which makes sense to me) but your example seems to be state 1…

@djibux good catch. State 2 is correct. Updated the comment.

**Comment by y2kbugger** [comment]
Just toggling between all and none checked when clicking Checkbox would be sufficient. There is no reason to toggle back to the original state unless the Checkbox was clicked by accident. In this case an accept changes/dismiss changes would work with no guess work on the user's part. I could also see this route have far fewer code paths in the implementation.

**Comment by doranism** [comment]
I would consider returning to the intermediate state of the Checkbox as an undo of completing/uncompleting all selected tasks. Therefore I would expect the function to return to the state of the last change of a single task and the last intermediate state. In other words, the function should restart after a change of a single task. This way only the basic case would be left over.

I mostly hide completed tasks, so I won't have a mixed selection very often. Toggling more than one task would be useful to me but the intermediate state would be a very special case.
