### ISSUE TITLE
Use different package name for non-release builds

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#559]
Recommendation from [source](https://github.com/futurice/android-best-practices#gradle-configuration):

>Use applicationIdSuffix for debug build type to be able to install both debug and release apk on the same device (do this also for custom build types, if you need any). This will be especially valuable later on in the app's lifecycle, after it has been published to the store.

>```
>android {
>    buildTypes {
>        debug {
>            applicationIdSuffix '.debug'
>            versionNameSuffix '-DEBUG'
>        }
>
>        release {
>            // ...
>        }
>    }
>}
>```
>
>Use different icons to distinguish the builds installed on a device—for example with different colors or an overlaid "debug" label. Gradle makes this very easy: with default project structure, simply put debug icon in app/src/debug/res and release icon in app/src/release/res. You could also change app name per build type, as well as versionName (as in the above example).

**Comment by smichel17** [comment]
I'm going to make a MR, just wanted to get the satisfaction of closing my own issues ;)

**Comment by mpcjanssen** [comment]
Ah now I see the point. I don't want any code changes between debug and release, but this is OK and fixes a nuisance I had with this for a while. I am not quite sure how this will interact with intents but for a regular user that wont be an isue.

**Comment by mpcjanssen** [comment]
I also see the provide duplication issue

**Comment by mpcjanssen** [comment]
Last commit fixed the duplication issue..
