### ISSUE TITLE
Pressing the hardware back button always closes the app

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#566]
On my galaxy S4, compiled from 37b13be. It takes the right action, but then closes the app afterwards. This should not happen if the drawers are open, if clearing selection, or if the 'back clears filter' setting is enabled.

I think I know what I did to cause this one.

**Comment by mpcjanssen** [comment]
Check onBackPressed

**Comment by smichel17** [comment]
Yeah. I was calling super.onBackPressed no matter what, instead of only when the app should exit.

**Comment by smichel17** [comment]
Yeah. I knew what the problem was. I had changed it so super.onBackPressed was *always* called, instead of only on the main screen, following the rules of BackClearsFilter.
