### ISSUE TITLE
[Beta] Performance improvements

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#568]
On my galaxy S4, each time the main screen is loaded, there is a delay and the spinner animation is very briefly shown.

**Comment by mpcjanssen** [comment]
Is this cloudless or Dropbox version?

**Comment by smichel17** [comment]
Cloudless. Screencap:

![simpletask_slowness_screencap](https://cloud.githubusercontent.com/assets/6563664/18291361/5eccc922-7455-11e6-93d1-b1bb7e24bc33.gif)

**Comment by smichel17** [comment]
A couple things I noticed:

- Exiting selection mode causes almost no lag  
The spinner is barely visible
- Closing the nav drawer without selecting a filter causes more lag  
The spinner gets around almost a full circle.
- Closing the nav drawer by selecting a filter (pictured above) causes the most lag  
It appears to be exactly twice as much lag as closing the drawer without selecting a filter. You'll notice that the spinner completes almost a full rotation, then it resets as the list changes, then it completes almost another full rotation, starting from the beginning again.

**Comment by smichel17** [comment]
I suspect it's in `onCreateOptionMenu` and helper functions. A couple things I noticed:

- Exiting selection mode causes almost no lag  
The spinner is barely visible
- Closing the nav drawer without selecting a filter causes more lag  
The spinner gets around almost a full circle.
- Closing the nav drawer by selecting a filter (pictured above) causes the most lag  
It appears to be exactly twice as much lag as closing the drawer without selecting a filter. You'll notice that the spinner completes almost a full rotation, then it resets as the list changes, then it completes almost another full rotation, starting from the beginning again.

**Comment by smichel17** [comment]
I suspect it's in `onCreateOptionMenu` and helper functions. A couple things I noticed:

- Exiting selection mode causes almost no lag  
The spinner is barely visible
- Closing the nav drawer without selecting a filter causes more lag  
The spinner gets around almost a full circle.
- Closing the nav drawer by selecting a filter (pictured above) causes the most lag  
It appears to be exactly twice as much lag as closing the drawer without selecting a filter. You'll notice that the spinner completes almost a full rotation, then it resets as the list changes, then it completes almost another full rotation, starting from the beginning again.

**Comment by smichel17** [comment]
I suspect it's in `onCreateOptionMenu` and helper functions. A couple things I noticed:

- Exiting selection mode causes almost no lag  
The spinner is barely visible
- Closing the nav drawer without selecting a filter causes more lag  
The spinner gets around almost a full circle.
- Closing the nav drawer by selecting a filter (pictured above) causes the most lag  
It appears to be exactly twice as much lag as closing the drawer without selecting a filter. You'll notice that the spinner completes almost a full rotation, then it resets as the list changes, then it completes almost another full rotation, starting from the beginning again.

**Comment by smichel17** [comment]
I suspect it's in `onCreateOptionMenu` and helper functions. A couple things I noticed:

- Exiting selection mode causes almost no lag  
The spinner is barely visible
- Closing the nav drawer without selecting a filter causes more lag  
The spinner gets around almost a full circle.
- Closing the nav drawer by selecting a filter (pictured above) causes the most lag  
It appears to be exactly twice as much lag as closing the drawer without selecting a filter. You'll notice that the spinner completes almost a full rotation, then it resets as the list changes, then it completes almost another full rotation, starting from the beginning again.

**Comment by smichel17** [comment]
I suspect it's in `onCreateOptionMenu` and helper functions. A couple things I noticed:

- Exiting selection mode causes almost no lag  
The spinner is barely visible
- Closing the nav drawer without selecting a filter causes more lag  
The spinner gets around almost a full circle.
- Closing the nav drawer by selecting a filter (pictured above) causes the most lag  
It appears to be exactly twice as much lag as closing the drawer without selecting a filter. You'll notice that the spinner completes almost a full rotation, then it resets as the list changes, then it completes almost another full rotation, starting from the beginning again.

**Comment by mpcjanssen** [comment]
@smichel17 how many tasks do you have?

**Comment by smichel17** [comment]
Around 130

**Comment by mpcjanssen** [comment]
I think this specific issues is fixed now.

**Comment by smichel17** [comment]
I think so too. I believe any remaining slowness is due to the performance of my lua scripts. It does still feel slower than it has been in the past, but this may be imagined because I'm paying attention to it right now.
