### ISSUE TITLE
Clear selection on filter change

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#581]
It's jarring to have previously selected tasks still be visible after you change filters from either drawer.

Keeping them selected after changing their lists or tags, even if they'd no longer be shown, is a good thing. Tasks showing up when you don't expect them to is not.

**Comment by mpcjanssen** [comment]
Easy way to achieve this is to clear selection when clicking drawer items

**Comment by smichel17** [comment]
Also the right way, I think.

**Comment by mpcjanssen** [comment]
Yes agreed

**Comment by smichel17** [comment]
Dupe of #543, oops.
