### ISSUE TITLE
Option "Append to list" is inverted.

### ISSUE THREAD

**Issue by ddisanti** [mpcjanssen/simpletask-android#600]
The option **"Append to list"** says _"Insert new tasks at the start of the file instead of the end"_.
It think this is inverted. If this is enabled, new tasks are added at the end of todo.txt. But after turning it off, new tasks are added at the beginning of the file.

**Comment by smichel17** [comment]
Just tested; it's just the tooltip that is incorrect. It should read

**Append to list**  
*Insert new tasks at the end of the file*

**Comment by ddisanti** [comment]
@smichel17  I don't know if I'm totally agree here. See, adding new lines at end of a file is the common way to do it. I think most users take this for granted.  The way you propose, users should activate this option to add new tasks at the end of the file. The logic of this option (or the way it is presented) should be inverted/changed so when activated, then new lines are added at the start of the file, which is the less common way to do it.

**Comment by ddisanti** [comment]
@smichel17 what I'm trying to say is that users will have to activate this option to get what is supposed to be an expected behaviour (new lines at the end)

**Comment by smichel17** [comment]
@ddisanti I was looking at this issue as being about inconsistency, not about functionality, so I made the smallest change to make everything consistent.

I agree that appending is the *expected* behavior. However, I think that prepending is the more *useful* behavior. Therefore, I think the setting should be changed from append to prepend, but should be on by default.

However, it's a pretty low priority for me.
