### ISSUE TITLE
Export/import option for Lua config.

### ISSUE THREAD

**Issue by ddisanti** [mpcjanssen/simpletask-android#601]
For backup/restore purposes. It could be like the one for Saved filters. 
(For some reason, right now, the Share option doesn't allow me to share to a text editor)

**Comment by smichel17** [comment]
Short term: select something -> select all -> copy -> paste to text editor

Long term: rearrange things a bit and a have a single export function for your entire profile (saved filters, lua config, preferences)

**Comment by mpcjanssen** [comment]
@smichel17 not sure if i agree a 100% here. The Lua part is app config. The filters describe views so they are different and should be treated separately.

**Comment by ddisanti** [comment]
> long term vision is to rearrange things a bit and have a single export function for your entire profile (saved filters, lua config, maybe even preferences)

I like this.

> Workaround: select something -> select all -> copy -> paste to text editor

Don't like. The text editor is just for saving the config. Edition is done inside SP.
I sync the whole SP dir and its files to Dropbox, so having Lua config saved to a file in this dir would be cool.

**Comment by smichel17** [comment]
@mpcjanssen On second thought, I agree. Filters are something that should happen within the flow of the app, not in the settings.

That said, I still anticipate the (lua) config interface changing / being moved, and I'm not going to add this until after we either move it or decide that we are not, in fact, going to move it

@ddisanti You're not supposed to like workarounds; they're just temporary solutions to get what you're after until a proper solution can be implemented. Which right now would look like creating a `lua_filters.txt` in the same directory as todo.txt, and manually copying your lua config into it with copy-paste through an android text editor.

**Comment by smichel17** [comment]
Turns out adding an import/export option was really easy, so I just went ahead and did it.

**Comment by mpcjanssen** [comment]
Fixed by #614
