### ISSUE TITLE
Unreadable widget name for dark theme.

### ISSUE THREAD

**Issue by satai** [mpcjanssen/simpletask-android#602]
- set dark wallpaper
- set simpletask widget theme to "Dark"
- create a new widget with name Foo

The "Foo" label is not readable because it's black text on a dark background.

Recommended fix: make the text the same colour as default task text in widget has.

**Comment by smichel17** [comment]
Theming is in the middle of an overhaul, with moderate changes to the front-end but large backend changes. Would you be willing to test if this is still broken? Here's a link to an apk I just built from the latest commit. http://smichel.me/simpletask/20160921_simpletask-android-cloudless-debug.apk

It's a debug version, so it will install as "Simpletask-DEBUG" alongside the version from the play store, with a different icon. You'll then be able to create a Simpletask-DEBUG widget.

I also welcome feedback on the updated theme (although really the light and dark themes have not changed much), with the caveat that landscape mode, drawers, and popup menus are varying degrees of complete.

**Comment by satai** [comment]
The problem persist with this build ;(

**Comment by smichel17** [comment]
I can't reproduce this :confused: . What are all of your settings and what phone/android version are you running? Could you attach a screenshot?

**Comment by satai** [comment]
Nexus 5X, Nougath september patch level, Apex launcher.

Screenshot - three widgets:
https://postimg.org/image/i1ntt7afj/

**Comment by smichel17** [comment]
Yesterday I was unable to reprroduce tthis on a 5X emulator running Android Marsmallow. Today I was able to reproduce it on an emulator running Android Nougat. So of course I thought it has to do with Nougat... but now I can reproduce it on the original device as well. Odd, but whatever; I'll see what I can do.

**Comment by smichel17** [comment]
hmm. And now it's working on the Marshmallow device again.

**Comment by satai** [comment]
Thanks.
I am looking forward the new release ;)

**Comment by satai** [comment]
Looks fixed.

Thank you very much.
