### ISSUE TITLE
Link to "Scripting with Lua" help page is broken for non English locale.

### ISSUE THREAD

**Issue by ddisanti** [mpcjanssen/simpletask-android#606]
From main screen:
_Help -> Scripting with Lua_  shows nothing.
Nevertheless, the one at the end of the Help main page works fine.
_(Obviously, it points to the original English version of the help)_

Of course, I assume that this is so because of the last Lua scripting changes.

Related #483 .

**Comment by smichel17** [comment]
I'll look at this when I tackle #553. @mpcjanssen is the only one who can do #483.

**Comment by mpcjanssen** [comment]
Regardless of adding translations, for non-existing translated assets, there should be a fallback for to en.
