### ISSUE TITLE
Update string resource IDs

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#616]
When I moved "Capitalize tasks" from the preferences to the addtask menu, I renamed the string ID `capitalize_tasks_pref_title` to `menu_capitalize_tasks`. I didn't change the string IDs of any translations. We should fix that.

I'm not sure if the right thing to do is change the ID of the translations, to revert the change I made, or to add both (and use the one with the more accurate ID).

**Comment by mpcjanssen** [comment]
Fixed in f3f2cfd41db91a75360d09d642edff5d96caff2c
