### ISSUE TITLE
Show task text and tasks count in delete confirmation dialog

### ISSUE THREAD

**Issue by roman-yagodin** [mpcjanssen/simpletask-android#629]
Currently, deleting tasks is somewhat unsafe, as there is no hints in the delete confirmation dialog about which task or how many tasks will be deleted. Displaying task text (shorten) for a single task and number of selected tasks in the delete confirmation dialog would be nice thing.

**Comment by smichel17** [comment]
Good idea. I'll see how hard this would be to add; otherwise we'll do it when conformation dialogs are replaced by undo (#102).

**Comment by roman-yagodin** [comment]
With recent UI changes (number of selected tasks at top left corner and in the delete confirmation dialog) it much more safe to delete tasks now. My thanks 👍

**Comment by smichel17** [comment]
:+1:
