### ISSUE TITLE
Notifications on specific time

### ISSUE THREAD

**Issue by roman-yagodin** [mpcjanssen/simpletask-android#630]
Notification system is a major part of GTD, but currently Simpletask is not very strong on this point. It would be nice to have ability to specify notification time directly, along with current ability to setup automatic notifications on threshold / due dates. It would require additional notification tag as well as ability to specify time, like `-n:2016-10-03T13:45`.

**Comment by smichel17** [comment]
Duplicate of #466

**Comment by roman-yagodin** [comment]
Closing this as a duplicate of #466. Thanks @smichel17!
