### ISSUE TITLE
custom sorting via onSort lua callback

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#646]
Takes two tasks, returns true if the first should be sorted above the second and false if the second should be sorted above the first.

Definitely wait on this until after the couple of bigger upcoming changes (database backend, queries).

**Comment by mpcjanssen** [comment]
Should be easy enough to implement. Both tasks will be tables with a similar format as the `onFilter` callback.

**Comment by smichel17** [comment]
Closing because #727 has a more recent description.
