### ISSUE TITLE
Consistency in regards with keyboard input

### ISSUE THREAD

**Issue by mimf** [mpcjanssen/simpletask-android#651]
Sorry for all the "spam", but I really like this app. This issue is a bit of nit-picking, but hopefully it's not taken in a negative way.

I've noticed some problems when adding tasks to a list in different ways:

- When we've a list filtered (let's say "list1") and we add a task, the input will be the following "@list1[cursor_here]"

I suggest adding a space between "@list1" and "[cursor_here]" so it becomes "@list1[space][cursor_here]"

- When we add a task (without lists filtered) and try to add a list (let's say @list1) by using the GUI, the input will be the following: "[cursor_here][space]@list1]"

This is not consistent with the behaviour I mentioned above. I suggest changing it to: "@list1[space][cursor_here]"

Sorry for the nit-picking. Perhaps there's a good reason as to why it is this way and I'm just unware of it.

**Comment by smichel17** [comment]
The reason for the cursor being on the beginning of the line is basically that it's really hard to set the cursor to the right spot, so it's better to do something dumb but consistent than try to be smart and mess it up. See #365, #478 for more info.

I don't think there's a good reason why cursor placement is inconsistent, though.

**Comment by mimf** [comment]
Sorry, I was not aware of it. Should've searched before creating this.

**Comment by smichel17** [comment]
No worries. Keep this open, though; it is a good idea to make the cursor placement consistent at the start of the line and I don't believe there's an open issue for that.

**Comment by smichel17** [comment]
One line code changes are the best :)

**Comment by jflinchbaugh** [comment]
Oh good, thanks for making a fix for this @smichel17. This change in behavior has been driving me crazy since the update. I was seeing it when hitting '+' from a widget of a filtered list.

**Comment by mimf** [comment]
Well... The bad thing is that now that the "@list" is after the prompt, there's always be an extra space in the beggining, because in order to activate the keyboard, I have to click on the input box, and I don't have enough space before the list, so I end up clicking somewhere after the list.

**Comment by smichel17** [comment]
@mimf Two things:

1. The only change I made was to where the cursor is placed, so if there is a space at the beginning now, I believe there also would have been a space at the beginning before.
2. You should not need to click in the input box in order to show the keyboard. Feel free to open an issue about this. It would be useful information to include if there are any times when the keyboard does remain open (eg, when adding a task without lists pre-fillwd, when adding a list/tag to a task in the add task box, etc)
