### ISSUE TITLE
multiselect checkbox checked state not drawn properly upon selection

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#666]
It draws properly when you manually change it, but when you select tasks that are all completed, it draws as a fully filled in box instead of a box with a check mark in it. Still functions correctly.

Edit: this is on my galaxy S4; I haven't tested on emulator yet.

Edit2: I'm also going to use this to track padding issues with the multiselect check box.

**Comment by ddisanti** [comment]
@smichel17 , checkboxes  works fine on my device. Tried the three themes and they are ok. But the check mark almost  vanishes when light theme is applied. My phone has a big screen and,maybe the check mark tends to disappear in smaller screens because of the low contrast between selection and filled checkbox colors.

**Comment by smichel17** [comment]
@ddisanti This bug is for a change that I made recently that has not been pushed to the play store yet, so you can't see it unless you're building from source.

I tried to repro again with mixed results. It seems to be the result the animation not completing; I haven't found consistent repro steps yet.

**Comment by smichel17** [comment]
@ddisanti In the version you're running, there's an overflow menu with complete/uncomplete in the bottom selection bar. In the version I'm running, those are gone and instead there's an indeterminate checkbox in the bottom selection bar that you can use for complete/uncomplete in bulk.

**Comment by smichel17** [comment]
Due to the change removing animations from the completion checkbox, this bug no longer happens.
