### ISSUE TITLE
Delete List Tags That Are No Longer in Use?

### ISSUE THREAD

**Issue by raffylopez** [mpcjanssen/simpletask-android#667]
The filter sidebar still displays @item's that are no longer existing for any task (say all tasks with @grocery have all been deleted). Shouldn't this housekeeping routine be automatic? Nor could I see any command that allows me to do clear out non-existent @item's automatically.

**Comment by smichel17** [comment]
`@list` and `+tag` should only appear in the sidebar if there is a task in your list that contains them. I would guess that you have a task with `h:1` or `t:YYYY-MM-DD` in the future, so your current filter just doesn't show them.

Try going into the filter, to the `OTHER` tab, and make sure that these three are checked:

- [x] `Show completed tasks`
- [x] `Show tasks with threshold date in the future`
- [x] `Show hidden tasks`

**Comment by raffylopez** [comment]
Looks like that was the case :) Found a completed  task tagged with the stubborn @list item. Removing the same task cleared out the @list item on the sidebar automatically. Thank you.

**Comment by smichel17** [comment]
My lists and tags are pretty static right now, but when I used s system where they weren't, I used to archive tasks periodically, for this reason.
