### ISSUE TITLE
Empty Debug log when sharing

### ISSUE THREAD

**Issue by ddisanti** [mpcjanssen/simpletask-android#670]
Cloudless 8.3.0 from Play Store. I can see debug info on screen but when trying to share it to another app, Simpletask sends nothing.

**Comment by smichel17** [comment]
Best guess: The debug log is too large to fit in an intent. We should probably save it to a file instead, then share that.

On the dropbox version we could alternatively allow uploading to an anonymous pastebin or github gist.

**Comment by smichel17** [comment]
And by "best guess" I mean I played around with the code and was able to display the tasks in the app using the exact same method used to generate tasks for sharing, and also confirm that sharing was working for other tasks, so I'm pretty sure about this one.

**Comment by ddisanti** [comment]
If it is of some help, before I was able to share to Inbox mail app. Now it says it can't attach an empty file.

**Comment by smichel17** [comment]
Your log was likely small enough to fit into an intent back then. As you used the app more, more stuff got logged (and/or we added more things to the log) and the log got too big to share via intent.

**Comment by mpcjanssen** [comment]
This was a bug because of the new content provider names. Fixed by eed84d58797c4accb7dc749c348d1cdcf33a16b4

**Comment by smichel17** [comment]
s/pretty sure/wrong/

**Comment by mpcjanssen** [comment]
@ddisanti this should be fixed in 8.3.1 which is now live. Can you confirm?

**Comment by ddisanti** [comment]
@mpcjanssen it works fine  now.
