### ISSUE TITLE
New Task Widget

### ISSUE THREAD

**Issue by y2kbugger** [mpcjanssen/simpletask-android#680]
Actual behavior
#############
New Task Widget  activates exciting the the selection from last time app was open.

Expected behavior
#############
New Task Widget activates  a new, blank, note.

Reproduce
#############
Select a few tasks
Return to Android launcher
Tap new Task Widget.

**Comment by smichel17** [comment]
Fixed in master. There's a (closed) duplicate issue of this somewhere that I can't find on mobile.

**Comment by smichel17** [comment]
If you want to build and test master, simpletask debug can now be installed alongside release. Or you can grab an apk that I built, [here](http://smichel.me/simpletask/20161028-simpletask-debug.apk).

This is actually what I do now, and I mostly just use debug, so I can get the latest additions more quickly :P

**Comment by y2kbugger** [comment]
Can confirm that this is fixed.
