### ISSUE TITLE
Installation failure on second profile?

### ISSUE THREAD

**Issue by celmi** [mpcjanssen/simpletask-android#683]
On my Sony Xperia I'm having two user profiles, one for work and one for private life.

 I'm experiencing the following problem: installing and connecting to drop box worked fine on my profile B (my work-profile, connecting to my dropbox account from work). But repeating the process on profile A (private profile) fails. 

After falling in love with simpletask I wanted to use it for my private life / private profile A as well, but with separate / private content. Thus I installed the app on profile A and tried to connect to my private dropbox account. I got as far as entering the drop box credentials in the mobile browser and granting the simpletask the nececcary privileges. But simpletask somehow doesn't proceed from there, and keeps displaying me the same startup-message with two buttons to log on to drop-box. I've been repeating this procedure several times now, restarting mobile phone etc. , all unsuccessful. I am using the standalone cloudless app now, on this profile...

I suppose my problem is related to having several profiles on the phone?

**Comment by mpcjanssen** [comment]
@celmi it is very likely caused by trying to connect to Dropbox from different profiles.  This is all handled by the Dropbox library.

1. Can you connect from both profiles using the official dropbox app?
2. Can you send some logging?

If 1. also fails, there is probably not much I can do about it.

**Comment by mpcjanssen** [comment]
Seems a general dropbox issue with multiple profiles. No feedback to suggest otherwise.
