### ISSUE TITLE
"Set threshold date(s)" button outside the screen in small displays

### ISSUE THREAD

**Issue by participante0** [mpcjanssen/simpletask-android#686]
Version:  8.3.1 from F-Droid.

I can't see it on a 480 x 800 display. There is an unnecessary gap between the buttons `check mark` and `Update` when selecting a task.

**Comment by smichel17** [comment]
The check mark button is added as a normal menu item just like everything else; I'm not sure why that gap exists.

When I tested on a virtual Nexus S, `Set threshold date` was squished to the side but not pushed completely off. I'll see if I can find time to fix this in the next few days.
