### ISSUE TITLE
Code style guide

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#688]
@mpcjanssen This would probably be a good thing to have documented somewhere. If you let me know where you'd like to put these ([filename].md in the top level?), I'll make a PR adding the rules that the xml follows as of #643.

I'm personally not a fan of strict style guidelines -- while consistency is important, sometimes formatting code in a nonstandard way can make it easier to read, and I don't like being restricted from using my best judgment. So, I suggest we start really small and add things as we go.

**Comment by mpcjanssen** [comment]
I don't think the effort to set up a style guideline gives enough benefits now. I agree with the main one though. Code should be written to be read, so it should be readable.

**Comment by smichel17** [comment]
Not that important.
