### ISSUE TITLE
"rec:" entries not recurring upon completion

### ISSUE THREAD

**Issue by boabawhales** [mpcjanssen/simpletask-android#689]
I have a task "update phone apps @home rec:+1w t:2016-11-17" that failed to recur when I completed it today. (I checked future tasks and the entry for next week wasn't there.) After undoing the task and redoing it, the next recurrence was added. (Error seems inconsistent.)

I'm syncing with Dropbox & *not* auto archiving. I'm not sure what other debugging information you want me to collect/provide. Let me know.

**Comment by boabawhales** [comment]
Same thing happened to my "18:00 log lunch in food log rec:+1d t:2016-11-17 due:2016-11-17" today. Not seeing a pattern yet.

**Comment by mpcjanssen** [comment]
Can you share the log? From Settings->Other->Debug log?

**Comment by boabawhales** [comment]
Here's the debug log:

[Simpletask dropbox v8.3.1 (3053) log.txt](https://github.com/mpcjanssen/simpletask-android/files/600016/Simpletask.dropbox.v8.3.1.3053.log.txt)

**Comment by boabawhales** [comment]
For the past few days I've been diligently checking to make sure my recurring items have been added everytime I completed a task. However, 2 tasks disappeared for me yesterday & today. I have verified that both tasks have properly "recurred" upon completion, but checking later showed the tasks disappearing.

When checking the todo.txt history in Dropbox, I noticed that the 2 recurrences that disappeared never made it into any of the versions. Is there a possibility that Dropbox saw those lines as "duplicates" when considering a new version of the file?

Here's the debug log: [Simpletask dropbox v8.3.1 (3053) log.txt](https://github.com/mpcjanssen/simpletask-android/files/605186/Simpletask.dropbox.v8.3.1.3053.log.txt)

**Comment by boabawhales** [comment]
I just completed a task '(B) 23:00 log dinner in food log rec:+1d t:2016-11-21 due:2016-11-21` & Simpletask shows the recurring task `(B) 23:00 log dinner in food log rec:+1d t:2016-11-22 due:2016-11-22`.

However, when checking the "todo.txt" on Dropbox, `x 2016-11-21 23:00 log dinner in food logrec:+1d t:2016-11-21 due:2016-11-21` is there, *but* `(B) 23:00 log dinner in food log rec:+1d t:2016-11-22 due:2016-11-22` is nowhere to be seen.

Upon refresh `(B) 23:00 log dinner in food log rec:+1d t:2016-11-22 due:2016-11-22` disappears from Simpletask, without any error or notification.

Here's the debug log: [Simpletask dropbox v8.3.1 (3053) log.txt](https://github.com/mpcjanssen/simpletask-android/files/605314/Simpletask.dropbox.v8.3.1.3053.log.txt)

**Comment by smichel17** [comment]
I wonder if this bug only affects recurring tasks, or whether there are other circumstances that would cause Dropbox to become out of sync.

**Comment by boabawhales** [comment]
I hope not :p I'm putting a lot of trust in Simpletask to be reliable for keeping track of what I need to do :)

So far I've yet to notice this happening on non-recurring tasks. (Which doesn't mean it's not happening.) If I notice sometime I'll post here.

**Comment by smichel17** [comment]
>I hope not :p I'm putting a lot of trust in Simpletask to be reliable for keeping track of what I need to do :)

Me too! Although I use the cloudless version and then sync the file with owncloud.

**Comment by boabawhales** [comment]
I've noticed pretty consistently that most recurrences get out of sync: the "done" task gets into Dropbox, but the recurrence doesn't.

One way I've found that effectively force the sync is to randomly edited & save any task (change priority, etc.) after completed tasks that recur.

**Comment by smichel17** [comment]
Hypothesis: ST is making two updates very quickly and Dropbox is not picking up on the second update (adding the recurring task). Then later the local version is somehow overridden by the Dropbox version.

Basis for hypothesis: I use cloudless. I sync my todo.txt file via owncloud. If I make a change while the file is uploading, owncloud thinks there is a file conflict. It's possible Dropbox does the same but handles it differently (owncloud asks you which version to keep).

**Comment by mpcjanssen** [comment]
adding recurring tasks and completing should happen in one go. I hope they are also in the same db transaction.

**Comment by fleapower** [comment]
Any progress on this bug?  I just lost a recurring task from last week. BTW, I'm using Resilio Sync with ST Cloudless.

**Comment by fleapower** [comment]
Just happened again, today.  I checked off a recurring item last night.  It looked good when I did it, but I checked this morning for my upcoming tasks and it was missing.

**Comment by smichel17** [comment]
I don't know when I'll have time to look at this as I have a bunch of other things on my plate. As a workaround if you'd like, I can provide you with a debug build of an older version that doesn't have the bug (debug builds can be installed alongside release).

**Comment by fleapower** [comment]
Sure.  Thanks.


*--- This account can receive encrypted emails via OpenPGP
<https://www.mailvelope.com/>or Virtru <https://www.virtru.com/> ---*

**Comment by smichel17** [comment]
Anyone know which version was the last in which this bug didn't exist?

**Comment by mpcjanssen** [comment]
@fleapower unfortunately I do not have a lot of time to work on ST at the moment. I will get to this if I can though.
