### ISSUE TITLE
tag sorting different in selection mode vs. editing mode and left drawer

### ISSUE THREAD

**Issue by aurisnoctis** [mpcjanssen/simpletask-android#699]
When selecting a task and the pressing the tag button, capitalized tags are sorted before other tags. (This is independent of checked and not checked tags).

In the left drawer and in editing mode, capitalization of tags is ignored. Capitalized tags appear alphabetically among non-capitalized tags.

**Comment by smichel17** [comment]
Possible duplicate of #239

**Comment by aurisnoctis** [comment]
Accepted as duplicate if lists (@, issue #239 ) and tags (+, this issue) are handled the same way.

**Comment by smichel17** [comment]
I'm pretty sure they are, but if not it would still be the same problem / same fix applied in two places, so imo it'd be better just to make a note in that issue that it affects tags, too.

**Comment by aurisnoctis** [comment]
Will do that!
