### ISSUE TITLE
Can't change sort

### ISSUE THREAD

**Issue by Dynalt-glj1** [mpcjanssen/simpletask-android#700]
Older versions worked fine.
Had to get new phone and now all items sort as "none" and the sort settings have no impact.

**Comment by Dynalt-glj1** [comment]
I have the same behavior on a Galaxy Tab 5.
Not all tasks show up as "none". Some sort into a few projects/ I thought it was related to having multiple projects for a task, but that isn't consistent. Tasks with multiple projects show up in both kinds of list.
It is my favorite todo.txt tool and I would like it back.

[todo.txt](https://github.com/mpcjanssen/simpletask-android/files/667778/todo.txt)

**Comment by Dynalt-glj1** [comment]
Didn't mean to close this. It is still very much open.

**Comment by smichel17** [comment]
Do you have `function onGroup(t, f, e)` defined anywhere in your saved filter's `SCRIPT` tab, *or* in your lua global config?

**Comment by smichel17** [comment]
Could you also share your sort order (the sort tab)? A screenshot is probably the easiest way, or you could type it using /\ and \/ to indicate direction, or something like that.

**Comment by Dynalt-glj1** [comment]
![screenshot_20161221-174108](https://cloud.githubusercontent.com/assets/5554489/21412779/98c1b408-c7a7-11e6-9378-f6bea1a7fe08.png)

I hope that worked.

I have tried several different settings with no change.

I haven't modified any lua scripts or the lua config.

**Comment by smichel17** [comment]
Thanks. I will try to reproduce this tomorrow morning.

**Comment by smichel17** [comment]
@Dynalt-glj1 Sorry for the delay. I finally got around to looking into this and I'm not able to reproduce it. When I try sorting that way with that list, I get these headers:

NONE (233)
99-CENT-STORE (3)
BEFORE-CLEANUP (1)
BUY (15)
COSTCO (1)
VIDEO (1)
WALMART (3)

---
Try this:

- Download and install this: http://smichel.me/simpletask/20170102_simpletask-android-cloudless-debug.apk
  - It's the exact version I was testing with. It's a debug version so it'll install alongside the release version on your phone.
- Download the todo.txt file you posted above in this thread
- Open it, and use the `Open todo file` option in the overflow menu to select it
- Open the filter and the `SORT` tab, and change it to be like the screenshot above
- See if you get the same result that I did.

If you **do** get the same result, great! You can use the debug version for the time being, and when the next release comes out things should work. In the meantime, could you try setting up the debug version with the same settings (eg, `Sort case sensitive`) as the main app, and see if it still works?

If you **don't** get the same result, can you share which version of android you're running?

**Comment by Dynalt-glj1** [comment]
That is the result I get from the version I have running on the Galaxy S7. Android 6.0.1.
The Samsung Tab 5 is running Android 4.4.2. It sorts the same way,
The problem is that all of the 233 sorted as None have projects, generally 2 or more.
Previous versions of SimpleTaxk sorted correctly. (BTW, the original todo.txt program sorts a task with multiple projects into all the projects.
If you get the same results from the debug version of SimpleTask, there doesn't seem to be much point in my running it, is there?

**Comment by smichel17** [comment]
I think the problem here might just be vocab. Simpletask uses the terms `@list` and `+tag`, which correspond to `@context` and `+project`. In the screenshot you're sorting by list (ie, context), not project.

**Comment by Dynalt-glj1** [comment]
That is indeed the problem. Sorting by tag gets the desired results. Thanks.

**Comment by smichel17** [comment]
There's a setting to use todo.txt terms under `other`, if you prefer them.
