### ISSUE TITLE
Shortcuts to saved filters are too persistent

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#701]
Steps to reproduce:

- Create a desktop shortcut to saved filter X
- Open app via this shortcut
- Select saved filter Y via the saved filter drawer
- Add a new task

Expected result: filter Y is active
Actual result: filter X is active

I need to double check that this bug is still present on master, as I'm reporting it from a debug build a few commits after 8.3.0.

**Comment by ddisanti** [comment]
I've just find this bug. Today I started using two desktop shortcuts to two different saved filters and I can confirm it is present on Cloudless 9.0.0.

**Comment by ghubby123** [comment]
I am unable to replicate this issue on Cloudless 9.0.0

**Comment by mpcjanssen** [comment]
I think this has been fixed as a side effect of the fix for #728.

**Comment by smichel17** [comment]
Confirmed fixed in 9.0.1
