### ISSUE TITLE
Bug: No list or tag in one scenario

### ISSUE THREAD

**Issue by Vijayanth-Reddy-K** [mpcjanssen/simpletask-android#708]
Steps to reproduce:

Assume there is an existing list `@Work`.

1. Create a new task or edit an existing task.
2. Choose the list or tag button from the bottom. In the text field, enter "Work" (without quotes) instead of selecting it from the list.

**Expected behavior**: `@Work` gets added to the task.
**What actually happens**: Nothing gets added but cursor gets re-positioned to the beginning of the line.

(Note that if, instead of typing in one of the existing lists or tags, a new list or tag respectively is typed in, it gets added.)

**Comment by mpcjanssen** [comment]
Same behavior from the main screen

**Comment by mpcjanssen** [comment]
Caused by the fact that the tag is added because of the text and then removed again because the existing tag checkbox is not set.
