### ISSUE TITLE
Consecutive add task screens when sharing to ST with "edit shared tasks" enabled

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#716]
Repro steps:

1. Make sure "edit shared tasks" is enabled in Settings > Features
2. Edit a task in ST. Let's call this task 1
3. Close the app with the home button
4. Share something to simpletask. Let's assume it's one line and call it task 2
  - Add/edit task screen opens, showing both task 1 and task 2 (this is correct behavior)
5. Save or discard

Expected result: Add task screen closes, showing home screen
Actual result: Add task screen closes, showing another add task screen, editing only task 1.

**Comment by smichel17** [comment]
The solution to this is to set `FLAG_ACTIVITY_SINGLE_TOP` as a flag on the intent used to launch the addtask activity [(source)](https://developer.android.com/reference/android/content/Intent.html#FLAG_ACTIVITY_SINGLE_TOP). I'm not 100% sure how this works, but I think it causes the intent to be delivered to the `onNewIntent` function if the activity is already running, so we'll need to override that with the code for adding the shared task to the existing screen.

**Comment by smichel17** [comment]
See https://github.com/raatmarien/red-moon/blob/master/app/src/main/java/com/jmstudios/redmoon/activity/ShortcutCreationActivity.java and https://github.com/raatmarien/red-moon/blob/master/app/src/main/java/com/jmstudios/redmoon/activity/ShadesActivity.java for a working example

**Comment by mpcjanssen** [comment]
See #721.
