### ISSUE TITLE
Google Drive vs Dropbox

### ISSUE THREAD

**Issue by sttrebo** [mpcjanssen/simpletask-android#718]
Any chance on connecting this with Google Drive like you do with Dropbox?

**Comment by mpcjanssen** [comment]
Only if you use the cloudless release and use something like foldersync to sync the todo.txt file from your phone. Besides dropbox no other storage providers are planned at the moment.

**Comment by mpcjanssen** [comment]
Also see #617 for a possible future plugin architecture where writing and distributing different storage plugins becomes easier.

**Comment by smichel17** [comment]
Also see #470
