### ISSUE TITLE
Missing strings for translation in Weblate site

### ISSUE THREAD

**Issue by ddisanti** [mpcjanssen/simpletask-android#723]
These strings are missing for translation at [Weblate site](https://hosted.weblate.org/engage/simpletask/):

- Appearance. Task text ellipsizing  options:
 1. `None: Very long task text` 
 2. `Start: ...task text`
 3. `Middle: Very... text`
 4. `End: Very long...`
 5. ` Marquee: Very long ta`

- Quick Filter: Tag/List header: 
 1. `INVERTED`

- Filter Tab headers ( `LIST` and `TAG` are OK):
 1. `PRIO`
 2. `OTHER`
 3. `SORT`
 4. `SCRIPT`

- Script Tab:
 1. `Script from file`
 2. `Use script`
 3. `TEST`
 4. `Test task`
 5. `Script`
 6. `True, task will be shown`
 7. `False, task will not be shown`

- Lua config:
 1. `Lua config imported` toast.
 2. Also **wrong tooltip** on long press on Import/export button:  
`Import/export filters`

- Action pop up menu (long press on a task list item):
 1. ~~`Action`~~
 2. `Call: `
 3. `SMS: `

- Saved Filters:
 1. `Filters exported` tooltip

**Comment by luisfsr** [comment]
Indeed. In Brazilian Portuguese those strings weren't translated as well in version 9.0.0.

**Comment by smichel17** [comment]
Looked into this. The reason is that the strings are hard coded. We have this:

In `donottranslate.xml`
```
    <string-array name="task_text_ellipsizing">
        <item>None: Very long task text</item>
        <item>Start: ...task text</item>
        <item>Middle: Very... text</item>
        <item>End: Very long...</item>
        <item>Marquee: Very long ta</item>
</string-array>
```
What we need is this (I just fixed it for the first entry to demonstrate)
In `donottranslate.xml`:
```
    <string-array name="task_text_ellipsizing">
        <item>@string/task_text_ellipsizing__very_long_task_text</item>
        <item>Start: ...task text</item>
        <item>Middle: Very... text</item>
        <item>End: Very long...</item>
        <item>Marquee: Very long ta</item>
</string-array>
```
In `strings.xml`
```
<string name="task_text_ellipsizing__very_long_task_text">None: Very long task text</string>
```
The string name doesn't need to be `task_text_ellipsizing__very_long_task_text`, it just needs to make sense and be consistent.
