### ISSUE TITLE
context @ not recognised without a space

### ISSUE THREAD

**Issue by vj777** [mpcjanssen/simpletask-android#736]
If the context @ does not have a preceeding space, the context is not recognised. 
To recreate, create task with a context. 
Delete some characters at the end, including the whitespace before the @ and save task.
Task list has task under "None".

If you edit the task and add whitespace before the '@' it is then listed & filtered correctly.

**Comment by smichel17** [comment]
Could you include an example task that demonstrates this?

**Comment by vj777** [comment]
This is a test@work

**Comment by vj777** [comment]
using simple task v9.0.1.

**Comment by smichel17** [comment]
This is working as intended, and I doubt we'll add functionality to support it, for two reasons:

- You couldn't include an email without adding a context
- [The todo.txt spec](https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format#rule-3-contexts-and-projects-may-appear-anywhere-in-the-line-after-priorityprepended-date) says that projects & contexts are preceded by a space

**Comment by vj777** [comment]
Fair enough.
Could a luascript be created to show any such malformed tasks? It's not always easy to see the cursor position on a phone - Its easy to inadvertently position it in the wrong spot and delete the space.  
Manually running a filter would be nice...

**Comment by smichel17** [comment]
Definitely! I did some quick searching and found pages with relevant info:

- [Strings](http://www.lua.org/pil/2.4.html)
- [The string library](http://www.lua.org/pil/20.html)
- [Patterns](http://www.lua.org/pil/20.2.html)
  - I didn't check this, but I *think* the pattern you'll want is `@.+%s`, which *should* match an `@`, followed by one or more characters, followed by a space. Note that this won't work if the context is at the end of the line unless there's a trailing space.
- [The string library section of the lua reference manual](http://www.lua.org/manual/5.1/manual.html#5.4)
  - Specifically, I think you'll want `string.find`

Writing a comprehensive script might be a bit tricky, but a simple one that just finds one of these per task should be reasonable.

**Comment by mpcjanssen** [comment]
@vj777 finding tasks like this in Lua is definitely possible. See @smichel17 hints. Besides that, this behavior is as defined and expected.
