### ISSUE TITLE
When creating a new task, filtered tag is prefilled even when using inverted tag

### ISSUE THREAD

**Issue by djibux** [mpcjanssen/simpletask-android#739]
I just ran into a weird behaviour.
* I am using a tag called "+Next" that identifies next actions.
* I often use inverted tag to filter tasks not tagged as "+Next"
* When creating a new task from that filtered view, it prefills it with the tag "+Next" (which makes sense when filtering a single tag… but not when using an inverted filter!)

**Comment by mpcjanssen** [comment]
Agreed, will look into this.

**Comment by ghubby123** [comment]
I do not see this behavior in Simpletask Cloudless 9.0.7

**Comment by djibux** [comment]
I use the same version (from F-Droid).
Here are the steps to reproduce:

1. Create at least one task with a tag
2. Filter that tag
3. Invert filter clicking on `TAG` in the left sidebar
4. Create a new task

The task will be prefilled with the tag you selected (and excluded from view).

**Comment by ghubby123** [comment]
I do see the same behavior following the steps listed above.

**Comment by mpcjanssen** [comment]
Yes this is a bug which does need to be fixed. This should not be hard.

**Comment by mpcjanssen** [comment]
Fixed in PR
