### ISSUE TITLE
Build broken for AS 2.3 and gradle plugin 2.3

### ISSUE THREAD

**Issue by ggbc** [mpcjanssen/simpletask-android#742]
After I updated to Android Studio and Gradle Plugin both 2.3 build broke with message: 

"22:22 Gradle sync failed: A problem occurred configuring project ':app'. Consult IDE log for more details (Help | Show Log)"

And the log says:

"...
Caused by: kotlin.KotlinNullPointerException
	at org.jetbrains.dokka.gradle.DokkaAndroidPlugin.collectClasspath(mainAndroid.kt:45)
..."

Verifying the classpath for Dokka on jetbrains.org I saw that it shouldn't have the "-android-" in its name and the correct was 

`classpath "org.jetbrains.dokka:dokka-gradle-plugin:${dokka_version}"`

**Comment by ggbc** [comment]
Mark
How can I contribute for real. I mean. Hour can I push commits into GitHub?

I'm new to git and from what I understand I should try to make a push
request and then commit my changes into a new branch so that somebody could
merge them. Right?

Regards

Em 23/03/2017 5:54 AM, "Mark Janssen" <notifications@github.com> escreveu:

Closed #742 <https://github.com/mpcjanssen/simpletask-android/issues/742>
via 04cf614
<https://github.com/mpcjanssen/simpletask-android/commit/04cf61495c28481d08941165917b63fd5a69f380>
.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mpcjanssen/simpletask-android/issues/742#event-1011988607>,
or mute the thread

**Comment by smichel17** [comment]
@ggbc Yep! First, fork the repo (upper right corner). Then, clone the fork you just created. Make your changes, commit them, and push to the fork (just do it on master; don't worry about branches yet).

Then use the github web interface to make a pull request. "Pull request" and "Merge request" mean the same thing: "I (@ggbc) want you (@mpcjanssen) to *pull* my changes and *merge* them into your repo."

**Comment by ggbc** [comment]
Thank you !

Em 23/03/2017 8:02 AM, "smichel17" <notifications@github.com> escreveu:
