### ISSUE TITLE
Text after a space in context name is treated as text

### ISSUE THREAD

**Issue by nvllsvm** [mpcjanssen/simpletask-android#750]
When typing a new context or project name, anything after the first space will be treated as regular text in the task.

For example, typing "new1 new2" on the context dialog will result in a task with the text "@new1 new2". 

IMO - new contexts/projects should be created for each word delimited by spaces. "new1 new2" should become "@new1 @new2"

![screenshot_20170507-161951](https://cloud.githubusercontent.com/assets/6550543/25784870/845e15ea-3342-11e7-824e-111ac3e4a5e4.png)
![screenshot_20170507-162000](https://cloud.githubusercontent.com/assets/6550543/25784872/877e222e-3342-11e7-8829-a67f359ccda9.png)

**App:** Simpletask 9.0.2 from F-Droid
**Device:** OnePlus 3T
**Android:** 7.1.2
**ROM:** SultanXDA's LineageOS 14.1-20170430

**Comment by mpcjanssen** [comment]
Considering lists (contexts) and tags (projects) can't have spaces anyway, this makes sense. It's an easy change.
