### ISSUE TITLE
Can't save sort order

### ISSUE THREAD

**Issue by polsvoice** [mpcjanssen/simpletask-android#755]
I'm running Cloudless, and it won't save my filter settings. Here's what I'm doing:

1. Tap on filter icon.
2. Tap on Sort.
3. Drag and drop categories to change the sort order.
4. Tap the check mark at the top of the screen.

It reorders my tasks, but once I've closed and re-opened the app, the sort order is back to what it was before.

**Comment by mpcjanssen** [comment]
How do you reopen the app? From the launcher icon or from a widget?

**Comment by polsvoice** [comment]
Widget.

**Comment by smichel17** [comment]
When you open the app via widget, it shows the list as it is saved in the widget; I can't imagine changing this.

If you want to persist a different sorting, I'd create a saved filter that uses the same filter options but a different sort order, so you can quickly switch between them from the right drawer. Then, if you want to access that saved filter from your home screen, you can add a shortcut to your home screen (long press on the saved filter in the drawer).

Or, if you don't mind changing the sort in the widget, you could update that :)

**Comment by polsvoice** [comment]
@smichel17 Yeah, I just changed the sort order in the widget by clicking on the gear. I didn't realize the widget had separate settings. Thanks!

**Comment by mpcjanssen** [comment]
Works as designed.
