### ISSUE TITLE
Lua scripting example incorrect

### ISSUE THREAD

**Issue by jacobScottAllen** [mpcjanssen/simpletask-android#761]
The following example in the "Scripting with Lua" page is incorrect:

Show all tasks with the @errands tag:

    function onFilter(t,f,e)
          return f.tags["@errands"]
    end

This is incorrect for two reasons:

1. @errands is a list, not a tag
2. the @ symbol is not needed in the code

**Comment by mpcjanssen** [comment]
Thanks for reporting, fixed.
