### ISSUE TITLE
native Nextcloud support

### ISSUE THREAD

**Issue by schiessle** [mpcjanssen/simpletask-android#764]
Would be great to have native Nextcloud support. At the moment I use the cloudless version and sync the todo.txt with a additional app. I think it would be great if this would work out of the box with more cloud storages than just Dropbox.

**Comment by smichel17** [comment]
See #617

**Comment by mlncn** [comment]
Hi @schiessle, which app are you using to sync todo.txt to the Nextcloud directory?  That's the workaround i'm trying to implement.  Thanks!

**Comment by mpcjanssen** [comment]
@mlncn I use FolderSync webdav support for direct nextcloud sync and it works fine https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.full&hl=en

**Comment by smichel17** [comment]
@mlncn I use the Nextcloud app.

1. Upload your todo.txt file to nextcloud
2. Open the nextcloud app and find the todo.txt file.
  - Select it and set it as both a favorite and available offline.
3. Open simpletask, select `Open todo file` from the menu, and browse to the directory `/storage/emulated/0/Android/data/com.nextcloud.client/files/nextcloud/`, then find and select your todo.txt file.

**Comment by mlncn** [comment]
Thanks both!  I'm still on ownCloud (i think my [internet service membership organization](https://mayfirst.org/) will be moving soon) so that's perhaps why the direct approach didn't work, but i have it working with FolderSync now (though having copied the files already, FolderSync has no way of resolving a conflict i introduced just before trying to sync, but deleting the files fixed that...)

**Comment by rodrigoaguilera** [comment]
The problem I'm having with the setup of nextcloud app + simpletask is that if I use only my phone is ok but I can't edit tasks on other devices because that creates conflicts.

I opened this issue to solve part of the problem
https://github.com/mpcjanssen/simpletask-android/issues/735

The other would be that the interval that nextcloud checks for an updated todo.txt is too long and that also generates conflicts because I'm working on an outdated todo.txt file.

**Comment by smichel17** [comment]
> The other would be that the interval that nextcloud checks for an updated todo.txt is too long and that also generates conflicts because I'm working on an outdated todo.txt file.

I also have this problem. There's a couple ways to solve it:

- The nextcloud app could handle this more intelligently. If it uploads something *from this device*, and then that same file is changed on this device, it shouldn't find a conflict.
- We could batch changes and delay writing to the todo file for a few seconds. I thought I'd created an issue proposing to do this, but apparently not.

**Comment by daniellandau** [comment]
I made native Nextcloud integration (https://github.com/mpcjanssen/simpletask-android/pull/769) and it's now in a branch https://github.com/mpcjanssen/simpletask-android/tree/nextcloud. I recommend merging master to the branch before building, as there's a fix for syncing when using the "add task" widget in master.

**Comment by mpcjanssen** [comment]
I just remerged master so Nextcloud branch should be up to date

**Comment by mpcjanssen** [comment]
Will merge nextcloud branch into master. I usually build specific flavors anyway.

**Comment by schiessle** [comment]
Will it than appear as a special build in f-droid and Google play?

**Comment by smichel17** [comment]
> Will it than appear as a special build in f-droid and Google play?

Not automatically. On f-droid, you'd need to make a PR requesting inclusion (as a separate application, I believe); on Google Play @mpcjanssen would need to release a new application.

^That's why @mpcjanssen was hesitant to merge your PR; releasing flavors like that doesn't scale very well.

**Comment by mpcjanssen** [comment]
It will just make it easier to build your own. No plans for addibg it to fdroid at all.

**Comment by gogolo2** [comment]
I have created a tasker solution. Tasker listens to file changes and then advises folder sync (via plugin) to sync. Also when ST starts a sync is done.

**Comment by smichel17** [comment]
It looks like the Nextcloud app also recently started to handle this more intelligently and no longer generates conflicts in most cases when you're editing quickly.

**Comment by mpcjanssen** [comment]
Nextcloud version available on Playstore.

**Comment by varac** [comment]
https://play.google.com/store/apps/details?id=nl.mpcjanssen.simpletask.nextcloud&hl=en

**Comment by acbg** [comment]
Will this version be added to fdroid?

**Comment by mpcjanssen** [comment]
@acbg no plans for that as of now. You can always download the latest development version from: https://mpcjanssen.nl/artifacts/

**Comment by hlovdal** [comment]
Update to step 3 in [this comment](https://github.com/mpcjanssen/simpletask-android/issues/764#issuecomment-312451789): the default storage location for the nextcloud client is no longer 

`/storage/emulated/0/Android/data/com.nextcloud.client/files/nextcloud/`

but

`/storage/emulated/0/Android/media/com.nextcloud.client/your_username@your_server.example.com%3A8080`

**Comment by smichel17** [comment]
That folder exists on my device, but is empty (nextcloud still uses the old one). Maybe it only uses the new one for fresh installs?
