### ISSUE TITLE
[feature request] filter: due today

### ISSUE THREAD

**Issue by symbolisch1234** [mpcjanssen/simpletask-android#780]
a "filter: due today" would be very useful, especially for the widget.

apologies if this exists already, but i cannot find it. Thank you for the great app!

**Comment by smichel17** [comment]
You may find my saved filters and lua scripts useful: [saved_filters.txt](https://github.com/mpcjanssen/simpletask-android/files/1308672/saved_filters.txt), [config.lua.txt](https://github.com/mpcjanssen/simpletask-android/files/1308674/config.lua.txt)

Note: My filters use scripts that are defined in the lua config, so they won't work unless you import the config, too. To import them into ST:

- Download the files
- Remove the `.txt` ending from the config (I only added it because github wouldn't allow me to upload a file with a `.lua` extension)
- Copy them to the same folder as the todo.txt file on your phone (or dropbox)
- Open ST, open the right drawer, tap the up/down arrows menu item, then choose `import`
    - This will add my filters in addition to your filters -- nothing will be lost.
- Close the drawer, and select `Lua Config` from the overflow (3 dot) menu.
- From the lua config screen, tap the up/down arrows menu item, then select `Import`
    - If you have any of your own lua config, now is the time to save (copy) it
    - Hit the X in the upper right corner to finish the import -- **your previous lua config will be lost**
    - If you copied any of your own previous lua config, return to the lua config screen and paste it back in at the bottom.

**Comment by symbolisch1234** [comment]
I tried it, but i have to say for now it is beyond me. I will dig deeper into Lua and the config later.

But thank you very much for now!

**Comment by mpcjanssen** [comment]
I will not add any more custom filters than which are available now. Anything else can relatively easily be accomplished using the Lua filtering (see @smichel17 example)

**Comment by moosavy** [comment]
> 
> 
> You may find my saved filters useful. They use functions that are defined in the lua config (so I can use them in multiple filters), so you'll need that, too. To import both them into ST:
> 
>     * Download the files: [saved_filters.txt](https://github.com/mpcjanssen/simpletask-android/files/1308672/saved_filters.txt), [config.lua.txt](https://github.com/mpcjanssen/simpletask-android/files/1308674/config.lua.txt)
> 
>     * Remove the `.txt` ending from the config (I only added it because github wouldn't allow me to upload a file with a `.lua` extension)
> 
>     * Copy them to the same folder as the todo.txt file on your phone (or dropbox)
> 
>     * Open ST, open the right drawer, tap the up/down arrows menu item, then choose `import`
>       
>       * This will add my filters in addition to your filters -- nothing will be lost.
> 
>     * Close the drawer, and select `Lua Config` from the overflow (3 dot) menu.
> 
>     * From the lua config screen, tap the up/down arrows menu item, then select `Import`
>       
>       * If you have any of your own lua config, now is the time to save (copy) it
>       * Hit the X in the upper right corner to finish the import -- **your previous lua config will be lost**
>       * If you copied any of your own previous lua config, return to the lua config screen and paste it back in at the bottom.
> 
> 
> In particular, I think you'll be interested in the filter called "NOW", that I use as a daily todo list. It shows tasks that are:
> 
>     * **Due today** -- I use `due` exclusively to mean "has an external deadline for this date"
>       OR
> 
>     * **Priority A** -- if there's a task without a strict deadline that I decide to do today, I give it priority A.
>       OR
> 
>     * **Completed today** -- The visual satisfaction of seeing things get crossed off my list is really important for me, so I also show all the stuff I've already done today.

Hi @smichel17 
why you have uploaded saved_filter.txt file? You didn't say anything about that. Also I think that newer versions of simpletask have different UI from what you explained on this post. 
Please update you guide.

**Comment by smichel17** [comment]
I guess I forgot to respond to this.

> why you have uploaded saved_filter.txt file?

Saved filters are where you put the lua functions — `onFilter`, `onGroup`, `onSort` — that have an effect on what is shown.

What if you want two filters that show the same tasks, but sorted differently? You could copy the `onFilter` function into both filters, but then you need to update two places each time you want to make a change. This is what the lua config is for — anything you put in it, is available to your functions inside the filters.

`config.lua` has global configuration. This is made available in all filters

> Also I think that newer versions of simpletask have different UI from what you explained on this post.

Ah, yes. We now have a UI that actually makes sense :laughing: (hitting X to save? :dizzy_face:).

Updated! I also uploaded a later version of my saved filters and lua config (my current one, although currently the more complicated filters, that use lua, have been mostly replaced by a whiteboard). Made a gist instead this time: https://gist.github.com/smichel17/3b7a0f99dcd03dc53d1bc6b1784d391f
