### ISSUE TITLE
Mistake in Lua Config Help (Example: show tasks with the @errand tag)

### ISSUE THREAD

**Issue by symbolisch1234** [mpcjanssen/simpletask-android#783]
i found an actual error :-)

In Lua Config > Help > Examples there is an example how to show all tasks with a tag.
* tags are not denoted by @ but by +
* the actual syntax to show the tag is not `return f.tags["@errands"]` or even `return f.tags["+errands"]`, but `return f.tags["errands"]` without a symbol at all

**Comment by mpcjanssen** [comment]
Thank you for reporting. This is already fixed on HEAD.
