### ISSUE TITLE
No auto refresh? 

### ISSUE THREAD

**Issue by gogolo2** [mpcjanssen/simpletask-android#784]
Hi I have to manually refresh in the menu to see changes made by folder sync from own cloud. Couldn't st check for changes in the file or better have a option auto refresh? Thx

**Comment by gogolo2** [comment]
I see this has already been discussed:
https://github.com/mpcjanssen/simpletask-android/issues/735

**Comment by mpcjanssen** [comment]
Closed as duplicate updates on #735
