### ISSUE TITLE
Adding new task when filter is inverted

### ISSUE THREAD

**Issue by colinsullivan** [mpcjanssen/simpletask-android#786]
Hello!

To whom it may concern, I've found a behavior that doesn't quite make sense to me. 

Observed behavior:

1. Filter the task list based on an inverted context. For example, only show tasks without `@home`
1. Press the "+" button to add a new task
1. The `@home` context is automatically added to the new task

Desired behavior: inverted filter elements are not automatically added to the task when "+" is pressed when viewing the filtered list. 

Does this make sense?

Another example:

Filter on `+Next` without any items including `@work`.  Adding a new task from this view should automatically add `+Next` but not `@work`

**Comment by mpcjanssen** [comment]
Duplicate of #739?

**Comment by colinsullivan** [comment]
Yes indeed thanks much!
