### ISSUE TITLE
dropbox working?

### ISSUE THREAD

**Issue by keenahn** [mpcjanssen/simpletask-android#788]
Hello, just found your app today, it looks great. I tried connecting my dropbox (both ways) and the Simpletask folder is created in my Apps directory, but I see no todo.txt in there. Help?

**Comment by mpcjanssen** [comment]
Nope: see https://blogs.dropbox.com/developers/2017/06/updated-api-v1-deprecation-timeline/
Deploying update as we speak.

**Comment by mpcjanssen** [comment]
Leave open for visibility

**Comment by mpcjanssen** [comment]
v9.1.0 from the playstore works with the new Dropbox API

**Comment by keenahn** [comment]
Can confirm working. Thanks!

**Comment by chrisvel** [comment]
Same for me, I allow the access from Dropbox and Simplenote's Login button never go any further.

**Comment by mpcjanssen** [comment]
@chrisvel you mean for you it doesn't work properly? Please log a different issue for that.
