### ISSUE TITLE
howto use plus-sign in task (but not a project)

### ISSUE THREAD

**Issue by aput** [mpcjanssen/simpletask-android#791]
How can I add a plus-sign to my task description, without it being recognized as a project?

Example:
`Switch dial to +200`

I found no solution in the Todo.txt syntax description (https://github.com/todotxt/todotxt/).

Thanks,
Andre

**Comment by mpcjanssen** [comment]
The todo.txt format is a bit under-specified in this sense a common approach would be to allow `\` escaping.

**Comment by aput** [comment]
Indeed Simpletask no longer sees it as a project, but still prints whatever I use as an escape character:
`Switch dial to \+200`

I can live with that, but will 'escape' with an underscore (`_`) which I find less disturbing:
`Switch dial to _+200`

Thanks,
Andre

**Comment by mpcjanssen** [comment]
Limitation of todo.txt which can be worked around fairly easily.
