### ISSUE TITLE
Layout: indentation needed in the Filter section

### ISSUE THREAD

**Issue by aput** [mpcjanssen/simpletask-android#792]
After pressing the Filter icon, then in tabs 'Contect', 'Project' and 'Prio':
the text 'Invert filter' could use some indentation (at least on my phone)

**Comment by mpcjanssen** [comment]
![screenshot_20171002-135827](https://user-images.githubusercontent.com/146895/31076349-f8a28b74-a779-11e7-9345-650926378656.png)
