### ISSUE TITLE
done.txt not appearing Dropbox Folder

### ISSUE THREAD

**Issue by rp-karanth** [mpcjanssen/simpletask-android#794]
Simple Task v. 9.1.1
After applying archive action only todo.txt is updated in Dropbox folder.

[SimpleTask.log](https://github.com/mpcjanssen/simpletask-android/files/1354719/SimpleTask.log)

**Comment by mpcjanssen** [comment]
should be fixed in 9.1.2. can you confirm?

**Comment by rp-karanth** [comment]
Yes it is now fixed. Sorry I didnt check the update.

**Comment by mpcjanssen** [comment]
No problem, thanks for confirming. Please check the already 'archived' tasks in you previous dropbox versions of the history in the app. Any tasks archived with 9.1.0 or 9.1.1 will otherwise be lost.
