### ISSUE TITLE
Question about Dropbox (Pay) version 

### ISSUE THREAD

**Issue by leogbar** [mpcjanssen/simpletask-android#795]
Hello Mark,

I think to buy the pay version of simpletask, but i dont use google play store, so, i can use the app?
You have a alternative metod to contribuye?

Thanks.

Leonardo

**Comment by smichel17** [comment]
All functionality is available in the free version. The paid one on Google Play is a way of donating; there's also a PayPal link around somewhere if you'd prefer that.

**Comment by mpcjanssen** [comment]
@leogbar , nice to hear you are enjoying Simpletask. If you would like to donate, the paypal link is https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=mpc%2ejanssen%40gmail%2ecom&lc=NL&item_name=mpcjanssen%2enl&item_number=Simpletask&currency_code=EUR&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted
