### ISSUE TITLE
Quick filter does not show any project or context

### ISSUE THREAD

**Issue by AlexGrok** [mpcjanssen/simpletask-android#798]
Latest update (10.0.0) has this issue. Quick filter just does not collect current projects and contexts from my items. Please fix it - thanks.

**Comment by mpcjanssen** [comment]
@AlexGrok I was able to reproduce it once. Do you have a reliable way to reproduce the issue?

**Comment by mpcjanssen** [comment]
Also which version are you using Dropbox, Cloudless or Nextcloud so I can send you a test update.

**Comment by mpcjanssen** [comment]
Seems to occur when Simpletask has been running in the background for a while.

**Comment by AlexGrok** [comment]
As for me it looks like initially application does not parse data file till something occur. I suppose that before Dropbox sync, but I cannot prove this. Right now it works.

**Comment by AlexGrok** [comment]
I have no ability to rollback and check it - sorry.

**Comment by mpcjanssen** [comment]
@AlexGrok 10.0.1 should fix it. It was caused by the drawer being filled before the todolist was loaded. I will release it to the playstore ASAP
