### ISSUE TITLE
tasks without due date - sort order has changed

### ISSUE THREAD

**Issue by aput** [mpcjanssen/simpletask-android#800]
Tasks without due date appear before tasks with a due date.
This was different one or two days ago.
So my guess is it was introduced in one of the recent v10.0.x versions.

Andre

**Comment by smellymoo** [comment]
Also now tasks without priority are ABOVE tasks with a priority. And there is no way to change this.

Probably the same bug.

**Comment by mpcjanssen** [comment]
@smellymoo task prio sort was fixed in 10.0.3. I will commit a fix for this issue soon.

**Comment by smellymoo** [comment]
Updated, you are correct. Sorry.

**Comment by mpcjanssen** [comment]
@smellymoo thanks for reporting. Deploying 10.0.4 with fix as we speak.

**Comment by aput** [comment]
> @smellymoo thanks for reporting

Actually it was me :-) , you are welcome

**Comment by mpcjanssen** [comment]
@aput thanks, sorry :)
