### ISSUE TITLE
Simpletask Nextcloud - unable to login

### ISSUE THREAD

**Issue by PietroProraso** [mpcjanssen/simpletask-android#804]
Hi,
maybe this is just me being a dumb user, but I don't know what I'm doing wrong

Here you can see that I'm unable to login:

https://imgur.com/a/yjB9o

I am 100% positive, that the url is correct, that the url to my ocloud is indeed an instance of nextcloud, that the password is correct (I tried to use a Nextcloud App-password as well - which did not work).

I tried the url with https:// and without

How can I find out, why it is not working?

PS: THANKS for your amazing app. My life would be only half as good without it :D 
I bought your donation version when I read about nextcloud support. Thanks to all guys who are putting in work here! It's great

**Comment by mpcjanssen** [comment]
@PietroProraso the logging should give an indication of why this fails. However you can't get to the settings with logging in, so maybe you can do an adb logcat while trying to log in. If you can't do that, I can make the login failed message more explicit.

**Comment by PietroProraso** [comment]
sorry the late answer.
Here is what I get from logcat when 

`10-15 11:44:04.622 14230-14230/nl.mpcjanssen.simpletask.nextcloud D/OwnCloudClient #3: Creating OwnCloudClient
10-15 11:44:04.625 14230-16343/nl.mpcjanssen.simpletask.nextcloud D/OwnCloudClient #3: REQUEST GET /ocs/v1.php/cloud/user
10-15 11:44:04.631 14230-16343/nl.mpcjanssen.simpletask.nextcloud D/AdvancedSslSocketFactory: Creating SSL Socket with remote MYUSERNAME.ocloud.de:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@5f1961
10-15 11:44:04.631 14230-16343/nl.mpcjanssen.simpletask.nextcloud D/AdvancedSslSocketFactory:  ... with connection timeout 60000 and socket timeout 60000
10-15 11:44:04.638 14230-16343/nl.mpcjanssen.simpletask.nextcloud I/ServerNameIndicator: SNI done, hostname: MYUSERNAME.ocloud.de
10-15 11:44:04.816 14230-16343/nl.mpcjanssen.simpletask.nextcloud E/GetRemoteUserInfoOperation: Failed response while getting user information 
10-15 11:44:04.816 14230-16343/nl.mpcjanssen.simpletask.nextcloud E/GetRemoteUserInfoOperation: *** status code: 403 ; response message: <!DOCTYPE html>
                                                                                                <html class="ng-csp" data-placeholder-focus="false" lang="en" >
                                                                                                	<head data-requesttoken="bllYHkwZVCNbCj8DBjAVAS41EwshaWRmTn8jAgVACyU=:ZhiO+/6dtSKhCQfXwOdIDXTTw2GlBqik7j3l+HXoN/w=">
                                                                                                		<meta charset="utf-8">
                                                                                                		<title>
                                                                                                		Nextcloud		</title>
                                                                                                		<meta http-equiv="X-UA-Compatible" content="IE=edge">
                                                                                                		<meta name="referrer" content="never">
                                                                                                		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
                                                                                                		<meta name="apple-itunes-app" content="app-id=1125420102">
                                                                                                		<meta name="theme-color" content="#0082c9">
                                                                                                		<link rel="icon" href="/core/img/favicon.ico">
                                                                                                		<link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png">
                                                                                                		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#1d2d44">
                                                                                                					<link rel="stylesheet" href="/core/css/styles.css?v=5446b29c0628da3e0f3e14308ee46cfe">
                                                                                                					<link rel="stylesheet" href="/core/css/inputs.css?v=5446b29c0628da3e0f3e14308ee46cfe">
                                                                                                					<link rel="stylesheet" href="/core/css/header.css?v=5446b29c0628da3e0f3e14308ee46cfe">
                                                                                                					<link rel="stylesheet" href="/core/css/icons.css?v=5446b29c0628da3e0f3e14308ee46cfe">
                                                                                                					<link rel="stylesheet" href="/core/css/fonts.css?v=5446b29c0628da3e0f3e14308ee46cfe">
                                                                                                					<link rel="stylesheet" href="/core/css/apps.css?v=5446b29c0628da3e0f3e14308ee46cfe">
                                                                                                					<link rel="stylesheet" href="/core/css/global.css?v=5446b29c0628da3e0f3e14308ee46cfe">
                                                                                                					<link rel="stylesheet" href="/core/css/fixes.css?v=5446b29c0628da3e0f3e14308ee46cfe">
                                                                                                					<link rel="stylesheet" href="/core/css/multiselect.css?v=5446b29c0628da3e0f3e14308ee46cfe">
                                                                                                					<link rel="stylesheet" href="/core/css/mobile.css?v=5446b29c0628da3e0f3e14308ee46cfe">
                                                                                                					<link rel="stylesheet" href="/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=5446b29c0628da3e0f3e14308ee46cfe">
                                                                                                					<link rel="stylesheet" href="/core/css/jquery-ui-fixes.css?v=5446b29c0628da3e0f3e14308ee46cfe">
                                                                                                					<link rel="stylesheet" href="/core/css/tooltip.css?v=5446b29c0628da3e0f3e14308ee46cfe">
                                                                                                					<link rel="stylesheet" href="/core/css/jquery.ocdialog.css?v=5446b29c0628da3e0f3e14308ee46cfe">
                                                                                                									<script src="/index.php/core/js/oc.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/vendor/jquery/dist/jquery.min.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/vendor/jquery-migrate/jquery-migrate.min.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/vendor/underscore/underscore.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/vendor/moment/min/moment-with-locales.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/vendor/handlebars/handlebars.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/vendor/blueimp-md5/js/md5.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/vendor/bootstrap/js/tooltip.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/vendor/backbone/backbone.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/vendor/es6-promise/dist/es6-promise.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/vendor/davclient.js/lib/client.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/vendor/clipboard/dist/clipboard.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/js/placeholders.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/js/compatibility.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/js/jquery.ocdialog.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/js/oc-dialogs.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/js/js.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/js/l10n.js?v=5446b29c0628da3e0f3e14308ee46cfe"></script>
                                                                                                					<script src="/core/js/o
10-15 11:44:06.830 1490-1490/system_process W/WindowManager: Attempted to remove non-existing token: android.os.Binder@56cc21c
`

**Comment by mpcjanssen** [comment]
I just tried with my own account and indeed it doesn't work. The 403 seems to indicate there is an authentication issue, but I am not sure exactly what.

**Comment by mpcjanssen** [comment]
I did notice they are using a fairly old server version. This might be related.

**Comment by mpcjanssen** [comment]
It would be interesting to know if syncing with the nextcloud desktop client works.

**Comment by PietroProraso** [comment]
I think it is a problem of the outdated nextcloud version that is used by ocloud.de

I tried woelkli.com - they use v12.0.2 - login worked without a problem. However woelkli.com does not offer version control in their free program.

However I discovered that my university provides a nextcloud service for its users (v12.0.3). Login worked without problems. And version control enabeled. I'm happy.

**Comment by mpcjanssen** [comment]
Closed. But good to know the library used doesn't seem to support older ownclouds.

**Comment by tseaver** [comment]
I have this bug on one device (a Huawei Honor 5x phone) but not another (Samsung Galaxy Tab-10).

FWIW, I can also edit the file via `davfs`.

**Comment by mpcjanssen** [comment]
@tseaver could you attach the logging for the failing Huawei phone?

**Comment by tseaver** [comment]
@mpcjanssen Sure!  Can you suggest a set of `adb logcat` filters which will isolate the interesting bits?  The spew is enormous.

**Comment by tseaver** [comment]
The "error" log entry is like the one @PietroProraso reported:

```
E/GetRemoteUserInfoOperation( 3757): Failed response while getting user information 
E/GetRemoteUserInfoOperation( 3757): *** status code: 404 ; response message: <?xml version="1.0" encoding="utf-8"?>
E/GetRemoteUserInfoOperation( 3757): <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
E/GetRemoteUserInfoOperation( 3757):   <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
E/GetRemoteUserInfoOperation( 3757):   <s:message>File with name ocs/v1.php/cloud/user could not be located</s:message>
E/GetRemoteUserInfoOperation( 3757): </d:error>
```

**Comment by tseaver** [comment]
FWIW, I'm running NextCloud 12.0.3 on my own host.

**Comment by tseaver** [comment]
Ouch! I just logged out of the "working" version in order to look at the login flow:  I am now unable to log back in on the tablet, either.

**Comment by mpcjanssen** [comment]
@tseaver maybe a recent update on the server screwed something up. If there are some remaining simpletask issues, please log a new one.

**Comment by tseaver** [comment]
@mpcjanssen The server code hasn't update (as I said, I control horizontal / vertical there).

Can you suggest the right `adb logcat` incantation to show how the app gets the OAuth token?

**Comment by mpcjanssen** [comment]
@tseaver I don't think `adb`supports filtering on application. So just do a full logcat and then filter it with `grep nl.mpcjanssen`.

**Comment by wokawoka** [comment]
I'm experiencing the same problem trying to connect to my nextcoud hosted exactly on ocloud.de.
It's a pretty nextcloud 13 installation (so I wouldn't say that ocloud.de's server version is old).
Any more ideas about how to solve this issue?

**Comment by mpcjanssen** [comment]
Ra
