### ISSUE TITLE
Cannot archive tasks, Dropbox

### ISSUE THREAD

**Issue by chelmertz** [mpcjanssen/simpletask-android#812]
I am using the latest, 10.0.6, version of Simpletask Dropbox.

When trying to archive finished tasks, either from a single task or all of them through the menu, I get the error message 'Task archiving failed'.

Ironically, the Share button in the debug log view doesn't work for me either, so here is a screenshot of it:

![](https://i.imgur.com/DSGdCVP_d.jpg?maxwidth=640&shape=thumb&fidelity=medium) 

Except for the archiving, all of the tasks are  updated properly in the text file inside of Dropbox. Not sure if it matters, but the root directory is set to /sdcard/.

**Comment by mpcjanssen** [comment]
You need to have an existing done.txt. I thought I fixed this bug.

**Comment by chelmertz** [comment]
Thanks for pointing me at the workaround. Adding "done.txt" in the same folder worked for me.

**Comment by mpcjanssen** [comment]
Will be fixed in 10.0.7
