### ISSUE TITLE
Effective Task Filtering

### ISSUE THREAD

**Issue by kaushiknfs** [mpcjanssen/simpletask-android#813]
The greatest strength of the task app comes with ease where you segregate the bunch of tasks into appropriate lists.

While Lua filtering does that it has 2 problems.
     1. The onGroup and onFilter methods are not well documented, for example am still not clear as to what onGroup or OnDisplay does, will be glad to update the wiki if i get that knowledge.
 2. Its too much to ask a non technical user to write lua filters.

It would be great to have effective intuitivce filter UI to do
Where 
Project = one 
AND Project != two
AND Context = three
AND Context != four

Something like this, i guess the current filter screen does not let you do the same.

It would be good if we can write the filter in plaintext with nested brackets and decompose the same into lua or a filter object internally,

Like this

`(+one && !+two ) && (@three || !@four) & A
`
or

`(today | overdue) && +Work
`

Plain text filters /query greatly enhances the possiblities of doing things and saving them as Lists.

Sampling from: https://support.todoist.com/hc/en-us/articles/205248842-Filters#project

Please consider. This would be a single most defining feature of simple task.

**Comment by smichel17** [comment]
> 1. The onGroup and onFilter methods are not well documented, for example am still not clear as to what onGroup or OnDisplay does, will be glad to update the wiki if i get that knowledge.

onFilter decides if a task should be shown. onGroup decides what header the task should be shown under (without a script, grouping is by the first sort criteria). onDisplay decides what text should be shown for that task (for exanple, if you wanted to not display a certain tag, but you didn't want to hide *all* tags).

> 2. Its too much to ask a non technical user to write lua filters.

The vast majority of use cases should be covered by the UI. However, there are some use cases that will only fit a tiny amount of users; supporting those would quickly bloat the UI, making it much less usable for the majority of people. 

Lua is designed to fill this gap, by allowing you to write a script for your niche case. It's also a nice testing ground for new features, to see if we think they're worth building a ui for. Thus, it doesn't need to be *quite* as accessible as the main UI (although the help file should be enough for people to get started).

> Text filter queries

I think that making the lua less verbose would be a good thing, as long as it does not prevent accessing the full power of lua. For example, iterating through all lists/tags; how would you do that with the proposed interface? Although, there is also a cost to changing the syntax, namely that older scripts will need to be updated.

However, I also wonder if making lua scripts less verbose is the right solution to the problem. "Show only tasks due today" and "Show tasks on this list but not that one" both seem like pretty common ways to filter. Maybe we should support this through the UI.

**Comment by kaushiknfs** [comment]
We have here two ways to define a list.

1. a powerless quiet bunny, which can do simple things - The UI Filter
2. a vastly powerful dinosaur, which can do anything -  Lua.

In hopes of simpletask acceptance and recognition of its capacities, the filter should be simple enough a construct - plain text that any layman can write. and powerful enough for a user to filter and get a desired task set. That was the reason I asked for ' Plain Text Filter Queries'

That aside, as you describe the onGroup and onDisplay capablties, its fantastic, i may have to learn some basic lua to use them. But if you think of a average list maker wanting to use it ? that gives use another question, does an average non-tech list maker ever come to use todo.txt? most likely not. even f they attempt to they get scared by the complexity of usage.

**Comment by kaushiknfs** [comment]
Do you happen to have sample for onGroup and onDisplay ? can a filter have both onGroup and onFilter methods overriden?

**Comment by smichel17** [comment]
Have you checked out the in-app help (or its source file [here](https://github.com/mpcjanssen/simpletask-android/blob/master/app/src/main/assets/script.en.md))?

**Comment by mpcjanssen** [comment]
@kaushiknfs writing a plaintext filter query language will just eventually lead to implementing something like Lua from scratch. So I much prefer using an existing well defined language even if the barrier is slightly higher.
Taskwarrior takes the custom querying approach and it requires a lot of infrastructure that is built from scratch.

**Comment by mpcjanssen** [comment]
For the verbosity the best way (IMO) would be to define a Lua library which supports doing standard functions like:

* Is this task due today
* Is this task overdue

It will then be straightforward to do simple queries. This library could be copy pasted in the application wide Lua config.

**Comment by mpcjanssen** [comment]
Just to be clear, a plain text special filter query language will never be added. Adding a Lua library for easier filtering will.

**Comment by mpcjanssen** [comment]
See #815

**Comment by mpcjanssen** [comment]
Since no other querying language will be added. And adding helper functions are covered by another issue. I am closing this.
