### ISSUE TITLE
Font color issue

### ISSUE THREAD

**Issue by aubreyz** [mpcjanssen/simpletask-android#814]
A very minor issue. I like the dark themes - better for my sleep and battery. However even with the black theme the todo items are really hard to read at least with my phone and old eyes. This is because the item text fonts are very far from white and too close to the background.  I think you need an option in the dark theme to make the fonts completely and properly white (apart from colored @ and + if required) -- or at least make the default a whole lot lighter.

**Comment by smichel17** [comment]
I believe the text is technically pure white, but partially transparent (if not, it should be). So, although the black background is darker, the text should not be as bright in that theme, either => both should be equally readable.

I agree that it is a bit hard to read, particularly outside during the day. However, I would not like it to be very much more opaque (a little would be ok); too much contrast is painful to my eyes at night. So, I wonder if there are other solutions to the problem --

Is it still hard to read if you increase the size of the text? I know there are other reasons you may not want to do that, I'm just curious whether it helps with this issue.

**Comment by aubreyz** [comment]
Yup larger fonts are easier, but that is a bad trade-off. The dark theme is actually far easier to read than the black one. What I think you need is to make the font in the black theme as least as light as the one in the dark theme - not darker....... otherwise the black theme is just like the dark theme with the brightness turned down :)

Everything else (like the on screen keyboard) is pure white on dark, and I don't find that too distressing.

**Comment by aubreyz** [comment]
OK, this is embarrassing.  There is something wrong with my phone screen....

For whatever reason it showed itself most dramatically in simpletask with the black theme. But now it is worsened, and is showing up in other apps. I have migrated to identical model phone (Moto G) and it is great as is. Hangs head in shame. I am therefore closing this.
