### ISSUE TITLE
Add standard library for task manipulation

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#815]
Use this library as the default application Lua config and add a button to append the stdlib to the Lua config (for people who have customised the main config)

**Comment by smichel17** [comment]
Seems like it would be simpler to include this regardless of whether someone has customized their lua config. That is, the active lua module would include is stdlib + custom config + active filter

**Comment by mpcjanssen** [comment]
@smichel17 that is what actually is already don now :) See https://github.com/mpcjanssen/simpletask-android/blob/master/app/src/main/java/nl/mpcjanssen/simpletask/LuaInterpreter.kt#L22-L110
Would be nice to at least extract the stdlib to a separate asset.
