### ISSUE TITLE
"(80/140) Filtered on: Search" is missing

### ISSUE THREAD

**Issue by participante0** [mpcjanssen/simpletask-android#818]
I can only see it after selecting one task and modifying it.
Current version: 10.0.5

**Comment by smichel17** [comment]
Can confirm on v10.0.6, after typing a search and pressing enter (search), "search" does not appear in the filter bar.

Anything which triggers onResume (and, presumably, any other action which causes the filter bar to be updated) will cause it to appear.

**Comment by mpcjanssen** [comment]
Fixed in 10.1.12
