### ISSUE TITLE
edit: no automatic line break in landscape mode

### ISSUE THREAD

**Issue by jotwewe** [mpcjanssen/simpletask-android#823]
When editing a task in portrait mode, there is an automatic line break, which is fine. 
The screen looks completely different in landscape mode while the keyboard is visible (no icons for lists, tags, priority, due date and save). Other apps use this edit view too. In contrast to those other apps there is no automatic line break in simpletask, which is a pain when editing long texts.

Please enable automatic line break.

Samsung S4 mini
CM13.0
simpletask 9.0.7 from f-droid

**Comment by smichel17** [comment]
@jotwewe When the keyboard is active in landscape mode, the display is controlled nearly 100% by the keyboard; there's very few things an app can modify. I am pretty sure that it is not possible to show the icons for lists and tags. I didn't actually realizs it was possible to control how line breaks are displayed, but it looks like [this app](https://github.com/SimpleMobileTools/Simple-Notes) forces therm to be displayed; we can investigate and see how it's done.

**Comment by jotwewe** [comment]
I'm fine with not displaying icons, I only want automatic line breaks.

@smichel17: to be more explicit, it is not about displaying line
breaks with some sort of special character, but about automatically
breaking the line. For example k9mail looks just like simpletask when
editing in landscape mode, but breaks long text into multiple lines.

Thanks for looking into this.

**Comment by mpcjanssen** [comment]
The line breaks are actually there, they are just not shown properly. IMO this is suckiness of the Android SDK and it should just work without additional effort.

**Comment by jotwewe** [comment]
Well, maybe it should work, but it does not. Some screenshots:

simpletask in portrait mode when editing:
![screenshot_20171124-115135](https://user-images.githubusercontent.com/4405433/33207794-60bc59c4-d10f-11e7-99c0-579d6d85eae5.png)

after turning the display, line breaks are gone:
![screenshot_20171124-115150](https://user-images.githubusercontent.com/4405433/33207795-60ea890c-d10f-11e7-8439-ff6ef940482f.png)

after hiding the keyboard:
![screenshot_20171124-115235](https://user-images.githubusercontent.com/4405433/33207796-611b7652-d10f-11e7-9aec-d191851e4c7c.png)

Doing the same using K9-Mail. The editing view looks identical to simpletask, but linebreaks are there:
![screenshot_20171124-115430](https://user-images.githubusercontent.com/4405433/33207797-6150fa8e-d10f-11e7-8367-8ea3eb6a4f9b.png)

**Comment by mpcjanssen** [comment]
I know it doesn't actually work, but I am getting tired of fighting the Android SDK to get basic stuff like this working.

**Comment by smichel17** [comment]
In about 3 weeks I will have some time to spend on stuff like this. As I mentioned earlier,  a brief look into this did not reveal the cause and, to be honest, I'm not interested in spending a ton of time tracking down why it happens, either; I add tasks almost exclusively in portrait. However, if someone else wanted to do some research and point me to relevant android docs / stackoverflow questions, I'd be willing to implement the fix.

**Comment by smichel17** [comment]
I started looking at this. I cut out a big section of AddTask.kt and it work correctly, so it's something we're doing that causes the bug, not a broken default. Next step: figuring out which part is causing the problem.

**Comment by smichel17** [comment]
It's a result of 

    textInputField.imeOptions = EditorInfo.IME_ACTION_NEXT
