### ISSUE TITLE
Filter not loaded when opened through the widget

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#825]
Steps to reproduce:

1. Have 2 saved filters, `A` and `B`, that show different tasks. 
2. Create a widget with filter A.
3. Open ST and activate filter B.
4. Go to the home screen and tap on the widget (header or task).

Expected result: ST opens written filter A active. If you tapped on a task, that task is selected. 
Actual result: ST opens with filter B active. If you tapped on the task, selection mode is correctly active, but the task is not shown.

v10.0.6

**Comment by johnnydvc** [comment]
Same exact thing here.
v10.0.6

**Comment by mpcjanssen** [comment]
This was caused by broken FILTER_INTENT handling.

Should be fixed in latest versions (works in 10.1.13)

**Comment by smichel17** [comment]
Confirmed fixed in 10.1.13
