### ISSUE TITLE
Hide completed items after x days

### ISSUE THREAD

**Issue by arjonvl** [mpcjanssen/simpletask-android#835]
Option to hide completed items after x days would be nice. This way one keeps the satisfaction of seeing completed tasks of the day, without having a long list of completed tasks.

**Comment by smichel17** [comment]
It's not baked in to the UI, but you can do this with a simple lua filter.

First, open the lua config from the main menu and add some helpers to make the script more readable:

```
DAY=86400

function inLast(period, time)
  now=os.time()
  return time ~= nil
      and time < now
      and time >= (now - period)
end
```

Then, add the following to the script tab of the filter:

```
function onFilter(t,f,e)
  return not f.completed
    or inLast(x*DAY, f.completedate)
end
```

**Comment by smichel17** [comment]
I have a similar filter I use that shows only tasks with prio A, due today, or completed today; it's very nice for keeping everything else out of my way when I don't need it.

**Comment by arjonvl** [comment]
Thanks a lot! Always so much faster to understand the scripting with an example. It should be f.completiondate by the way. Took a some troubleshooting to find that one out ;). Works like a charm now!
