### ISSUE TITLE
Allow to add description to priorities on the priority list

### ISSUE THREAD

**Issue by d1237** [mpcjanssen/simpletask-android#838]
A, B, C,..., Z doesn't add much information besides that there are 26 levels of priority. My suggestion is that, on the priority list, it could be possible to add a description to a priority. For example:

A - Urgent Tasks
B - Do until weekend
C - Do until next month

Or something similar according to the user choice. It would only affect the priority list, and help the user use priorities in a consistent way.

**Comment by smichel17** [comment]
Are you only concerned with how the headers are, or also with the menu that pops up when you want to set the priority?

If you are only concerned with the display, you can achieve this with a lua script like this:

First, open the lua config, from the main menu, and add this:

```
GROUP={ ["A"]="Urgent Tasks", ["B"]="Do until weekend", ["C"]="Do until next month", ["-"]="Someday/maybe" }
```
Then, in the script tab of the filter, write:
```
function onGroup(t,f,e)
  return GROUP[f.priority]
end
```

Note: I wrote this here, from memory, so there's a small chance I made a typo or something that would prevent this from working; let me know how it goes.

**Comment by mpcjanssen** [comment]
Once you do this, what is the benefit over using tags or lists for this?

So why not just use `@Urgent`, `@Week`, `@Month` ?

**Comment by smichel17** [comment]
I do something similar. Can't speak for @d1237 but I do it because I already use both lists and tags, and I prefer not to overloading their meaning.

**Comment by mpcjanssen** [comment]
Alternative option:

Just use the normal priorities and create saved filers in the right drawer which include the description.

Considering there are several ways to have full text display of priorities or use tags/lists I will not add a specific text description for a priority.
