### ISSUE TITLE
AddTask edit contents reset when rotating phone

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#843]
Reported on IRC: when I'm in task editor it resets the contents to the old text whenever I rotate my phone and the screen switches between portrait and landscape.

**Comment by smichel17** [comment]
(OnePlus 5, Android 8.0.0)

**Comment by shayneholmes** [comment]
Can also reproduce on a 1st-gen Moto X running Android 5.1.

**Comment by mpcjanssen** [comment]
It's not OS specific. The issue is that the AddTask activity is recreated after rotation and the previous contents of the text box are lost.

**Comment by smichel17** [comment]
Are we doing something special that is causing the bug? According to [this SO thread](https://stackoverflow.com/questions/19234653/edittext-not-automatically-saved-on-screen-orientation-change), EditText boxes should save themselves automatically as long as they have an id, which ours does…

**Comment by mpcjanssen** [comment]
The activity initialisation code refills the edittext overwriting any text already there. Maybe a simple check to see if the edittext is filled is enough to prevent this issue.

**Comment by smichel17** [comment]
If I edited tasks, deleted them all, and then rotated the screen, I think they would reappear. But, maybe that's a rare enough case we don't care. Certainly better than the current situation.
