### ISSUE TITLE
Document right drawer use

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#845]
Based on feedback, the right drawer is not very discoverable. It does part a large part of the convenience of simpletask for advanced use though.
Make the right drawer easier to find and use. At least include the following 'tutorial' somewhere:

## Save filter

- Configure the filter as you would normally do it.
- Swipe the right drawer.
- Press the plus button in the header.
- Give the filter a name.
- Press 'OK'

Now the filter is there.

## Saved filter options

You can also export/import saved filters (with the double arrow icon)
and change a saved filter (or make a shortcut on the homescreen) by
long pressing the filter name.

**Comment by smichel17** [comment]
I have a couple of ideas for this, all of which revolve around adding a control somewhere to open the drawer. In order to get a feel for how this, I suggest playing around with the github app, [OctoDroid](https://github.com/slapperwan/gh4a), which does this and whose right drawer is well-implemented, imo.

**Comment by mpcjanssen** [comment]
rightdrawer-ui branch has update inspired by Octodroid, thanks for the tip.

**Comment by mpcjanssen** [comment]
Will need some fine-tuning to make sorting and Lua scripting a bit more accessible, but I think it will help in discover-ability.

**Comment by doranism** [comment]
Fine! That was the thing that I was going to work on (at least I wanted to try :-) ), see #484. Another example is the right drawer/overflow menu of Firefox Android. It contains some icons for important actions too.

**Comment by smichel17** [comment]
@doranism I took the first step toward this recently, in #842
