### ISSUE TITLE
error: saving of todo file failed

### ISSUE THREAD

**Issue by grantiago** [mpcjanssen/simpletask-android#859]
Getting an error alert; but indeed the file is saved.
Simpletask cloudless v 10.0.7 (3075)
android 6.1
samsung galaxy s5

**Comment by mpcjanssen** [comment]
Are you sure it's saved? Did you check the actual file using another application?

**Comment by smichel17** [comment]
Could you include the full text of the error message? It should include slightly more information about exactly what failed at the end.

**Comment by grantiago** [comment]
You are right. The file has not been updated. Where is the app getting the updated data? because that is showing in the app. I've done a full search for other todo.txt files. nothing. 
The exact message is in a small popup: `Saving of todo file failed`
In  `settings/other/root:// directory` I have entered: `/sdcard/docs_g/to_do/` 
However in the title bar it shows `/s/9/d/t/todo...` which is the  abbreviated path to my external sd card. changing the path does not take.  

my phone is rooted. gerris GROMV6DUOS [6.0.1] custom rom. mostly a debloat. gives no problems elsewhere. 

Permission Denied. 
here is last few lines of the error log: 
`--------- beginning of main
01-25 12:15:08.687 20748 20748 I AlarmReceiver: Executing Alarm callback
01-25 12:15:08.687 20748 20748 I Util    : Sending file changed broadcast
01-25 12:15:08.707 20748 20748 I TodoApplication: Received broadcast FILE_SYNC
01-25 12:15:08.707 20748 20748 I TodoApplication: Loading todolist
01-25 12:15:08.837 20748 20760 I TodoActionQueue: TLQ: Reload: From BROADCAST_FILE_SYNC
01-25 12:15:08.837 20748 20760 I Util    : Sending file sync start broadcast
01-25 12:15:08.857 20748 20760 I TodoList: Not loading, changes pending
01-25 12:15:08.857 20748 20760 I TodoList: Saving instead of loading
01-25 12:15:08.857 20748 20760 I Util    : Sending file sync start broadcast
01-25 12:15:08.917 20748 20761 I TodoActionQueue: FSQ: Save
01-25 12:15:08.917 20748 20761 I TodoList: Saving todo list, size 88
01-25 12:15:08.917 20748 20761 I FileStore: Saving tasks to file: /storage/9C33-6BBD/docs_g/to_do/todo.txt
01-25 12:15:08.937 20748 20761 E TodoList: TodoList save to /storage/9C33-6BBD/docs_g/to_do/todo.txt failed
01-25 12:15:08.937 20748 20761 E TodoList: java.io.FileNotFoundException: /storage/9C33-6BBD/docs_g/to_do/todo.txt: open failed: EACCES (Permission denied)`

**Comment by smichel17** [comment]
You choose the location of the todo file from the main menu, "Open task list file". The `root://` setting you mentioned is for if you want to put links in your tasks to content on your phone. It allows you to use a relative path (to the root you set), to help with allowing the links to resolve on other devices.

**Comment by smichel17** [comment]
As for the error, it looks like, for whatever reason, ST does not have write permissions on that todo file. Try putting it in a different location? If you're set on that location, you could look into setting file permissions or making ST a system app (although both of these solutions seem like overkill to me. Moving is likely to be far easier).

**Comment by grantiago** [comment]
Thanks.  Sorry  to put you through this. The two dots `..`  for the parent directory in the `open task list file` dialog are  almost outside the limits of my vision.  I was tapping on the bold path. So sorry.

**Comment by smichel17** [comment]
I think that's a valid problem :)

Covered by #844

**Comment by mpcjanssen** [comment]
As a post mortem, Android doesn't allow storing files on the SD card in recent versions. I probably should not allow opening of read only files at all.

Simpletask always keeps a copy of the todo file in the application preferences. This is what is being used to retain the changes. And whenever changes are pending the file is not reloaded (to prevent data loss)
