### ISSUE TITLE
todo.txt file filled with "Main activity resume"

### ISSUE THREAD

**Issue by eater** [mpcjanssen/simpletask-android#860]
I can't reproduce this reliably, but it's happened twice. Last night I completed some tasks in the app. This morning I viewed the file and found it had been corrupted as follows: All the line breaks are gone, leaving a single line of todo items alternating with "Main activity resume".  So it starts out like: 

`Get hair cut Main activity resumeMain activity resumeMake lunch  @food Main activity resumeMain activity resumex 2018-01-24 buy coffee  @food`

There's no other app that writes to the file, although I view it read-only on various platforms.

**Comment by mpcjanssen** [comment]
Are these terms also in the actual todo file?

**Comment by mpcjanssen** [comment]
The `Main activity resume` is a log message. This shouldn't end up in the todo file.

**Comment by mpcjanssen** [comment]
Whoops found the issue.
