### ISSUE TITLE
Amazon Kindle Fire version - cannot retrieve Dropbox file

### ISSUE THREAD

**Issue by erictlee** [mpcjanssen/simpletask-android#863]
I think this was raised regarding the Android version, which works fine for me on my Android phone - and you made a fix there, in the Google Play store version of Simpletask.  But the version of Simpletask in the Amazon app store seems to be broken, and I cannot get it to access my todo.txt file on Dropbox.  (It accesses Dropbox with no problem through the app, but freezes up when I try to load the todo.txt file.)  I'd really appreciate this being fixed as Simpletask is probably my favourite app, the one I use throughout the day.  If I cannot get it to work on the Fire HD, that device becomes almost useless to me.  Thanks!

**Comment by mpcjanssen** [comment]
Can you install apk's directly on an Kindle? Keeping all the app stores updated is quite some work, it would be much easier to download a latest build and install it.

**Comment by mpcjanssen** [comment]
Of course Amazon discourages people to bypass their walled garden? Is it possible to install an apk at all?
Regardless, I will update the version on the Amazon store to at least use the new Dropbox API

**Comment by erictlee** [comment]
Thanks, Mark!

**Comment by mpcjanssen** [comment]
10.0.7 should arrive in the Amazon store tomorrow.

**Comment by erictlee** [comment]
That's great news - thanks so much Mark.  I look forward to testing it on the Fire HD tomorrow.

**Comment by erictlee** [comment]
Thanks again for taking care of this - SimpleTask updated automatically on my Amazon Fire HD, and I can now use my favourite app on my new tablet.  Really appreciate this.

**Comment by mpcjanssen** [comment]
Updated to more recent version. dropbox works.
