### ISSUE TITLE
Project quick filter stopped working in 10.1.0

### ISSUE THREAD

**Issue by firecat53** [mpcjanssen/simpletask-android#864]
Quick filter by project stopped working in this version. The results show no matches no matter which project I select. Filtering by context still works.

Let me know if you need more information.

**Comment by mpcjanssen** [comment]
You mean from the left drawer?

**Comment by firecat53** [comment]
On February 26, 2018 1:54:04 PM PST, Mark Janssen <notifications@github.com> wrote:
>You mean from the left drawer?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mpcjanssen/simpletask-android/issues/864#issuecomment-368664189

Correct.

**Comment by mpcjanssen** [comment]
I can reproduce, will investigate.
