### ISSUE TITLE
Use Google i18n APIs to parse phone numbers

### ISSUE THREAD

**Issue by edgewood** [mpcjanssen/simpletask-android#866]
Use Google i18n APIs to parse phone numbers so that users can use locale-appropriate formats for phone numbers and still have them recognized as such by Simpletask.
I thought that Simpletask didn't recognize phone numbers at all, and searched for an existing issue before opening another.  Issue #173 says that Simpletask just parses strings of digits, and digging into the code I see that is so.
I knew that todo.txt-android recognized phone numbers in one of the standard US formats (NNN-NNN-NNNN) and decided to see if it had a regex Simpletext could grab, but it looks like they use Google i18n APIs (com.google.i18n.phonenumbers) rather than a regex.
Would it be possible to change Simpletask to use the same APIs?

**Comment by edgewood** [comment]
Well, it doesn't use the Google APIs, but it will work for me, so thanks!  And thanks for the app in general.

**Comment by mpcjanssen** [comment]
My remark that this breaks my phone number use seems to have been lost. For the record:

I use a locale on the phone not matching my local number format so when using the google API this would not detect my phone number format. Flexible approach committed also works well for me.

**Comment by edgewood** [comment]
I wasn't really wedded to using the Google APIs, I just thought that would be more acceptable than "please support the format I use". <grin>  The fix provided works for me, so thank you again.
