### ISSUE TITLE
Content not displayed after update to 10.1.3

### ISSUE THREAD

**Issue by ghgary** [mpcjanssen/simpletask-android#868]
Sometime today, my Samsung Galaxy S8 automatically updated Simpletask to Version 10.1.3. Now the default display shows nothing. Selecting any of my filters, list or task, displays "(0/840) Filtered on: List", for example. The data file is clearly there, as the List and Tag lists are populated, and I can see the contents of todo.txt using the Dropbox Text Editor. I verified that the file contains 840 entries. I uninstalled and reinstalled Simpletask, but I still can't see any data.

**Comment by mpcjanssen** [comment]
Could you apply the filter and the attach the log from Settings->other->view debug info.

**Comment by ghgary** [comment]
[simpletask.txt](https://github.com/mpcjanssen/simpletask-android/files/1775342/simpletask.txt)

Here is the debugging info you requested. I selected a single List filter item that should have displayed 100 items total. Instead, nothing was displayed except the message "(0/840) Filtered on: List".

**Comment by smichel17** [comment]
I suspect this may be the same issue I have, where my filter that should show every task in my list shows none instead.

**Comment by mpcjanssen** [comment]
@ghgary the log doesn't show anything odd, could you install the version from https://cloud.mpcjanssen.nl/index.php/s/t7nYWB6jLyYn9Lp/download and attach the log again? 

NB this will reveal your filter in the logging so possibly also your tag and list
 names. If that's an issue to put publicly, just mail mpc.janssen@gmail.com

**Comment by ghgary** [comment]
This is not going well. I installed the version from the link above. I deleted the simpletask.txt file from my Dropbox folder. I ran the experiment again and looked at the new Debugging info. The timestamps are from a few minutes ago. Then I shared the new Debugging info to Dropbox and it appeared to save the file. But when I look at the file in my Dropbox folder, it is identical to the one I saved this morning and has the timestamps from this morning. I'll try again later.

**Comment by ghgary** [comment]
I tried again. This time the debug log I saved had the latest time stamps. I didn't see any personal information in it, so I'm going to attach it here. Yesterday was hectic--I have more time today if there is anything else you need.
[simpletask_debug.txt](https://github.com/mpcjanssen/simpletask-android/files/1777758/simpletask_debug.txt)

**Comment by mpcjanssen** [comment]
@ghgary, the logging for the active filter only showed the sorts. Could you try again with https://cloud.mpcjanssen.nl/index.php/s/t7nYWB6jLyYn9Lp ?

**Comment by ghgary** [comment]
Here it is.
[simpletaskdebug.txt](https://github.com/mpcjanssen/simpletask-android/files/1777833/simpletaskdebug.txt)

**Comment by mpcjanssen** [comment]
@ghgary seems I was barking up the wrong tree. Can you check again with the current version at the same URL?

**Comment by ghgary** [comment]
Yay! That last one works! I seem to have all my filtering functionality back. Thank you.

**Comment by mpcjanssen** [comment]
@ghgary will make a new release soon. Thanks for logging the issue and helping in debugging

**Comment by mpcjanssen** [comment]
@ghgary can you confirm it still works in the last version from the playstore 10.1.13?

**Comment by ghgary** [comment]
My phone automatically updated to 10.1.12 sometime last night or this morning and that version works fine. Opening Play Store also showed an Update button for Simpletask, so I executed that which installed version 10.1.13. That version works fine as well. Thanks again.

**Comment by mpcjanssen** [comment]
@ghgary thanks for confirming.
