### ISSUE TITLE
Search not working since last update

### ISSUE THREAD

**Issue by aubreyz** [mpcjanssen/simpletask-android#870]
When no filter set is applied, typing a search filters the items properly.  However the little cross to clear the search filter no longer shows as it did before. 

When any tray filter is active (even one that includes everything) searches do not filter at all, which they previously did perfectly. Both filter as you type and submitting a final search do nothing. 

To clarify: The only way to search for an item currently is to
a) Clear all other filters
b) Type the search
c) And then the only way to undo the search, since there is no indication now that there is a search filter in place, is to go back to search and clear the search. 

(using cloudless version, on latest update)

**Comment by mpcjanssen** [comment]
@aubreyz this should all be fixed in 10.1.5. Sorry for the inconvenience.

**Comment by aubreyz** [comment]
@mpcjanssen - this one seems fixed my end -- perfect.
