### ISSUE TITLE
Trouble syncing on my Nexus 6p

### ISSUE THREAD

**Issue by WNYmathGuy** [mpcjanssen/simpletask-android#873]
Took me a while to decide where on GIT I was supposed to post this.

I'm new to NextCloud. I put the **Simpletask** app on my Nexus 6p. I also have the **DAVdroid** app to sync my calendar and contacts. I also have the **ICSdroid** app and **OpenTasks** (_which does sync properly_) but I don't think those matter. (and obviously, I have the **Nextcloud** and the **Nextcloud Talk** apps)

I was routinely getting a failed to sync status message popping up from the bottom of the screen. Because I didn't know which task app was throwing the message, I put different tasks in each one. (neither synced for different reasons) I added a task to the NextCloud web interface on my server then ran synch on my mobile device. It pushed out to OpenTasks, and that's when I realized their app has a local folder that I put my initial test task in. I have full 2-way synch with OpenTasks. 

I don't know what to do to help you more, but I would like to. Let me know how to help.

**Comment by mpcjanssen** [comment]
@WNYmathGuy can you explain exactly how far you can get:

- [ ] Can you login to the Nextcloud server from Simpletask Nextcloud?
- [ ] Does a file get downloaded?
- [ ] Can you browse Nextcloud when you go to Menu -> Open task list file
- [ ] Can you send the logging from Settings->Other->View debug log?

**Comment by smichel17** [comment]
Also, confirm that you are running Simpletask Nextcloud. There is an f-droid bug causing it to show Nextcloud when it is actually the cloudless version.

**Comment by WNYmathGuy** [comment]
@mpcjanssen 
* I think I'm logged in fine. I get the "success?" screen after the login.
  * ![screenshot_20180308-120138](https://user-images.githubusercontent.com/28640985/37165027-9d64a4f6-22c9-11e8-96c0-417cd1a20883.png)
* I wouldn't know if a file got downloaded. Where do I look?
* Yes! I didn't know that was there yet. (_noob_) I see the list of my particular folders on my NextCloud.
* Yes I can! Also didn't know that was there.
  * [Simpletask nextcloud v10.1.13 (3089) log.txt](https://github.com/mpcjanssen/simpletask-android/files/1794095/Simpletask.nextcloud.v10.1.13.3089.log.txt)

-------------------------------------------------------------------------------------------------
@smichel17 I'm not in the weeds enough to understand you. How would I discover the answer?

**Comment by mpcjanssen** [comment]
Ah again fell for this one.

Simpletask doesn't integrate with the Nextcloud task functionality. It synchronizes with a todo.txt file in the todo folder. So I think it's working as intended. 
You can confirm by checking this file on your Nextcloud server.

**Comment by smichel17** [comment]
The only version on f-droid is cloudless, but f-droid incorrectly reports it at Nextcloud (there is no bug in the app itself, just in the name as displayed in f-droid).

**Comment by WNYmathGuy** [comment]
@mpcjanssen I saw that todo.txt and didn't know why it was there. Now I get it. I falsely assumed that Simpletask was a core component of the NextCloud Tasks app. Your look and feel are there. The login to NextCloud helped me go there in my head. 

@smichel17 Okay. I didn't know about the f-droid software at all. Just searched for it and no I don't have any f-droid managing my apps. (yet)
