### ISSUE TITLE
Renaming a query duplicates it instead

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#879]
Long press -> rename -> choose new name -> new query is created with the new name; old one remains

Cloudless v10.1.13 via fdroid

**Comment by mpcjanssen** [comment]
Works for me. Is this with a new install without saved filters or are you renaming existing filters?

**Comment by smichel17** [comment]
Turns out this only occurs when renaming queries that were created with an earlier version. Updating a query will have the same effect.

Presumably, it's related to the change from generated ids to base64. In either rename or update, a new base64 version is saved, but the generatedId version is not deleted.

**Comment by mpcjanssen** [comment]
Right. No real way around it. Best way to rename the filter and then delete the old version. That should work. If delete doesn't work please reopen the issue.
