### ISSUE TITLE
Share list

### ISSUE THREAD

**Issue by perafon** [mpcjanssen/simpletask-android#880]
I've tried to find a solution to my queries on this forum but im only a happy amateur and dont understand professional programming. 
 
My question is as follows:
Is there a way to share parts of my main todolist with someone who can change the content, and then sync and merge back to my mainlist without duplicates?

**Comment by mpcjanssen** [comment]
You can share parts, if you select tasks and press share, only the selected tasks will be shared. 

Importing changed tasks without duplicates is not possible (how do we know what was the original task). 
Merging tasks in general is only possible if we have a unique identity for a task. `todo.txt` doesn't provide this.

**Comment by smichel17** [comment]
It should be possible to:

1. Select the tasks to be modified
2. Press "share" to share only the selected tasks
3. Person you shared them with modifies them and sends them back to you
4. Copy the text you receive from them
5. Select the same tasks from step 1
6. Press edit, then delete everything in the text box and paste in the modified versions
7. Press save

**Important note: This will not work if the *number* of tasks is modified.** If you want the person you're sharing with to be able to add or remove tasks, you need to replace step 6 with: Delete those tasks, then press the add task button, and then paste the modified tasks as new tasks.

**Comment by perafon** [comment]
Okay, I will try your method smichel17.
 
Thanks for your time and the clarification  over the subject.
