### ISSUE TITLE
Text typed kills itself when orientation is changed from portrait to landscape vice versa

### ISSUE THREAD

**Issue by rp-karanth** [mpcjanssen/simpletask-android#882]
This might be specific to my Android please somebody check and confirm. Whenever I am keying my task, if accidentally the orientation changes then the whole text entered obliterates. 
But when I am updating a task the old text remains same but any new text entered gets deleted when orientation of phone is changed.

Is this a bug?

**Comment by smichel17** [comment]
It is a bug, fixed in the next release. See #843.
