### ISSUE TITLE
Calendar notifications not working

### ISSUE THREAD

**Issue by sebastianopilla** [mpcjanssen/simpletask-android#895]
Using Simpletask Dropbox v10.1.15 on a Nexus 5x phone running Android 8, I have due dates and threshold dates set on a number of tasks, enabled calendar notifications and set the notification time to 10:00. I have checked the "Simpletask Reminders" in the Google Calendar app, the default notification for this calendar is set to "10 minutes before".

**Expected result**
The tasks entered in Simpletask appear in the Google Calendar app, notifications appear near the threshold date and the due date.

**Actual result**
None of the task entered in Simpletask show up, notifications do not appear.

**Comment by mpcjanssen** [comment]
@sebastianopilla you did have the calendar sync settings enabled? I assume you do, but I have to ask.

**Comment by vojtechkral** [comment]
Is there a log?

**Comment by sebastianopilla** [comment]
It turns out, embarassingly, that it was an _operator error_.

The "Due date reminders" and the "Threshold date reminders" checkboxes were both on, so I tried the old _turn it off and on again_. When I checked the "Due date reminders" checkbox I saw an Android dialog box asking me to grant to Simpletask the permission to access my calendar, which I couldn't remember having seen before.

Of course, once granted the proper permission, the reminders appeared correctly in my calendar and I got a notification for a test task today, at the time configured in Simpletask.

**Comment by mpcjanssen** [comment]
Good it's solved. Funny thing is that the latest lint tooling from google actually detects this scenario now and gives a warning that some calendar calls can fail because of permissions and need to be handled.

**Comment by sibelius1269** [comment]
I have this same problem. Y use a Huawei Honor 9 with Android 8.0.0 (layer Emui). Nothing I have tried has solved this bug
