### ISSUE TITLE
todo.txt inside folder

### ISSUE THREAD

**Issue by pprw** [mpcjanssen/simpletask-android#897]
My todo.txt is inside a "todo" folder on the root of my nextcloud account. This folder contains also a done.txt and a report.txt.

There is no way to indicate to Simpletask to read todo.txt from this folder. The folder is displayed when I click "open todo.txt file" but I cannot access files of the second level.

I also tried to set the nextcloud address to https://mynextcloud.com/todo without success.

Is SimpleTask only supporting todo.txt at the root?

**Comment by pprw** [comment]
In fact, it doesn't work either when opening a todo.txt at the root. It seems I have a permissions issue, maybe related to oreo?

**Comment by mpcjanssen** [comment]
No, selecting a `todo.txt` anywhere else should work.
Do you see any errors in the logging ? Settings -> Other -> View debug log?

**Comment by bushrang3r** [comment]
A few versions ago, I had this issue but it seems to work for me now.

**Comment by mpcjanssen** [comment]
If it re-occurs please attach the log and re-open.
