### ISSUE TITLE
Add Serbian to weblate

### ISSUE THREAD

**Issue by stalker314314** [mpcjanssen/simpletask-android#900]
Not sure if this is proper way to ask for it, but I would be interested in translating simpletask to Serbian, but I am not seeing it in Weblate. Can you please bootstrap it? If I can do it, or request over there, LMK!

for reference: https://hosted.weblate.org/user/stalker/

**Comment by mpcjanssen** [comment]
Thanks for offering. I have started the weblate Serbian translation.
See https://hosted.weblate.org/projects/simpletask/strings/sr/
