### ISSUE TITLE
Quick Filter refreshes after click

### ISSUE THREAD

**Issue by jorgb** [mpcjanssen/simpletask-android#901]
Hi,

I have about 26 contexts and projects. When I click one outside the visible range (I have to scroll for it), the list resets to the beginning. This is quite cumbersome if you just want to see how many  tasks some projects or contexts have.

Android 7.0
Samsung Galaxy Edge S7

With regards,
- Jorgen

**Comment by smichel17** [comment]
Pretty sure there is an open issue for this already. I looked into it and it's not a trivial fix (although I want to do it; it annoys me, too).

**Comment by jorgb** [comment]
Thank you for replying, it's nice to see that SimpleTask has evolved over
the years. Took a side step on something else but simplicity beats all!

- Jorgen

**Comment by smichel17** [comment]
I'm going to close this in favor of #820
