### ISSUE TITLE
Wrong placement of task in todo.txt after priority modification

### ISSUE THREAD

**Issue by archphile** [mpcjanssen/simpletask-android#905]
Hi,

I am using latest Simpletask 10.1.16 (Nextcloud) and I noticed that if I have a task with ex. priority A, when I change to another priority, ex. C, it remains in the line it was with the previous priority.

**Example:**

Lets say that we have the following list:

> _A first task
> A second task
> B third task_

I now modify the priority of first task to C. 

What Simpletask does is:

> _C first task
> A second task
> B third task_

Instead of:

> _A second task
> B third task
> C first task_

It's a very minor issue, as everything still work ok, but it confuses people like me that sometimes edit and use todo.txt with plain text editors.

Regards,
Mike

**Comment by mpcjanssen** [comment]
This is by design. Simpletask doesn't modify the order of existing tasks and whitespace.

**Comment by archphile** [comment]
Ok, 

thanks for the immediate reply.

Regards,
Mike
