### ISSUE TITLE
Can't save new tags or lists to a task

### ISSUE THREAD

**Issue by doranism** [mpcjanssen/simpletask-android#907]
(in Cloudless, also in the recent debug version)

Steps to reproduce:
Select a task, open the dialogue for tags or lists, enter a new tag or list, hit enter > close keyboard > OK

Expected result:
Add new tag or list to task.

Actual result:
Nothing is added to the task.

Same thing if added from the task edit screen. Only typing them manually to the task text works. 

Would be nice if you could look after that. Thank you for your great app!

**Comment by mpcjanssen** [comment]
I cannot reproduce this issue. Can you attach the debug logging?

**Comment by doranism** [comment]
Here is the log:
--------- beginning of /dev/log/main
W/dalvikvm( 9565): VFY: unable to resolve static method 19040: Landroid/view/PointerIcon;.create (Landroid/graphics/Bitmap;FF)Landroid/view/PointerIcon;
W/dalvikvm( 9565): VFY: unable to resolve static method 19042: Landroid/view/PointerIcon;.load (Landroid/content/res/Resources;I)Landroid/view/PointerIcon;
W/dalvikvm( 9565): VFY: unable to resolve virtual method 20467: Landroid/widget/Spinner;.getPopupContext ()Landroid/content/Context;
E/dalvikvm( 9565): Could not find class 'android.widget.ThemedSpinnerAdapter', referenced from method android.support.v7.widget.AppCompatSpinner$DropDownAdapter.<init>
W/dalvikvm( 9565): VFY: unable to resolve instanceof 2584 (Landroid/widget/ThemedSpinnerAdapter;) in Landroid/support/v7/widget/AppCompatSpinner$DropDownAdapter;

I use Android v4.2 if that is of interest.

**Comment by mpcjanssen** [comment]
That doesnt help much. Do you use anything which reduces the log level on the phone like a custom kernel?

Also does the tag never display or does it not get saved to file

**Comment by mpcjanssen** [comment]
Also, which recent debug version did you use? And can you check if there is any difference with the version from https://mpcjanssen.nl/artifacts/

**Comment by doranism** [comment]
When I type in a new tag, it is added to the list of tags with a blue check as expected. When I hit "OK", the menu closes but the new list or tag is not saved to the task.

As I played around, I noticed that this bug must be related to the big amount of tags and lists I am using (20 +10 at the moment), because all worked as expected with another todo.txt file with just five tags. 

Can you reproduce it, if you add so many tags so that the lower part of the list in the tag adding screen lies under the keyboard? In this case the only way to reach OK is to close the keyboard with the android "back" button.

I use this debug version: https://mpcjanssen.nl/artifacts/app-cloudless-debug.apk but it occurs with cloudless v 10.1.16 from f-droid too.

**Comment by mpcjanssen** [comment]
Thanks for the additional info. I can reproduce it now. Adding any new tag doesn't work

**Comment by mpcjanssen** [comment]
That is when you press enter and then press OK.  Directly pressing ok when the tag is in the textbox does work.

**Comment by mpcjanssen** [comment]
Same for lists.

**Comment by mpcjanssen** [comment]
@doranism latest CI builds appearing at  https://mpcjanssen.nl/artifacts/ should have this issue fixed.

**Comment by doranism** [comment]
Ah, yes. I didn't try this.

**Comment by doranism** [comment]
I tested your update: works like a charm now. Thank you!

**Comment by doranism** [comment]
Do you think it is possible to make the tags/lists list scrollable to the bottom so that the OK button is not overlayed by the keyboard? I remember that this confused me, when I started to use ST. Another possibility would be to close the keyboard after pressing the "done" button and reopen it, if the cursor is set to the input field to type in another tag/list.

**Comment by mpcjanssen** [comment]
Handeling keyboard visibility is anything but trivial in Android. #785 covers this issue.
