### ISSUE TITLE
Lua scripting: "field text" parameter not properly returned if it contains numbers or URLs.

### ISSUE THREAD

**Issue by ddisanti** [mpcjanssen/simpletask-android#909]
If the field text parameter (a.k.a. ``f.text``) contains numbers they are removed in the returned string by any callback.

Example task:

```2018-07-01 1234 Task text with some 33-33 random numbers 12345678 @a +b due:2019-01-01 t:2019-01-01```

Example function (not a useful one, it is just to help me explain myself)
```
function onDisplay(t, f, e)
 return f.text
end
```
Expected result

```1234 Text with 33-33 random numbers 12345678```

Actual result:

```Text with random numbers```

This happens especially if the numbers are at the beginning and at the end of the task text.

**Comment by mpcjanssen** [comment]
Can be fixed by extending the use of 5d8c983773121b219c9f0a9b89ae2f0f557540f9 to the Lua code

**Comment by ddisanti** [comment]
The same happens if the task text contains an URL.

**Comment by mpcjanssen** [comment]
This currently works as designed. What would your definition of the text of a task be? Asking this question to 10 different people might give 10 different answers.

**Comment by ddisanti** [comment]
> What would your definition of the text of a task be?
It would be all the full text entering when adding a task without the keywords and/or string that are part of the todo.txt format (due:, t:, create date, @context, +project, etc).

**Comment by smichel17** [comment]
+1, we may be able to add special actions for URIs, phone numbers, etc, but unless they're extensions they're still part of the text

**Comment by ddisanti** [comment]
@mpcjanssen this seems to be fixed  in latest builds from  https://mpcjanssen.nl/artifacts

**Comment by mpcjanssen** [comment]
Thanks for confirming.
