### ISSUE TITLE
Update google play screenshots

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#92]
The current google play screenshots are not up to date anymore. They need to be updated.

**Comment by okurz** [comment]
screenshots look fine to me. maybe screenshot were updated in the meantime? solved?

**Comment by vojtechkral** [comment]
They seem old to me. Definitely not material design.

**Comment by mpcjanssen** [comment]
The screenshots are ancient. Will need to update them.

**Comment by mpcjanssen** [comment]
Closed, see #338
