### ISSUE TITLE
All available lists does not appear in list dialog

### ISSUE THREAD

**Issue by nthorne** [mpcjanssen/simpletask-android#937]
Only a select few of my lists show up in the lists dialog. Version 10 2.5

**Comment by nthorne** [comment]
It looks like the lists dialog actually contains the lists of the selected tasks as well as the tags, but not all available lists.

**Comment by mpcjanssen** [comment]
Fix included in 10.2.6

**Comment by nthorne** [comment]
Nicely done! Thanks!
