### ISSUE TITLE
List sorting order

### ISSUE THREAD

**Issue by nthorne** [mpcjanssen/simpletask-android#938]
I use multiple lists for my tasks; e.g @1. Monday and @@home. Previously sorting by list organised the tasks into lists by list names, sorted alphanumerically; now it's by order of list appearance in task. It'd be nice to at least have the option to have alphanumeric sorting.

**Comment by mpcjanssen** [comment]
Ignore that commit. It fixed #936 and #937.

**Comment by mpcjanssen** [comment]
Currently the task list 

```
Test @@1
Test @@@home
Test @Monday
```

has the lists sorted as

```
@1
@@home
Monday
```

How was it before?

**Comment by mpcjanssen** [comment]
The sorting of the lists in the navigation drawer should now be consistent with the grouping. Before it wasn't and that was a bug.

**Comment by nthorne** [comment]
Previously it always grouped alphabetically, eg

Do things @@1.monday @@home
Do more things @@home 1.monday

Yielded

1.monday
Do things
Do more things

Whereas now it yields
1.monday
Do things

Home
Do more things

**Comment by mpcjanssen** [comment]
Ah I understand. The lists coming from a task are not sorted now. This is causing several issues.
