### ISSUE TITLE
When closing the add task screen with X confirmation should be asked if there are changes

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#94]

**Comment by smichel17** [comment]
This seems like pretty low-hanging fruit? Or is it currently difficult to check if changes have occurred?

**Comment by mpcjanssen** [comment]
Not difficult. I will look into this.

**Comment by smichel17** [comment]
I propose never to fix this.

- Discarding changes with the upper left `X` is hard to do by accident.
- When you actually do want to discard changes, it adds an annoying extra tap
- Confirmation dialogues are not that effective anyway.
  - If you do the action often, you form a habit of clicking through them without thinking, which defeats the purpose of a confirmation dialogue. Undo is much better, for this reason.
