### ISSUE TITLE
Reverting to top of list for every action

### ISSUE THREAD

**Issue by sarana1** [mpcjanssen/simpletask-android#941]
Hi,

I find it terribly annoying that the app scrolls back to the top of the list every time I perform a function in the app, i.e. adding a task(which is probably after a sync each time). I would rather it remember where I was and stay/go back there, or at least have that option in the settings.

I use the latest version 10.2.6 on Android 6.0.

I use this almost everyday, so THANK YOU!

Sebastián

**Comment by smichel17** [comment]
Are there any actions aside from adding a task that reset the position when you'd rather it be remembered?

**Comment by sarana1** [comment]
I'll keep an eye out for others, but I know editing a task does this, too,
although if a search is underway, it does not do this.

If I find any others, I'll let you know. Those two actions, adding a task,
and editing a task, are things I do frequently, hence, my annoyance.

Thanks, again!

Sebastián

**Comment by sarana1** [comment]
And I don't know if it helps, but I keep my sorting at priority first
(pointing down). The app just moves back to the top (the "A's" in my case)
every time I perform the above actions, even if I'm working from the "D's,"
for example. And by editing, I don't meaning changing the priority with
your "star" icon, I mean changing the text of the todo item with the editor.

**Comment by sarana1** [comment]
Also, I just realized that it reverts to the top of the file when I exit
the app, then go back in.

Thanks,

Sebastián

**Comment by mpcjanssen** [comment]
Fixing this is harder than it seems. I have tried unsuccessfully to fix this a couple of times already.

**Comment by sarana1** [comment]
That's fine, man. I appreciate the effort. I was just providing all the
info I could.

Thanks,

Sebastián

**Comment by michaelcoyote** [comment]
I'm seeing this too. This is my only issue with the app so far.

**Comment by sarana1** [comment]
Something that might alleviate the issue is adding a scroll bar on the side of the screen to make scrolling through the app faster.  That would be nice, and maybe easier to implement. Thanks! I know Pandora has one and it shows the letter of the first entry as you scroll by. I don't know if the latter is necessary . . . .

**Comment by jan-gerard** [comment]
Maybe it's possible to store the scroll position when scrolling or re-ordering occurs.
Then, if no manual scroll was triggered, but the current scroll position appears different from the previous (after turning screen of and back on for exae) , the app could move to the stored position.

**Comment by mpcjanssen** [comment]
@jan-gerard that is what the code tries to do now, but it doesn't work

**Comment by jan-gerard** [comment]
Ah, I didn't know that. Is the stored scroll position lost after screen off/on, or does the programmatic scrolling to restore the position not work?

**Comment by mpcjanssen** [comment]
Restoring doesn't seem to work.

**Comment by mpcjanssen** [comment]
development branch should now properly restore the scrolling position.

**Comment by jan-gerard** [comment]
Great! Glad you fixed it. Do you want me to test it somehow?

**Comment by mpcjanssen** [comment]
@jan-gerard you could try a development build from https://www.mpcjanssen.nl/artifacts

**Comment by mpcjanssen** [comment]
Fixed in 10.3.3

**Comment by sarana1** [comment]
Amazing! Thank you!
