### ISSUE TITLE
Switch symbols for classic GTD terms

### ISSUE THREAD

**Issue by ajfriesen** [mpcjanssen/simpletask-android#944]
I want to use the original terms by David Allen and the GTD concept which is possible.
Everything looks fine but the only thing that bothers me are the symbols which are used when adding and editing entrys:
 
* The List symbol is for context.
* The Tag symbol is for project.

Is it possible to just change these symbols?

The tag symbol should contain the "context" and the list symbol should contain the "project".
Since a project always has more than one thing to do and a context can stand for itself.

I always see myself touching the wrong button and this drives me nuts ;-)

**Comment by ajfriesen** [comment]
I think this would be a great solution too, even better when this is easier for you.

**Comment by gladomat** [comment]
Why not let users edit these names? I'm not sure how hard it is to implement.

**Comment by mpcjanssen** [comment]
@gladomat nothing is really "hard" it's all just work though. Most notably making the UI to change it and adding the logic to retrieve at all the proper spots.
