### ISSUE TITLE
Switch position of due date and begin date

### ISSUE THREAD

**Issue by ajfriesen** [mpcjanssen/simpletask-android#945]
As a daily user I often see myself using the wrong button when it comes to due dates and begin dates.

Why?

* For me the begin date should be the first date to set (if intended) but the symbol is on the far right.
* The due date is the last date you want to set (if intended) but the symbol is not the last one in the row.

It would be convenient if you just swap the positions for a logical order.

**Comment by smichel17** [comment]
Related: #419
