### ISSUE TITLE
Donation button will get to PayPal page in dutch

### ISSUE THREAD

**Issue by ajfriesen** [mpcjanssen/simpletask-android#946]
I wanted to donate some gold coins via your donate button for your awesome work ;-)

But the PayPal page was in dutch which I do not understand.

You can easily change the locale in the URL to German (in my case) or English but this is not obvious for everyone.

Maybe change the link to the device language or at least to English as fallback?

**Comment by mpcjanssen** [comment]
I will change it to a version without locale so it should take your preferred language:

https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=mpc%2ejanssen%40gmail%2ecom&item_name=mpcjanssen%2enl&item_number=Simpletask&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted
