### ISSUE TITLE
Sort alphabetically divides in tasks with capital and small first letter

### ISSUE THREAD

**Issue by Strubbl** [mpcjanssen/simpletask-android#949]
The sorting feature currently sorts the tasks alphabetically, but lists all tasks with capital letter first and afterwards all tasks with small first letter.

Current:
A1
A3
B
C
a2
b
c

It would be nice if the above list of tasks could be sorted independet of the first letter being small or capital:

A1
a2
A3
B
b
C
c

**Comment by mpcjanssen** [comment]
@Strubbl did you disable the sort case dependent setting? (In Other)

**Comment by Strubbl** [comment]
No, sorry. I had not seen that option although i took  a look in the settings. Thank you.
