### ISSUE TITLE
tasks without list/context sorting

### ISSUE THREAD

**Issue by Gregory-K** [mpcjanssen/simpletask-android#962]
Hello,
is there a way to sort tasks which have nor list or tags at the bottom?

Case study: sometimes I just write down ideas of tasks to look up to them at a later time. It 's a quick process, no tags no lists. I think it will be more convenient for this workflow these tasks to be grouped as `n/a` at the bottom of the list and not alphabetical as `none` (they get in the way of more properly categorized tasks).

The only way I found till now, is to use an inverted filter but that means just more clicks to show and hide them.

Just a thought ...
Thanks for this great app anyway

**Comment by mpcjanssen** [comment]
If the inverted filter works for you, you can save it the right drawer to reduce the clicks.

**Comment by Gregory-K** [comment]
yep, I found it already

thanks
