### ISSUE TITLE
option for recurring

### ISSUE THREAD

**Issue by MarkoShiva** [mpcjanssen/simpletask-android#972]
Can you add the option to have yeah recurring also reminders and app would be complete.

**Comment by colinsullivan** [comment]
+1 for recurring

Other tools use the syntax:

`rec:1w` (for 1 week from completion date)
`rec:+1w` (for "strict" recurring one week from due date)

**Comment by mpcjanssen** [comment]
rec is supported and calendar integration is also there. What is missing exactly?

**Comment by colinsullivan** [comment]
Ah okay cool, I was confused - good for my needs 👍
