### ISSUE TITLE
nextcloud: can't save outside LAN

### ISSUE THREAD

**Issue by jpalczewski** [mpcjanssen/simpletask-android#973]
Hello,

Recently I have discovered weird issue: when I'm connected to self-hosted LAN everything works correctly, but when I'm trying to connect over internet - saving of Todo file fails.
It isn't an issue related to nextcloud instance (davx5 and nextcloud clients work). Log:
```
05-06 16:00:20.975 18863 18863 I TodoList: Saving instead of loading
05-06 16:00:20.975 18863 18863 I Util    : Sending file sync start broadcast
05-06 16:00:20.977 18863 18863 I FSQ     : -> Save
05-06 16:00:20.979 18863 18932 I FSQ     : <- Save
05-06 16:00:20.999 18863 18932 I TodoList: Saving todo list, size 4
05-06 16:00:21.002 18863 18932 I FileStore: Saving to file /todo.txt
05-06 16:00:21.013 18863 18932 D OwnCloudClient #0: REQUEST PUT /remote.php/webdav/todo.txt
05-06 16:00:21.116 18863 18932 D OwnCloudClient #0: REQUEST PROPFIND /remote.php/webdav/todo.txt
05-06 16:00:21.191 18863 18932 E TodoList: TodoList save to /todo.txt failed
05-06 16:00:21.191 18863 18932 E TodoList: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
05-06 16:00:21.191 18863 18932 E TodoList: 	at nl.mpcjanssen.simpletask.remote.FileStore.saveTasksToFile(FileStore.kt:154)
05-06 16:00:21.191 18863 18932 E TodoList: 	at nl.mpcjanssen.simpletask.task.TodoList$save$1.invoke(TodoList.kt:298)
05-06 16:00:21.191 18863 18932 E TodoList: 	at nl.mpcjanssen.simpletask.task.TodoList$save$1.invoke(TodoList.kt:21)
05-06 16:00:21.191 18863 18932 E TodoList: 	at nl.mpcjanssen.simpletask.util.ActionQueue$add$1.invoke(ActionQueues.kt:16)
05-06 16:00:21.191 18863 18932 E TodoList: 	at nl.mpcjanssen.simpletask.util.ActionQueue$add$1.invoke(ActionQueues.kt:9)
05-06 16:00:21.191 18863 18932 E TodoList: 	at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Async.kt:143)
05-06 16:00:21.191 18863 18932 E TodoList: 	at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Unknown Source:0)
05-06 16:00:21.191 18863 18932 E TodoList: 	at org.jetbrains.anko.AsyncKt$sam$java_util_concurrent_Callable$0.call(Unknown Source:2)
05-06 16:00:21.191 18863 18932 E TodoList: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-06 16:00:21.191 18863 18932 E TodoList: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
05-06 16:00:21.191 18863 18932 E TodoList: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-06 16:00:21.191 18863 18932 E TodoList: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-06 16:00:21.191 18863 18932 E TodoList: 	at java.lang.Thread.run(Thread.java:764)
05-06 16:00:21.193 18863 18932 I Util    : Sending file sync done changed broadcast
```
I tried to login again today outside wifi, if I remember correctly there was an issue related to 403 forbidden.

**Comment by mpcjanssen** [comment]
Was there a conflict in the file while saving?

**Comment by jpalczewski** [comment]
Nope, even logging out and trying to login again failed - I don't remember now, but message in-app was a bit different(something near 500).

**Comment by mpcjanssen** [comment]
Does updating to the last version make any difference?

**Comment by jpalczewski** [comment]
Sorry for late answer: now from 10.3.1  i tried to return to your app and possible reason was found:
11-07 12:27:30.039 21658 22058 E GetRemoteUserInfoOperation:             <p>The owner of this website (domain) has banned your access based on your browser's signature (id).</p>
peek into cloudflare firewall says that its the issue with Browser Integrity Check. Happily it can stay enabled domain-wide and two page rules applied allows simpletask to work  correctly

**Comment by mpcjanssen** [comment]
The nextcloud client sets a specific user agent. This could be related.

**Comment by mpcjanssen** [comment]
Hmm seems like a red herring. The Simpletask code specifically requests to use the Nextcloud UA

**Comment by mpcjanssen** [comment]
Could you try again with the nextcloud version from: https://www.mpcjanssen.nl/artifacts/

**Comment by jpalczewski** [comment]
>The nextcloud client sets a specific user agent. This could be related.
That was my thought yesterday also, in Cloudflare logs it appears as `Jakarta Commons-HttpClient/3.1` which may be blacklisted by CF (there's ongoing scan attempt by `Python-urllib/2.7`)
To the point:  I have installed debug version and disabled pagerules and results are:
 - debug version works flawlessly
 - recent play store version dies sends `saving of todo.txt file failed' with similar NPE  error log as in issue
So we can say thatt this issue is fixed Thanks for your work!
