### ISSUE TITLE
Smart Date Recognition and Daily Review in the Simpletask app

### ISSUE THREAD

**Issue by ammarraisafti** [mpcjanssen/simpletask-android#976]
# Components
The following are the features that I want to recommend:

- Smart Date Recognition 
- Daily Review

# Proposal
Propose to the Simpletask application developer, to add the "Smart Date Recognition" feature in the application settings section, in the Feature section, and give the user access to enable the feature, and give the user benefit information gained if the user activates it. And propose to the Simpletask application developer to add the "Daily Review" feature in the notification settings section, as well as give the user access to activate it and give the user some options in it, which feature send notification at feature, Only Show With tasks feature and Include Overdue tasks feature. And developers should provide information about the benefits.

# Mockups / Examples
Here is an example of a picture of the two features I proposed, the "Smart date recognition" feature and the "Daily Review" feature.

- Example image placement section features Smart date recognition
![Screenshot_20180307-132622-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520761389/blh8q3ys0a77j8kbcdkv.png)

- An example of a section image that should be modified by the developer
![Screenshot_20180307-132622-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520761406/yawqdwyq65wzovzjmu7t.png)

- An example image after the developer adds the Smart date recognition feature in the Feature section and gives the user information about the feature.
![Screenshot_20180307-132622-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520761451/xhdj3okszuxuhsidomj6.png)

- Sample image of placement section features Daily Review.
![Screenshot_20180307-132622-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520761994/zjm5lvdgqoslucrzv6cx.png)

- An example image after the developer adds the Daily Review feature in the notification area
![Screenshot_20180307-132622-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520762178/uinjcmddn9dti3oveuzm.png)

- An example of a picture after the user selects and opens the Daily Review feature.
![Screenshot_20180312-234603-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520874669/h7koqmebwo7h4663qf3k.png)

- An example of a picture after the user activates the Daily Review feature.
![Screenshot_20180312-234603-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520874619/irfzoid32s84nmmus4vl.png)

- Example image after user activate Daily Review feature, and choose send notification at feature, then user can set time as desired.
![Screenshot_20180312-234603-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520873460/ne93aitoapa5ncgyfdsx.png)

- An example of a picture after the user activates the show only features with tasks and features include overdue tasks, and gets information about both features.
![Screenshot_20180312-234603-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520873556/erucas8anbign16h3vwu.png)

# Benefits
With the Smart date recognition feature in the Simpletask app, users can use the feature to automatically detect due dates in tasks, and it is a great advantage for the user. So users feel very happy with the presence of these features in the application Simpletask, and invite other users to download this application. And with the presence of the "Daily Review" feature in the Simpletask app, users can use the feature for send notification at, the user can also show if there are tasks planned, and show overdue tasks as well as today's tasks.

**Comment by mpcjanssen** [comment]
Thank you for the extensive request.
For now all this can be done with customized Lua filters. The main reason to include Lua is to allow a user to make very specific views based on his/her workflow.
Adding specific views like this not only is a considerable amount of work which is only usable for a limited amount of users. So this is very unlikely to be added. I am open to suggestions of making specific views more accessible.

**Comment by mpcjanssen** [comment]
Also I don't understand the due date detection. Due dates in tasks are recognized.
