### ISSUE TITLE
crashing after inserting a newline into a task

### ISSUE THREAD

**Issue by pierrefrancois** [mpcjanssen/simpletask-android#980]

**Comment by pierrefrancois** [comment]
I gave my phone to another person for inserting her email after her name into a task that was open for editing. She probably hit the enter key during the input (see todo.txt attached) and since that day, the app is always crashing with message "Simpletask has stopped".
[todo.txt](https://github.com/mpcjanssen/simpletask-android/files/3249190/todo.txt)

**Comment by mpcjanssen** [comment]
I have downloaded the file, and it works without problems for me. (I also deleted it from here as it has private info). How did you install the app? Did you install it from playstore or fdroid?
Any possibility you can send a crash report or adb logcat?

**Comment by mpcjanssen** [comment]
Also how do you sort the list?

**Comment by pierrefrancois** [comment]
Thank you Mark for removing my private info from the web.

I think I was using the F-droid version of the app. I didn't collect any 
crash report.

I removed the app and installed the Simpletask Dropbox from Google Play, 
edited the *todo.txt* for removing the unwanted line breaks and put it 
inside of the *~/Dropbox/todo* directory, and now, Simpletask (Dropbox) 
is again in the air.

If you tell me where to lookfor the logs, I can still send these to you, 
if still present.

Kind regards.

Pierre

**Comment by pierrefrancois** [comment]
Since I uninstalled the F-droid version of Simpletask and installed a 
working version (Simpletask Dropbox) from Google Play, I no longer can 
figure it out. I don't remember, sorry.

**Comment by mpcjanssen** [comment]
You could install the Cloudless version from the Play store and reopen the same (local) file you used with the cloudless version from F-Droid (if you still have that on your phone). Then a crash would allow you to report the issue.

**Comment by pierrefrancois** [comment]
Hello Mark

I am sorry, but the app belongs to a production environment, accessed 
also by other software. I can no longer experiment with it.

Since my file *todo.txt* didn't crash the app in your environment, and I 
was probably using an old version of the app, it will probably no longer 
crash. I suggest you to close the issue. If something happens again, I 
will reopen this issue.

Met dank voor alle moeite.

Pierre
