### ISSUE TITLE
Add "TASK PROGRESS" feature in the SimpleTask app

### ISSUE THREAD

**Issue by ammarraisafti** [mpcjanssen/simpletask-android#981]
# Components
The following are the features that I want to recommend:

- TASK PROGRESS 

# Proposal description
Propose a new feature in the SimpleTask app. 

- Add the TASK PROGRESS feature in the SimpleTask app at the top of the shortcut menu option.

- Modify the TASK PROGRESS feature section to provide some important features in it, such as ALMOST DONE, HALFWAY THERE, WAY TO GO, NOTHING ACCOMPLISED, and DONE features.

- The developer should display the ongoing TASK PROGRESS information, and provide the user with information on the TASK number, in each feature that has been added.

# Mockups / Examples
- An example image after the developer adds the TASK PROGRESS feature at the top of the Simpletask app selection shortcut.
![Screenshot_20180301-105137-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520570149/otwuabfriwem9gyerpwb.png)

- An example image after the developer provides several feature options in the TASK PROGRESS section.
![Screenshot_20180301-105137-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520570678/aqdjsmcw0abqkx3mxlbp.png)

- An example image after the developer provides TASK PROGRESS information on each feature provided, to give the user TASK number information on each of these features.
![Screenshot_20180301-105137-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520570859/j851sopojad5zashozed.png)

# Benefits
Simpletask application users will be more interesting using Simpletask application after the developers add TASK PROGRESS feature, kare users Simpletask application can find information about TASK that has been created by using TASK PROGRESS feature, Users can find information about the number of tasks that have been created, because the developer provides some features to display TASK information in accordance with the choice when creating tasks in the Simpletask app, such as date order, and many more. And it is very awesome and useful for users. So users feel very happy with the presence of these features. And give the star Rating five for the Simpletask app.

**Comment by mpcjanssen** [comment]
Not going to work with a non standard extension to the todo.txt format. How are you going to store the progress on a task?
