### ISSUE TITLE
CSS class of bold text?

### ISSUE THREAD

**Issue by hut** [mpcjanssen/simpletask-android#983]
Hi,

I'm trying to style bold text with a custom CSS, but I can't figure out what CSS selector to use.

For italic text, "em" works, but styling the "b" tag has no effect. Any ideas?

**Comment by mpcjanssen** [comment]
How are you using css for styling?

**Comment by mpcjanssen** [comment]
You mean in the embedded documentation?

**Comment by hut** [comment]
Well, this is awkward. I opened this issue in the wrong GitHub project. Sorry!

Then let me take this opportunity to say thanks for this excellent app. I've been using it for years and always come back to it. :) It's simple, yet powerful & extensible enough to cover so many use cases.

**Comment by mpcjanssen** [comment]
No problem, thanks for closing it to confirm I wasn't losing it :grin:
