### ISSUE TITLE
LUA script - help filtering by week

### ISSUE THREAD

**Issue by mimmori** [mpcjanssen/simpletask-android#985]
I am not LUA expert programmer but I usually write code in other languages.
I tried to write a script for filtering all tasks with due date before the end of the week but I have some troubles to determine the limit of condition for determine the visibility.

Is there someone that has realised something similar?

**Comment by hiqua** [comment]
You want to check if the week number of the task is lower or equal to the current week number.

If the ISO week number works for you (e.g., your weeks start on Mondays), you can use `os.date("%V")` to get the current week number, and `os.date("%V", d)` to get the week number corresponding to the due date `d`. From the documentation, I assume that `d` is in the right format.

**Comment by smichel17** [comment]
> Post your filter once you've succeeded, other people could use it maybe (I think we should have some folder with a lot of such examples).

I've wanted to do this for a while. I think the best way might be to put some common helper functions, commented, into the default global lua config.

**Comment by mimmori** [comment]
I have some trouble with the solution suggested.

I tried this:

function onFilter(t,f,e)
  if f.due~=nil then
    return os.date("%V", f.due) <= os.date("%V");
  else 
    return false;
  end
end

but it seem not working because the task will be always shown even if the due date is far away from now

**Comment by hiqua** [comment]
The format "%V" may not be supported by the Lua engine used (and its C library), and I think that os.date("%V") just fails silently (@smichel17 I guess this is intended, but wouldn't it be better if the script just failed instead? E.g., having only `os.this_function_does_not_exist()` in an `onFilter` function will show every task rather than failing).

 So another option would be:
* check if the difference between the date is less than one week (`7*24*60*60 seconds`)
* if it is, then check that the task week day is higher than the current week day (to avoid showing tasks due by Tuesday if today is Saturday)

You can access the week day using `os.date("*t").wday` and `os.date("*t", f.due).wday` (more about this there: https://www.lua.org/pil/22.1.html).

**Comment by mimmori** [comment]
Now it works correctly. Thanks.

Below an extract of the code to help who need it.

```
function onFilter(t,f,e)
  if f.due~=nil then
    diffTime = f.due - os.time(); 

    -- week day start from monday(1) to sunday(7)
    taskWday = os.date("*t", f.due).wday-1;
    if(taskWday == 0) then
      taskWday = 7;  
    end

    currWday = os.date("*t").wday-1;
    if(currWday == 0) then
      currWday = 7;
    end

    return ((diffTime <= 604800) and (taskWday >= currWday));  -- 604800=7*24*60*60
  else 
    return false;
  end
end
```

**Comment by mpcjanssen** [comment]
I would prefer to keep the Lua stdlib file lean, so no large amount of commented code. I will create a scripting examples md file in the help assets. Snippets can then be added by PRs to this file.

**Comment by mpcjanssen** [comment]
See #992

**Comment by smichel17** [comment]
Sorry it took me so long to get around to posting this, but here's some stuff from my Lua config that might be helpful, too:

```lua
DAY=86400
WEEK=DAY*7
--now=os.time()

function inPast(time)
  now=os.time()
  return time ~= nil
      and time < now
end

function inLast(period, time)
  now=os.time()
  return time ~= nil
      and time < now
      and time >= (now - period)
end

function inNext(period, time)
  now=os.time()
  return time ~= nil
      and time > now
      and time <= (now + period)
end
```
Example usage:
```lua
function groupToday(f)
  return f.priority == "A"
    or inLast(2*DAY, f.due)
end
```

**Comment by smichel17** [comment]
@mpcjanssen I don't mean adding functions to the stdlib, I mean pre-populating the user's lua config with some common helpful functions, which can then be edited or deleted if they want.

**Comment by mpcjanssen** [comment]
@smichel17 ah right, I do not know if parsing all the commented code would make startup slower. I still prefer to add it to the help instead.
