### ISSUE TITLE
Improve vertical space utilization on Edit screen

### ISSUE THREAD

**Issue by OSupporter** [mpcjanssen/simpletask-android#990]
The Edit screen UI could be improved if the whitespace wasted (at least apparently on a Pixel 3) below a longer To-Do task was filled with the task text instead of reserved as blank white-space (see attached screen-shot red mark-up).  In addition, if one of the 3 horizontal bars could be eliminated by rearranging the icons elsewhere it could further add to the vertical space in the task text Edit field, which would make task editing more productive than a 3 line or so pane as it stands now (on my Pixel 3 anyway).  Thank you for your consideration of this enhancement and let me know if you have any questions.  
![SimpleTask_Edit](https://user-images.githubusercontent.com/52611049/60761367-d8498e00-a014-11e9-847d-870cda2d6975.jpg)

**Comment by mpcjanssen** [comment]
Wasted space at botteom of edit text is a bug. I will not move the buttons (I really like them like this)
