### ISSUE TITLE
[Bug] Clear all the text in the "Update" page and updating again can double the same task

### ISSUE THREAD

**Issue by junior291492659** [mpcjanssen/simpletask-android#993]
#### General information

* **App version:**  10.3.0(the latest version in the google play )
* **System:** Android 6.0 (can be reproduced on an Android emulator 6.0 and a Redmi Note 4X phone )

#### Description
    
  I install the version 10.3.0 and start the app, click the floating button to create a task named "Task1" successfully, then click the task, click the "update" icon below to the "Update" page and clear all the text, click save to go back to the main page.
  
  Then I click the task, click the "update" icon below again to the "Update" page. It is confusing that there are doubled the cleared text. And if I click BACK now to return to the main page, the "Task1" get doubled. Also it can get tripled as long as I repeat this operation again. This is strange and can be a bug somehow.

#### Reproducing video
[https://youtu.be/jrfuYIOTwfM](https://youtu.be/jrfuYIOTwfM)

Thanks for your amazing application.
It would be really appreciated to get your concern on this.

**Comment by mpcjanssen** [comment]
Thanks for the clear bug report. This should be fixed in the next version.
