### ISSUE TITLE
AddTask activity changes its state after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [mpcjanssen/simpletask-android#998]
When I change the orientation of the device screen, AddTask activity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
"Cut, Copy, Paste" options disappear
![2019-07-24 12-26-47_before](https://user-images.githubusercontent.com/53469180/62221507-0c189900-b3b2-11e9-8eda-81994a74a6e7.png)
![2019-07-24 12-26-47_after](https://user-images.githubusercontent.com/53469180/62221508-0cb12f80-b3b2-11e9-85e8-c1ccba49e1f4.png)

-- second case --
The Dialog disappears
![2019-07-24 12-00-47_before](https://user-images.githubusercontent.com/53469180/62221509-0cb12f80-b3b2-11e9-80e1-a13e90a404ce.png)
![2019-07-24 12-00-47_after](https://user-images.githubusercontent.com/53469180/62221511-0cb12f80-b3b2-11e9-8d01-003f9cb637f3.png)

**Comment by mpcjanssen** [comment]
Reconfiguration handling in Android is a PITA. I am not very inclined to fix these issues. I wonder if the copy paste popup issue is fixable at all.

**Comment by mpcjanssen** [comment]
@dlicse do you know any apps that handle this properly?

**Comment by mpcjanssen** [comment]
Seems issues created by some automated process spamming hundreds of projects with the same minor issues. Wont fix unless there is anything where dataloss is occurring.
