### ISSUE TITLE
FilterActivity changes its state after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [mpcjanssen/simpletask-android#999]
When I change the orientation of the device screen, FilterActivity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
The options disappear
![2019-07-25 03-06-43_before](https://user-images.githubusercontent.com/53469180/62221754-7af5f200-b3b2-11e9-8094-8d94d28f2c50.png)
![2019-07-25 03-06-43_after](https://user-images.githubusercontent.com/53469180/62221755-7b8e8880-b3b2-11e9-8098-5d1458eecae6.png)

-- second case --
The Dialog disappears
![2019-07-24 14-40-46_before](https://user-images.githubusercontent.com/53469180/62221756-7b8e8880-b3b2-11e9-8577-79e20173817b.png)
![2019-07-24 14-40-46_after](https://user-images.githubusercontent.com/53469180/62221757-7b8e8880-b3b2-11e9-8694-e6b26479d76d.png)

**Comment by mpcjanssen** [comment]
Reconfiguration handling in Android is a PITA. I am not very inclined to fix these issues. I wonder if the popup scroll issue is fixable at all.

**Comment by mpcjanssen** [comment]
Seems issues created by some automated process spamming hundreds of projects with the same minor issues. Wont fix unless there is anything where dataloss is occurring.
